### PR TITLE
chore: Add Eslint and prettier configuration

### PR DESCRIPTION
**Pull request by iamsaumya**
Closes : #118

### CODE REVIEW

**Comment by iamsaumya** [comment]
The codebase has been formated using eslint. 

1. Unnecessary try/catch blocks are removed.
2. `==` are replaced with `===`.
3. Unused variables are removed from the codebase for better readability.

**Comment by iamsaumya** [comment]
@Laurell876 please review.

**Comment by Laurell876** [comment]
change the target branch to develop and resolve the conflicts

**Comment by gauravdas014** [comment]
@iamsaumya can you please explain, why you termed the try-catch blocks as unnecessary? Those are async-await functions, so we can definitely use try-catch for error handling, I think

**Comment by abhijit-hota** [comment]
@gauravdas014 Look at [this file](https://github.com/PalisadoesFoundation/talawa-api/blob/6a960e9bdea76e90d8fb2ab8ab029fd0611fc3df/resolvers/functions/authCheck.js).

The try-catch block there is redundant and this PR fixes that.

**Comment by gauravdas014** [comment]
@abhijit-hota Okay Thanks

**Comment by iamsaumya** [comment]
@Laurell876 @Sagar2366 I request you to please merge this PR before merging any other. Otherwise, we will have a conflict and It really kills a lot of time fixing errors manually. I hope you understand my haste.

**Comment by iamsaumya** [comment]
Was busing with some work this week so I couldn't resolve the conflict sooner.

**Comment by iamsaumya** [comment]
Hey @Sagar2366 and @Laurell876, Any updates on the mergeability of the PR?

**Comment by iamsaumya** [comment]
@Laurell876 The contributors have their own formatting style configured in their IDE. As a result the PR don't exactly give a useful code difference on the changes. A lot of code gets changed and it gets hard to review PRs. 

It will be very helpful if this PR gets merged and then everyone can have a uniform formatting style.

**Pull request merged**
