### PR TITLE
merged develop into develop-userTypeFix branch

### LINKED ISSUE #1904: Update the`develop-userTypeFix` branch with the latest features from `develop` - Fundraising / Recurring Events
**Is your feature request related to a problem? Please describe.**
1. We recently fixed the usage of `userType` with this PR.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. A new `develop-userTypeFix` branch was created to add this feature
1. We need to make sure that the  `develop-userTypeFix` branch:
    1. Maintains its current functionality
    1. Includes any new features in the `develop` branch and adjusts them to the new `userType` functionality. 
     1. Has all valid and passing tests that maintain our current test code coverage levels

This is required to support new Fundraising and Recurring events features added to `develop`:

1. https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+is%3Amerged+funds
2. https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+is%3Amerged+recurring

**Describe the solution you'd like**
1. Merge `develop` into the `develop-userTypeFix` branch
3. Make sure all newly added features to the `develop` branch are included in the  `develop-userTypeFix` branch.
4. **The new functionality of `userType` must be unchanged.**
5. No other features must be affected
6. All tests must be valid and pass

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile

Research these issues for context with the new `userType` functionality:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
1. https://github.com/PalisadoesFoundation/talawa/issues/2373
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
merged develop into develop-userTypeFix branch by refactoring all the changes of the develop and making them compatible with the `develop-usertypeFix` branch.

**Issue Number:**

Fixes #1904 

**Did you add tests for your changes?**

**Snapshots/Videos:**
Not required

**If relevant, did you update the documentation?**
Not relevant

**Summary**

**Does this PR introduce a breaking change?**

**Other information**
Not required

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by AdityaRaimec22** [comment]
Hii @AVtheking and @palisadoes kindly PTAL at the changes by that time I am fixing the tests. Thanks

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

1. We are going to have to merge this PR before your mongoose upgrade work. It has been worked on for the past 2 weeks.
2. Make your changes against this PR in the mean time
3. We will freeze after this merge.

**Comment by palisadoes** [comment]
@adi790uu Take note of this PR

**Comment by adi790uu** [comment]
> @adi790uu Take note of this PR 

👍

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 I see you are working on the failed tests, I know some may be needed due to the nature of the change.  Please let me know when all failed tests that should be fixed are complete.  Thank you!

**Comment by AdityaRaimec22** [comment]
@palisadoes I think everything is fine now. You can merge this.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
