### PR TITLE
feat: Updated `pull_request.yaml`

### LINKED ISSUE #2101: Github Action: Utlize `changed-files` action for file-count-check and unauthorized-changes-check
**Is your feature request related to a problem? Please describe.**
 - We have a GitHub action file authorized-changes-detection.yml that, during pull requests, detects when sensitive files are modified and exits with an error.
https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/authorized-changes-detection.yml
- Unfortunately, it does not mention the file that is not authorized to change.

**Describe the solution you'd like**

1. Utilize the `tj-actions/changed-files` github action, and create a new job in  `pull-request.yml`, to check if the PR has changes in authorized files.
2. Utilize the same action, in the `File-Count-Check` Job defined in `pull_request.yml`, to count the files in a PR. Instead of checking file count with a python script.

3. If the above two are done, we can get rid of `authorized-changes-detection.yml` and `check_files_submitted.py` file form workflow

**Additional context**
This PR achieves the same in talawa-admin repo https://github.com/PalisadoesFoundation/talawa-admin/pull/1793

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
Check for authorized file changes and the Changed files count using `tj-actions`.

**Issue Number:**

Fixes #2101 

**Did you add tests for your changes?**
N/A

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
N/A

**Summary**
- Integrated authorized files as a job in the pull_request.yaml
- Modified file-count-check job.
- Removed authorized_changes file and check_files_subcount
- Followed the same approach as mentioned in the issue description

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by akhilender-bongirwar** [comment]
On what basis are we checking that file changes should not be greater than `100` ? Why specifically `100`?

**Comment by akhilender-bongirwar** [comment]
Like previously we were checking if the files modified is greater than 20 then we were failing this check.

**Comment by palisadoes** [comment]
> Like previously we were checking if the files modified is greater than 20 then we were failing this check.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1793#discussion_r1536867404

**Comment by akhilender-bongirwar** [comment]
And I have one more query, that in the backend we are putting `schema.graphql` file as an unauthorized file change but this actually should be kept in the frontend.

**Comment by akhilender-bongirwar** [comment]
It is because the `PR Workflow / Runs Introspection on the GitHub talawa-api repo on the schema.graphql file` will fail when the support for the modifications in `schema.graphql` file are not present in the API `schema.graphql` file.

**Comment by akhilender-bongirwar** [comment]
Including this file in the list of unauthorized files on the frontend would cause the check to fail. This serves as a reminder to verify if the backend supports the modifications planned for the frontend for the `schema.graphql` file

**Pull request merged**
