### PR TITLE
Feature to Encrypt user email in database

### PR DESCRIPTION
**Pull request by prayanshchh**
**What kind of change does this PR introduce?**
Feature to encrypt user email addresses in the Database

**Issue Number:**
#1756
Fixes #

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
No

**Summary**
two functionalities have been implemented

encryption and decryption of emails
storing hashingEmails in db
storing encrypted emails in db, decrypted function is implemented to decrypt emails
hashed version of email is also stored in db, for faster lookups we can use hashing if a match occurs then we can return a encrypted or a decrypted email based on the functionality.

hashing was introduced to avoid going through all the users and decrypting every email to find a match, hashing makes this faster.

**Does this PR introduce a breaking change?**
Yes this is a significant change in the codebase

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Release Notes

- **New Features**
	- Introduced email encryption and hashing for enhanced security across user-related functionalities.
	- Added environment variables `ENCRYPTION_KEY` and `HASH_PEPPER` for secure email handling.
	- Updated user profile to include `hashedEmail` and encrypted email fields.

- **Bug Fixes**
	- Improved error handling in various resolvers to ensure accurate feedback during user retrieval and email processing.

- **Documentation**
	- Enhanced documentation for environment variables and their usage in the setup process.

- **Tests**
	- Updated tests to incorporate email encryption and hashing, ensuring that user data is handled securely in all scenarios.

### CODE REVIEW

**Comment by prayanshchh** [comment]
will fix these linting errors, and I have to edit .env.sample, setup.ts and schema.graphql are necessary for me to change to implement this functionality

**Comment by prayanshchh** [comment]
also please note, I will resume my work on this in 3-4 days as festive season is going on

**Comment by prayanshchh** [comment]
@pranshugupta54 does everything look good now, there are no comments by coderrabit ai, also it would be great if you could guide me with resolving linting errors

**Comment by pranshugupta54** [comment]
please fix conflicting files first

**Comment by prayanshchh** [comment]
fixed conflicting files, now can you guide me with eslint issues @pranshugupta54

**Comment by pranshugupta54** [comment]
Please fix failing tests and code rabbit comments (if the outdated comments are no longer valid then mark them resolved)

**Comment by prayanshchh** [comment]
> Please fix failing tests and code rabbit comments (if the outdated comments are no longer valid then mark them resolved)

I was trying to fix eslint issue and remove the disabled line. 

can you please recommend a method 
 I tried this
 tsconfig.json
```
 "baseUrl": ".", 
"paths": {"@constants/*": ["./src/constants/*"],
"@setup/*": ["./src/setup/*"],
"@utilities/*": ["./src/utilities/*"]}
import { askForMongoDBUrl, checkConnection, checkExistingMongoDB, } from "@setup/MongoDB"; 
import { loadDefaultOrganiation } from "@utilities/loadDefaultOrg"; 
```

 it passed eslint checks but this error is coming up in github workflow
Cannot find module '@/setup/getNodeEnvironment' or its corresponding type declarations.ts(2307)
can you please suggest a alternative?

**Comment by pranshugupta54** [comment]
If it was disabled earlier, you can leave it like that. It can be fixed in a separate isssue. Keep this PR related only to email encryption.

**Comment by prayanshchh** [comment]
alright then, I will add the disable line, I will create an issue after this about the same

**Comment by pranshugupta54** [comment]
Those files are in File changes in your PR. If some files got added to this PR due to some merge conflicts then u can get them back from `develop` branch and push into your PR

**Comment by prayanshchh** [comment]
> Those files are in File changes in your PR. If some files got added to this PR due to some merge conflicts then u can get them back from `develop` branch and push into your PR

It worked now, thanks!

**Comment by prayanshchh** [comment]
I wanted to clear some doubts, these are related to increase code coverage in encrypt email db pr - https://github.com/PalisadoesFoundation/talawa-api/pull/2627
for example this a file for which I have to write a test for:
export const members: OrganizationResolvers["members"] = async (parent) => {
  const users = await User.find({
    _id: {
      $in: parent.members,
    },
  }).lean();
  const decryptedUsers = users.map((user: InterfaceUser) => {
    if (!user.email) {
      logger.warn("User missing email field", { userId: user._id });
      return user;
    }
    try {
      const { decrypted } = decryptEmail(user.email);
      if (!decrypted) {
        throw new Error("Decryption resulted in null or empty email");
      }
      return { ...user, email: decrypted };
    } catch (error) {
      logger.error("Email decryption failed", {
        userId: user._id,
        error: error instanceof Error ? error.message : "Unknown error",
      });
      // Consider throwing an error instead of silently continuing
      throw new GraphQLError("Failed to process user data");
    }
  });
  return decryptedUsers;
};
how can I test that this code throws warn if user.email doesn't exist, and if code throws error if decryption has failed or not
I am asking this as we have not implemented tests where we handle errors for fields that were queried from the db (in this case users is queried from the db)
just nudge me in the right direction

@pranshugupta54 @coderabbitai

**Comment by prayanshchh** [comment]
the reason why code cov is less is we haven't implemented testing for scenarios where we do a db cal(for example extracting users from db) and then testing if application throws error if user.email doesn't exist...can I follow the approach give by codderrabitai, or can you help me with this

@pranshugupta54 (I slacked the same thing, but I didn't get reply)

**Comment by prayanshchh** [comment]
this feature is on hold until the develop-postgres branch reaches the same state as develop..no point of adding this functionality in develop if everything will have to be redone when develop-postgres becomes the default branch to contribute.

**Comment by palisadoes** [comment]
We are going to have to close this PR. The `develop-postgres` code will soon overwrite `develop` and there will be too many merge conflicts.

**Comment by prayanshchh** [comment]
alright I will resume my work in a new branch once `develop-postgres` is ready

**Pull request closed without merging**
