### PR TITLE
Fixed the eslint_disable_check.py script

### LINKED ISSUE #2519: API: Fix the `eslint_disable_check.py` script
**Describe the bug**

1. Our code base has suffered over the years because contributors ignored linting errors
2. We created a `.github/workflows/eslint_disable_check.py` script to detect the use of the `eslint-disable` string in files submitted in the PR
3. It does not work with this line `// eslint-disable-next-line @typescript-eslint/no-unused-vars`

**To Reproduce**

1. Submit a PR
2. Make one of the files have the following line in it
    1. `// eslint-disable-next-line @typescript-eslint/no-unused-vars`
1. The PR does not fail

**Expected behavior**

1. Submit a PR
2. Make one of the files have the following line in it
    1. `// eslint-disable-next-line @typescript-eslint/no-unused-vars`
1. The PR must fail

The script must fail with the string `eslint-disable` discovered any where in any line

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

The same person should be assigned to both these issues

- https://github.com/PalisadoesFoundation/talawa-api/issues/2519
- https://github.com/PalisadoesFoundation/talawa-admin/issues/2257

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ARYANSHAH1567**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #2519

## Summary by CodeRabbit

- **New Features**
	- Introduced a Python script to enforce code quality by checking for `eslint-disable` statements in TypeScript files.
	- Enhanced the linting process to include this new custom check for improved adherence to coding standards.

- **Bug Fixes**
	- Improved error handling in the `wipeExistingData` function for better context in error logging.

### CODE REVIEW

**Comment by ARYANSHAH1567** [comment]
I am not sure but hope this fixed the issue . If any changes required do let me know

**Comment by Cioppolo14** [comment]
@ARYANSHAH1567 Can you test using the guidance in the issue to make sure it does?

**Comment by palisadoes** [comment]
1. You need to test it against this PR to see why it's not working as expected
2. Edit files and restore them to their original condition as part of the testing

**Comment by ARYANSHAH1567** [comment]
@palisadoes found the problem. In the pull-request.yml while running the linting error it was running only the eslint check and not executing the eslint-disable.py file due to which these errors were not failing the tests. Now my pr fails for linting due to comment //eslint-disable

**Comment by ARYANSHAH1567** [comment]
Same for the Admin it also executes only the command npx eslint does not include the eslint-disable.py script

**Comment by palisadoes** [comment]
Have you tried asking our slack channel for assistance?

**Comment by ARYANSHAH1567** [comment]
> Have you tried asking our slack channel for assistance?

I have added the script for disable comment check. Now if I remove the comments from my pr then the pr will pass all its tests

**Comment by ARYANSHAH1567** [comment]
my previous commit on this pr failed as the line //eslint-disable next line was present

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
