### PR TITLE
Feat: Updated the express-rate-limit package to v7.1.5 #1463

### LINKED ISSUE #1463: Upgrade package `express-rate-limit` from 5.5.1 to 7.1.5
For security purposes, we need to bump package  [express-rate-limit](https://github.com/express-rate-limit/express-rate-limit) from 5.5.1 to 7.1.5.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1459

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105185828/job/19341811113?pr=1459
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105186275/job/19341812520?pr=1459

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

### PR DESCRIPTION
**Pull request by alanansari**
**What kind of change does this PR introduce?**
Package Update

**Issue Number:** #1463 

Closes #1463

**Did you add tests for your changes?** No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Upgraded the express-rate-limit package to the latest v7.1.5 and also updated the deprecated usage in the app.ts
Previous:
image
Now:
image

**Does this PR introduce a breaking change?** No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** Yes

### CODE REVIEW

**Comment by alanansari** [comment]
#1473

**Comment by Cioppolo14** [comment]
@alanansari Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by alanansari** [comment]
> @alanansari Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.
> 
> Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

I've added the closes keyword.

**Comment by palisadoes** [comment]
1. Please merge with the latest upstream
2. You'll need to figure out why the tests are not being run. It's probably related to the package upgrade

**Comment by palisadoes** [comment]
Any updates on this?

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
