### PR TITLE
Fixed setup not detecting SERVER_PORT in .env

### LINKED ISSUE #2286: Setup doesn't detect a pre-existing `SERVER_PORT` value in the `.env` file
**Describe the bug**

1. Setup doesn't detect a pre-existing `SERVER_PORT` value in the `.env` file
2. If a value, say `4006`, is configured the setup process prompts for port 4000.
3. Other variables detect preexisting values and prepopulate the values in the prompts as the desired value. 
4. See the mongodb example in the screenshot below
5. This reduces ensures that the parameters are not overwritten

**To Reproduce**

1. Run setup with a non `4000` value in the `.env` file
2. The value is not detected and used as the prompt default.

**Expected behavior**

1. Run setup with a non `4000` value in the `.env` file
2. The value is detected and used as the prompt default.
3. If no value is present, then `4000` should be the prompted default .

**Actual behavior**

- See above

**Screenshots**

image

**Additional details**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by lokeshsingh3721**
What kind of change does this PR introduce?

A bugfix

Fixes   #2286
  
Did you add tests for your changes?

not needed.

Snapshots/Videos:

https://github.com/PalisadoesFoundation/talawa-api/assets/71646466/fa648c07-1f9b-48b1-9133-938b26cfe00e

If relevant, did you update the documentation?

not needed

This pull request resolves an issue during the setup of Talawa-API. Previously, it failed to fetch the server port number from the .env file. With this update, it now correctly detects the port number from the .env file. Additionally, if no port number is configured in the .env file, it defaults to 4000.

Does this PR introduce a breaking change?

NO

### CODE REVIEW

**Comment by Huy1996** [comment]
@lokeshsingh3721 Could you fix the failing test?

**Comment by lokeshsingh3721** [comment]
> @lokeshsingh3721 Could you fix the failing test?

Yeah  , i can fix one test . Other test is not passing because i have changed the setup .ts which is the unauthorized file.

**Comment by lokeshsingh3721** [comment]
> @lokeshsingh3721 Could you fix the failing test?

yeah .

**Comment by Cioppolo14** [comment]
@SiddheshKukade @EshaanAgg Can you review this PR?

**Comment by SiddheshKukade** [comment]
checking

**Review by SiddheshKukade — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
