### PR TITLE
Add additional tests for the src/lib/resolvers/Mutation/otp.ts (Issue #903)

### LINKED ISSUE #903: Test: src/lib/resolvers/Mutation/otp.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Mutation/otp.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/resolvers/Mutation/otp.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**

This PR adds the 2 additional tests for the src/lib/resolvers/Mutation/refreshToken.ts file, which checks the following areas of the code:
- throws Error if no user exists with email === args.data.email
- otp token expires after 15 minutes
- otp token is signed with the ACCESS_TOKEN_SECRET

**Issue Number:**

Fixes #903

**Did you add tests for your changes?**
I haven't introduced any new change to the source code. Added the automated tests for the file.

**Snapshots/Videos:**
image
image

**If relevant, did you update the documentation?**
The documentation update was not required.

**Summary**
This PR adds two additional tests to check the code for its robustness. Previously, the automated test was only checking, if the error is been thrown if user is not found inside the database.
But now, the check for Expiration of the OTP, and Signing of the OTP with ACCESS_TOKEN_SECRET is also introduced.

**Does this PR introduce a breaking change?**
No, this is just a change in the automated testing of the file (src/lib/resolvers/Mutation/otp.ts)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
I think the mailer configuration on the GitHub actions is not properly configured. Due to which, the PR Workflow is failing. The tests are running fine on the local machine, with Gmail as a Mailer configured.

**Comment by palisadoes** [comment]
- The configuration variable names changed slightly last week. Please verify that your changes include them.
- Other PRs in the queue have passed. This may be an issue with yours exclusively. Please double check

**Comment by anshgoyalevil** [comment]
> * The configuration variable names changed slightly last week. Please verify that your changes include them.
> * Other PRs in the queue have passed. This may be an issue with yours exclusively. Please double check

I checked my code files Sir. Everything is alright from that side.

The tests which I have written are using the mailer from Utilities folder.
I searched, if any other test is using the mailer utility, but, none of them is using nodemailer or mailer, which is the reason, why all other tests are passing on the GitHub actions.

Please take a look and help out Sir @palisadoes

**Comment by palisadoes** [comment]
Thanks. What is your proposed GitHub action modification to get it working? The proposed GitHub file changes should be a part of the PR too. It looks like you may have found a bug in our code and/or pipeline

**Comment by anshgoyalevil** [comment]
> Thanks. What is your proposed GitHub action modification to get it working? The proposed GitHub file changes should be a part of the PR too. It looks like you may have found a bug in our code and/or pipeline

I am new to the CI/CD pipelines, but I will try my best to get a solution on this within 24 hours.

**Comment by palisadoes** [comment]
You may have to mock sending mail as actual mail may be blocked by GitHub due to spamming concerns

**Comment by anshgoyalevil** [comment]
> You may have to mock sending mail as actual mail may be blocked by GitHub due to spamming concerns

You are absolutely correct Sir, but mock sending the mail wouldn't fulfill the aim of automated testing, which checks the actual code.

The test, that I have written is checking whether the actual code really sends out mail or not, and if it sends, what is the expiration time of the otp, and that whether the otp is correctly encrypted or not.

If we mock send the mail, then, We wouldn't be able to check the actual code for it coverage. Also, the actual code is returning the ```{otpToken}``` object after sending the actual mail using the nodemailer. The test would need that ```{otpToken}``` object for checking the code, and thus, would have to simulate by sending an actual mail.

A solution to this would require some code change of otp.ts file, which could possibly break some things, so is not recommended.

**Comment by palisadoes** [comment]
@SiddheshKukade @DMills27 @JamaicanFriedChicken Any suggestions?

**Comment by JamaicanFriedChicken** [comment]
I wouldn't want code changes to be made to the otp.ts file at this time, this can possibly affect everyone else as @anshgoyalevil mentioned. Seems like we'd need to investigate this Github workflow issue though.

**Comment by palisadoes** [comment]
> I wouldn't want code changes to be made to the otp.ts file at this time, this can possibly affect everyone else as @anshgoyalevil mentioned. Seems like we'd need to investigate this Github workflow issue though.

- If you are referring to the CodeCov workflow, it started working. It appeared to be a CodeCov service provider issue.
- BTW, Code coverage won't run until all the tests pass

**Comment by anshgoyalevil** [comment]
> > I wouldn't want code changes to be made to the otp.ts file at this time, this can possibly affect everyone else as @anshgoyalevil mentioned. Seems like we'd need to investigate this Github workflow issue though.
> 
> * If you are referring to the CodeCov workflow, it started working. It appeared to be a CodeCov service provider issue.
> * BTW, Code coverage won't run until all the tests pass

Actually the issue is with the Mailer. It is not configured in the GitHub workflow, which is running the automated tests.

**Comment by tonythegr8** [comment]
Please

**Comment by palisadoes** [comment]
Please work with @JamaicanFriedChicken on a way to add this to the workflow. You have discovered a weakness that we need to resolve

**Comment by anshgoyalevil** [comment]
@JamaicanFriedChicken Could you please guide me for adding the mailer configuration to the GitHub Workflow. I will create a fake google account to get the mail credentials.
Just don't know, how and where to add those credentials for the mailer to work on GitHub Workflow System.

**Comment by anshgoyalevil** [comment]
> @JamaicanFriedChicken Could you please guide me for adding the mailer configuration to the GitHub Workflow. I will create a fake google account to get the mail credentials. Just don't know, how and where to add those credentials for the mailer to work on GitHub Workflow System.

I think, those variables need to be added here
image

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing tests and also resolve the conflicts.

**Comment by anshgoyalevil** [comment]
> Please fix the failing tests and also resolve the conflicts.

Yes, I was just resolving the conflicts, but I need some help from @palisadoes Sir and @JamaicanFriedChicken Sir for adding the mail options in the Workflow files.

**Pull request closed without merging**
