### PR TITLE
Session timeout

### LINKED ISSUE #1637: Backend for configurable session-management
**Is your feature request related to a problem? Please describe.**

Currently, the timeout for Talawa-Admin is hard-coded in Talawa-Api. However, there is no feature to set a custom timeout for different organizations.

**Describe the solution you'd like**

Implement configurable session timeout for each organization and provide admins and super-admins the ability to access and change the session timeout for an organization, with the default timeout set to 30 minutes.

**Describe alternatives you've considered**
NA

**Additional context**

Related to the issue in Talawa-Admin [#1305](https://github.com/PalisadoesFoundation/talawa-admin/issues/1305).

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1637

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[session-management-api.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/ecf48e22-6b86-4d73-ab90-1a95ab9c9cec)

**Summary**

**Changes:**
1. Implemented configurable session-timeout for an organization by the admin or super-admin.
2. Implemented retrieval of session-timeout for an organization by the admin or super-admin.
3. Added tests for all the changes made.

**Constraints:**
1. Only admins and super-admins can update and retrieve the session-timeout for any organization.
2. Admins can only update the session-timeout of organizations they are admin of.
3. Timeout should be in range of 15 to 60 minutes (both including), and a multiple of 5. 

**Does this PR introduce a breaking change?**

No

**Other information**

Related to Talawa-Admin issue [#1305](https://github.com/PalisadoesFoundation/talawa-admin/issues/1305)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
This would be much better served at the Community level with a single value for all organizations. Therefore it would be managed by the SuperAdmin using this profile page for the configuration
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1334#issuecomment-1879522861

Please make the appropriate changes to make this a single universal parameter

**Comment by palisadoes** [comment]
There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

**Comment by chandel-aman** [comment]
> There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

Apologies for the oversight. I'll review the PR guidelines and make the necessary adjustments. I appreciate your guidance.

**Comment by chandel-aman** [comment]
> This would be much better served at the Community level with a single value for all organizations. Therefore it would be managed by the SuperAdmin using this profile page for the configuration
> 
>     * [Add the ability to change pre-login imagery talawa-admin#1334 (comment)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1334#issuecomment-1879522861)
> 
> 
> Please make the appropriate changes to make this a single universal parameter

Correct me if I'm wrong.

1. You're proposing that the session timeout be configurable at the community level, implying that organizations would fall under the community umbrella, and the session timeout data should be applicable universally all the organizations under of that community.
2. Additionally, you're recommending that only super-admins should have the authority to update the session timeout, excluding admins from this privilege.

**Comment by palisadoes** [comment]
Yes

**Pull request closed without merging**
