### PR TITLE
Tests for `src/resolvers/Mutation/updateTask.ts`

### LINKED ISSUE #1032: Test for `src/resolvers/Mutation/updateTask.ts`
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file src/resolvers/Mutation/updateTask.ts
We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name __tests__/resolvers/Mutation/updateTask.spec.ts. You may need to create the appropriate directory structure to do this.

Screenshot from 2023-02-08 10-37-07

IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1032

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by xoldyckk** [comment]
@kb-0311 remove that `IN_PRODUCTION === true` thingy.

**Comment by kb-0311** [comment]
@xoldyckk wutt? Could you pls be a little bit more specific?

**Comment by kb-0311** [comment]
Oh okay nevermind , got it .

**Comment by xoldyckk** [comment]
@kb-0311 remove the `IN_PRODUCTION = true` from test messages as well.

**Comment by kb-0311** [comment]
@xoldyckk done.

**Comment by xoldyckk** [comment]
@kb-0311 brother remove every last bit of it left in the file. Remove that explicit `IN_PRODUCTION=true` in `vi.constants`.

**Comment by xoldyckk** [comment]
BTW what's the use of mocking constants?

**Comment by kb-0311** [comment]
@xoldyckk yeah you are right, mocking constants is not necessary, I was tripping, I removed all the constants mocks. Keeping the mocked implementation of requestContext.translate for testing purposes.

**Comment by kb-0311** [comment]
@xoldyckk codecov failed to load properly

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
