### PR TITLE
Update the comments of resolvers to show the in which clients they are being currently used [Fixes #1309 and #1335]

### LINKED ISSUE #1309: Feature Request: Update the comments of resolvers to show the in which clients they are being currently used.
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to figure out which queries and mutations are being used in which clients, and thus developers are not often able to gauge the impact of the changes they make on the API side.

**Describe the solution you'd like**
Update the `typeDefs` of the resolvers to show which clients (Talawa Mobile and Talawa Admin) are they being used in. This would allow for automatic updating of the code in the talawa-docs repository as well.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #1309, #1335

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Updated the typeDefs of the resolvers to show which clients (Talawa Mobile and Talawa Admin) are they being used in. This would allow for automatic updating of the code in the talawa-docs repository as well.

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@EshaanAgg Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
Please work with your mentors to review and merge this

**Comment by EshaanAgg** [comment]
@palisadoes Can you please assign reviewers to this PR?

**Comment by palisadoes** [comment]
@EshaanAgg you should be able to request reviewers. Please do so in future for your mentors if possible

**Comment by xoldyckk** [comment]
@EshaanAgg why is this needed?

**Comment by EshaanAgg** [comment]
@xoldyckk Automatic documentation would add these comments as descriptions in these queries and mutations in the main Talawa Documentation website. This would provide reference to developers in the future about which clients they may break while making changes to the resolvers for the same.

The changes in package-lock.json are simply due to the same being outdated.

**Comment by xoldyckk** [comment]
Ok, I read the issue. Instead of this you should mention what permissions are required to trigger a particular operation. That'd be much better.

Graphql schema comments are very flexible, you can go all in while documenting them, they support markdown format as well. 

Here are some resources to learn:-
[graphql-spec](https://spec.graphql.org/draft/#sec-Descriptions)
[markdown format specified in graphql-spec](https://commonmark.org/)

**Comment by palisadoes** [comment]
Should this be closed and included in the API apollo / yoga update work?

**Comment by EshaanAgg** [comment]
Yes sir. It would make much more sense to have it there. I'll close the PR.

**Pull request closed without merging**
