### PR TITLE
Setup script will now prompt for LAST_RESORT_SUPER_ADMIN

### LINKED ISSUE #1524: The setup script does not prompt for `LAST_RESORT_SUPERADMIN_EMAIL`
**Is your feature request related to a problem? Please describe.**
The setup script does not prompt for the `LAST_RESORT_SUPERADMIN_EMAIL` parameter. This causes difficulty for people to set up the application as it is a prerequisite parameter for smooth operation.

**Describe the solution you'd like**
1. The setup script must prompt for the `LAST_RESORT_SUPERADMIN_EMAIL` parameter in both the initial setup and whenever the script is re-run
2. The parameter must be added to the configuration file
4. No other features must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
-N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
Earlier the setup script wasn't asking for `LAST_RESORT_SUPER_ADMIN` but not it will.

**Issue Number:**

Fixes #1524 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Not required

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22 Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 3. The code does not comply with our linting check or other related formatting requirements
> 
> We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

@Cioppolo14, the test failures are not a result of the modifications in my pull request. Instead, they are occurring due to alterations made in other pull requests. My changes have full test coverage. Thank you.

**Comment by palisadoes** [comment]
1. The newly added Redis feature is not visible in your submission. It was merged into setup.ts earlier today.
2. Please merge your code with the newly updated `upstream`.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. The newly added Redis feature is not visible in your submission. It was merged into setup.ts earlier today.
2. Please merge your code with the newly updated `upstream`.

**Comment by palisadoes** [comment]
You seem to have created your `brach2 ` from our `main` branch. You need to make changes to our `develop` branch as mentioned in our documentation.

You will see many references to Redis in the current file in the `develop` branch.
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/setup.ts

I'm going to close this. Please create a new PR when the correct branch is updated.

**Pull request closed without merging**
