### PR TITLE
Added Support for User Family Members

### LINKED ISSUE #1584: Add Support for User Family Members
**Is your feature request related to a problem? Please describe.**

1. To be even more useful to Administrators, there needs to be the ability to group Users as members of the same family.
2. When implemented in the API, the Admin Portal will be able to visualize and edit the family group members of each user in the user profile page.

**Describe the solution you'd like**
1. We should have the ability to add, and remove people from families. 
1. Families can only be valid if there are more than one member. Therefore when:
    1. there is only one member in a group, the family group entry should be empty
    2. a new family is created, the family group instantaneously has two family members
1. Other functionality must not be affected
1. You must write tests to validate your work

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- Work with @xoldyckk on evaluating your solution here and in the subsequent PR
- This may be a prerequisite for our menu of project ideas for GSoC 2024

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
Add Support for User Family Members

**Issue Number:**

Fixes #1584 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
Not relevant

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**
Some tests are failing and I am currently addressing them, and I have raised a pull request because the assigned issue has been pending for a significant period.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by AdityaRaimec22** [comment]
@palisadoes The linting checks again passed here without any issue. Please take a look Thanks.

**Comment by palisadoes** [comment]
OK. I'm going to merge this.  We can monitor it over the next few hours

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
1. Please merge with the latest upstream. 
2. I can't import your data via setup.ts.
3. We made a change that reverted the use of ts-node which is what your version is using

**Comment by AdityaRaimec22** [comment]
> 1. Please merge with the latest upstream.
> 2. I can't import your data via setup.ts.
> 3. We made a change that reverted the use of ts-node which is what your version is using

done.

**Comment by palisadoes** [comment]
Please sync one more time. We merged just after your last sync

**Comment by palisadoes** [comment]
Join the discussion here if you have any linting issues after doing that.
- https://github.com/PalisadoesFoundation/talawa-api/issues/1548#issuecomment-1925593787

**Comment by palisadoes** [comment]
1. You are not merging correctly somehow.
2. With the latest develop branch, `package.json` has no references to `ts-node`

**Comment by palisadoes** [comment]
It looks OK now.

**Comment by AdityaRaimec22** [comment]
@palisadoes you can merge it now.

**Comment by LakshyaSatpal** [comment]
@palisadoes Something isn't right here.

@AdityaRaimec22 We stricted the lint rules, some days back. 
I understand that your code is inspired by the current code, but we do lint checks only on files that you change. 
1. Many files in the code are still following older lint rules.
2. So, Even if you have made a small change in a file, it should follow new lint rules.

@palisadoes If the checks are passing on PR something is wrong with PR workflow, imo. 

I can still see `any` in files, which should fail the lint checks again, ideally. Attaching screenshots of lint rules for ref.
image

**Comment by AdityaRaimec22** [comment]
> @palisadoes Something isn't right here.
> 
> @AdityaRaimec22 We stricted the lint rules, some days back. I understand that your code is inspired by the current code, but we do lint checks only on files that you change.
> 
> 1. Many files in the code are still following older lint rules.
> 2. So, Even if you have made a small change in a file, it should follow new lint rules.
> 
> @palisadoes If the checks are passing on PR something is wrong with PR workflow, imo.
> 
> I can still see `any` in files in this PR, which should fail the lint checks, ideally. image

@LakshyaSatpal How you are able to generate this.

**Review by SiddheshKukade — APPROVED** [review]
Looks fine.  Good to see that you've done all the error checks as well. Good job.

**Comment by LakshyaSatpal** [comment]
@AdityaRaimec22 Sorry, generate what? This screenshot is from `.eslintrc.json` on develop branch

**Comment by palisadoes** [comment]
@AdityaRaimec22 

1. Have you merged the latest `upstream/develop` into your `FamilyBranch`?
2. I think that may be the cause of the unexpected behavior.

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22
> 
> 1. Have you merged the latest `upstream/develop` into your `FamilyBranch`?
> 2. I think that may be the cause of the unexpected behavior.

merged with upstream/develop

**Comment by palisadoes** [comment]
@AdityaRaimec22 

We got it to work. Please merge with `upstream/develop` again

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22
> 
> We got it to work. Please merge with `upstream/develop` again

It is up to date.

**Comment by AdityaRaimec22** [comment]
> > @AdityaRaimec22
> > We got it to work. Please merge with `upstream/develop` again
> 
 It is up to date. There is nothing to merge.

**Comment by palisadoes** [comment]
Please make a minor commit to trigger the workflow

**Comment by palisadoes** [comment]
@NamitBhutani Your git linting seems to be failing again

**Comment by AdityaRaimec22** [comment]
> @NamitBhutani
> 
> 1. Your git linting seems to be failing again, or is it passing and formatting the repo as expected?
> 2. Why wasn't the formatting occurring before? We just upgraded the prettier package which may have different functionality

@palisadoes I think the possible reason beyond git linting failing is that it is unable to find a git commit hash which has been deleted. And I don't think this failure can cause any error.

**Comment by NamitBhutani** [comment]
> @NamitBhutani
> 
> 1. Your git linting seems to be failing again, or is it passing and formatting the repo as expected?
> 2. Why wasn't the formatting occurring before? We just upgraded the prettier package which may have different functionality

Its failing because of the fact that there are 2 parent commits, we fixed one issue yesterday - being when someone else's commit is merged in develop, it caused errors with git diff, now another one has popped up.
I think that we should use **https://github.com/marketplace/actions/changed-files** like its being used in talawa-admin to get the list of the changed files and run eslint for that.

**Comment by palisadoes** [comment]
> > @NamitBhutani
> > 
> > 1. Your git linting seems to be failing again, or is it passing and formatting the repo as expected?
> > 2. Why wasn't the formatting occurring before? We just upgraded the prettier package which may have different functionality
> 
> Its failing because of the fact that there are 2 parent commits, we fixed one issue yesterday - being when someone else's commit is merged in develop, it caused errors with git diff, now another one has popped up. I think that we should use **https://github.com/marketplace/actions/changed-files** like its being used in talawa-admin to get the list of the changed files and run eslint for that. Because I feel that the current methods has a lot of exceptions that we can no longer afford to test , because it's blocking other's PRs too.

@NamitBhutani 

Please fix this with a new PR for the same issue. This is really not desirable. Can that be done in the next few hours?

**Comment by palisadoes** [comment]
@NamitBhutani Should we merge this?

**Comment by NamitBhutani** [comment]
> @NamitBhutani Should we merge this?

I don't think so, there still might be linting errors, if they can confirm that all linting errors are removed from the pre commit hook we can go ahead.

**Comment by palisadoes** [comment]
@AdityaRaimec22 Please verify that there are no further errors from your `git commit`.

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22 Please verify that there are no further errors from your `git commit`.

image

here is the results.

**Comment by NamitBhutani** [comment]
@palisadoes it works (finally), it caught all the linting errors!

**Comment by NamitBhutani** [comment]
> @palisadoes The linting test are again failing and this time for nearly every single file in the codebase. How can I remove these errors.

This is because you merged develop into your branch, so a lot of files changed.

**Comment by palisadoes** [comment]
I'm not sure why yours is the only PR that has this issue.

Please close and submit another one.

I know it must be frustrating but it seems your process isn't quite right.

Please start with a fresh upstream develop and add your changes

**Comment by palisadoes** [comment]
1. I'm going to have to close this. 
2. Too many linting issues
3. Too many files updated. It'll be impossible to review.
4. Please open another PR using the latest `upstream/develop` as the starting point
5. This is the only PR with this characteristic. Something is not right.

**Pull request closed without merging**
