### PR TITLE
Added tests for the file src/resolvers/Mutation/updateUserProfile.ts

### LINKED ISSUE #1822: Test: src/resolvers/Mutation/updateUserProfile.ts
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file `src/resolvers/Mutation/updateUserProfile.ts`
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Added tests for src/resolvers/Mutation/updateUserProfile.ts.

**Issue Number:**

Fixes #1822 

**Did you add tests for your changes?**
N/A

**Snapshots/Videos:**
All the tests after adding the test
Screenshot from 2024-02-12 12-00-34

Overall code coverage for the file
Screenshot from 2024-02-12 12-00-17

**If relevant, did you update the documentation?**
N/A

**Summary**
Increasing code coverage of the file to 100%

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Anvita0305 Please fix the failing lint test.

**Comment by Anvita0305** [comment]
Hello, @Cioppolo14 I have fixed linting errors. Can you please check? Thanks!

**Comment by palisadoes** [comment]
1. You have disabled linting in multiple locations. 
1. Please restore

You will degrade the quality of our code base with this approach

**Comment by Anvita0305** [comment]
Hello, I have restored the disabled code and updated it with new one. Can you please review it? Thanks!

**Comment by palisadoes** [comment]
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

**Comment by palisadoes** [comment]
1. We have to close this PR
1. There are over 400 modified files.
1. Please reopen with just the necessary files

**Comment by Anvita0305** [comment]
Yes working on it

**Pull request closed without merging**
