### PR TITLE
feat : Event agendas - Minor improvements and fixes 

### LINKED ISSUE #2230: Event agendas - Minor improvements and fixes
**Is your feature request related to a problem? Please describe.**
 - Currently, in the implementation of the agenda items, there is a need to correct two things in the implementation of agenda 
  items. First, that the user type in the agenda item is a string. This does not seem like a bad practice. Plus the user type is 
  conflicting, it should be of `User` type. 
- Secondly, i think that the note agenda item's functionality is a little bit skewed right now. We have two variables in the agenda 
item model, one is a boolean type isNote and another is an enum ItemType, which both work towards the same goal. Removing either of them whichever seems simpler and more functional would be a great nway to introduce simplicity.

**Describe the solution you'd like**

 - The solution for the user type would be to use the `User` model and not the `string` type. 
 - We will have to make a field level resolver for finding out the user (Main speakers or people in the event)
 - Optionally, it can be an array of `User` type if we want more than one main speakers in an event agendas. 
 - The solution for note type is to implement a different schema for a note type agenda item. Right now it is really confusing on how to create a note type agenda item.
 - Implementing one or more resolvers for a note type agenda item seems like the best option to me.

**Describe alternatives you've considered**

  Implementation of the above. Also removing redundant and useless functionalities in the code. 

 
**Additional context**

Refers isssue #1588  

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Atharva-Kanherkar**
**What kind of change does this PR introduce?**

 Feature

**Issue Number:**

Fixes #2230 

**Did you add tests for your changes?**

Yes 

**Snapshots/Videos:**

N/A 

**If relevant, did you update the documentation?**

No 

**Summary**

 I have made a new schema called as "Note" Which is embedded to an agenda item. Whenever you create an agenda item, you can : 
- Create a note for the agenda item by simply providing the ID. 
- Delete the note. If the agenda item is deleted, the all the notes get deleted automatically. Notes can not exist independently. 
- If a note is created, it automatically gets pushed to the notes array of an agenda item 
- The note has just the content and related agenda item fieds as the input 
- We can easily bind the interspersed agenda items and notes as each note is connected to its agenda item and can not exist independently. 
- User can make as many notes as he wants per agenda item 
- Makes note making and agenda item making more feature rich
- Removed redundant item type enum and isNote boolean from agenda item schema
- Added queries to fetch all the notes per agenda item
- Added queries to fetch a particular note too
- Also fixed the "User" Type in agenda item. It is no longer a string now. It is an array of actual, real talawa users.
-  Added field level query resolver for fetching all the users related to that agenda item. 
- All the added tests have been covered with 100% Test code coverage.

**Does this PR introduce a breaking change?**

No

 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

 Yes

### CODE REVIEW

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Please review the PR. I will add the missing tests in an hour, they didnt get uploaded because of some reason. Thank you!

**Comment by Cioppolo14** [comment]
@Atharva-Kanherkar Please fix the failing codecov tests.

**Comment by Atharva-Kanherkar** [comment]
> @Atharva-Kanherkar Please fix the failing codecov tests.

Yes, in a bit.

**Comment by Atharva-Kanherkar** [comment]
@Cioppolo14 @palisadoes This error does not seem to arrive because of my delta files. Could you please look into it or Tigger re-run for the tests? I think the error is because of some other issues in the codebase.

**Pull request merged**
