### PR TITLE
Stable npm test run

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Bug

**Issue Number:**

Fixes #611 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
Not needed

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Sumitra is this fixing https://github.com/PalisadoesFoundation/talawa-api/issues/477 or is it a fix to make sure #477 works correctly?

Did you create an issue for this? We need to follow the procedure

- https://github.com/PalisadoesFoundation/talawa-api/pull/610 @DivyanshuParwal was working on this and we want to make sure his work gets credited too.

**Comment by sumitra19jha** [comment]
> Sumitra is this fixing #477 or is it a fix to make sure #477 works correctly?
> 
> Did you create an issue for this? We need to follow the procedure
> 
> * [Upgrade nanoid to 3.1.31 #610](https://github.com/PalisadoesFoundation/talawa-api/pull/610) @DivyanshuParwal was working on this and we want to make sure his work gets credited too.

I am not working on the @[DivyanshuParwal](https://github.com/DivyanshuParwal) issue. In my local system, I run 2-3 times npm run test` and every time the result was different. So I just copied the code of Divyanshu and checked if the workflow is working now, and it did. But this will not solve the issue as in my local system different errors are coming at a different run. Below is the snapshot:

Screenshot 2022-03-12 at 11 17 17 PM

**Comment by sumitra19jha** [comment]
@palisadoes I will create an issue for this

**Comment by palisadoes** [comment]
Thanks, please don't include the changes @DivyanshuParwal in your final PR.

**Comment by sumitra19jha** [comment]
> Thanks, please don't include the changes @DivyanshuParwal in your final PR.

For sure

**Comment by sumitra19jha** [comment]
@palisadoes Please merge

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
