### PR TITLE
talawa-api typescript migration changes

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

refactoring

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

-

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

Yes

**Summary**

This PR includes the work I did for my first half of GSOC 2022. It includes the initial changes that were to be made for typescript migration of talawa-api. Most of the work is done. The only thing remaining is to migrate resolver functions and their respective tests to typescript and the migration will be complete. Some little refactors here and there could still be made whenever the project demands for it.

**Does this PR introduce a breaking change?**

Yes, this PR introduces many breaking changes. 

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@ttaylor92 @DMills27 Please review

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by xoldyckk** [comment]
@palisadoes The conflicting files are because of how github workflow is written for talawa-api. It needs to be updated for new files  and the process.

**Comment by xoldyckk** [comment]
@palisadoes The conflicts are because of deleted older javascript files and new typescript files. Also the github workflow needs to be reconfigured to work with typescript version.

**Comment by palisadoes** [comment]
When do you think you'll be able to approve and merge this into the code base? @ttaylor92 @JamaicanFriedChicken @DMills27

**Comment by palisadoes** [comment]
1. @xoldyckk Please fix the conflicting files. 
2. @ttaylor92 @taslangraham please review

**Review by taslangraham — APPROVED** [review]
looks alright

**Comment by taslangraham** [comment]
@xoldyckk Please resolve the conflicts

**Comment by xoldyckk** [comment]
@taslangraham I believe the conflicts are because javascript files are deleted and typescript files are added in their place. It's not a problem on my part right?

**Pull request closed without merging**
