### PR TITLE
Fixes access to image from the frontend

### LINKED ISSUE #1626: [Bug]: Post images not loading due to same-origin policy
**Describe the bug**
Image inside the post doesn't render because same-origin policy in server blocks access to image stored inside the images folder on the server.

**To Reproduce**

1. Go to manage organization.
2. Create a post with an image.
3. Reload the page.

**Expected behavior**
Posts along with the image should render.

**Actual behavior**
Images are saved in the database and the backend server but they don't render on the frontend.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by wingman47**
**What kind of change does this PR introduce?**

Bug Fix: Images doesn't render on the frontend because same-origin policy in server blocks access to image stored inside the images folder on the server.

**Issue Number:**

Fixes #1626 

**Snapshots/Videos:**

Before:
image

After:
image

Posts along with the image now renders.

### CODE REVIEW

**Comment by wingman47** [comment]
`removeSampleOrganization.spec.ts` test is failing because of not being able to find an existingOrganization in `removeSampleOrganization.ts` at line 38:
`const existingOrganization = await SampleData.findOne({
      collectionName: "Organization",
    });`
Any idea how to fix this?

**Comment by palisadoes** [comment]
> `removeSampleOrganization.spec.ts` test is failing because of not being able to find an existingOrganization in `/src/resolvers/removeSampleOrganization.ts` at line 38: `const existingOrganization = await SampleData.findOne({ collectionName: "Organization", });` Any idea how to fix this?

Create one

**Comment by xoldyckk** [comment]
@wingman47 fix this using corsOptions:- https://github.com/PalisadoesFoundation/talawa-api/blob/61d4122b769c91d70b59bda26477b35ef773eb81/src/app.ts#L28

the corsOptions variable isn't being used for some reason, make it work and pass it to the cors middleware

**Review by EshaanAgg — APPROVED** [review]

**Review by EshaanAgg — CHANGES_REQUESTED** [review]
Re-requesting to dismiss the previous moot approval.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
