### PR TITLE
Simulated Testing Database

### PR DESCRIPTION
**Pull request by JamarTG**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**
#1368

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Will be included in related frontend changes which will be linked.

**Summary**
Acts as a mock database used for demonstrating the application's features and for efficient testing of the software.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@JamarTG 
1. Please create an issue describing what you are trying to fix and why.
2. Add the issue to this PR so that the issue automatically closes when the PR is merged

Also contact the GSoC contributors about your work. They may have ideas. We want to use the test data in the collection to run tests against.

**Comment by JamarTG** [comment]
> @JamarTG
> 
> 1. Please create an issue describing what you are trying to fix and why.
> 2. Add the issue to this PR so that the issue automatically closes when the PR is merged
> 
> Also contact the GSoC contributors about your work. They may have ideas. We want to use the test data in the collection to run tests against.

Sure, sir

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by JamarTG** [comment]
> Please fix the conflicting files

Good day sir, I don't think the errors are errors on my side

**Comment by palisadoes** [comment]
Please fix the conflicting files. We merged a PR from someone else who edited a file you have submitted. You will need to adjust your code to match the functionality of that PR. @jordan-barrett-jm @JamaicanFriedChicken Please provide guidance.

**Comment by JamarTG** [comment]
New PR : https://github.com/PalisadoesFoundation/talawa-api/pull/1369. I'll be closing this PR

**Pull request closed without merging**
