### PR TITLE
Test for `src/resolvers/Subscription/directMessageChat.ts`

### LINKED ISSUE #892: Test: src/lib/resolvers/Subscription/directMessageChat.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Subscription/directMessageChat.ts `
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Subscription/directMessageChat.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #892 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
I don't know why there is a partial in the code, in my local system, it is 100% , also the codecov is not showing up for the latest commit for some reason.

**Comment by kb-0311** [comment]
@palisadoes I don't understand why the codecov load is failing

**Comment by palisadoes** [comment]
I've been trying to regenerate the CodeCov report. It fails periodically and when it passes the report isn't generated. 

Can you paste a screen shot of your results?

**Comment by kb-0311** [comment]
Yes , here it is ->

Screenshot from 2023-02-02 23-24-43

**Comment by anshgoyalevil** [comment]
> Yes , here it is ->
> 
> Screenshot from 2023-02-02 23-24-43

The 100% branches are not covered.

**Comment by kb-0311** [comment]
@anshgoyalevil - Yes I am aware, the thing is that the implementation of the Subscription resolver itself is not completely fool proof , pls refer to this thread over here - https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1675333096255079

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil - Yes I am aware, the thing is that the implementation of the Subscription resolver itself is not completely fool proof , pls refer to this thread over here - https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1675333096255079

Oh Great. Got it.

**Pull request merged**
