### PR TITLE
[Fixes #1000 Fixes #987] Refactor first 1-40 tests in tests/resolvers/mutation folder

### LINKED ISSUE #987: Refactor: tests/resolvers/Mutation [File 21 to File 40]
This is a child issue to the issue listed here: #971 and #965

- Code need to be refactored for folder ```tests/resolvers/Mutation```
- There are several files in this folder, so the files from 21 to 40 range [CreateOrganization.spec.ts to removeComment.spec.ts]
- There are certain test files in this folder, which do not cover 100% of their respective code. You may ignore them, for this issue.
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issues on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### LINKED ISSUE #1000: Refactor: tests/resolvers/Mutation [File 1 to File 20] [Remove the conditional check process.env !== "PRODUCTION" for requestContext.translate()]
This is a child issue to the issue listed here: #993
- Code need to be refactored for folder ```tests/resolvers/Mutation```
- There are certain test files in this folder, which do not cover 100% of their respective code. You may ignore them, for this issue.
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issues on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/993)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This includes the code refactoring for the 1-40 tests in tests/resolvers/mutation

**Issue Number:**
Fixes #1000
Fixes #987

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Not required

**Summary**
This includes the code refactoring for the 1-40 tests in tests/resolvers/mutation

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@anshgoyalevil Please change the tittle to `Fixes #issue_number : "Original Issue"`

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil Please change the tittle to `Fixes #issue_number : "Original Issue"`

I renamed the title. I am not adding the Fixes {issue_number} anywhere in this PR because, I don't want to close the issue automatically after getting it merged, since this is a 1/3 part for the fix of that issue.

**Comment by noman2002** [comment]
> > @anshgoyalevil Please change the tittle to `Fixes #issue_number : "Original Issue"`
> 
> I renamed the title. I am not adding the Fixes {issue_number} anywhere in this PR because, I don't want to close the issue automatically after getting it merged, since this is a 1/3 part for the fix of that issue.

Create child issues for the Parent so we have a better track of what is done and what needs to be done.  and link that child issue to this PR.

**Comment by anshgoyalevil** [comment]
> > > @anshgoyalevil Please change the tittle to `Fixes #issue_number : "Original Issue"`
> > 
> > 
> > I renamed the title. I am not adding the Fixes {issue_number} anywhere in this PR because, I don't want to close the issue automatically after getting it merged, since this is a 1/3 part for the fix of that issue.
> 
> Create child issues for the Parent so we have a better track of what is done and what needs to be done. and link that child issue to this PR.

Okay. Sure

**Comment by anshgoyalevil** [comment]
> > > @anshgoyalevil Please change the tittle to `Fixes #issue_number : "Original Issue"`
> > 
> > 
> > I renamed the title. I am not adding the Fixes {issue_number} anywhere in this PR because, I don't want to close the issue automatically after getting it merged, since this is a 1/3 part for the fix of that issue.
> 
> Create child issues for the Parent so we have a better track of what is done and what needs to be done. and link that child issue to this PR.

Done Sir.

**Pull request closed without merging**
