### PR TITLE
Fixes issue #235

### LINKED ISSUE #235: Add and test GitHub action to lint all PRs before submission
We need to lint all code as part of the pull request process. 

1. The commands for the actions file can be found at the beginning of the documentation of this [outdated GitHub action](https://github.com/marketplace/actions/run-eslint)
1. We will need the action to be activated only on a pull request. [We have an example of how to do that in the Talawa repo](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/linter.yml)
1. Make the action be defined in a file named `linter.yml`

Test and make sure it doesn't break the code. Try running the linter on the code base as proof.

### PR DESCRIPTION
**Pull request by mihdas**
**What kind of change does this PR introduce?**
Adder linter.yml in .github/workflows

**Did you add tests for your changes?**
No, but tested with existing files

**If relevant, did you update the documentation?**
Not relevant
**Summary**

fixes #235 
**Does this PR introduce a breaking change?**
No

**Other information**
None.

### CODE REVIEW

**Review by DangaRanga — COMMENTED** [review]
The linter seems to be working, but you may want to resolve the errors that appeared after linting before merging.

**Comment by mihdas** [comment]
@DangaRanga I did try to lint the file which is causing the error [chats.spec.dev.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/tests/dist/chats.spec.dev.js). However, it doubled the errors caught by the linter. Might have been due to the fact that my local eslint configuration is different from that of the [Github action](https://github.com/marketplace/actions/run-eslint)

**Comment by palisadoes** [comment]
@mihdas the eslint issue was resolved by @DangaRanga. Please merge your code and resubmit. If it fails please work with @DangaRanga for the resolution.

**Comment by palisadoes** [comment]
@mihdas [The linter is failing repeatedly](https://github.com/PalisadoesFoundation/talawa-api/pull/239/checks?check_run_id=2646942628). You will need to make sure the code complies with the new standard.

**Comment by mihdas** [comment]
@palisadoes The linter is working fine. I deleted [chats.spec.dev.js](https://github.com/PalisadoesFoundation/talawa-api/blob/master/tests/dist/chats.spec.dev.js) in my local branch and the linter worked smoothly. [Click here to see](https://github.com/mihdas/talawa-api/pull/12/checks). The file in question [(chats.spec.dev.js)](https://github.com/PalisadoesFoundation/talawa-api/blob/master/tests/dist/chats.spec.dev.js) has not been changed since [25th March](https://github.com/PalisadoesFoundation/talawa-api/commit/99edb23eb45d0d95343628b5e4970894f654dde2).

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
