### PR TITLE
[Feature Request] Forgot Password, OTP, and Recaptcha for Talawa-admin added

### LINKED ISSUE #717: [Feature Request] New Features for Talawa-admin
**Is your feature request related to a problem? Please describe.**

Currently, in Talawa-admin, the feature for forgetting passwords is not present, and while logging in or signup there is no captcha to detect the bot activity. Also, there is no feature that exists in talawa-admin to allow only authorized admins and the current super admin is not able to create new super admins. For more info PalisadoesFoundation/talawa-admin#342

**Describe the solution you'd like**

* Mailer will be configured to send OTP mails to the user.
* Google Recaptcha backend endpoint will be configured.
* Resolvers for forgotten passwords, verify google Recaptcha, and OTP will be implemented.
* A mutation will be added in order to toggle the roles of users.
* A new field will be added in the user model name ‘adminApproved’ to verify whether the user is an authorized admin or not.
* A mutation will be added in order to accept or reject the request of an admin.
* A new field will be added in the organization model name ‘tags’ to store the tags of an organization.
* A new field will be added in the user model name ‘createdAt’ to track the time when a user is created. This data will be useful while displaying users in the talawa-admin.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #717

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

* Google Recaptcha verification
  image

* Requesting for OTP
  image

* OTP received on email
  Screenshot 2022-06-13 at 17-39-19 OTP for Talawa-admin forgot password - asmitsirohi9761@gmail com - Gmail_LI

* Forget Password
  image

**If relevant, did you update the documentation?**

Yes

**Summary**

This Pull request is the changes in the backend regarding PalisadoesFoundation/talawa-admin#343.

In this, the following things are implemented,

* Mailer is configured to send OTP mails to the user.
* Google Recaptcha backend endpoint is configured.
* Resolvers for forgotten passwords, verify google Recaptcha, and OTPis implemented.
* Documentation is updated regarding mailer credentials and google Recaptcha key. 

**Does this PR introduce a breaking change?**

No

**Other information**

This pull request is under GSoC'22.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Asmit. Have you made these features optional? 

We need to make sure that basicTalawa installation doesn't require accounts with multiple third party providers.

The GSoD participants need to know about three installation changes too. Please notify them on the #gsoc channel.

**Comment by asmitsirohi** [comment]
> Asmit. Have you made these features optional?
> 
> We need to make sure that basicTalawa installation doesn't require accounts with multiple third party providers.
> 
> The GSoD participants need to know about three installation changes too. Please notify them on the #gsoc channel.

Yes, It may be optional if talawa-API is used only in the talawa mobile app but for the talawa-admin these are mandatory.

Okay, I will notify about the changes in the #gsoc channel.

**Comment by asmitsirohi** [comment]
@palisadoes @yasharth291, The failed tests are from the package marked and marked-terminal which are used to set up a project automatically. These are independent of changes I have made, I am not able to figure out odd in this case. Any assistance is appreciable. 

Although the fixes working in my local machine perfectly.

* Error
image

**Comment by guptapriyanshu7** [comment]
Hey @asmitsirohi, I think we are using outdated versions of marked and marked-terminal, they are available at v4 and v5 respectively but we are currently using v2 and v4. Try to update these packages maybe it helps.

**Comment by asmitsirohi** [comment]
> Hey @asmitsirohi, I think we are using outdated versions of marked and marked-terminal, they are available at v4 and v5 respectively but we are currently using v2 and v4. Try to update these packages maybe it helps.

Thanks, @guptapriyanshu7 It helps.

**Review by yasharth291 — DISMISSED** [review]

**Comment by yasharth291** [comment]
@palisadoes  please merge it

**Comment by palisadoes** [comment]
@asmitsirohi Why has the code coverage percentage declined?

**Comment by asmitsirohi** [comment]
> @asmitsirohi Why has the code coverage percentage declined?

It was fixed in the last commit. That's why all the checks passed.

**Comment by asmitsirohi** [comment]
@palisadoes sir, please merge this pull request. Without merging this pull request it is difficult for me to complete future tasks.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
The code coverage has declined. Please write a test suite for this feature.

**Review by palisadoes — CHANGES_REQUESTED** [review]
The code coverage has declined. Please write a test suite for this feature.

**Comment by asmitsirohi** [comment]
@palisadoes please check the coverage now.

**Pull request closed without merging**
