### PR TITLE
Role Update Audit Logging System

### LINKED ISSUE #2147: Implement Fallback Mechanism and Audit Logging for Profile Edits
**Is your feature request related to a problem? Please describe.**
In light of recent security vulnerabilities discovered, #2131, we should implement a robust **fallback/recovery** mechanism and an **audit logging** system to enhance the security and integrity of user profile management.

Users may lose access to their accounts due to unauthorized profile changes, especially in roles and permissions. We need to implement a recovery mechanism that allows users to restore access to their accounts.

**Recovery Options:** 
Provide users with options to recover their accounts via email verification or security questions.

### Audit Logging System
To track and ensure the authorized use of profile editing capabilities, an audit log should be maintained. It will record every change made to user profiles along with who made the change.

#### Suggested Features:

1. **Log Entries:** Capture the timestamp, user ID of the editor, affected user ID, and a description of the change.
2. **Alert System:** Notify original users and admins of changes made to profiles, especially role changes.

### Use Cases
1. **SuperAdmins**: Should be able to edit all profiles and have access to audit logs and recovery options.
2. **Admins**: Can edit profiles at or below their access level, except SuperAdmin profiles. They should have access to recovery options but limited access to audit logs.
3. **Users/Members**: Limited to editing their own profiles with simplified recovery options and no access to audit logs.

### Questions/Considerations:

1. What would be the criteria for triggering a temporary account lockdown?
2. How long should audit logs be retained?
3. Should there be an escalation process for disputed profile changes?

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**
This PR introduces an audit logging system to enhance the security and integrity of user profile management, addressing the concerns raised in issue #2147 

**Issue Number:**

Fixes #2147

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
image

image

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by krishna619** [comment]
We further need to discuss key points here:
1) How should we implement recovery mechanism incase a user loses his/her account.
2) How long should audit logs be retained considering legal and operational requirements?
3) Under what conditions should temporary lockdowns be triggered?

**Comment by pranshugupta54** [comment]
It was decided to take Audit loggings in future and not now.
> https://github.com/PalisadoesFoundation/talawa-api/issues/2195#issuecomment-2051645951

We had plan of making a separate page for Audit logs with filtering options.

**Comment by Cioppolo14** [comment]
@krishna619 Please fix the failing tests.

**Comment by meetulr** [comment]
> It was decided to take Audit loggings in future and not now.

Yes, shouldn't something like this be planned first? A separate model just for user role audits? We would need a standard approach for handling audits for everything (most things).

**Comment by krishna619** [comment]
Closing till we all decide on a standard approach.

**Pull request closed without merging**
