### PR TITLE
Renamed isPublic to userRegistrationRequired in sample-data and added import-sample-data generator github actions

### LINKED ISSUE #1685: Create GitHub Action to Import Database for PR Testing
**Describe the bug**

1. Running the command `npm run import:sample-data` fails
2. This is due to an update in the DB schema which is not compatible with our sample data
3. We also don't have the ability to automatically test the command as part of our PR approval process

**To Reproduce**

1. Run `npm run import:sample-data`
2. Failure

**Expected behavior**
 
1. The sample data must be modified to accommodate the new DB schema where the `userRegistrationRequired` field now replaces the `isPublic` field. The logic of `userRegistrationRequired` is opposite of `isPublic` therefore `True` will replace `False` and vice versa for these fields in the data update.
    1. Data importation must succeed without error
1. A GitHub must be created to import the data as part of the PR YAML file.
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml
    1. This must occur after running the test suite and before the code coverage is calculated
     1. The GitHub action pass this stage of the workflow

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- https://github.com/PalisadoesFoundation/talawa/pull/2322#issuecomment-1890647988
- https://github.com/PalisadoesFoundation/talawa-api/issues/1604#issuecomment-1890876772

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aialok**
**What kind of change does this PR introduce?**

- Bug Fix: Renamed isPublic to userRegistrationRequired in sample-data
-  Added `npm run import:sample-data` in github actions

**Issue Number:**

Fixes #1685 

**Did you add tests for your changes?**

- No

**Snapshots/Videos:**

[cinnamon-2024-01-14T225802+0530.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/66772290/ceb1fdbc-d2b8-4e36-b303-a17e4212bdad)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by aialok** [comment]
> Just to confirm, the DB importation doesn't require the API to be running correct?

I don't have much idea about this but if importing this will create sample organisation in real mongoDB cluster then it might create problem for us because we have hard-coded the _id in sample data json file and if another one try to merge PR then it might throw error of duplicate ID.

Please correct me if I am wrong.

**Comment by palisadoes** [comment]
I meant for the purposes of the PR workflow. We should be OK correct?

**Comment by aialok** [comment]
> I meant for the purposes of the PR workflow. We should be OK correct?

But if it really creating a sample-data in real mongoDB cluster then it will throw error for sure.

**Comment by aialok** [comment]
> I meant for the purposes of the PR workflow. We should be OK correct?

If this sample-data is for the development purpose only then I think there is no need of putting it into github-actions workflow.

**Comment by palisadoes** [comment]
We need it in the workflow to make sure that the sample data loads correctly every time. We have regular schema changes and this will make sure the person submitting the PR knows the test data is valid.

We are OK

**Comment by aialok** [comment]
> We need it in the workflow to make sure that the sample data loads correctly every time. We have regular schema changes and this will make sure the person submitting the PR knows the test data is valid.
> 
> We are OK 

Ok : )

**Comment by Dante291** [comment]
@palisadoes @aialok  Even though this PR has got merged but sampledata is still not updated in the codebase, check [here](https://github.com/PalisadoesFoundation/talawa-api/blob/main/sample_data/organizations.json) it still has isPublic field in Organisation document.

**Comment by Azad99-9** [comment]
Yes somehow the sample data has not updated. The last commit for respective files is 9 months ago.

**Comment by aialok** [comment]
> @palisadoes @aialok  Even though this PR has got merged but sampledata is still not updated in the codebase, check [here](https://github.com/PalisadoesFoundation/talawa-api/blob/main/sample_data/organizations.json) it still has isPublic field in Organisation document.

You guys are checking in main branch.
In develop branch it is already updated.

**Comment by Azad99-9** [comment]
https://github.com/PalisadoesFoundation/talawa-api/pull/1714#issue-2087516399 this `revert` has caused the alteration of the sample date. @palisadoes @Dante291 @aialok.

**Comment by Dante291** [comment]
> > @palisadoes @aialok  Even though this PR has got merged but sampledata is still not updated in the codebase, check [here](https://github.com/PalisadoesFoundation/talawa-api/blob/main/sample_data/organizations.json) it still has isPublic field in Organisation document.
> 
> You guys are checking in main branch. In develop branch it is already updated.

Ok we got confused as in Mobile the default branch is Develop thought its the same for API repo too and didnt check. Thanks for clarifying Alok

**Comment by Dante291** [comment]
> > @palisadoes @aialok  Even though this PR has got merged but sampledata is still not updated in the codebase, check [here](https://github.com/PalisadoesFoundation/talawa-api/blob/main/sample_data/organizations.json) it still has isPublic field in Organisation document.
> 
> You guys are checking in main branch. In develop branch it is already updated.

Thanks for clarifying Alok.

**Pull request merged**
