### PR TITLE
feat: fix formatting before commit

### LINKED ISSUE #1778: add formatting pre-commit check
**Is your feature request related to a problem? Please describe.**
We don't check correct prettier formatting of code before commit, though we do have lint checks.

**Describe the solution you'd like**
Use the scripts defined in package.json and check for formatting before every commit.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by LakshyaSatpal**
**What kind of change does this PR introduce?**
This PR adds a pre-commit script run, to fix formatting

**Issue Number:**

Fixes #1778 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@LakshyaSatpal Please fix the failing tests.

**Comment by Cioppolo14** [comment]
You may need to merge with the latest upstream.

**Comment by LakshyaSatpal** [comment]
My branch up to date with develop. The error in tests is unrelated to my changes.
I think, the problem is `package.json` does not include `ts-node` as a dependency, and `import:sample-data` script is directly using it.

**Comment by palisadoes** [comment]
Please restore the ts-node dependency in this PR.

**Comment by LakshyaSatpal** [comment]
I see `lint-staged` is configured to format the staged files on a commit.

**Comment by LakshyaSatpal** [comment]
@palisadoes Tests are passing now.

**Comment by palisadoes** [comment]
1. What was changed in this PR? 
2. Was it just the restoration of the `ts-node` package?
3. What PR removed `ts-node` in the first place?

**Comment by palisadoes** [comment]
Merging. Something isn't right

**Pull request merged**
