### PR TITLE
fix: remove `adminApproved` field and its usage

### LINKED ISSUE #2122: [userTypeFix] Removal of adminApproved field
**Describe the bug**
- `adminApproved` field is not being used anymore after the change in userType.
- Remove all the code using it.

**Actual behavior**
Every feature should be working, tests and code coverage.

**Screenshots**
NA

**Additional details**

1. We are using `userRegistrationRequired` bool for checking approval in Org. 
2. `membershipRequests` array for list of pending users in Org.
3. `adminApproved` was earlier used for orgs but it's global.
4. All tests must pass and be valid
5. No other functionality must be affected

**References:**

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1845
2. https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1711717178931399

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
### What kind of change does this PR introduce?

It removes the uses and references of the `adminApproved` field.

### Issue Number:

Fixes #2122 

### If relevant, did you update the documentation?

Yes

### CODE REVIEW

**Comment by Olatade** [comment]
@meetulr please fix failing tests

**Comment by meetulr** [comment]
> @meetulr please fix failing tests

The failing test is because of a recent `eslint` upgrade. There's an issue open to address [link](https://github.com/PalisadoesFoundation/talawa-api/issues/2146). I'll merge with upstream as soon as it's resolved.

**Comment by palisadoes** [comment]
Please update with the latest upstream. It's Fixed.

- https://github.com/PalisadoesFoundation/talawa-api/issues/2146

**Comment by meetulr** [comment]
This is ready.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
