### PR TITLE
Added README.md for typeDefs directory and restructured the files into corresponding SDL fields.

### LINKED ISSUE #1050: Refactor/Feature:- Add README.md for typeDefs directory and restructure the files.
**Is your feature request related to a problem? Please describe.**

`typeDefs` directory is very cluttered and hard to work with. There's no particular ordering of things and requires additional mental overhead to work with.

**Describe the solution you'd like**

Restructure the `typeDefs` directory into files according to the `graphQL SDL` fields they represent. Add `README.md` for the directory mentioning some important details for the future contributers who want to work on that directory.

**Describe alternatives you've considered**

 -

**Approach to be followed (optional)**

 -
 
**Additional context**

Here's what it will look like after the restructure:-
structure

Here's the README.md file:-
README md

**Potential internship candidates**
 -

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:**

Fixes #1050

**Did you add tests for your changes?**

 No

**Snapshots/Videos:**
structure

README

**If relevant, did you update the documentation?**

 -

**Summary**

Restructured the typeDefs directory into files according to the graphQL SDL fields they represent. Add README.md for the directory mentioning some important details for the future contributers who want to work on that directory.

**Does this PR introduce a breaking change?**

 -

**Other information**

More improvements to README.md could be made.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

 Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
There is a theme here of a PR experience for the developer.

1. Do we have, `iGraphQL` functionality for the API?
1. How could it best be implemented if not?
1. We should also consider adding attribute descriptions for all the stems definitions to make `iGraphQL`more usable

It's probably out of scope for this PR, but we should create an issue to verify this functionality

**Comment by xoldyckk** [comment]
@palisadoes what is IGraphql?

**Comment by palisadoes** [comment]
It is a featured with `python-graphene` that allows you to use an `/igraphql` webserver endpoint to do interactive GraphQL queries like this. It's very useful.

image

**Comment by xoldyckk** [comment]
> 1. It is a featured with `python-graphene` that allows you to use an `/igraphql` webserver endpoint to do interactive GraphQL queries like this. It's very useful.
> 2. When you set the attribute help text in the schema, iGraphQL will also give you the help text as you add the new nodes to the interactive query
>    image

This is already present in talawa-api. It's done using graphql-playground.

**Comment by palisadoes** [comment]
Unfortunately, it's not documented. Can you create an issue for someone to add it to CONTRIBUTING.md?

**Comment by xoldyckk** [comment]
It's actually called `GRAPHIQL` not `IGRAPHQL`.

**Comment by xoldyckk** [comment]
> Unfortunately, it's not documented. Can you create an issue for someone to add it to CONTRIBUTING.md?

Documenting the graphQL schema is not only beneficial for the interactive playground but also for documenting talawa-api docs website. This one https://docs.talawa.io/talawa-api/schema/index.html.

**Comment by xoldyckk** [comment]
> Unfortunately, it's not documented. Can you create an issue for someone to add it to CONTRIBUTING.md?

U mean telling contributers about the playground?

**Comment by palisadoes** [comment]
> > Unfortunately, it's not documented. Can you create an issue for someone to add it to CONTRIBUTING.md?
> 
> U mean telling contributers about the playground?

Yes. And letting them know to access it for the API

**Comment by palisadoes** [comment]
@Tajcore @Kevoniat please review

**Comment by palisadoes** [comment]
@noman, please review. Also what are your thoughts on documenting the playground?

**Comment by noman2002** [comment]
> @noman, please review. Also what are your thoughts on documenting the playground?

I think it a very good idea to document the playground as it will increase the readability and make it easier for everyone.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
