### PR TITLE
Signup route changed

### PR DESCRIPTION
**Pull request by Manik2708**
**What kind of change does this PR introduce?**

1) As per the need, now responsibility of creating a fresh member is shifted to `Admin` of organization from `Super Admin`.
2) Fixes the issue that previously `adminApproved` was only for testing purpose but now will be used for authenticating whether user is actually Admin approved or not.
3) `acceptMemeberShip` mutation is also modified to approve the user if it's his first request.
4) `@ts-ignore` and `delete` operand  was used before to delete the password from `createdUser`, now `omit` method is used by creating a separate interface of the user which doesn't consists password.  

**Issue Number:**

Fixes  #1703 

**Did you add tests for your changes?**

 Yes

**Snapshots/Videos:**

New SignUp Route

Screenshot from 2024-01-24 14-17-51

New Accept Membership Request Route

Screenshot from 2024-01-24 14-17-27

Query with output, when user tries to signUp with Organization that doesn't require User Registration

The organization which was used in above query

Query with output, when user tries to signUp with Organization that require User Registration

The default organization, which was also used in above query

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

Yes, I have tried to make the system more secured by using `adminApproved` flag.
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

 Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please update `setup.js`. If the user decides not to use the sample data, and the database contains no organizations, then the default organization needs to be created. There must always be at least one organization in the database

**Comment by palisadoes** [comment]
The flow is as expected. Thanks.

**Comment by Manik2708** [comment]
Please see the problem and flow of setting up project now:

Screenshot from 2024-01-25 01-55-45

If resetup is also required then an automation logic should be implemented to format database before setup but it will lead to loss of data. Also `Installation.md` file should also be edited if the newly added script logic is fine!

**Comment by Manik2708** [comment]
> Please see the problem and flow of setting up project now:
> 
> Screenshot from 2024-01-25 01-55-45
> 
> If resetup is also required then an automation logic should be implemented to format database before setup but it will lead to loss of data. Also `Installation.md` file should also be edited if the newly added script logic is fine!

Please let me know the problem in this approach and if not then I can proceed with editing the `Installation.md` file!

**Comment by palisadoes** [comment]
1. Importing setup data currently overwrites the existing database. You can do the importation multiple times without conflicts.  Please confirm.
1. If the script isn't importing test data and the script detects at least one organization is detected, then the default organization must not be imported.

The developer must not need to do any manual database updates to get started with the repos. We had this before and it required excessive support with our communiy members.

**Comment by Manik2708** [comment]
Please see the new setup route:

Screenshot from 2024-01-25 18-18-07

Also I think the newly added function in `utilities` need to be ignored by codecov. As I can't find tests for `loadSampleData` also. Please inform me if Tests are to be written for the new function. Also if this is ready for merging then I have to update `Installation.md` file also.

**Comment by palisadoes** [comment]
image

**Comment by Manik2708** [comment]
> image

But as per the need no matter, whether Developer want to import data or not there should be a default organization in the database. If user selects not to import data then there would be 0 organizations in DB which is contradictory to the need.

**Comment by Manik2708** [comment]
> > image
> 
> But as per the need no matter, whether Developer want to import data or not there should be a default organization in the database. If user selects not to import data then there would be 0 organizations in DB which is contradictory to the need.

A wiping question needed to be asked from the developer if data is there because that's how `importData` function is working. We can follow a new route to avoid this question when data is already there!

**Comment by palisadoes** [comment]
OK

If the DB is empty then the person running the script should be asked to import the sample data, if sample data is not desired then the default should be imported.

If the DB is not empty, then there should be three options to overwrite with sample data. If no, then do nothing

**Comment by Manik2708** [comment]
> OK
> 
> If the DB is empty then the person running the script should be asked to import the sample data, if sample data is not desired then the default should be imported.
> 
> If the DB is not empty, then there should be three options to overwrite with sample data. If no, then do nothing

Is this what you are saying?

Screenshot from 2024-01-26 11-26-06

If data is already there, then return with doing nothing, else import the data!

**Comment by palisadoes** [comment]
I updated my comment. There were a few typos. It will be clearer now.

**Comment by Manik2708** [comment]
The new route: 

Screenshot from 2024-01-26 19-41-20

**Comment by palisadoes** [comment]
Yes, this is the correct setup flow

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Manik2708** [comment]
I can't see the reason for type errors. Is `require` changed to `import` ? Or it should be kept `require`?

**Comment by palisadoes** [comment]
> I can't see the reason for type errors. Is `require` changed to `import` ? Or it should be kept `require`?

Use `import`, the existing standard in the file.
- https://flexiple.com/javascript/javascript-require-vs-import#section2

**Comment by Manik2708** [comment]
> > I can't see the reason for type errors. Is `require` changed to `import` ? Or it should be kept `require`?
> 
> Use `import`, the existing standard in the file.
> 
>     * https://flexiple.com/javascript/javascript-require-vs-import#section2

Please trigger the workflow!

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by Manik2708** [comment]
> ## [Codecov](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> 
> Attention: `62 lines` in your changes are missing coverage. Please review.
> 
> > Comparison is base [(`c0468a4`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/commit/c0468a48fa452b2b92f74599c4f6f0c9e5869019?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 98.17% compared to head [(`2002b50`)](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 97.63%.
> > Report is 195 commits behind head on develop.
> 
> [Files](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) 	Patch % 	Lines
> [src/resolvers/Mutation/updateUserProfile.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi91cGRhdGVVc2VyUHJvZmlsZS50cw==) 	70.90% 	[1 Missing and 15 partials ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Mutation/createEvent.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9jcmVhdGVFdmVudC50cw==) 	83.51% 	[13 Missing and 2 partials ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/middleware/currentUserExists.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9taWRkbGV3YXJlL2N1cnJlbnRVc2VyRXhpc3RzLnRz) 	45.83% 	[13 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Mutation/createPost.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9jcmVhdGVQb3N0LnRz) 	90.32% 	[6 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Mutation/createOrganization.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9jcmVhdGVPcmdhbml6YXRpb24udHM=) 	95.40% 	[4 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Mutation/removeAdvertisement.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9yZW1vdmVBZHZlcnRpc2VtZW50LnRz) 	92.85% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Mutation/signUp.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9zaWduVXAudHM=) 	98.13% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [...c/resolvers/Query/postsByOrganizationConnection.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9RdWVyeS9wb3N0c0J5T3JnYW5pemF0aW9uQ29ubmVjdGlvbi50cw==) 	33.33% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/helpers/eventInstances/weekly.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2hlbHBlcnMvZXZlbnRJbnN0YW5jZXMvd2Vla2x5LnRz) 	98.11% 	[1 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> [src/resolvers/Query/postsByOrganization.ts](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9RdWVyeS9wb3N0c0J5T3JnYW5pemF0aW9uLnRz) 	0.00% 	[1 Missing ⚠️ ](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1741?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation).

Actually I have edited only two files in this PR and have written extra test cases for them. Rest of the files are committed as a result of resolving conflicts. If you say, I can write tests for these files also but I think this PR needs to be merged urgently  as Admin and Mobile repos are waiting for this PR.

**Comment by palisadoes** [comment]
1. Thanks for the explanation of the cause of the coverage errors. That is instructive.
2. I'll merge without other reviewers as an exception.
3. If there are post merge errors, you will need to fix them. I don't want to revert.

**Review by palisadoes — APPROVED** [review]

**Comment by Manik2708** [comment]
> 1. Thanks for the explanation of the cause of the coverage errors. That is instructive.
> 2. I'll merge without other reviewers as an exception.
> 3. If there are post merge errors, you will need to fix them. I don't want to revert.

For sure, I am always there for fixing the errors! Thanks!

**Pull request merged**
