### PR TITLE
Fixed pre-login imagery APIs

### LINKED ISSUE #2014: Fix: Support for pre-login imagery
**Describe the bug**
In the recent PR #1935 which got merged recently, there are some bugs. So I am creating this PR to resolve those bugs.

**Additional details**
I am working on [this PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1649) which needs fixing of the bugs in the API.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
**What kind of change does this PR introduce?**
Bug Fix.

**Issue Number:**

Fixes #2014 

**Did you add tests for your changes?**
Yes

**If relevant, did you update the documentation?**
N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by git-init-priyanshu** [comment]
Please don't merge this PR right now. I am testing this PR against my frontend code.

**Comment by git-init-priyanshu** [comment]
This PR is ready to be merged if it is approved.

**Comment by Huy1996** [comment]
@SiddheshKukade @EshaanAgg Could you review this PR?

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by git-init-priyanshu** [comment]
> We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.
> 
> They need to assigned on a per organization basis versus per API instance. This is the tracking issue.
> 
> * [PARENT ISSUE: Fix the usage of userType #1965](https://github.com/PalisadoesFoundation/talawa-api/issues/1965)
> 
> Reviews of PRs for all branches will continue

So what do I need to do sir?

**Comment by palisadoes** [comment]
Hold on for a day or two. There will be some merge conflicts. We need to get this functionality implemented and the pause is necessary

**Comment by git-init-priyanshu** [comment]
> Hold on for a day or two. There will be some merge conflicts. We need to get this functionality implemented and the pause is necessary

Ok sir.

**Comment by git-init-priyanshu** [comment]
Hey @palisadoes Is the issue fixed?

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
