### PR TITLE
Separate testing database

### LINKED ISSUE #964: Feature Request: Separation of testing database
**Is your feature request related to a problem? Please describe.**
Currently the same database is being used for managing the user data as well the test data. This is not desirable, as every time the tests are run, the database gets bloated with objects which are not going to be used by the user anytime soon. 

**Describe the solution you'd like**
To make the database and production system system ready, I would like to propose a two step solution. 
1. Add another environment variable to store a database connection to a `MONGO_TEST` database which should be used for testing.
 
Some relevant points:-
- If the user does not have the testing database set, we can default to the main database for testing.
- In all of the files, only the `.connect()` method would need to be changed with a `.connectTest()` method, which will open the connection to the test database instead of the main database.

2. Deletion of the objects created during testing in the `afterAll` clause of each of the tests must also be done. This must be done to ensure that even the testing database does not become bloated with stale data. This would allow us to up the integrity of our API testing, as we should ensure that the state of our database before and after running the test should be EXACTLY the same. If any test would fail, the data would be directly present in the testing database, and would help the developers to debug the API.

The second step is somewhat of a long project, which can be done on a per test file basis, as was done with code coverage. The implementation of the same would help debugging for developers in the future as new features are added, and make for better and scalable experience.

**Approach to be followed (optional)**
Described above

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Separates the testing database from the primary database.

**Issue Number:**
Fixes #964 

**Did you add tests for your changes?**
Tested the functionality manually.

**Snapshots/Videos:**

### Before Testing
before
(Only test-talawa exists, which is my primary database)

### After running `npm run test`
image
(test-talawa_TEST is automatically created and fillled with the testing data)

image
(All tests are still pass)

image
(`NODE_ENV` returns back to `undefined` as soon as the testing command is complete)

**If relevant, did you update the documentation?**
Yes.
Updated documentation in the `INSTALLATION.md`

**Does this PR introduce a breaking change?**
No

**Other information**
1. Added caution message about this functionality in the section about `testing` in `INSTALLATION.md`.
2. No changes in GitHub Action needed as it itself uses the `npm run test` script, thus the maintainers with access to the `MONGO_DB` database can indeed verify all the data is only added to a newly created testing database.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by noman2002 — COMMENTED** [review]
Changes looks good to me. Please attach a screenshot for coverage of db.ts

**Comment by EshaanAgg** [comment]
@noman2002 I don't think so `db.ts` is included in the coverage as no test file exists for it.

**Comment by noman2002** [comment]
Got it.

**Review by noman2002 — DISMISSED** [review]
Looks good to me.

**Comment by xoldyckk** [comment]
@EshaanAgg This is too much complication for no reason. Instead of this just edit the `connect` function in `db.ts` to accept an optional `dbName` argument. Each test can then pass a `dbName` argument to the `connect` function to change database used for testing.

**Review by xoldyckk — CHANGES_REQUESTED** [review]
@EshaanAgg This is too much complication for no reason. Instead of this just edit the connect function in db.ts to accept an optional dbName argument. Each test can then pass a dbName argument to the connect function to change database used for testing.

In mongoose.connect(uri, options) options object accepts an optional field called dbName to use a custom database instead of the default one provided in .env file. The database will be accessible on the same port under the name we provide for dbName.

**Comment by EshaanAgg** [comment]
@xoldyckk The whole point of setting up the `NODE_ENV` as `testing` was to ensure that we didn't need to manually change the database for each test, and we can do it at a centralized location, in the connect function. This was the workflow that was decided with @palisadoes.

Still, if you feel that the optional argument method is better, you can let me know and I'll make the necessary changes today.

**Comment by xoldyckk** [comment]
@EshaanAgg Your implementation is also error prone. You can't just append `_TEST` to the end of a connection string. Connection string comes in different formats, you can't just expect it to always end with a database name.

**Comment by EshaanAgg** [comment]
I wasn't aware of this. Thanks, @xoldyckk for this pointer. Would migrate all the tests to use the optional database name parameter. 
Is `TALAWA_TESTING_DB` alright for the optional DB_NAME to be used in the tests?

**Comment by xoldyckk** [comment]
> 

Yeah

**Comment by xoldyckk** [comment]
> I wasn't aware of this. Thanks, @xoldyckk for this pointer. Would migrate all the tests to use the optional database name parameter. Is `TALAWA_TESTING_DB` alright for the optional DB_NAME to be used in the tests?

Yeah

**Comment by palisadoes** [comment]
> > I wasn't aware of this. Thanks, @xoldyckk for this pointer. Would migrate all the tests to use the optional database name parameter. Is `TALAWA_TESTING_DB` alright for the optional DB_NAME to be used in the tests?
> 
> Here's what I suggest. Use the `NODE_ENV=testing` no problem. Check against that environment variable inside `connect` function. If `NODE_ENV === "testing"` results in `true` use the `dbName` method I mentioned.

Also, tests must only be run on the test database. Under no circumstance should tests operate on a non test database. I understand passing the db name in the function, but that may be too much flexibility for something that could potentially incapacitate a production database.

**Comment by EshaanAgg** [comment]
> Here's what I suggest. Use the `NODE_ENV=testing` no problem. Check against that environment variable inside `connect` function. If `NODE_ENV === "testing"` results in `true` use the `dbName` method I mentioned.

Makes the most sense. Allows us to get the best of both worlds. Will try to implement till. This would also help to mitigate @palisadoes's concern that we must not accidentally modify the production database while testing.

**Comment by EshaanAgg** [comment]
@palisadoes @xoldyckk 
Have made the required changes. Added checks to ensure that we can only connect to the custom database if and only if the environment is set to `testing`. Also updated the README.md about the same and linted files which weren't linted properly in the recent commits.

**Comment by EshaanAgg** [comment]
Can the maintainers rerun the test workflow on this PR? All the tests are passing locally.

**Comment by palisadoes** [comment]
You have done something to lower the overall level of code coverage. Please investigate and fix.

**Comment by EshaanAgg** [comment]
@palisadoes Reverted the changes in the affected files.

**Comment by palisadoes** [comment]
@xoldyckk and @noman2002 Please provide feedback and approve the PR if applicable.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Resolve the conflicting files.

**Comment by EshaanAgg** [comment]
The conflicts are due to the recently merged PRs. It would be easier for me to open a new PR and modify the code there. Thus I am closing this PR here.

**Pull request closed without merging**
