### PR TITLE
Add node modules caching to Github workflow

### LINKED ISSUE #1471: Feature Request: Cache npm dependencies in workflows
**Is your feature request related to a problem? Please describe.**
We can cache the `node_modules` folder in workflows with artifacts to ensure faster workflow runs. 

**Describe the solution you'd like**
[Refer to this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Veer0x1**
**What kind of change does this PR introduce?**
This change adds node modules caching to the Github workflow (pull-request.yml) to speed up CI runs. By using the 'actions/cache' Github action and keying off the 'package-lock.json' file, it's ensured that unnecessary re-installations of dependencies are avoided. If the cache is missed, a debug command to list the state of node modules is run.

**Issue Number:**

Fixes #1471

**Did you add tests for your changes?**
No

### CODE REVIEW

**Review by EshaanAgg — CHANGES_REQUESTED** [review]
- We do need the `npm list` step.
- The changes to use this cache must be made in all the relevant workflows.

You can take a look at the workflows implemented in Talawa admin to see a reference as to how the same is to be done. [Ref](https://github.com/PalisadoesFoundation/talawa-admin/pull/1162)

**Comment by Veer0x1** [comment]
@EshaanAgg just to confirm do you need the `npm list` or not? Coz the reference you provide, there you said to remove this step.

**Comment by EshaanAgg** [comment]
We do not need the same. Sorry for the confusion.

**Comment by palisadoes** [comment]
We have to close this PR. You have modified 379 files when only a few should have been updated. 

Closing

**Comment by Veer0x1** [comment]
That's my bad; I don't know how talawa-api-docs folder got committed. Let me make a clean pull request.

**Pull request closed without merging**
