### PR TITLE
solving issues: #578 and #579

### PR DESCRIPTION
**Pull request by ebrahim354**
**What kind of change does this PR introduce?**
bugfix, tests.

**Issue Number:**

fixes: #578 and #579

**Did you add tests for your changes?**
yes

**Other information**
checking of  the user and organization existence  throws an error from the database directly without using the error system of the api this was resulting after adding tests for both the block and unblock files.

### CODE REVIEW

**Comment by jadeharr** [comment]
The code coverage has decreased with your commits. Please update your code for the coverage difference to be the same or above the developed coverage before we look at the PR.

**Comment by ebrahim354** [comment]
> The code coverage has decreased with your commits. Please update your code for the coverage difference to be the same or above the developed coverage before we look at the PR.

the codecov doesn't want to upload to the most recent commits

**Comment by palisadoes** [comment]
Please lint your code. The tests are failing because your linting is failing.

**Comment by ebrahim354** [comment]
I have fixed the linting problem but the tests are failing on a file that I haven't touched should I close this PR and branch a clean one from the develop branch ?

**Comment by palisadoes** [comment]
Please merge with the latest version of the code base to make sure. Then update this PR.

**Comment by ebrahim354** [comment]
> Please merge with the latest version of the code base to make sure. Then update this PR.

I've done that already.

**Comment by palisadoes** [comment]
Regarding `tests/users_connection.spec.js` [That file was last edited two months ago](https://github.com/PalisadoesFoundation/talawa-api/tree/develop/tests)

You seem to have found an error with its logic with your tests. Can you review to see how it can be fixed?

**Comment by ebrahim354** [comment]
sure

**Comment by ebrahim354** [comment]
I've found the problem the remove organization resolver was not clearing the blocked users after it's remove. so I solved it however I have found an interesting thing : `  organizationsBlockedBy: user._doc.organizationsBlockedBy.filter( 
     2           (organization) => { 
     1             organization.id !== org.id; 
     0           } 
` in this block when I remove the curlies around the arrow function inside filter the code doesn't work and I have no idea if you have the time to try that. but any how the tests should work fine now

**Review by JamaicanFriedChicken — APPROVED** [review]
Looks good.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
We have to revert these changes. The tests are failing for other PRs. Please review your tests, there may be some random order generator causing the issue or the tests may not work when run all together. Here is an example of the failed tests.

- https://github.com/PalisadoesFoundation/talawa-api/runs/5695901896?check_suite_focus=true

**Pull request merged**
