### PR TITLE
Documentation Automation: Bridging talawa-api and talawa-docs repositories

### LINKED ISSUE #1897: Feature Request : Documentation Automation: Bridging talawa-api and talawa-docs repositories
The current approach to generating and synchronizing documentation between the talawa-api and talawa-docs repositories faces challenges related to branch protection rules and the specification of source and destination branches.

*Current Workflow*:
talawa-api generates markdown files from inline tsdoc comments. These files are stored in a dedicated folder within the talawa-api repository. GitHub Actions encounters difficulties transferring these files to the talawa-docs repository, particularly due to some rules.

*Challenges*:
1. Branch Protection Rules: The develop branch in talawa-api is safeguarded, impeding direct commits.
2. Source and Destination Branch Specification: Complications arise in specifying source and destination branches for the documentation transfer.

*Proposed Solution*:
Trigger the workflow on a schedule or in response to push events on the develop branch of talawa-api.
Automate the generation of documentation files from inline comments (Already Implemented).
Commit files directly to the specified branch and folder location in the talawa-docs repository.

*Implementation Steps*:
Explore existing workflows for innovative insights and references.
Fork the talawa-api and talawa-docs repository to kickstart the documentation automation.
Conduct thorough local testing to validate the efficacy of the automation.

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1897 

**Did you add tests for your changes?**

**Snapshots/Videos:**

1. Push workflow runs when a PR is merged to develop branch
2. when PR is merged to develop then it creates a empty commit to automated-docs branch
3. then after empty commit copy-docs-to-talawa-docs workflow runs 

**it's working locally on my forked repo.**

image

image

image

image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **Chores**
  - Updated GitHub workflow to trigger on `develop` branch instead of all branches.
  - Refined Typedoc generation command for better documentation output.
  - Added a new step to automate copying documentation to another repository.

### CODE REVIEW

**Review by tasneemkoushar — APPROVED** [review]

**Comment by tasneemkoushar** [comment]
@gautam-divyanshu LGTM, approving your PR. Feel free to merge. I hope you have tested it in your local.

**Comment by tasneemkoushar** [comment]
@anwersayeed can you please review & approve the PR

**Comment by gautam-divyanshu** [comment]
@tasneemkoushar Yes I have tested it locally

**Comment by anwersayeed** [comment]
Closing this PR because the mechanism to update the documentation into talawa-docs has now changed. Please refer to https://github.com/PalisadoesFoundation/talawa-docs/commit/de85194509acb2f74a8ca3f24d48a95d3bc9e056. Thanks.

**Comment by anwersayeed** [comment]
Closing this PR because the mechanism to update the documentation into talawa-docs has now changed. Please refer to https://github.com/PalisadoesFoundation/talawa-docs/commit/de85194509acb2f74a8ca3f24d48a95d3bc9e056. Thanks.

**Pull request closed without merging**
