### PR TITLE
updated test for createOrg mutation , added user info update checks

### LINKED ISSUE #376: [Child Issue] createOrganization mutation testing
Is your feature request related to a problem? Please describe.
Test Case is required for createOrganization Mutation

Describe the solution you'd like
As the existing admin login into the system, we take admin input, verify it and create organization. When writing the test code please cover all the business logic involved in the process. Go through the createOrganization Mutation for understanding the logic.

**Additional context**
Parent Issue: 
- #375

### PR DESCRIPTION
**Pull request by akshatgarg12**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #376

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
CreateOrganisation Mutation tests updated :  
1. Added more fields in response object to check complete organisation object
2. Added tests to check whether user info is updated or not

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by sumitra19jha — CHANGES_REQUESTED** [review]
Please remove all the files except `tests/organization.spec.js`
Rest the code is good to go

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@sumitra19jha Please take a look.

**Comment by sumitra19jha** [comment]
@akshatgarg12 Please go through git documentation to understand how to remove files from PR. You have deleted the file and then push the code. Merging them will delete the test code files.

**Review by sumitra19jha — CHANGES_REQUESTED** [review]
Please don't delete and commit

**Comment by akshatgarg12** [comment]
> Please don't delete and commit

Are you asking me to revert the changes of **package-lock.json** and **coverage/lcov.info** ?

**Comment by palisadoes** [comment]
@ akshatgarg12  I'm checking up on older open PRs. Please update your repo with the latest changes so we can merge this PR.

**Comment by palisadoes** [comment]
@sumitra19jha @DMills27 Please review. It's been some time.

**Comment by akshatgarg12** [comment]
> Please fix the conflicting files.

done

**Comment by palisadoes** [comment]
@akshatgarg12 Please resolve the conflicting files so we can merge this PR into the code base.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
