### PR TITLE
Tests for `src/lib/libraries/logger.ts`

### PR DESCRIPTION
**Pull request by KrutikaBhatt**
**What kind of change does this PR introduce?**

**Issue Number:** #915 

**Did you add tests for your changes?**  : Yes

**Snapshots/Videos:**
image

**Summary**
Mock of winston logger was created and the logger was tested for when info is sent and error is sent using spyOn. Winston createLogger, format and transports were checked to see if they are defined and called in excepted way.

**Other information**
There was a code block in logger.ts file which was ignored. 

A possible fix to that was to call `logger.stream` before exporting the logger. Changes have been made accordingly 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** : Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests - Linting

**Comment by KrutikaBhatt** [comment]
Yes, working on it

**Review by noman2002 — CHANGES_REQUESTED** [review]
Currently the code coverage is at 81.03% for logger.ts, please try to get it up to 100%

**Comment by KrutikaBhatt** [comment]
Hey @noman2002, These are the certain changes I made : 
1. Issue with the logger stream solved
`logger.stream` was defined in the logger.ts file but it didn't work. This issue occurred because the stream was directly added to our logger. Instead, we can use the same function defined separately. The stream function was also used in `server.ts` which is fixed. Tests are also covered for this in `logger.spec.ts`
2. Tests for colorize console messages

I tried multiple ways to cover tests for `customFormat` (LoggerFormat) but no luck. The LoggerFormat uses printf module of winston. I tried using spyOn and mockImplementation functions but I could not get it covered in tests. Please do give it a look.

**Comment by palisadoes** [comment]
@KrutikaBhatt Do you think you have found an error in the design for logger.ts? If so, what changes would you make to overcome this setback?

**Comment by KrutikaBhatt** [comment]
> @KrutikaBhatt Do you think you have found an error in the design for logger.ts? If so, what changes would you make to overcome this setback?

No sir, I have went through the documentation of winston logger and the design for logger.ts is fine. I have modified the functions a bit to increase the code coverage in tests but I am not able to cover one branch which is managed by global variable. So far the code coverage I have obtained for `logger.ts` is this - 

image

I am not been able to cover that branch in tests but there is no problem with the design of logger

**Comment by palisadoes** [comment]
@noman2002 Please update your review

**Comment by noman2002** [comment]
> @noman2002 Please update your review

The coverage is significantly up to 97%. We should merge this PR but let the issue be open.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
