### PR TITLE
Tests and minor fixes formessageSentToDirectChat 

### LINKED ISSUE #890: Test: src/lib/resolvers/Subscription/messageSentToDirectChat.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Subscription/messageSentToDirectChat.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name ` __tests__/resolvers/Subscription/messageSentToDirectChat.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by Frey0-0**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #890

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
There was no need to update the documentation

**Summary**
The codebase should have 100% test coverage 

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by xoldyckk** [comment]
@Frey0-0 lint/format the code

**Review by noman2002 — DISMISSED** [review]
Fix the failing test.

**Comment by Frey0-0** [comment]
I have made the linting changes and it looks like that was also the reason for the failing test.

**Review by xoldyckk — DISMISSED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please get the code coverage for the file up to 100% as mentioned in the issue: https://github.com/PalisadoesFoundation/talawa-api/issues/890

**Pull request closed without merging**
