### PR TITLE
feat: database transaction logging for all models

### LINKED ISSUE #1829: Database Logging for all models
- Recently logging middleware was introduced in the PR #1716. 
- The logging middleware can be found in `src/libraries/dbLogger.ts`. Currently, it is only applied to `User` model. 
- We should add it for all models.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by lakshz**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1829 

**Summary**
- added `createLoggingMiddleware` for all model files 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@LakshyaSatpal Please fix the failing tests.

**Comment by LakshyaSatpal** [comment]
@Cioppolo14 Tests passing now.

**Comment by Olatade** [comment]
@EshaanAgg @SiddheshKukade please can you review?

**Review by EshaanAgg — DISMISSED** [review]

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files so that we can merge

**Comment by SiddheshKukade** [comment]
Please fix merge conflicts so that I can review.

**Comment by lakshz** [comment]
@palisadoes Is this ready to be merged?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
