### PR TITLE
Fixes the workflow for revoking a block on a user (un-blocking).

### LINKED ISSUE #1863: Fix the workflow for revoking a block on a user (un-blocking)
**Is your feature request related to a problem? Please describe.**

We don't have a clearly defined workflow for blocking users

**Describe the solution you'd like**

1. A blocked user cannot be a member of an `Organization`, but they can be listed in an `Organization`'s `blockedUsers` field
2. Blocked users for an `Organization` must not be able to send a `membershipRequest` to that `Organization`
3. When a user is unblocked:
     1. if registration approval is required a `membershipRequest` should be sent to the `Organization` unblocking the user
     1. if registration approval is not required, then the user should be added to the members field of the `Organization`.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**
1. This need was identified here:
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1770
1. Screen shot of the `Organization` collection

    image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sahi1l-Kumar**
**What kind of change does this PR introduce?**
A feature.

**Issue Number:**
Fixes #1863 

**Did you add tests for your changes?**
Yes.

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
In the following implementation I have ensured proper handling of user blocking and unblocking while maintaining consistency with the organization's membership process. Additionally, it prevents blocked users from unauthorized actions and appropriately manages their access upon unblocking.

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by plasma018** [comment]
@Sahi1l-Kumar

Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by Sahi1l-Kumar** [comment]
> @Sahi1l-Kumar
> 
> Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 3. The code does not comply with our linting check or other related formatting requirements
> 
> We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

Ok i will be fixing this soon

**Comment by Sahi1l-Kumar** [comment]
What should I do about these `error types` in the `test files`? Am I allowed to add a custom type to fix this?
image

**Comment by palisadoes** [comment]
Yes

**Comment by Sahi1l-Kumar** [comment]
@palisadoes Should be good for review now.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
