### PR TITLE
chore: Remove unused packages

### PR DESCRIPTION
**Pull request by iamsaumya**
Fixes: #128

### CODE REVIEW

**Review by yasharth291 — CHANGES_REQUESTED** [review]
don't remove config and apollo-server

**Comment by yasharth291** [comment]
@iamsaumya  there is no issue like #128

**Comment by iamsaumya** [comment]
Please don't be hasty and please don't DM me as well to look for your comments. 

I prefer all the conversation on GitHub or public chat group in the spirit of Open source. 

Moreover, I don't see how this issue is related to my other for you to mention it here.

 I understand why you r doing these things but please maintain the decorum. 

Thanks! I hope you understand.

**Comment by iamsaumya** [comment]
Please don't be hasty and please don't DM me as well to look for your comments. I prefer all the conversation on GitHub or public chat group in the spirit of Open source.

**Pull request merged**
