### PR TITLE
Mongoose upgraded to v8.2.0

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
Mongoose upgraded to version `v8.2.0` from `v5.13.21`

Fixes: #1695

### CODE REVIEW

**Comment by gautam-divyanshu** [comment]
@palisadoes  eslint errors and warnings removed, please take a look

**Comment by palisadoes** [comment]
Create the small one line for this issue PR as requested before. As this is your first PR in the repo we have to manually approve running every GitHub action after every one of your commits. This is time consuming and therefore causes delays.

By creating the small PR and merging it, this PR will not have to be manually run each time.

Please create the other PR now

**Comment by gautam-divyanshu** [comment]
@palisadoes  like this 

image

It's my first time , so I am not getting it properly

**Comment by palisadoes** [comment]
1. Create another API PR, some minor change. Use the same issue number
1. Leave this one open

**Comment by gautam-divyanshu** [comment]
@palisadoes  this another pr, https://github.com/PalisadoesFoundation/talawa-api/pull/1973

**Comment by palisadoes** [comment]
1. Please create a brand new PR with only one file in it. A minor file change for example
1. We will merge it to prevent us having to manually activate the GitHub action's with each of your commits on this one.

**Comment by palisadoes** [comment]
1. Please also close this PR and use a branch name that doesn't match that of the target branch
1. We won't be able to checkout the local branch from the PR to verify your changes otherwise

**Pull request closed without merging**
