### PR TITLE
Fixes #1897

### LINKED ISSUE #1897: Feature Request : Documentation Automation: Bridging talawa-api and talawa-docs repositories
The current approach to generating and synchronizing documentation between the talawa-api and talawa-docs repositories faces challenges related to branch protection rules and the specification of source and destination branches.

*Current Workflow*:
talawa-api generates markdown files from inline tsdoc comments. These files are stored in a dedicated folder within the talawa-api repository. GitHub Actions encounters difficulties transferring these files to the talawa-docs repository, particularly due to some rules.

*Challenges*:
1. Branch Protection Rules: The develop branch in talawa-api is safeguarded, impeding direct commits.
2. Source and Destination Branch Specification: Complications arise in specifying source and destination branches for the documentation transfer.

*Proposed Solution*:
Trigger the workflow on a schedule or in response to push events on the develop branch of talawa-api.
Automate the generation of documentation files from inline comments (Already Implemented).
Commit files directly to the specified branch and folder location in the talawa-docs repository.

*Implementation Steps*:
Explore existing workflows for innovative insights and references.
Fork the talawa-api and talawa-docs repository to kickstart the documentation automation.
Conduct thorough local testing to validate the efficacy of the automation.

### PR DESCRIPTION
**Pull request by adi790uu**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1897 

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

No

**Summary**

Removes some unnecessary steps, workflows and scripts.

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@adi790uu Please fix the conflicting files.

**Comment by adi790uu** [comment]
@Cioppolo14 it will fail as I have removed certain parts of the workflow which are not necessary after the merge of my latest PR in talawa-docs repo

**Comment by adi790uu** [comment]
@anwersayeed can you review this.

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by anwersayeed** [comment]
@adi790uu Please resolve the conflicts, we will merge this PR as https://github.com/PalisadoesFoundation/talawa-docs/pull/774 is now working.

**Comment by palisadoes** [comment]
Please fix the conflicting files. The documentation workflow is still failing.

**Comment by palisadoes** [comment]
Closing as abandoned. No activity for 3 weeks.

**Comment by adi790uu** [comment]
@palisadoes sorry for the delay but can you reopen this, I am working on mobile docs automation after that I will fix this.

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by palisadoes** [comment]
Closing as abandoned

**Pull request closed without merging**
