### PR TITLE
Mongoose upgraded to version 8.2.0

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
This PR updates Mongoose to version 8.2.0. Syntax, classes and new functions added to codebase.

**Issue Number:**  1695

Fixes #

**Did you add tests for your changes?**
No, But removed a test file called "removeSampleOrganization.spec.ts"

**Snapshots/Videos:**
image

image
This test and src code of this file commented because causing some issues.

image

**If relevant, did you update the documentation?** 
No

**Summary**
Existing version of mongoose is discontinued which is 5.x, so this pr upgraded the mongoose version to latest version which 8.2.0, the reason behind deleting test file is that , it is breaking the mongoose instance , and I tried my best to fix that but didn't get success

**Does this PR introduce a breaking change?**
issues will only be caused by above function in screenshot and , test file that have been removed

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@gautam-divyanshu Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.
Please also fix the conflicting files.

**Comment by Cioppolo14** [comment]
@noman2002 @DMills27 Can you review this PR?

**Comment by palisadoes** [comment]
Did you manage to get your questions answered by@xoldyckk?

**Comment by Cioppolo14** [comment]
@gautam-divyanshu Please fix the conflicting files.

**Comment by gautam-divyanshu** [comment]
> Did you get your questions answered by @xoldyckk?

Yes, but I may have few more queries.

**Comment by gautam-divyanshu** [comment]
> @gautam-divyanshu Please fix the conflicting files.

@Cioppolo14  @palisadoes  I am working on that.

**Pull request closed without merging**
