### PR TITLE
Fixes 1559 of Talawa-Mobile, The user detail fetch populated by membe…

### PR DESCRIPTION
**Pull request by Ayush0Chaudhary**
…rshipRequest

**What kind of change does this PR introduce?**
The mobile requires the the list of membership request made by the user and this was not provided by the talawa-api.
This is required to run the Basic app. 

**Issue Number:**

Fixes https://github.com/PalisadoesFoundation/talawa/issues/1559

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
no

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @xoldyckk @noman2002 please review it.

**Comment by Ayush0Chaudhary** [comment]
Small PR :sweat_smile: 
But important for Talawa-Mobile

**Comment by xoldyckk** [comment]
@Ayush0Chaudhary I had explained to you to not use this approach in [this discussion](https://github.com/PalisadoesFoundation/talawa-api/discussions/1208#discussioncomment-5370473). You have to create a seperate resolver for it under `User` type.

**Comment by EshaanAgg** [comment]
@Ayush0Chaudhary This requires to implemented via a cursor-based pagination connection. If you want, I can take up the same, as I had been working on similar PRs for user tags support in the API.

**Comment by EshaanAgg** [comment]
Sounds great! You can check the official docs to learn about the pagination, and [this PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1187) for the prospective implementation.

**Comment by palisadoes** [comment]
@xoldyckk, @ttaylor92 @sumitra19jha  Please review

**Pull request closed without merging**
