### PR TITLE
Replace package vm2 with isolated-vm

### LINKED ISSUE #1519: Replace package `vm2` with `isolated-vm`
**Describe the bug**
When installing the application we get this error on the console

```
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
```

The package needs to be replaced with ` isolated-vm`

**To Reproduce**
- Run the `npm install` command

**Expected behavior**
1. The error message goes away after the upgrade. No error message must be suppressed
1. All PR tests pass
1. No functionality is affected by the change
1. You must verify whether the package is still used at all and if not, remove it from any configuration files

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Community-Programmer**
**What kind of change does this PR introduce?**
Replaced package vm2 with isolated-vm  for security improvements

**Issue Number:**

Fixes #1519 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

image
image

**If relevant, did you update the documentation?**

No

**Summary**

Replaced package vm2 with isolated-vm  since vm2 has discontinued because of critical security reasons

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Did you check wether the package is used at all and whether it could be removed completely?
1. Please prove that this action was taken

**Comment by Community-Programmer** [comment]
### Actions Taken

1. **Checked Codebase:**
   - Searched the entire codebase for occurrences of the `vm2` package.
   - Verified that there are no import statements, require statements, or references to the `vm2` package in the project.

2. **Dependency Verification:**
   - Analyzed the code context where `vm2` was previously used.
   - Determined that the functionality provided by `vm2` is not essential for the application and can be safely replaced with `isolated-vm`.
 
### Proof
image
image

**Comment by palisadoes** [comment]
Thanks. If that's the case, why did you replace vm2? Shouldn't it be removed?

**Comment by Community-Programmer** [comment]
@palisadoes 

Thank you for your message and your keen observation. After conducting extensive testing of the application and thoroughly reviewing the entire codebase, I identified that we no longer require the use of vm2 or isolated-vm. 

As part of this optimization, I have created a commit to remove both vm2 and isolated-vm dependencies from our codebase. This commit ensures that our application remains efficient and free from unnecessary dependencies

image

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
