### PR TITLE
Added graphql query to find direct chats by id[Urgent}

### PR DESCRIPTION
**Pull request by nishnatadebnath**
**[Urgent approval needed for frotend app work}**

**What kind of change does this PR introduce?**
This is a graphql used to find directChats related with a specific user by user ID

**Did you add tests for your changes?**

No a seperate Issue has been created
**Snapshots/Vide
Screenshot from 2022-01-24 19-17-02
os:**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing PR tests.

**Comment by nishnatadebnath** [comment]
@sandeep-v1404 can you tell why this error is happening?

**Comment by sandeep-v1404** [comment]
> @sandeep-v1404 can you tell why this error is happening?

You need to format the code with `npm run lint` after the changes.

**Comment by nishnatadebnath** [comment]
@sandeep-v1404  Thank you!

**Comment by palisadoes** [comment]
Is this ready to review?

**Comment by palisadoes** [comment]
Where are the tests for this? We need to ensure 100% assurance the code base works as expected. Please add them.

**Comment by nishnatadebnath** [comment]
@palisadoes Yes, this is ready to review. I had a word with @sandeep-v1404 , he will do the testing of the files if the review is okay as it will help in speedy development of the chat feature and always he has a greater idea and knowledge about the testing .Is it ok @palisadoes ?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
