### PR TITLE
feat: implemented Reply functionality for chat

### LINKED ISSUE #2416: Add support to reply to messages in direct chat and group chat
**Is your feature request related to a problem? Please describe.**
Add support to reply to messages in direct chat and group chat

**Describe the solution you'd like**
Users should be able to reply to messages in direct chat and group chat.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Related to https://github.com/PalisadoesFoundation/talawa-admin/issues/2103

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2416 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Introduced a `replyTo` feature for both direct and group chat messages, enabling users to reference previous messages in their replies.
	- Updated mutations for sending messages to include the `replyTo` parameter.

- **Bug Fixes**
	- Added a constant for handling missing message errors.

- **Deprecation**
	- Removed the `removeGroupChat` mutation, indicating it is no longer supported.

- **Configuration Changes**
	- Enhanced ESLint configuration with new rules for TypeScript and GraphQL file handling, improving code quality and consistency.

### CODE REVIEW

**Comment by disha1202** [comment]
Hi @palisadoes, 

I have updated the PRs. 
Can you please take a look.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting file.

**Comment by disha1202** [comment]
Hi @palisadoes 

Updated the PR, 
Please look into it

**Review by DMills27 — APPROVED** [review]
LGTM

**Pull request merged**
