### PR TITLE
[Fixes] Resolvers: Create tests for comments.js

### LINKED ISSUE #590: Resolvers: Create tests for comments.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/post_query/comments.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/post_query/comments.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/post_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by ShwetKhatri2001**
**What kind of change does this PR introduce?**
Test for resolvers

**Issue Number:**

Fixes #590 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
comments-spec-js

**If relevant, did you update the documentation?**
No

**Summary**

I have added the tests for `lib/resolvers/post_query/comments.js`.
Currently its not covering 100% code of the file.
The issue I am facing is that I can't have two different payloads to check for success and error tests. 
So I am using a single test which will either succeed or fail, so can cover any one of them.
I'd like to know if its possible to cover 100% code and would be happy to make required changes (if required). 

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks for the update. Please lint your code and update the PR. Please check our slack channel to see if anyone can assist with creating the test for normal and error conditions. Doing only one is not a true test. We need 100% coverage.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by ShwetKhatri2001** [comment]
Yes, I'm figuring out a better testing approach.

**Comment by palisadoes** [comment]
Please fix the failing tests. Linting.

**Comment by JamaicanFriedChicken** [comment]
@ShwetKhatri2001 are you still working on this?

**Comment by JamaicanFriedChicken** [comment]
Closed due to inactivity

**Pull request closed without merging**
