### PR TITLE
Documentation: TSDoc comments in Resolvers folder

### LINKED ISSUE #2408: Feature Request: Write Tsdoc comments in Resolvers folder Part-3 (final)
**Is your feature request related to a problem? Please describe.**
write tsdoc comments 

**Describe the solution you'd like**
write comments in 
image

**Additional context**
Part of Internship phase 1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
 doc comments 

**Issue Number:**

Fixes #2408 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
Yes

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks. Please fix the conflicting file so we can merge.

**Comment by palisadoes** [comment]
Please check the linting

**Comment by gautam-divyanshu** [comment]
on it.

**Comment by gautam-divyanshu** [comment]
@palisadoes good to go,  `Checks if no unauthorized files are changed `workflow fails because I used prettier that made changes in that file,

**Pull request merged**
