### PR TITLE
Fix bug recurring event

### LINKED ISSUE #1583: Fix Recurring Events
---
### Note

This is a very important feature to implement. 
1. We need someone with either demonstrable:
    1. experience with GraphQL
    2. activity in their GitHub account with a focus on TypeScript
1. This is not an issue for a first time attempt at the technology. 
    1. The first PR needs to be created within a week
    1. All PRs must be completed by the end of February
1. Read through the comments in the closed PR about the progress and why the approach was selected. There are further details below.

In summary:
1. This is not for a newbie
1. This is not for someone with limited time over the next month
---

**Describe the bug**
The creation of a recurring event only creates a single event in the API clients.

**To Reproduce**

1. Create a recurring event
3. Only a single instance is visible

**Expected behavior**

1. You'll need to update or create new mutations that include start and end date for the event recurrence, not just the event itself
1. There will need to be a query created or updated that would return all the calendar entries for a particular time frame including the recurring ones.
1. We will need the ability to edit any recurrence of the event at any time that the event occurs. The edits would need to be valid for:
    1. All instances in the series
    2. Just the instance in question
    4. The instance in question and all those in future
1. Administrators will need to be able to track attendance for any type of event. Therefore you will need to think of ways to create permanence for historical recurring events for this purpose
1. We don't want the creation of an infinite number of event calendar entries if a recurring event has no end date
1. Other functionality must not be affected
1. You must write tests to validate your work

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
1. Work with @xoldyckk on evaluating your solution here and in the subsequent PR
1. This is a prerequisite for our menu of project ideas for GSoC 2024
1.  When this issue is resolved we'll need to create another one to support custom recurrences, such as `3rd week of the month`, similar to what is available in Google Calendar
1. We almost completed the work for Weekly recurring when the assignee @Community-Programmer was unable to continue due to exam time constraints. 
    1. The first PR for this issue will need to build on the work in this abandoned PR as it was almost approved for merging. 
        1. https://github.com/PalisadoesFoundation/talawa-api/pull/1738
    1. You will need to submit a plan as described here
         1. https://github.com/PalisadoesFoundation/talawa-api/pull/1738#issuecomment-1910724294
1. You will need to split this issue into multiple PRs, each with custom options provided by the RRULE package
    1. Weekly recurring
    2. Daily recurring
    3. Monthly recurring
    5. Annually recurring

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Community-Programmer**
**What kind of change does this PR introduce?**
Fixed the bug on creating recurring event only single event is created

**Issue Number:**

Fixes #1583 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-api/assets/76515568/3af2eb7e-535c-4666-b33f-7289351a392f

**If relevant, did you update the documentation?**
No

**Summary**

**Implementation Details:**
**Validation:**

No other functionalities is affected by changes made in the createEvent mutation
All test files passed

image

**Does this PR introduce a breaking change?**
Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

PR related:
#1658 
#1712

### CODE REVIEW

**Comment by Community-Programmer** [comment]
> Regarding the use of `rruleString`in the Event schema
> 
> Wouldn't this be better represented by an RRULE object with the same structure as the JavaScript library?
> 
> Admin and mobile could use it too.
> 
> That way we can replace the package more easily in future in the function that translates between our objects and the underlying library.

The RRULE object can be generated from the rrulestring. I initially considered storing the object in the same format, but decided against it. This is because in monthly recurrence, we need to set events like 'last Monday' or 'second Monday.

image

If necessary I can try to do the same

**Comment by palisadoes** [comment]
It's supported in the object

- https://github.com/jkbrzt/rrule

image

**Comment by Community-Programmer** [comment]
@palisadoes 
Can you tell exactly what I we have to store?
What we need to store is already present in the document, including information such as frequency, endDate, startDate, etc. that is required for rrlue.

**Comment by palisadoes** [comment]
I'd assume entries for all the RRULE constructor parameters:

- https://github.com/jkbrzt/rrule#rrule-constructor

**Comment by Community-Programmer** [comment]
> I'd assume entries for all the RRULE constructor parameters:
> 
> * https://github.com/jkbrzt/rrule#rrule-constructor

Ok got it but I am still confused whether it is really needed?

It's unnecessary to store parameters like dstart (which is equivalent to startDate), until (which is equivalent to endDate), and frequency separately in the database. I believe storing only the event information makes more sense, as the rrule can be generated anytime from that
see below
image

**Comment by palisadoes** [comment]
Yes, whatever parameters you don't already have

**Comment by Community-Programmer** [comment]
@palisadoes 

when saving all parameters we are getting it something like this

image

Here, where 0 represents Monday and 4 represents the fourth occurrence (equivalent to **RRule.MO.nth(4)**), it becomes challenging to reuse the logic, as one has to rewrite it. Can We store the entire RRule object as a JSON string?

Like this
image

**Comment by palisadoes** [comment]
OK. Start with that and let's see what the other reviewers say.

**Comment by EshaanAgg** [comment]
Refer to [this article](https://vertabelo.com/blog/again-and-again-managing-recurring-events-in-a-data-model/). We definitely do not need to store all the bloated data that is being provided by the `Rrule` object.
image
This is an example of a simple schema which can cover almost all of the recurrences that a user may need. We could create a utility in API that takes it and converts it to the format required by the library we are using to generate the dates.

**Comment by palisadoes** [comment]
@EshaanAgg 

If we use RRULE then we have a lot of flexibility in not having to write code. I think it's necessary for the long term maintainability, new features and speed of implementation.

I feel we are better off storing the parameters as a formal data structure to enforce compliance.

The amount of overhead is low. There won't be billions of calendar entries per organization.

We will be wasting time creating our own solution that has to be updated with each new recurrence idea.

Are you in favor of storing the data in a structured format as I was hoping for earlier?

**Comment by Community-Programmer** [comment]
@EshaanAgg @palisadoes 

Else  can we store both rrule string + object?

**Comment by palisadoes** [comment]
@EshaanAgg 

We'll need to handle and desired combination of months, days, and weeks:

1. Every X day on the Nth week of the month
3. Weekly on X and Y day
4. Every X day on the last day of the month 
5. Day X of every month
6. Day X of every year (birthdays, holidays etc)
7. Monthly on the last X weekday of the month

**Comment by Community-Programmer** [comment]
@EshaanAgg 

yaa we do have these methods

image

**Comment by Community-Programmer** [comment]
@palisadoes 

can you tell which file is unauthorized why this test case is failing?

image

**Comment by EshaanAgg** [comment]
> @EshaanAgg
> 
> We'll need to handle and desired combination of months, days, and weeks:
> 
> 1. Every X day on the Nth week of the month
> 2. Weekly on X and Y day
> 3. Every X day on the last day of the month
> 4. Day X of every month
> 5. Day X of every year (birthdays, holidays etc)
> 6. Monthly on the last X weekday of the month
> 
> We need to support any combination of options that Google Calendar and its competitors provide. The end user is going to expect that. We may not support it all now, but we will need to do so eventually. Making provisions for this at the very beginning will reduce the burden later on.

Got it. @Community-Programmer It's your call now. I am against storing the whole RRule object for I feel the same to be highly bloated, but if it is necesary to support all the use cases and more that @palisadoes expressed above, then we can. Please explore the options for the same, including any alternative libraries that might not be as bulky.

**Comment by EshaanAgg** [comment]
> @palisadoes
> 
> can you tell which file is unauthorized why this test is failing?
> 
> image

`package.json` and `package-lock.json` as the you added the `rrule` library.

**Comment by Community-Programmer** [comment]
Bro, how can I take the call? I've worked on many open source projects previously, but this one is special. I've learned many things while implementing these ideas, fixing issues, and writing test cases. I really need guidance from you all to complete this project.

**Comment by palisadoes** [comment]
@Community-Programmer 

1. I'll make the executive decision for you to add the RRULE fields in some way to the Event type and not store this data as text strings or JSON. 
2. So many planned features will rely on this PR that we have to exhaust the options and get consensus agreement from they key contributors. This is certainly an exception.

Please proceed.

**Comment by palisadoes** [comment]
If this test fit review?

**Comment by xoldyckk** [comment]
@Community-Programmer before code implementation writing a detailed plan with visual diagrams would be better, explaining the flow of a client sending a CRUD http request, api user input validation, api create/update/delete business logic, api dynamic data generation, database models, their relationships and constraints etc.

**Comment by Community-Programmer** [comment]
> If this ready for review?

Yes It is prepared for mutation and schema review

**Comment by palisadoes** [comment]
@xoldyckk 

Some of that logic was provided here:

- https://github.com/PalisadoesFoundation/talawa-api/pull/1712#issuecomment-1904488484

image

**Comment by Community-Programmer** [comment]
@xoldyckk 

I have prepared this please have a look and suggest all necessary  changes
This is just a rough idea how things will work
298672038-54d4f157-a59c-4f13-a7a4-9011b40d8f17

**Comment by palisadoes** [comment]
@xoldyckk 

1. There isn't a need for a description of business logic. It's simply implementing a recurring meeting.
1. We will be utilizing the logic of the RRULE package with the parameters here. The parameters are reflected in the schema presented in this PR
     1. https://github.com/PalisadoesFoundation/talawa-api/pull/1738#issuecomment-1908601913

**Comment by palisadoes** [comment]
@Community-Programmer 

1. Please provide a brief answer for the questions on the constraints, input validations. 
1. Update your code to match

@xoldyckk, @EshaanAgg 

1. Over the past week, we had 62 comments in the previous PR prior to it being accidentally closed. This one has reached 26 in just 2 days. 
2. Let's focus on the recurring event feature. If there are other tangential questions make that into a separate issue and not make it delay approval of this PR. We need to get this concluded.

**Comment by xoldyckk** [comment]
@palisadoes if number of comments on a pull request is a problem, the discussions should be held in the issues or discussions tab, having discussions is a good thing

this is a fairly complex feature request, that's why having discussions and finalizing on a general, easy to understand plan would be beneficial, the finalized plan has to be something easy to understand and reference for the reviewers when reviewing the PR, the reviewer can't scroll through the discussions to understand what has to be done in the PR, I mentioned business logic and other entities because while reviewing the PR the reviewers can't keep the context of all that in their heads, they should have a finalized general initial plan to reference, especially for PRs that are huge in size
 
figuring out mistakes after the code is implemented also leads to PRs with great number of comments because there's constant friction between what needed to be done and what was done, this is caused because of not having a general initial plan

**Comment by palisadoes** [comment]
@xoldyckk 

I completely agree with your comments.

1. I'm more concerned with a digression in the discussion thread here causing delays versus discussion of the necessary aspects of this PR causing the delays. We can determine the forum for side discussions if needed at that time. I think the risk is low, but I wanted to set expectations. 
2. We need the summary document at this stage after so much back and forth. Like you, I have asked for this too.

**Comment by palisadoes** [comment]
@Community-Programmer 

Do you require any other guidance?

**Comment by Community-Programmer** [comment]
> @Community-Programmer 
> 
> Do you require any other guidance?

What should be my next step??
I think it is ready in terms of mutation and model

Should I have to create a general and finalized plan as @xoldyckk mentioned??

**Comment by palisadoes** [comment]
Yes, that would help

**Comment by palisadoes** [comment]
Thanks in advance. We need this work to be completed as it's fixing a glaring omission in the basic expected functionality of all the API clients

**Comment by palisadoes** [comment]
Closing as @Community-Programmer contacted me to say he won't have time to work on this for the next month.

**Pull request closed without merging**
