### PR TITLE
Fix/user type

### PR DESCRIPTION
**Pull request by AVtheking**
What kind of change does this PR introduce?

Fix the usage of userType ,created a new appUserProfile model

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1711

Did you add tests for your changes?

Yes

Does this PR introduce a breaking change?

Ye

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing application tests

**Comment by AVtheking** [comment]
image
sir my test is failing because of this but this package is already initialized in app.ts file but still this is throwing error ?

**Comment by palisadoes** [comment]
Could it be due to any of the most recent merged PRs since your most recent commits?

**Comment by AVtheking** [comment]
Maybe but this issue is being faced by other contributors too

**Comment by palisadoes** [comment]
1. Are you sure others are seeing this issue? More recent PRs are not failing because of this.
2. Have you tried merging with the latest develop?

**Comment by AVtheking** [comment]
Yes I have asked in the slack channel and there also one mate said he is facing same issue

**Comment by AVtheking** [comment]
It is throwing some error that i18n library is not initialised but I haven't change anything related to it .It is saying to use app.use(i18n.init) which is already present

**Comment by AVtheking** [comment]
Those test files are working fine the only thing is failing is the initialisation of this library as we are translating the error messages which is not working properly

**Comment by palisadoes** [comment]
> Yes I have asked in the slack channel and there also one mate said he is facing same issue

1. 
2. I checked slack, no one replied to your two messages saying they are facing the issue. One said it was passing, but remember they would not be using your branch.
3. No other PRs face this issue
4. As you feel it's a translation issue, it could be because a translation for a new or existing error message doesn't exist. Have you checked that?

It would have to be one of your recent changes because it wasn't failing before. The files identified haven't been updated for weeks, and in some cases months.

**Comment by AVtheking** [comment]
I have fixed my tests but still it should throw error message instead it is throwing translation message maybe this library is not working as intended.

**Comment by AVtheking** [comment]
okay I understand it is not problem with the library I have to just initialized in the test itself to use it

**Comment by AVtheking** [comment]
@palisadoes  sir please assign reviewers so that It can be reviewed

**Comment by palisadoes** [comment]
1. The test code coverage for your patch is too low at 76%. The test code coverage has dropped by over 3%
2. Please fix the coverage tests
3. We'll assign reviewers when you have reached that goal

**Comment by AVtheking** [comment]
@palisadoes  sir I have added test for the changes I have done

**Comment by palisadoes** [comment]
Please fix all these introduced security advisories

image

**Comment by AVtheking** [comment]
fixed those warnings

**Comment by palisadoes** [comment]
Please merge with the latest upstream. We recently merged PRs

**Comment by Cioppolo14** [comment]
@EshaanAgg @SiddheshKukade Can you review this PR?

**Comment by EshaanAgg** [comment]
The diff for this PR is 7k lines added and 3k lines removed. This is not reviewable. Please figure out a way to reduce the diff or break it in smaller parts.

**Comment by palisadoes** [comment]
@EshaanAgg 

Given that this feature touches so many aspects of the apps it's going to be complicated

- Can you suggest ways to simplify it?

There are other considerations:

1. It's not being merged into develop, so we could:
    1. Create similar branches in the other repos
    1. Create issues to make the new branches compatible with this one
     1. Create issues to make all new features on develop address to this branch

Next week we expect a lot of activity that is like to channel productively. We could take advantage of the GSoC evaluation period to get this long overdue feature properly implemented instead of having to manage lots of one one line PRs.

I think it's worth taking the chance. Do you in think so in that context?

**Comment by EshaanAgg** [comment]
Sounds good. 
- If we want smaller PRs, we can ask the contributors to migrate only a certain number of resolvers (~10) in PR so that the same remains reviewable. 
- If that seems too much work, we can take the risk and rely on manual and feature testing, as highlighted in your approach. Once the same is stable in all branches, we can merge into the `develop` branch in all the related repositories.

**Comment by palisadoes** [comment]
I'm going to merge it. Having some resolvers working the new way while others work the old way will cause hardship.

**Comment by palisadoes** [comment]
@AVtheking 

1. Do you feel sufficiently comfortable with the web front end to apply the necessary changes to work with this PR?
2. How would you propose to split up the Talawa-Admin PRs for this to make them easier to review?

**Comment by AVtheking** [comment]
@palisadoes sir Although I have not worked with graphql client before in the frontend but have experience in working with the frontend so I can make it through

We can raise pr according to feature wise of the application ,in that way it can be easily reviewed

**Comment by palisadoes** [comment]
1. Can you suggest a series of PRs that we'd need?
2. I want to know how we could split the workload.

**Comment by palisadoes** [comment]
@AVtheking 

1. I just realized that we created this issue in Admin too.
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. I think it'll be best to monitor the `develop` branch and create issues to correctly merge new `develop` PRs into `develop-userTypeFix`. You can create issues when necessary. Could you do that?
2. You'll also need to assist in troubleshooting the Admin PR that will certainly need assistance. New issues could be created for that independently by you for that too.

What do you think?

**Comment by AVtheking** [comment]
I didn't get the second point
Yes I am ready to assist the admin PRs

**Comment by AVtheking** [comment]
I would tell series of PRs in about half an hour sir

**Comment by AVtheking** [comment]
Ok sir I understood

**Comment by Atharva-Kanherkar** [comment]
@AVtheking Can i contact you on slack?

**Comment by AVtheking** [comment]
@Atharva-Kanherkar yeah sure

**Pull request merged**
