### PR TITLE
commented firebase notification code

### LINKED ISSUE #1500: Removal of firebase messaging from Create Event
**Describe the bug**
When we create an event in Talawa mobile app, we get an exception from backend that notifications are not enabled. This prevents from creating an event. We have discontinued using Firebase Notifications in our app. So I would request to get the code removed or commented out from the backend as well.

**To Reproduce**

1. Login to Talawa App.
2. Click on create Event.
3. Type in the details.
4. Click Add

**Expected behavior**
• A message based on the success or failure(apart from notifications) of the event creation process.

**Actual behavior**
• Getting an exception that says notifications are not enabled.

**Screenshots**

**Additional details**
• You can find the code that needs to be removed in resolvers/creatEvent.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Veer0x1**
**What kind of change does this PR introduce?**
Commented the Firebase notification on creating an event, and also test corresponding to it. And also removed firebase-related installation and configuration instructions.

**Issue Number:**

Fixes #1500

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
The aim is to remove all references to firebase in the code base not just for creating events therefore:

1. References to firebase packages need to be removed from `package.json`
1. All references to firebase in the code base

**Comment by Veer0x1** [comment]
Okay got it.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Also remove references here https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.env.sample

**Comment by Veer0x1** [comment]
Yup,working on it.

**Comment by Veer0x1** [comment]
Ig now, I have removed all the instances of Firebase from the codebase; please review.

**Comment by palisadoes** [comment]
1. Are you removing all Firebase references or only those related to events? If not, what other Firebase references would be left?
2. We will eventually need to remove all references.

**Comment by Abhisheksainii** [comment]
@Veer0x1 , we are also storing FCM token through mutation and asking for androidFirebaseOptions, iOSFirebaseOptions through Query.
Kindly check if these references to firebase has also been removed.

**Comment by Veer0x1** [comment]
> 1. Are you removing all Firebase references or only those related to events? If not, what other Firebase references would be left?
> 2. We will eventually need to remove all references.

In my attempt to eliminate all Firebase references, I systematically removed them and deleted the Firebase package. After running all tests, I observed that all but two tests (which were failing before also )passed successfully. Consequently, I believe I have successfully eradicated all traces of Firebase from the codebase.

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
