### PR TITLE
converted promise/callback syntax to async-await

### LINKED ISSUE #265: Consistently use the `async-await` pattern
**Is your feature request related to a problem? Please describe.**

Most of the code uses `async-await` functions, but some some functions are returning `Promise`.

**Describe the solution you'd like**

1. Use the Async await paradigm instead of Promise - https://itnext.io/javascripts-async-await-versus-promise-the-great-debate-6308cb2e10b3
2. Use either the `lodash` or `ramda` library which has beautiful functions to write concise code

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

Discuss in the comments below

**Additional context**

Parent issue #259

### PR DESCRIPTION
**Pull request by akshatgarg12**
**What kind of change does this PR introduce?**
Closes #265 

**Did you add tests for your changes?**
NA
**If relevant, did you update the documentation?**
NA
**Summary**
converted all promise based syntax to async-await for consistency in the code.

**Does this PR introduce a breaking change?**
NA

**Other information**
A package image-hash uses callback to hash image paths, i had to use promise syntax there to return the value from callback.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
@akshatgarg12 we are trying to get multilingual support for the summer. @sumitra19jha is working on this a lot. Please contact him on how the errors you are creating will be translated.

**Comment by impiyush83** [comment]
@akshatgarg12  This is good. Let's halt this PR until the multilingual error reaches prod.

**Comment by akshatgarg12** [comment]
@impiyush83  @palisadoes  I have added the standard error!

**Comment by palisadoes** [comment]
@sumitra19jha What is your view on this? I know you are working on this in general.

**Comment by sumitra19jha** [comment]
@akshatgarg12 Please resolve conflict. Rest it looks good to me

**Comment by akshatgarg12** [comment]
> @akshatgarg12 Please resolve conflict. Rest it looks good to me

I have already replaced the errors with the custom error objects, for multilingual support.

**Comment by akshatgarg12** [comment]
> @akshatgarg12 Please resolve conflict. Rest it looks good to me

done

**Comment by impiyush83** [comment]
@akshatgarg12  Fix the lint issue.

**Comment by akshatgarg12** [comment]
> @akshatgarg12 Fix the lint issue.

yeah fixed it.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@ranilwallace @Laurell876 Please review and merge.

**Comment by palisadoes** [comment]
@akshatgarg12 Please resubmit against the develop branch. All features are now only being added there.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@akshatgarg12 Please fix the ESlint errors in the GitHub Actions workflow

**Comment by akshatgarg12** [comment]
> @akshatgarg12 Please fix the ESlint errors in the GitHub Actions workflow
It was an issue with npm [details](https://github.com/npm/npm/issues/17340)

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
