### PR TITLE
Added support for configurable session timeout

### LINKED ISSUE #1637: Backend for configurable session-management
**Is your feature request related to a problem? Please describe.**

Currently, the timeout for Talawa-Admin is hard-coded in Talawa-Api. However, there is no feature to set a custom timeout for different organizations.

**Describe the solution you'd like**

Implement configurable session timeout for each organization and provide admins and super-admins the ability to access and change the session timeout for an organization, with the default timeout set to 30 minutes.

**Describe alternatives you've considered**
NA

**Additional context**

Related to the issue in Talawa-Admin [#1305](https://github.com/PalisadoesFoundation/talawa-admin/issues/1305).

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1637 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[video](https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/1b3bcb36-1ae7-4536-9ff0-929f90f1183e)

**If relevant, did you update the documentation?**

**Summary**

Changes:

1. Implemented configurable session-timeout for an organization by the super-admin.
2. Added tests for all the changes made.

Constraints:

1. Only super-admins can update the session-timeout for any organization.
2. Timeout should be in range of 15 to 60 minutes (both including), and a multiple of 5.

**Other information**

Test coverage
imgae1
image2

Related Talawa-Admin issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/1305#event-11973757736

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by chandel-aman** [comment]
@palisadoes 
Could you please review this PR?

**Comment by Cioppolo14** [comment]
@chandel-aman Please fix the failing tests.

**Comment by chandel-aman** [comment]
@Cioppolo14,

The tests are failing because:

1. This PR adds a mutation to the GraphQL schema, updating the schema.graphql file, which is listed in unauthorized files.
Screenshot from 2024-03-08 08-59-05

2. The linting and formatting check is failing because the constants.ts file has exceeded the maximum lines of code limit. However, I believe this can be ignored since it is a constants file.
Screenshot from 2024-03-08 09-00-26


3. The number of files changed for this PR is more than 20, which was necessary to implement these changes.

**Comment by palisadoes** [comment]
Please add the constants file to the pull request GitHub action YAML file's line count check

**Comment by chandel-aman** [comment]
> Should the constants file be added to the pull request GitHub Action YAML file to exclude it from the line count check?

Is this what you meant?

**Comment by palisadoes** [comment]
In this file where the check is done

- https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-request.yml

**Comment by chandel-aman** [comment]
sure sir will do that right away

**Comment by chandel-aman** [comment]
@EshaanAgg @DMills27 Could you please review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
Closing. No activity

**Pull request closed without merging**
