### PR TITLE
Adding Graphql-inspector for versioning(GSoC) 2023

### LINKED ISSUE #1339: Graphql-Inspector for API schema versioning
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

THere needs to be a system in check to detect schema breaking changes to the talawa-api application.

Graphql Inspector is perfect for it.

```bash

graphql-inspector diff git:origin/develop:./schema.graphql ./graphql
```

Running this command will result in the difference in schemas between the schema in the develop branch and the one worked in locally by contributors.

there is also the `npm run check:schema` script to automate the entire process by generating the `schema.graphql` file and then checking for breaking changes.

 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1339

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by kb-0311** [comment]
Graphql-inspector will work completely fine locally with its CLI tool

1. However to add it to the CI CD pipeline we will first have to install its Github Application which is currently free in the marketplace. I have added the checks for the same in this PR already.
2. I would ignore the unauthorized check failed error in this PR because it is occurring due to my changes in package.json file.

**Comment by palisadoes** [comment]
1. Please create an issue for this and link it to the PR
2. We have no indication of what you are trying to achieve with this change.

**Comment by kb-0311** [comment]
@palisadoes 
1. Done.

3. What this PR does is that it 

a. installs graphql-inspector package which is then used to generate a file called `schema.graphql` which is the Graphql SDL version of all the schemas defined in the API .
b. The `schema.graphql` is then used as a "source of truth" for the client applications which can then use graphql-inspector in their own projects to check for schema-breaking changes in the CI/CD  pipeline on each PR. (The PR for the client apps will be done once this one is merged)

**Comment by kb-0311** [comment]
Is there a way we can securely access the github access token for Palisadoes' talawa repos within a CI/CD pipeline  for the mobile and admin apps?

**Comment by kb-0311** [comment]
@palisadoes any update on this?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
