### PR TITLE
Feature: Addition of Event Venue

### LINKED ISSUE #1640: API - Add support for event venues
**Is your feature request related to a problem? Please describe.**

We need the ability to add API functionality to assign a venue to an event. Currently you can assign geographic coordinates, but you cannot also provide one of a list of pre-defined venues (eg. "Conference Room", "Sports Field" or "Theater") This would be a useful capability to add.

**Describe the solution you'd like**

The aim would be for Admins to do CRU activities (no deletions, but disabling/enabling) for venues on an Org screen, and for these venues to appear as options whenever events are scheduled.

The API must be able to:

1. determine whether the venue is already allocated during all or some part of the proposed event timeslot when the event is being created and not make it appear as an option.
    1. if there are no venues configured, or no available venues, then the returned result be meaningful and the app must not crash
2. reject the creation of an event if the requested location is unavailable
3. return an availability status for a selected venue for a given timeslot that could be used whenever the event timing is adjusted.

Other

1. We will also need the ability to set the maximum capacity of the venue in terms of user checkins. This will help with events that require pre-registration
1. Venues can often be reconfigured to have less or more seating. This means that there will need to be the ability to override the checkin limit on a per event basis.

The schema must include support for:

1. Venue ID
2. Venue name
3. Venue description 

This issue should be split into multiple PRs for ease of review:

1. Venue CRUD
2. Adding a venue to a single Event
3. Verifying the venue isn't already used for a single event
4. Managing event checkins for venue capacity
5. Adding the venues to recurring events

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

Related issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1640
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1390

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by wingman47**
**What kind of change does this PR introduce?**
Introduces concept of pre defined venues in organization to directly select while event creation. It also checks for availability of the venues during event creation to avoid any potential clash of events for same venue.

Features Added:
 
Query -
1. CheckVenue: Gives the list of venues which aren't scheduled yet and are available for events in a given timeframe.
2. VenuesInOrganization: Gives the list of all available venues in an organization.

Mutation -
1. CreateVenue: Create a new venue with these attributes: Name, Description, Capacity of the Venue, Image of the Venue
2. EditVenue: Edit the attributes of already available venue in an organization.

Fixes:
1. Fixed start time and end time of the events whose date part of the time used to be current date instead of start date entered by the user.

**Issue Number:**

Fixes #1640.

**Did you add tests for your changes?**

Yes.

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-api/assets/49762303/78795bff-2753-4f6b-8e2e-0333850c6df3

https://github.com/PalisadoesFoundation/talawa-api/assets/49762303/5c67e57d-f46c-471c-a9ee-75857f53cb0b

**Summary**

API functionality to assign a venue to an event. Currently you can assign geographic coordinates, but you cannot also provide one of a list of pre-defined venues (eg. "Conference Room", "Sports Field" or "Theater").

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@wingman47 Please fix the failing tests.

**Comment by wingman47** [comment]
> @wingman47 Please fix the failing tests.

Done.

**Comment by Cioppolo14** [comment]
@wingman47 There are still some failing tests.  Can you fix them or document in a comment why they are acceptable?

**Comment by wingman47** [comment]
> @wingman47 There are still some failing tests. Can you fix them or document in a comment why they are acceptable?

I will try to fix those failing tests

**Comment by palisadoes** [comment]
@wingman47 

This is too much for our reviewers to process all at once. It will take too long to review and the PR may never be merged. Create separate PRs for:

1. Venue CRUD
2. Adding a venue to a single Event
3. Verifying the venue isn't already used for a single event
4. Managing event checkins for venue capacity
5. Adding the venues to recurring events

Your overall experience will be better this way. The effort is appreciated and it will be more so if you follow these guidelines.

Please close this PR and make these incremental changes. Reviewing 41 files is too much.

**Comment by wingman47** [comment]
> @wingman47 There are still some failing tests. Can you fix them or document in a comment why they are acceptable?

I improved code coverage, but I'm stuck on tests of controllers which I haven't worked on and the other two failing tests ('Unauthorized file changes' and 'Counting files changed'), I don't know how to fix from my end (like Unauthorized file changes). Should I modify workflow files in .github folder? Any guidance would be helpful. Thanks.

**Comment by palisadoes** [comment]
I'm going to close this PR for the reasons stated previously.

1. The counting files test is failing because you have submitted so many files.
2. The unauthorized file access test is because the schema file has been edited. This is expected for the work you are doing

Create multiple branches based on your event-venue branch, one for each PR mentioned previously to make the process easier.

**Comment by wingman47** [comment]
> @wingman47
> 
> This is too much for our reviewers to process all at once. It will take too long to review and the PR may never be merged. Create separate PRs for:
> 
> 1. Venue CRUD
> 2. Adding a venue to a single Event
> 3. Verifying the venue isn't already used for a single event
> 4. Managing event checkins for venue capacity
> 5. Adding the venues to recurring events
> 
> Your overall experience will be better this way. The effort is appreciated and it will be more so if you follow these guidelines.
> 
> Please close this PR and make these incremental changes. Reviewing 41 files is too much.

Sorry I missed your message in my previous reply. I will create separate PRs for features to make it more easy to review. Thank you for your guidance.

**Pull request closed without merging**
