### PR TITLE
[Feature Request] Posts and Events features and Spam mitigation for Talawa-admin issue fixed

### LINKED ISSUE #740: [Feature Request] Posts and Events features and Spam mitigation for Talawa-admin
**Is your feature request related to a problem? Please describe.**
Currently, In talawa-admin, the posts and events list contains hard-coded values, and some fields are missing while creating events and posts. Also, as the count of posts and events increases, there is a need for search functionality.

Also, there is no way in Talawa-admin to detect the user who spammed in the organization group chat and block that user.

For more info PalisadoesFoundation/talawa-admin#357

**Describe the solution you'd like**
* A mutation will be added to update the already existing post.
* A new function will be implemented in the postsByOrganization resolver to filter the posts.
* A new function will be implemented in the eventsByOrganization resolver to filter the events.
* A new field will be added in the organization schema named ‘spamCount’ to store the details of users who spammed in the organization.
* A new field will be added in the user schema named ‘spamInOrganizations’ to store the details of the organization in which the user has spammed.
* A new helper function will be created named ‘checkSpamMessages’ to check whether the message is spam or not.
* To check whether the message is spam or not following tasks will be done:
    * Check whether the message contains the keywords of spam or not.
    * Check the frequency of the last 30 messages. If the message frequency is less than 5 seconds then it is spam.
* A helper function will check the spam just before storing the messages in the database i.e. in the ‘sendMessageToGroupChat’ resolver.
* A new mutation will be added named ‘updateSpamNotifcation’, to update the readed notifications in talawa-admin.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #740 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

* Filter events
Screenshot 2022-08-09 at 06-03-08 Playground - http __localhost 4000_graphql

* Filter posts
Screenshot 2022-08-09 at 06-04-39 Playground - http __localhost 4000_graphql

* Update post
Screenshot 2022-08-09 at 06-09-09 Playground - http __localhost 4000_graphql

* Spamming an organization group chat 
Screenshot 2022-08-09 at 06-15-46 Playground - http __localhost 4000_graphql

* Spammed user stores in organization
Screenshot 2022-08-09 at 06-17-59 Playground - http __localhost 4000_graphql

* User document holding the data in which user has spammed
Screenshot 2022-08-09 at 06-20-43 Playground - http __localhost 4000_graphql

**If relevant, did you update the documentation?**

No

**Summary**

This Pull request is the changes in the backend regarding PalisadoesFoundation/talawa-admin#358

In this, the following things are implemented,

* A mutation is added to update the already existing post.
* A new function is implemented in the postsByOrganization resolver to filter the posts.
* A new function is implemented in the eventsByOrganization resolver to filter the events.
* A new field is added in the organization schema named ‘spamCount’ to store the details of users who spammed in the organization.
* A new field is added in the user schema named ‘spamInOrganizations’ to store the details of the organization in which the user has spammed.
* A new helper function is created named ‘checkSpamMessages’ to check whether the message is spam or not.
* To check whether the message is spam or not following tasks is done:
   * Check whether the message contains the keywords of spam or not.
   * Check the frequency of the last 30 messages. If the message frequency is less than 5 seconds then it is spam.
* A helper function is checking about the spam just before storing the messages in the database i.e. in the ‘sendMessageToGroupChat’ resolver.
* A new mutation is added named ‘updateSpamNotifcation’, to update the readed notifications in talawa-admin.

**Does this PR introduce a breaking change?**

No

**Other information**

This pull request is under GSoC'22.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by asmitsirohi** [comment]
@yasharth291 please review

**Comment by palisadoes** [comment]
@yasharth291 Please review.

**Comment by palisadoes** [comment]
@yasharth291 Please review

**Comment by palisadoes** [comment]
@yasharth291 Please review so we can merge.

**Review by yasharth291 — APPROVED** [review]

**Comment by yasharth291** [comment]
@asmitsirohi  remove the conflicts

**Review by yasharth291 — APPROVED** [review]

**Comment by palisadoes** [comment]
@asmitsirohi Please fix the failing tests

**Comment by palisadoes** [comment]
The code coverage has also declined with this PR. Please also add the corresponding tests needed to restore the coverage to the previous value or better.

**Comment by asmitsirohi** [comment]
@palisadoes @yasharth291, please see this now, I have resolved all the conflicts.

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
