### PR TITLE
Add tests for Mutation/createEventProject

### LINKED ISSUE #879: Resolvers: Create tests for src/lib/resolvers/Mutation/createEventProject.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `/src/lib/resolvers/Mutation/createEventProject.ts`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Mutation/createEventProject.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #490 

### PR Acceptance Criteria

- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/blob/develop/src/lib/resolvers/Mutation/createEventProject.ts). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by Kunal4now**
**What kind of change does this PR introduce?**

Add tests for `Mutation/createEventProject.ts`

**Issue Number:**

Fixes #879 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Good work. Please try to see how you can get the code coverage up to 100%

**Comment by SiddheshKukade** [comment]
I can't find any issue linked and assigned for this PR.

**Comment by Kunal4now** [comment]
I've created an issue and linked it to this PR.

**Comment by palisadoes** [comment]
@Kunal4now the process is to create the issue first and get it assigned. This way we don't have multiple people duplicating efforts. It greatly helps with management. Please ask to get assigned to the issue you created.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@Kunal4now the process is to create the issue first and get it assigned. This way we don't have multiple people duplicating efforts. It greatly helps with management. Please ask to get assigned to the issue you created.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please try to get the code coverage to 100% for the file you have made changes.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
