### PR TITLE
made selection of organization while sign up

### LINKED ISSUE #1703: API - Select organization on registration
**Is your feature request related to a problem? Please describe.**

We are working on migrating the approval of requests to join organizations to a new Admin screen as outlined in this issue:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1416

Prior to this the process was:

1. New registrants joined the Community
1. Super Admins would approve the request
1. Approved registrants would login and select an organization

There were disadvantages to this approach:

1. This gave too much responsibility to the Super Admin who may not necessarily know people requesting to join in the way an Admin would. 
1. The two step process where the organization was selected post approval, could have been reduced to a simpler single step.

**Describe the solution you'd like**

_TALAWA API_

- This new requirement means that:
    1.  New `USER`s and `NON_USER`s will need to select an organization when registering so that the request can be directed to the correct organization's Admin screens.
    1. The setup script needs to create a single organization with a generic name on installation to facilitate registration to choice of at least one organization
    1. There can never be less than one organization in the DB
    1. The registration mutation must include organization ID information that issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1416 will be able to detect.
    1. The current GitHub action pull request workflow needs to be updated so that the default organization is created successfully. This is in addition to the already existing test data importation test.
    1. The default organization creation mode mutation needs set the registration approval required flag to True to err on the side of caution.

_TALAWA MOBILE_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA ADMIN_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_OTHER_
1. You will need to write tests for the updated code 
1. All other functionality must be maintained

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. Related issues:
     1. https://github.com/PalisadoesFoundation/talawa-api/issues/1703
     2. https://github.com/PalisadoesFoundation/talawa/issues/2330
     3. https://github.com/PalisadoesFoundation/talawa-admin/issues/1440
1. User definitions in the DB schema
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### LINKED ISSUE #1706: Address npm Audit Warnings: glob-parent and minimist vulnerabilities
### Issue Summary:
I encountered npm audit warnings related to vulnerabilities in the dependencies of this project. The affected packages are `glob-parent` and `minimist`. 

### Vulnerabilities:
1. **glob-parent:** [GHSA-ww39-953v-wcq6](https://github.com/advisories/GHSA-ww39-953v-wcq6)
   - Severity: High
   - Fix: `npm install pm2@5.3.0` (breaking change)

2. **minimist:** [GHSA-xvch-5gv4-984h](https://github.com/advisories/GHSA-xvch-5gv4-984h)
   - Severity: Critical
   - Fix: `npm audit fix --force` (will install pm2@5.3.0, breaking change)
  

### Proposed Solution:
1. Upgrade `pm2` to version `5.3.0` using `npm install pm2@5.3.0`.
2. Run `npm audit fix --force` to address remaining vulnerabilities.

Screenshot 2024-01-17 at 12 55 50 AM

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**

User now selects organization while registering process.

**Issue Number:**

Fixes #1703

**Did you add tests for your changes?**

Yes

**Summary**

1. User will select the organization while sign up process.
2.  if the organization has `userRegistrationRequired` field to true then the membership request would be sent to the organization.

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
@AVtheking, the issue you have referenced to is already closed and no-one is assigned.

**Comment by palisadoes** [comment]
1. It's for:
    1. #1703
2. There is a linting error. An `eslint-parser` upgrade was recently merged. We'll need to open an issue to fix this

**Comment by palisadoes** [comment]
Lint fix issue:

- https://github.com/PalisadoesFoundation/talawa-api/issues/2146

**Comment by AVtheking** [comment]
> @AVtheking, the issue you have referenced to is already closed and no-one is assigned.

@akhilender-bongirwar I think I have linked correct issue ,you may check again.

**Comment by Manik2708** [comment]
The logic is pretty fine! `adminApproved` is getting removed, which solves most of the confusion. But as I discussed with @palisadoes, we need to ensure that only those new users should be allowed into Talawa which are approved by the organization chosen at the time of sign up. So once this PR is merged we need to work on:
1) Introducing a variable which will check, whether user is validated by admins of organization or not. If not validated, then user should not be allowed to enter Talawa.
2) If rejected, giving user an option to re-select the organization after login.
3) When rejected multiple times by different organizations, marking user as spam.
This will ensure that only serious users are in the Talawa ecosystem.

**Comment by palisadoes** [comment]
1. @AVtheking Please fix the failing tests.
2. @Manik2708 All good points. We can add the validation logic after this basic functionality is added.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
