### PR TITLE
add tests case for ImageSizeLimitExceeded class

### LINKED ISSUE #1819: Test: src/libraries/errors/ImageSizeLimitExceeded.ts`
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file `src/libraries/errors/ImageSizeLimitExceeded.ts`
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by samiali12**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1819 

**Did you add tests for your changes?**

Yes, a new test case has been added to cover the `ImageSizeLimitExceeded` error.

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

No documentation updates are required for this test case.

**Summary**

The goal of this PR is to enhance the test coverage by adding a specific test case for the `ImageSizeLimitExceeded` error. The test checks if the error is thrown correctly when the image size exceeds the specified limit.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes, I have read and followed the project's contributing guide.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. There is no need for you to edit `package.json` for this PR
2. Please revert the "@parcel/watcher": "^2.4.1" line

**Comment by Olatade** [comment]
@samiali12 

There is no need for you to edit package.json for this PR
Please revert the "@parcel/watcher": "^2.4.1" line

**Comment by samiali12** [comment]
> @samiali12
> 
> There is no need for you to edit package.json for this PR Please revert the "@parcel/watcher": "^2.4.1" line

I have already revert the "@parcel/watcher": "^2.4.1" line. Please review the PR.

**Comment by palisadoes** [comment]
It's still there and you have updated the faker package which seems to be out of scope of this issue.

Click on the files list for this PR to see

**Comment by samiali12** [comment]
> It's still there and you have updated the faker package which seems to be out of scope of this issue.
> 
> Click on the files list for this PR to see

I appreciate your feedback. I've revisited the pull request, and I understand the concern. I noticed the update to the 'faker' package, which was unintentional and out of the scope of this particular issue.  I've reopened the pull request for your review

**Comment by Olatade** [comment]
@samiali12 can you please update your branch with the latest changes from the develop branch

**Comment by samiali12** [comment]
> @samiali12 can you please update your branch with the latest changes from the develop branch

Done. I have update my develop branc with latest changes.

**Comment by samiali12** [comment]
> @samiali12 can you please update your branch with the latest changes from the develop branch

Updated done

**Comment by palisadoes** [comment]
Please fix the conflicting files so that we can review

**Comment by Cioppolo14** [comment]
@samiali12 Please fix the failing tests and conflicting files.

**Comment by samiali12** [comment]
> @samiali12 Please fix the failing tests and conflicting files.

Okay.

**Pull request closed without merging**
