### PR TITLE
bugFix: #288 ws package upgrade

### PR DESCRIPTION
**Pull request by impiyush83**
**What kind of change does this PR introduce?**

**Issue Number:**
#288 
Fixes #

**Did you add tests for your changes?**
N/A

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Bump up ws package

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@DMills27
@Laurell876

We need your review. Two reviewers are required for non develop branches.

**Review by ranilwallace — DISMISSED** [review]

**Comment by ranilwallace** [comment]
@impiyush83 Please pull from the latest master to resolve the conflict

**Review by palisadoes — CHANGES_REQUESTED** [review]
@impiyush83 you need to fix the conflict with `package.json`

**Comment by impiyush83** [comment]
@palisadoes  Resolved conflicts.

**Comment by ranilwallace** [comment]
Hi @impiyush83 

Awesome. Gonna need you to resolve the requested change and then we can merge this!

**Review by ranilwallace — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
