### PR TITLE
added unit tests for event_query/event.js

### LINKED ISSUE #542: Resolvers: Create tests for event.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/event_query/event.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/event_query/event.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/event_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by akshatgarg12**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #542 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Screenshot 2022-03-02 at 12 39 10 AM
Screenshot 2022-03-02 at 12 39 17 AM

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Based on this `event_query/event.js` only has 87% coverage. We'll need to get it to 100%. Almost there!

**Comment by akshatgarg12** [comment]
> Based on this `event_query/event.js` only has 87% coverage. We'll need to get it to 100%. Almost there!

Working on it

**Comment by palisadoes** [comment]
Please fix the conflicting file.

**Comment by palisadoes** [comment]
Thanks. We are at 87% code coverage. We'll need to get it to 100%. Almost there!

**Comment by akshatgarg12** [comment]
> Thanks. We are at 87% code coverage. We'll need to get it to 100%. Almost there!

There is an issue with i18n library because of which i'm not able to test the error test case of the function, i have posted that issue on slack channel. We will reach 100% coverage once its resolved.

**Comment by palisadoes** [comment]
We are having an issue with our GitHub Actions with failing tests. This PR looks like the last one that was succeeding. I'm going to merge the code in the hope of fixing the problem. I'll reopen the source issue when the merge is complete as we still need to get to 100% coverage.

**Pull request merged**
