### PR TITLE
created test for post query

### LINKED ISSUE #591: Resolvers: Create tests for post.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/post_query/post.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/post_query/post.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/post_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by arnab15**
**What kind of change does this PR introduce?**
added 100% test coverage for post query resolver
It's for post query resolver testing

**Issue Number:**

Fixes #591

**Did you add tests for your changes?**

yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please try to get the code coverage for the file up to 100%

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please try to get the coverage on the file up to 100%

image

**Comment by arnab15** [comment]
@palisadoes In my command line it says post.js file is 100% covered.
image

**Comment by palisadoes** [comment]
My comment may be a legacy of the fact that the original code coverage for your PR was 13.92% but since then it has increased to  14.43%, so it appears to have declined when in fact it hasn't

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
