### PR TITLE
Added support for pre-login imagery

### LINKED ISSUE #1611: Add support to change pre-login imagery
**Is your feature request related to a problem? Please describe.**
1. Communities need the ability to change the social media icons and logo images upon login.
1. We don't want users thinking that they are always logging into Palisadoes

**Describe the solution you'd like**
1. `Talawa-API`
    1. You will need to create a new collection specifically meant to store the customizations listed below
    1. You will need to write valid tests for your code
    1. No other functionality must be affected
1. `Talawa-Admin`
    1. Our login screen is not specific to organizations, so we'll need to make this change at the Community level.
    1. This will require the creation of a Community Profile button at the Super Admin level which would lead to a Community Profile edit screen
    1. This screen must be designed in keeping with our Talawa Admin Figma design found here
        1. https://docs.talawa.io/docs/design/ux/ux-design-system
    1. The logo and social media icons to be edited are visible in the attached screen shots
    1. By default, when the Palisadoes Logo is changed, the Palisadoes specific social icons should disappear so that the Community can add theirs. If the Logo is left blank, then the Palisadoes imagery should return, but the database parameters must remain so that the Admin doesn't have to re-enter the information.
    1. This will require the creation of a new collection in the API
    1. Please work with @aashimawadhwa and @rishav-jha-mech on the design approval before submitting a PR

**Related Issues**
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Images that should be editable: 
    image
1. Location of the Community Profile
    image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1611 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[Screencast from 03-03-24 02:02:23 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/51ce6c52-8fbc-47bd-b7c3-8c435acf8ac0)

To show the working of community logo upload I've used the create post modal.

**Summary**

1. Added support for changing pre-login imagery and links to social media for a community.
2. Implemented API endpoints for updating, resetting, and fetching community details.
3. Restricted access to these features to super-admins only.

**Other information**

Related Talawa-admin issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1334

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by chandel-aman** [comment]
@palisadoes 
Could you please provide the review for this PR?

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by chandel-aman** [comment]
@palisadoes
The conflicts have been resolved.
Could you please review this?

**Comment by chandel-aman** [comment]
@palisadoes @Olatade 
The conflicting files have been resolved.
For all the modified files relating to this PR test coverage is 100%.

The workflow checks are failing because
1. constants and typedef files have exceeded the max number of lines limit
2. number of files changed in this PR is more than 20

Could you please review this PR?

**Comment by chandel-aman** [comment]
@palisadoes,

I also need to create a PR for [this issue](https://github.com/PalisadoesFoundation/talawa-api/issues/1637#event-11965161279), which is dependent on the current PR for updating the community timeout. I've already implemented the session timeout feature and am awaiting the merge for this PR. It would significantly help me contribute to this project if we could have these PRs reviewed.

**Comment by palisadoes** [comment]
Which PR needs to be merged first?

**Comment by Cioppolo14** [comment]
@chandel-aman Can you fix the linting failed test?

**Comment by chandel-aman** [comment]
> @chandel-aman Can you fix the linting failed test?

this test is failing because the number of lines in typedefs and constans file has exceeded the maximum allowed limit
image

i believe that there is no point in checking the number of lines for these files as they are constants
i'll be adding these files to the workflow to exclude it from this check

**Comment by palisadoes** [comment]
We recently merged a PR

> > @chandel-aman Can you fix the linting failed test?
> 
> this test is failing because the number of lines in typedefs and constans file has exceeded the maximum allowed limit image
> 
> i believe that there is no point in checking the number of lines for these files as they are constants i'll be adding these files to the workflow to exclude it from this check

Yes, please add that file to the count line check in this PR
https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Comment by chandel-aman** [comment]
> We recently merged a PR
> 
> > > @chandel-aman Can you fix the linting failed test?
> > 
> > 
> > this test is failing because the number of lines in typedefs and constans file has exceeded the maximum allowed limit image
> > i believe that there is no point in checking the number of lines for these files as they are constants i'll be adding these files to the workflow to exclude it from this check
> 
> Yes, please add that file to the count line check in this PR https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

Sure sir

**Comment by chandel-aman** [comment]
@palisadoes, I've already added the required support for the admin PR, which is dependent on this PR for including the features to update, fetch, and reset pre-login imagery.

> This PR is dependent upon this one. Will you be able to complete this soon? The issue was opened on December 31.
> 
>     * [Feature: Ability to change pre-login imagery talawa-admin#1649](https://github.com/PalisadoesFoundation/talawa-admin/pull/1649)
> 
> 
> If you cannot complete this in the next few days we'll have to use the solution used in the Admin PR by @git-init-priyanshu

**Comment by palisadoes** [comment]
The tests are failing. Please fix them.

**Comment by palisadoes** [comment]
We cannot merge until you fix the tests in this PR

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by Olatade** [comment]
@chandel-aman please fix the conflicting files

**Comment by Olatade** [comment]
@chandel-aman please don't forget to resolve the failing tests

**Comment by chandel-aman** [comment]
> @chandel-aman please don't forget to resolve the failing tests



> @chandel-aman please don't forget to resolve the failing tests

All the tests that are failing are not related to this PR (errors are thrown in src/resolvers/Mutation/updateUserRoleInOrganization.ts)
image

**Comment by palisadoes** [comment]
1. Merge your code with the latest upstream to see whether that helps
1. We have other PRs in the queue where this failure has occurred.
2. This issue has been open and assigned to you since the New Year
3. I'll have to close this if it's not remediated in the next 12 hours

**Comment by chandel-aman** [comment]
I apologize for the inconvenience. I'll fix the code. Thank you for your patience.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
