### PR TITLE
Test created for updateLanguage mutation

### LINKED ISSUE #521: Resolvers: Create tests for updateLanguage.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/language_mutation/updateLanguage.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/language_mutation/updateLanguage.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/language_mutation/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
refactoring

**Issue Number:**

Fixes #521 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
Not needed

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by sumitra19jha** [comment]
@jadeharr @palisadoes Please Merge

**Review by palisadoes — CHANGES_REQUESTED** [review]
@sumitra19jha There is a issue with this PR. `coverage/lcov.info` is included when we already have the `coverage/` directory in the `.gitignore` file.

Please remove the `coverage/` directory and fix .gitignore so that `coverage/` and any files within it are never checked in to the code base.

This was inadvertently accepted in your last PR and needs to be resolved.

The conflicting merged files will be resolved when you make this change.

**Comment by Sagar2366** [comment]
@sumitra19jha please resolve the conflicts on your PR.
Thank you for your contributions.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please see how you can get to 100% coverage. You are at 92% now.

**Comment by sumitra19jha** [comment]
@palisadoes The coverage is 100%. The Codecov is not refreshed after further commit. Please find the snap below
Screenshot 2022-03-11 at 11 27 27 AM

**Pull request merged**
