### PR TITLE
Lint only updated files with stricter linting

### LINKED ISSUE #1548: Apply Linting Only to Files Updated in `git`
We need the ability to selectively adjust our linting rules so that they are eventually applied to our entire code base.

1. Linting rules are managed by the `.eslintrc.json` file.
1. They are applied to the entire code base at once.
1. If we change a rule from `warn` to `error` then every file in the code base will be checked and we have frequently seen our tests fail for dozens of files in hundreds of lines of code.

This is not acceptable.

We have been trying to more strictly lint the entire code base manually, but it has been very slow.

## At the user CLI
We need a way to edit `.eslintrc.json` with increasingly stricter linting rules in such a way that the tests are only applied to the changed files with every `git commit` and `git push` command. 

These `git` commands must fail if the linting fails.

## With Every Pull Request

We recently merged a Talawa-API pull request that checks each submitted file for linting compliance. This can be used as an example of how to run the test against individual files.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1242

You must make sure that this functionality applied for all PRs for this repository whenever the  `.eslintrc.json` file is updated

## Other

1. There may be ways to achieve the CLI goals by updating our existing Git Hooks
1. Your solution should preferably work within coding environments such as VScode
1. Please work with @anwersayeed and @tasneemkoushar on this issue
1. Related issues:
    - https://github.com/PalisadoesFoundation/talawa-admin/issues/1270

## Screenshots

When complete, you should be able to convert all these  `.eslintrc.json` file lines containing `warn` to `error` and the tests will only be applied to the changed files in `git`

image

### PR DESCRIPTION
**Pull request by NamitBhutani**
**What kind of change does this PR introduce?**

Feature 

**Issue Number:**

Fixes #1548

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

No

**Summary**

Run linting only for changed files for each commit and introduce stronger linting rules to slowly improve code integrity.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@NamitBhutani 

1. Please fix the conflicting files. 
2. This will greatly help the consistence of our code and is long overdue.

**Comment by xoldyckk** [comment]
@palisadoes as i understand the problem is that there are lint issues in codebase, but turning lint rules from warn to error would result in too many errors at once.

if i'm correct in my assumption then the best way to deal with this would be to ignore all the codebase files in `eslintrc.json` file and then create many smaller issues to resolve the lint issues in a particular directory/file

each PR associated to a particular issue would remove the corresponding directory/file from the list of files eslint is ignoring and fix the lint issues within that directory/file

there isn't a need to make it per file as that would create too many atomic issues, instead directory based approach is better, assign a contributor to fix lint issues in a directory

eventually all the ignored codebase files would be removed from eslint's ignore list, after that the PR workflows can simply detect new lint issues and error out if they are found

**Comment by palisadoes** [comment]
We were trying the incremental linting approach and it was too difficult to manage.

This will just lint files committed in the local repo of the developer.

We already have a GitHub action to lint files submitted in the PR as a verifier

**Comment by palisadoes** [comment]
@NamitBhutani Please fix the failing tests

**Comment by palisadoes** [comment]
@EshaanAgg Your thoughts on this will be helpful too

**Comment by EshaanAgg** [comment]
Please refer to [this PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1353#pullrequestreview-1807755733).

**Comment by NamitBhutani** [comment]
> @NamitBhutani Please fix the failing tests

I think one of the tests will fail, because I have to edit eslintrc.json and .husky/pre-commit which come under unauthorized changes.
I have hopefully fixed the other failing test.

**Comment by NamitBhutani** [comment]
The lockfile got messed up, extremely sorry for that, I have pushed a new commit that should hopefully fix it, if it does not I'll make another pull request and close this one.

**Comment by palisadoes** [comment]
Don't create another PR. Only use this one.

**Comment by NamitBhutani** [comment]
> Don't create another PR. Only use this one.

I think all the issues have been fixed! The lint errors are due to the change in eslintrc.

**Comment by palisadoes** [comment]
Are the linting errors expected for only this PR and will work satisfactorily from the CLI?

**Comment by NamitBhutani** [comment]
> Are the linting errors expected for only this PR and will work satisfactorily from the CLI?

Yes, they will! as in the workflow, lint check is ran for every file, that's why there are errors.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
