### PR TITLE
Feature/change PR template with check list added.

### LINKED ISSUE #2689: Update Pull Request Template to Enforce Standards
**Problem**
We need to ensure contributors follow repository standards, including implementing `coderaabbitai` suggestions and maintaining test coverage. This is currently not enforced via the PR template.

**Proposed Solution**
Update the Pull Request (PR) template to include:

-[ ] A checklist for implementing `coderaabbitai` suggestions.

-[ ]A checklist for verifying that tests are written for changes made in PR and coverage meets or exceeds current test coverage (~90/95).

**Acceptance Criteria**
- A PR template is updated in the `.github` directory.
- The template includes a checklist for `coderaabbitai` suggestions and test coverage.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**NOTE** 
Submit PRS for both branches `develop` and `develop-postgres`

### PR DESCRIPTION
**Pull request by HarshDodiya1**
**What kind of change does this PR introduce?**
feature change

**Issue Number:**

Fixes #2689 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
No

**Summary**
The `pull_request_template.md` file now contains new added check list for

1. Implementing coderaabbitai suggestions
2. A checklist for verifying that tests are written for changes made in PR and coverage meets or exceeds current test coverage (~90/95).

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a checklist in the pull request template for "CodeRabbit AI Review" and "Test Coverage" to enhance review processes.

- **Documentation**
	- Updated the pull request template to improve clarity and ensure comprehensive testing practices are followed.

### CODE REVIEW

**Comment by varshith257** [comment]
@HarshDodiya1 implement coderaabbitai suggestions of coderaabbitai checklist

**Comment by HarshDodiya1** [comment]
Okay @varshith257, I have added the suggested checklist.

**Review by varshith257 — APPROVED** [review]

**Comment by HarshDodiya1** [comment]
Hey @varshith257, I am very much thankful to you. I have merged my first PR to a large org. I will always remember this. 🙂

Can I do the same for the `develop-postgres` branch?

**Comment by varshith257** [comment]
Yes, go ahead

**Pull request merged**
