### PR TITLE
BugFix #1979 Add more options to UserOrderByInput

### LINKED ISSUE #1979: Add more options to UserOrderByInput
**Is your feature request related to a problem? Please describe.**
Implement more options to filter for users

**Describe the solution you'd like**
Add options like `created_ASC` and `created_DESC` to `UserOrderByInput`

Currently:
image

**Additional context**
Users are fetched on frontend in different sets, example `$first:10` but API has no option to fetch Newest first or Oldest first, whereas Admin panel has the filtering on frontend which messes up the order.
Reference: PalisadoesFoundation/talawa-admin#1706

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by rahulch07**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1979 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-api/assets/87270395/1ddaa562-f53a-42ef-9868-6bcc2da70437

**Summary**

This PR solves the jumps in list of users that were appearing in infinite scroll in Users screen.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please exclude the README.md file from the PR. 
2. Editing it is out of scope.

**Comment by Cioppolo14** [comment]
@rahulch07 Please remove the readme file.

**Comment by AVtheking** [comment]
@rahulch07  please remove readme.md file and update the branch. Rest is OK.

**Review by Atharva-Kanherkar — COMMENTED** [review]
Looks OK, just the readme file is redundant.

**Review by gautam-divyanshu — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
