### PR TITLE
Upgrade Typescript to version 5.3.2

### LINKED ISSUE #1464: Upgrade package `typescript` from 4.9.5 to 5.3.2
For security purposes, we need to bump package [typescript](https://github.com/Microsoft/TypeScript) from 4.9.5 to 5.3.2.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1458

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105178929/job/19341787583?pr=1458
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105179245/job/19341788466?pr=1458

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- You PR should have no warning messages
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

### PR DESCRIPTION
**Pull request by PriyadharshiniNagarathinam**
**What kind of change does this PR introduce?**

Dependency Update

**Issue Number:**

Fixes #1464 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

No

**Summary**

This pull request updates the TypeScript version to 5.3.2 in order to address security concerns.

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by EshaanAgg** [comment]
@PriyadharshiniNagarathinam Please pull the lastest changes from the main.

**Comment by PriyadharshiniNagarathinam** [comment]
@EshaanAgg  I tried doing that so....it shows me errors while accepting all the incoming changes of upstream. I didn't know am I going right or wrong Can you help me by giving some quick things what should I do?? I am a beginner, its bit tough for me to do everything faster

**Comment by EshaanAgg** [comment]
The same is known as merge conflicts. It is a common situation that arises while working with git and GitHub. I am sure you can google about the same and get to know better about it.

**Review by EshaanAgg — APPROVED** [review]
LGTM. We aren't using very advanced typescript in our project, so I don't think this should be a breaking change. Also since TypeScript doesn't follow `SemVer`, this upgrade is as good as a minor upgrade.

**Review by xoldyckk — APPROVED** [review]

**Pull request merged**
