### PR TITLE
Add Husky to improve developer experience [Fixes #1027]

### LINKED ISSUE #1027: Feature Request: Use Husky
**Is your feature request related to a problem? Please describe.**
With the introduction of typechecking, formatting and linting checks in the GitHub workflows, there are a couple of commands that the developer now needs to ensure to run after making changes, which might be tiresome. 

**Describe the solution you'd like**
We can add [Husky](https://www.npmjs.com/package/husky) to our code-base, which helps to make working with Git Hooks easy. 
Using Husky we can easily configure the code to run scripts like `format:check`, `lint:check` and `typecheck` for the developer locally each time he makes a commit, thus ensuring that their PRs do not fail when they create a PR.

**Describe alternatives you've considered**
Using a shell script to run all the checking and fixing commands.

**Approach to be followed (optional)**
1. Install Husky.
2. Add scripts to run `format:check`, `lint:check` and `typecheck` at each commit using `Husky`.
3. (Optional) Add script to run tests.
4. Update documentation about the same and about the `--no-verify` flag that can be used with `git commit` to bypass the `Husky` hooks (if the developer desires)

**Additional context**
I personally am a huge advocate for Husky, as it helps to minimise the number of commands that I as a developer have to run, and automates all of the burden, leaving only the responsibility of fixing my errors to me (and automates code quality and maintainance)

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Feature: Add and configure Husky

**Issue Number:**

Fixes #1027 
**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Sample terminal screenshots after using Husky
image
image

**If relevant, did you update the documentation?**
Yes

**Summary**
Added Husky to the code base, and configured it to run all the formatting, linting and type checking scripts on commits. Updated documentation about the same, and also added how to opt out of it.

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by EshaanAgg** [comment]
@palisadoes @noman2002 Can you please rerun the workflow for this PR and review it if possible?

**Review by xoldyckk — DISMISSED** [review]

**Review by xoldyckk — COMMENTED** [review]
@EshaanAgg is this not required?
https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod

**Comment by EshaanAgg** [comment]
I'll didn't find any instance of any commit action in the GitHub workflows, and thus I thought it wasn't necessary to include the same as Husky right now is only being run on commits.
Still I'll read the docs and figure out if there is a need to include the same.

**Comment by palisadoes** [comment]
@EshaanAgg

All the linting advice you give in `INSTALLATION.md` should be moved to `CONTRIBUTING.md`. End users are not interested in linting and code developers, but contributors are.

What do you think?

**Review by palisadoes — CHANGES_REQUESTED** [review]
All the linting advice you give in `INSTALLATION.md` should be moved to `CONTRIBUTING.md`. End users are not interested in linting and code developers, but contributors are.

**Review by xoldyckk — APPROVED** [review]

**Comment by xoldyckk** [comment]
@palisadoes done

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@xoldyckk Why did you push changes for someone else's PR? This should be the responsibility of the submitter.

**Pull request merged**
