### PR TITLE
[Bugfix]Update Profile Mutation Creation

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
(Issue #170) Update Profile Mutation is missing so it is Mutation creation for that

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
There is no need to update the current existing documentation for this.

**Summary**
With the introduction of this PR, users can now update there profile information

**Does this PR introduce a breaking change?**
No

**Other information**

https://user-images.githubusercontent.com/35868598/111876756-3293a980-89c6-11eb-9d53-9cd05e02e9df.mov

### CODE REVIEW

**Comment by Sagar2366** [comment]
@sumitra19jha good addition.
can you please add unit tests for this PR ?

**Comment by sumitra19jha** [comment]
> @sumitra19jha good addition.
> can you please add unit tests for this PR ?

Ok. Working on it

**Comment by sumitra19jha** [comment]
@Sagar2366 Test Code is Added.
Screenshot 2021-03-22 at 5 17 33 PM

**Comment by sumitra19jha** [comment]
Mentors the Travis-ci check failed because the API(mutation has not yet been merged). You can see the screenshot above for the local server where all checks have been passed.

**Comment by Sagar2366** [comment]
@sumitra19jha testcases are actually failing in local environment as well for me on your branch.

Screenshot 2021-03-22 at 5 57 27 PM

**Comment by sumitra19jha** [comment]
@Sagar2366 Sir, You have to check whether the following things exist
### 1. in tests/functions/getToken.js
Check whether the email and password user exist (in the database)
Screenshot 2021-03-22 at 6 30 37 PM

### 2.  in tests/functions/getUserId.js
Check whether the email and password user exist (in the database)
Screenshot 2021-03-22 at 6 31 48 PM

### 3. in tests/user.spec.js
Check whether the email and password user exist in the login test (in database)
Screenshot 2021-03-22 at 6 33 28 PM

### 4. in constants.js
Check whether the URL is "http://localhost:4000/graphql"
Screenshot 2021-03-22 at 6 35 00 PM


And Please run the test again after that

**Comment by sumitra19jha** [comment]
@Sagar2366 After making sure of those changes here is the attached video of execution


https://user-images.githubusercontent.com/35868598/112170691-4551ec80-8c19-11eb-855e-c9691339f8ac.mov

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@sumitra19jha travis CI is failing on your PR, have a look.

**Comment by sumitra19jha** [comment]
@Sagar2366 I removed the test code and as you can see CLI passes the check. I request you to pleases merge this PR First and then I will create a separate PR containing test code of the updateProfile mutation. And I am sure that will pass the CLI check.

**Pull request merged**
