### PR TITLE
added TalawaGraphQLError class

### LINKED ISSUE #2223: Standardizing the errors thrown inside graphQL resolvers
**Is your feature request related to a problem? Please describe.**
Currently the errors returned in the graphQL responses from talawa-api are arbitrary and undocumented. This prevents the client applications consuming the graphQL responses from talawa-api to make use of those errors in meaningful ways.

**Describe the solution you'd like**
Errors thrown inside the graphQL resolvers should have standardization in the information they can carry. This standardization ensures that client application contributers don't have to deal with unexpected new errors which they couldn't predict beforehand. 

**Describe alternatives you've considered**
The alternative would be to make use of errors in graphQL schema approach which right now isn't feasible because the scope of change is too big and it would need massive changes on both the client and server code for talawa applications.

**Approach to be followed (optional)**
1. Add a new `TalawaGraphQLError` class which extends the `GraphQLError` class exported from `graphql` package. This class would be restricted in the kind of errors it could throw and also be made type safe to catch violations of those restrictions by contributers.
2. The graphQL resolvers would be gracefully migrated to make use of the new `TalawaGraphQLError` class for throwing errors.
3. When all resolvers are successfully migrated, the currently existing errors will be removed from the codebase. 

**Additional context**
After this issue is resolved the newly standardized errors will be documented on talawa-docs for talawa client application contributers to easily reference. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by xoldd**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #2223

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

Not yet, will find the time to do so soon

**Summary**

Added the `TalawaGraphQLError` class as discussed in the linked issue. The class is highly documented to ensure that the contributers can easily grasp the usage patterns. 

**Does this PR introduce a breaking change?**

No

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@xoldd It looks like there are still failing tests, are you working on it?

**Comment by xoldd** [comment]
@Cioppolo14 this PR isn't a cause for the test failure

**Comment by akhilender-bongirwar** [comment]
@xoldd, can you push an empty commit to run the workflows again. All the checks will be passed.

**Comment by xoldd** [comment]
> @xoldd, can you push an empty commit to run the workflows again. All the checks will be passed. By empty I mean adding a space or any minor change...

Why are tests flaky? They should be idempotent.

**Comment by xoldd** [comment]
I think github gives the option of rerunning tests to the PR reviewers, @Cioppolo14 can you do that?

**Comment by palisadoes** [comment]
1. I've restarted the tests. It doesn't make sense that the tests will sporadically fail in this case. They have been running consistently otherwise
2. Yes, I've noticed that the testing time has reached 20 min for both API and Admin. We'll need to check this out

**Comment by akhilender-bongirwar** [comment]
> > @xoldd, can you push an empty commit to run the workflows again. All the checks will be passed. By empty I mean adding a space or any minor change...
> 
> Why are tests flaky? They should be idempotent.
> 
> Also 20 minutes for the tests doesn't seem right.

This unexpected test failure has actually happened for me twice before. You're right, 20 minutes is too long, but it is the case with the API tests only.

**Comment by palisadoes** [comment]
> > 1. I've restarted the tests. It doesn't make sense that the tests will sporadically fail in this case. They have been running consistently otherwise
> > 2. Yes, I've noticed that the testing time has reached 20 min for both API and Admin. We'll need to check this out
> 
> In my PR #2225, I ran into the same error. You can see [commit1-report](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8730773419/job/23955167950) . So I have made a new commit to run the workflows again then all the tests have been passed. 
> 
> Since the tests are failing again even after re running the workflows. Could you once try the same approach, @xoldd 

Please open an issue to correct this. Out has to be fixed. 

Make references to both failed GitHub actions with links

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
I opened an issue

**Pull request merged**
