### PR TITLE
Add Support for Production Environment - Part 2

### LINKED ISSUE #1916: Add Support for Production Build of Talawa Api
**Describe the bug**
In the repo `src/server.js` is a stale file and in package.json we are still using the server.js to run the production build files 

```
    "start": "cross-env pm2-runtime start ./build/server.js --watch",
    "prod": "cross-env NODE_ENV=production pm2-runtime start ./build/server.js",
```

We have an old  ts-config-build.json and most of the packages only support the ES modules compatible but our ts-config.build .json emits commonjs and it doesn't support them, leading to new errors for the build environment.

**To Reproduce**

1. npm run build
2. npm run start

**Expected behavior**

1. It has to be pointed to `index.js` instead server.js which is a commented file.
2. The npm run build command should be emitted without any errors. 
3. The server should be accessed at localhost:4000 in a production environment.

**Screenshots**

```
C:\Users\91970\Desktop\talawa\talawa-api>npm run start

> talawa-api@1.0.0 start
> cross-env pm2-runtime start ./build/index.js --watch

2024-02-28T00:17:02: PM2 log: Launching in no daemon mode
2024-02-28T00:17:02: PM2 log: [Watch] Start watching index
2024-02-28T00:17:02: PM2 log: App [index:0] starting in -fork mode-
2024-02-28T00:17:02: PM2 log: App [index:0] online
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\91970\Desktop\talawa\talawa-api\node_modules\nanoid\index.js from C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js not supported.
Instead change the require of index.js in C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\require-in-the-middle\index.js:101:39)
    at Object.<anonymous> (C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js:18:18)
    at Hook._require.Module.require 
```

**Additional details**
This has to be addressed in order to support the production setup of talawa-api and started working on it as discussed in #1885 .
This issue require multiple PRs to support Production environment build

### PR DESCRIPTION
**Pull request by varshith257**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1916 

**Did you add tests for your changes?**

N/A

**Summary**

Fixed deprecated ObjectID

**Does this PR introduce a breaking change?**

No

**Other information**

This PR is a part of series of PRs required to support Production environment of Talawa-API

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by varshith257** [comment]
@xoldd PTAL about files changed. I have changed the use of ObjectId deprecation by createFromTime which VSCode Editor has suggested. But it generates all 000000 instead of a valid ObjectID. Something it is expecting an input there

Ref:    

1.  https://mongodb.github.io/node-mongodb-native/4.9/classes/ObjectId.html#createFromTime
2. https://github.com/mongodb/js-bson/blob/main/src/objectid.ts#L295

**Comment by xoldd** [comment]
@varshith257 What deprecation are you talking about?
> I have changed the use of ObjectId deprecation by createFromTime which VSCode Editor has suggested.
Why would you do that? Are you using AI to fix it?

**Comment by varshith257** [comment]
@xoldd  No, the deprecation of using  new Types.ObjectId() for numeric values where it showing ObjectId is deprecated. The VS Code suggested to use instead createFromTime and same verified from above links to use it.

But it returning all zeros instead a numeric ObjectId l

**Comment by varshith257** [comment]
@xoldd  No, the deprecation of using  new Types.ObjectId() for numeric values where it showing ObjectId is deprecated. The VS Code suggested to use instead createFromTime and same verified from above links to use it.

But it returning all zeros instead a valid ObjectId

**Comment by varshith257** [comment]
> by createFromTime which VSCode Editor has suggested

This mean what I mean that the VS Code provide some suggestions beside in it's editor. I referred that :)

**Comment by Olatade** [comment]
@varshith257 you still have some failing tests. please take a look at them

**Comment by Huy1996** [comment]
@EshaanAgg @SiddheshKukade Could you review this PR?

**Comment by varshith257** [comment]
@palisadoes Can be merged?

**Comment by varshith257** [comment]
@xoldd Closing this PR as It getting efforts more than we thought. Getting every compatibility issue as new code added into codebase. I think we can add production supportonce the codebase got stabilized

**Comment by varshith257** [comment]
@palisadoes Please get revied this

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
