### PR TITLE
Feat: Upgrade package express-rate-limit from 5.5.1 to 7.1.5 #1463

### LINKED ISSUE #1463: Upgrade package `express-rate-limit` from 5.5.1 to 7.1.5
For security purposes, we need to bump package  [express-rate-limit](https://github.com/express-rate-limit/express-rate-limit) from 5.5.1 to 7.1.5.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1459

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105185828/job/19341811113?pr=1459
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7105186275/job/19341812520?pr=1459

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

### PR DESCRIPTION
**Pull request by Harsh1s**
**What kind of change does this PR introduce?**

- [ ] Bug Fix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactoring
- [x] Dependency Update

**Issue Number:**

Fixes #1463

**Did you add tests for your changes?**

N/A

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

N/A

**Summary**

This PR updates the `express-rate-limit` package from version 5.5.1 to 7.1.5 to address security concerns.

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Harsh1s** [comment]
@EshaanAgg Could you please review the changes now? Thanks!

**Review by EshaanAgg — COMMENTED** [review]
LGTM

**Review by palisadoes — CHANGES_REQUESTED** [review]
This is an upgrade of two major versions, and yet tests pass.

1. Is this package still used in the code base?
1. If it is, are there tests to cover the lines where it is used?

I don't want to merge this and break the app.

**Comment by EshaanAgg** [comment]
@palisadoes The same is used as a plugin to limit the number of requests per user we receive. We don't have any explicit tests for the same in our codebase, as it a third-party plugin, and they should be responsible for maintaining their integration with GitHub.

@Harsh1s Can you please confirm if the API is still running fine locally after this upgrade? If the same doesn't break anything locally, I think we are safe to proceed with it's merging.

**Comment by palisadoes** [comment]
@Harsh1s Please verify the question from Eshaan

**Comment by Harsh1s** [comment]
> @palisadoes The same is used as a plugin to limit the number of requests per user we receive. We don't have any explicit tests for the same in our codebase, as it's a third-party plugin, and they should be responsible for maintaining their integration with Express.
> 
> @Harsh1s Can you please confirm if the API is still running fine locally after this upgrade? If the same doesn't break anything locally, I think we are safe to proceed with its merging. 

Just got the chance to verify it. The answer is yes, everything is working as it should with the upgrade.

**Comment by Harsh1s** [comment]
> @Harsh1s Please verify the question from Eshaan

@EshaanAgg I answered the question, thanks!

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
1. I'm going to have to revert this. It's causing our push.yml workflow to fail. 
1. Please check it out:
    - https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7152285097

**Comment by palisadoes** [comment]
1. @Harsh1s Please resubmit this PR under the same issue.
2. There was a typo in a previous PR that caused this one to fail. 
3. It was only after I reverted that i realised the error.

**Comment by Harsh1s** [comment]
> 1. @Harsh1s Please resubmit this PR under the same issue.
> 2. There was a typo in a previous PR that caused this one to fail. 
> 3. It was only after I reverted that i realised the error.

Understood, I'll start working on it.

**Comment by dhruvgupta0503** [comment]
is this issue still open ,i would like to work on this issue

**Pull request merged**
