### PR TITLE
Modifying the src/index.ts file to handle the case where the SERVER_PORT was not defined.

### LINKED ISSUE #2285: API fails if the `SERVER_PORT` variable is not in the `.env` file
**Describe the bug**

API fails if the `SERVER_PORT` variable is not in the `.env` file

**To Reproduce**

1. Remove the SERVER_PORT variable from the `.env` file
2. Start the API
3. Errors are seen

**Expected behavior**

1. The API should default to a SERVER_PORT if the variable is not in the `.env` file
2. We need valid passing tests created to make sure that this is not repeated

**Actual behavior**

- See above

**Screenshots**

image

**Additional details**

The feature was added in this PR, but this edge case was not considered

- https://github.com/PalisadoesFoundation/talawa-api/issues/2259

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Suyash878**
**What kind of change does this PR introduce?**

Bug fix

**Issue Number:**

Fixes #2285 

**Did you add tests for your changes?**

Not sure if relevant here.

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Summary**
This PR introduces a fix to edge case where if the port is not defined in the .env file then it should default to 4000.

**Does this PR introduce a breaking change?**

No

**Other information**

None

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
  - Added validation for the `SERVER_PORT` environment variable to ensure it is a valid port number before starting the server. An error is provided if the port is invalid.
  - Introduced `serverHost` to dynamically store host information.

- **Dependencies**
  - Added `redis-server` dependency (version `1.2.2`).
  - Updated `@types/node` dependency version from `^20.14.0` to `^20.14.5`.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Suyash878 Please resolve the coderabbit comments and the failed checks.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why did you add the `redis-server` package?

**Comment by Suyash878** [comment]
@palisadoes I have removed the `redis-server` package. Kindly review the PR

**Comment by SiddheshKukade** [comment]
@Suyash878 Please take a pull.

**Comment by palisadoes** [comment]
Please fix the failing tests.

**Comment by Suyash878** [comment]
One of the checks states that the branch to which the changes will be commited to (ie: develop) for this case should be different from the branch I am currently making changes in. 
So I am **closing** this PR and creating a new PR that will commit changes from my own newly created branch "**bug-fix**" to the develop branch of Palisadoes.

**Pull request closed without merging**
