### PR TITLE
Remove unused packages from package.json

### LINKED ISSUE #1538: Remove all unused packages from `package.json`
**Is your feature request related to a problem? Please describe.**

1. We have implemented dependabot alerts to let us know when we have outdated packages
2. We have noticed in the past that in some cases the packages listed in `package.json` are no longer being used

**Describe the solution you'd like**
1. Remove all references to unused packages from `package.json`
2. Generate `package-lock.json` appropriately

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Community-Programmer**
**What kind of change does this PR introduce?**
Dependabot alerts were notifying us about outdated packages, but upon closer inspection, we discovered that certain packages listed in the package.json file were no longer in use

Issue Number:

Fixes #1538 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Summary**

**Implementation Details:**

In this pull request, I have diligently removed the following dependencies that were identified as unused in our codebase:

- `body-parser`
- `install`
- `vite`

This cleanup ensures that our project's dependencies accurately reflect the packages in active use.

**Validation:**

To ensure the reliability of this change, I thoroughly inspected the entire codebase and conducted multiple tests. The removal of these four dependencies has been validated, and our tests confirm that they are currently unused.

image
image
image

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by xoldyckk — DISMISSED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Community-Programmer** [comment]
@palisadoes 

I hope this message finds you well. I wanted to apologize for the confusion caused by my recent attempt to resolve the conflict 

It seems I made a mistake in resolving the conflict, and I acknowledge that it has affected the failing test case. I want to assure you that I am working on fixing the issue promptly. I will make the necessary adjustments to both the failing test case and the conflicting file to ensure everything is in order.

I appreciate your understanding and patience. Please bear with me as I address these issues. 

Thank you for your time, and sorry for any inconvenience caused

**Comment by palisadoes** [comment]
Conflicts are an expected part of overlapping PRs being merged.

**Comment by Community-Programmer** [comment]
> Conflicts are an expected part of overlapping PRs being merged.

Thank you for the assistance 
fixed the conflict

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
