### PR TITLE
Saymedgm

### LINKED ISSUE #317: Upgrade glob-parent to version 5.1.2 or later
**Describe the bug**
1. Upgrade glob-parent to version 5.1.2 or later. 
1. [The current version is vulnerable to a regular expression denial of service attack.](https://github.com/advisories/GHSA-ww39-953v-wcq6)

**To Reproduce**

* See advisory above

**Expected behavior**
* See advisory above

**Actual behavior**

* See advisory above

**Screenshots**

image

**Additional details**
None

### PR DESCRIPTION
**Pull request by saymedgm**
What kind of change does this PR introduce?

BugFix

Issue Number:

Fixes #317 

Did you add tests for your changes?

Not needed

If relevant, did you update the documentation?

No

Summary

Earlier versions of npm packages were vulnerable and contained some high security risk so I have updated all the npm packages to reduce security issues 

Does this PR introduce a breaking change?

No

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@saymedgm  please fix the conflicting files

**Review by palisadoes — CHANGES_REQUESTED** [review]
@saymedgm please fix the conflicting files

**Comment by saymedgm** [comment]
which conflicting issues @palisadoes

**Comment by palisadoes** [comment]
The conflicting files in your pull request. They are listed

**Comment by saymedgm** [comment]
@palisadoes i am facing some issues I am closing pull request will soon create a new

**Comment by saymedgm** [comment]
please re assign me this issue

**Comment by saymedgm** [comment]
please reassign me this issue

**Pull request closed without merging**
