### PR TITLE
Agenda Item By Event and Organization

### LINKED ISSUE #2345: Feature Request: Query for AgendaItem by Event and Organization
**Is your feature request related to a problem? Please describe.**
Query must fetch the agenda items for particular event and organization.

**Describe the solution you'd like**

**Parent issue**
- https://github.com/PalisadoesFoundation/talawa-api/issues/1588
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1778

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
Query implementation

**Issue Number:**

Fixes #2345

**Did you add tests for your changes?**

**Snapshots/Videos:**

Screenshot from 2024-06-14 17-23-01

Screenshot from 2024-06-14 17-08-59

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
  - Introduced GraphQL queries `agendaItemByEvent` and `agendaItemByOrganization` to fetch agenda items based on event or organization.

- **Tests**
  - Added tests for `agendaItemByEvent` to verify fetching items by event.
  - Added tests for `agendaItemByOrganization` to verify fetching items by organization.

### CODE REVIEW

**Review by varshith257 — APPROVED** [review]
LGTM

**Comment by tasneemkoushar** [comment]
@gautam-divyanshu in `ActionItem.ts`, shall we also change `relatedEventId to eventId` like you did for `organizationId`
@palisadoes would like you get your view on that

**Comment by gautam-divyanshu** [comment]
> hall we also chan

@tasneemkoushar Please confirm if it is `AgendaItem.ts` because I changed it for  `AgendaItem.ts `, according to me it won't matter because I changed organization to organizationId because for other file for this feature have organizationId, so to work this , I have to change

**Comment by tasneemkoushar** [comment]
> > hall we also chan
> 
> @tasneemkoushar Please confirm if it is `AgendaItem.ts` because I changed it for  `AgendaItem.ts `, according to me it won't matter because I changed organization to organizationId because for other file for this feature have organizationId, so to work this , I have to change

yeah @gautam-divyanshu I meant `AgendaItem.ts`

**Comment by tasneemkoushar** [comment]
@gautam-divyanshu LGTM apart from that minor comment. I am approving this PR but lets wait for @palisadoes review once on that minor change

**Review by tasneemkoushar — APPROVED** [review]

**Comment by gautam-divyanshu** [comment]
> @gautam-divyanshu LGTM apart from that minor comment. I am approving this PR but lets wait for @palisadoes review once on that minor change

ok

**Comment by gautam-divyanshu** [comment]
@palisadoes Can we merge this?

**Comment by gautam-divyanshu** [comment]
I have to create other PRs that depend on it.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
