### PR TITLE
feat: Created an User Type Flag Field - AppUserType

### LINKED ISSUE #1552: Create an `User Type` Flag Field
**Is your feature request related to a problem? Please describe.**

Currently our application assumes that all persons tracked in the database are Talawa users. This may not be the case in practice. Administrators will require the ability to manage people who either cannot access our apps or don't want to.

**Describe the solution you'd like**

1. We need to update the `User` collection to have a `User Type` field that could have at a minimum these possible values
     1. `App User`
     1. `Non App User`
1. This will need to be a mandatory field
1. Mutations for this field will need to be created for the `User` and related collections

The aim is that this field will be automatically populated during the registration process. Here are some examples:
1. Registrations through the mobile app would automatically be by an `App User`
1. Registrations through the User Portal web app would automatically be by an `App User`
1. Admins may want to manually add Users who may be an `App User` or a `Non App User`
1. Persons attending events may need to be checked in. If they are new to the organization, then the event organizer may want to add them as a `Non App User`

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1552 (This issue - Prerequisite)
1. https://github.com/PalisadoesFoundation/talawa/issues/2269
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1273

**Other**
- Valid tests for this must be created as part of the resolution of this issue

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Doraemon012**
**What kind of change does this PR introduce?**

- Feature
- This PR introduces a new feature to address issue #1552.
- It adds a User Type field named `AppUserType` to the User collection, allowing for the classification of users as either App Users or Non-App Users.

**Issue Number:**

Fixes #1552

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

SignUp (makes default `APP_USER`):

[signup.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/8ffd4b9d-9bda-4a4a-ad2c-8db28c8bde56)

Check the `AppUserType`:

[get_all_users.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/9ec0126f-dc21-4be0-83c7-1404741563c2)

`Superadmin` can update `AppUserType`:

[update_app_user.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/fda26196-c5ff-4ea7-8e37-99c9a12579d0)

**If relevant, did you update the documentation?**

The documentation does not need to be updated.

**Summary**

- This PR addresses the need to differentiate between `App Users` and `Non-App Users` in the `User collection`.
- The new `AppUserType` field has been added, and mutations have been created for the User and related collections.
- During the registration process, the field is automatically populated with a default value of `APP_USER`.
- Additionally, `superadmin` have the flexibility to change app user type.

**Does this PR introduce a breaking change?**

No
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by imshivam-gupta** [comment]
@Doraemon012 Can you please cover the remaining test coverage of changed  files  to pass all the failing tests

**Comment by palisadoes** [comment]
> @Doraemon012 Can you please cover the remaining test coverage of changed files to pass all the failing tests

@imshivam-gupta 

1. Our target coverage is 95% which the `Testing Application` workflow verifies. 
2. The code coverage helper tests will fail whenever there is a decline. The failing files are not a part of this PR.
3. We have separate issues for updating the code coverage for most of the files with outstanding testing requirements

**Comment by palisadoes** [comment]
@xoldyckk @sumitra19jha 

1. The videos show the desired functionality. 
2. Let's get this reviewed quickly as it is a blocking PR for other work.

**Comment by palisadoes** [comment]
@xoldyckk @sumitra19jha Please remember this

**Comment by xoldyckk** [comment]
This is dirty, a person who isn't a user of talawa apps shouldn't be added amongst the users who are by differentiating on a new field. That user's database object would get all the other fields that app users have, many weird checks would have be placed throughout the codebase to differentiate between app and non app users.

Instead there should be a generic `User` type that contains the absolute minimum of fields to identify a user of any type, while the app specific fields related to app users should be moved to another database object, something like `Profile`. Each user would be linked to exactly one `Profile` object and vice versa, `user.profile_id -> profile.id` and `profile.user_id -> user.id`.

**Comment by palisadoes** [comment]
@xoldyckk 

- These are the fields that we could put in an `appProfile`.

image

We'll need to finalize the approach soon as there will soon be many dependent issues based on this

**Review by sumitra19jha — DISMISSED** [review]

**Comment by sumitra19jha** [comment]
Code Logic is ok to merge, **if needed**

I am not sure about the concept of non-app user. It seems like we are talking about temp or active user. This word is what lot of edtech or online streaming platform uses. You create a temp session for a user and once user is added in active, then make temp history available

**Comment by palisadoes** [comment]
@sumitra19jha 
- What is your opinion of adding a `NON-USER` enum here?
image

**Comment by sumitra19jha** [comment]
Yes we should do it here @palisadoes . This will serve the purpose

**Comment by palisadoes** [comment]
> @sumitra19jha
> 
>     * What is your opinion of adding a `NON-USER` `enum` here instead?
>       image

@Doraemon012 Please proceed with this simpler approach

**Comment by Doraemon012** [comment]
@palisadoes , @sumitra19jha , @xoldyckk , I've updated the code. Please check it out.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
