### PR TITLE
table of content script

### PR DESCRIPTION
**Pull request by Veer0x1**
**What kind of change does this PR introduce?**
script to generate table of contents for markdown files.

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
We think this is the cause of the schema issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/1599

We can merge your work if it's OK

**Comment by Veer0x1** [comment]
Yes, I've observed that after submitting a pull request, if an additional commit is added, the Schema workflow fails. However, you can proceed with merging this pull request, as I've verified on my fork that its workflow is passing.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
1. This was merged without an issue number. What was it?
2. Please follow the procedure. We are tracking dozens of events simultaneously

**Comment by Veer0x1** [comment]
It was my bad, won't happen from next time

**Pull request merged**
