### PR TITLE
Schema modification

### LINKED ISSUE #310: Adding access status parameter in all data model
**Is your feature request related to a problem? Please describe.**
Data Maintenance within database

**Describe the solution you'd like**
Adding access parameter that shows access status 

**Approach to be followed (optional)**
Inserting access parameter in all data models

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
feature #310 

**Issue Number:**

Fixes #310 

**Did you add tests for your changes?**
Not needed here

**If relevant, did you update the documentation?**
Not needed here

**Summary**
Access parameter will help in maintaining record in DB

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by sumitra19jha** [comment]
@DMills27 @forevergareth Please review this PR

**Review by forevergareth — APPROVED** [review]

**Comment by ranilwallace** [comment]
@forevergareth are these changes okay to be merged?

**Comment by sumitra19jha** [comment]
@ranilwallace yes

**Comment by sumitra19jha** [comment]
@DMills27 
Please review the PR

**Review by DMills27 — APPROVED** [review]

**Pull request merged**
