### PR TITLE
Bug fixed to display markdown using marked

### LINKED ISSUE #845: Not able to display markdown while running setup command
**Describe the bug**
While running setup command, the terminal is falling with error,

console.log(marked(text));
              ^

TypeError: marked is not a function

**To Reproduce**

1. Run the command 'npm run setup'
2. Check the terminal, there will be a marked error

**Expected behavior**
It should execute the **automated installation** process of Talawa API. Each file contains a function to complete a particular step. All the functions are asynchronous and display whether the operation has been completed successfully or not.

**Screenshots**
image

**Actual behavior**
See above

**Additional details**

### PR DESCRIPTION
**Pull request by nishant3721**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #845 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

Not relevant

**Does this PR introduce a breaking change?**

No

**Other information**

Not required

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@nishant3721 I'm going to have to revert this PR. It is causing this error.  https://github.com/PalisadoesFoundation/talawa-api/actions/runs/3864858143

Please evaluate and resubmit.

**Comment by nishant3721** [comment]
@palisadoes Is this still causing error?

**Comment by palisadoes** [comment]
Please resubmit. We managed to find out what was wrong.

**Comment by nishant3721** [comment]
Ok @palisadoes

**Pull request merged**
