### PR TITLE
 Test : Tests for src/resolvers/Mutation/updateAdvertisement.ts 

### LINKED ISSUE #2055: Test: Create tests for src/resolvers/Mutation/updateAdvertisement.ts
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Atharva-Kanherkar**
**What kind of change does this PR introduce?**

 Test 
**Issue Number:**

Fixes #2055 

**Did you add tests for your changes?**

Yes 

**Snapshots/Videos:**

N/A 

**If relevant, did you update the documentation?**

 No

**Summary**

 Added and updated the existing unit tests to ensure 100% test code coverage for the file.

**Does this PR introduce a breaking change?**

No
 
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

 Yes

### CODE REVIEW

**Comment by Atharva-Kanherkar** [comment]
@palisadoes  All the tests are passing. I think it is good to merge.

**Comment by palisadoes** [comment]
The code coverage report wasn't generated. I ran the tests again to generate it, and now the tests are failing. Please check again.

**Comment by Atharva-Kanherkar** [comment]
> The code coverage report wasn't generated. I ran the tests again to generate it, and now the tests are failing. Please check again.

I ran the tests locally and all the tests pass : 
image
Also sir there is 100% Test code coverage as you can see here : 
image
What might be going wrong locally?

**Comment by palisadoes** [comment]
1. You are using a file in the `video/` directory which is specifically excluded from the repo in `.gitignore`.
2. We did it that way to make sure that uploaded videos are not added to the repository. Please check other video tests to see what they did to pass 

image

**Comment by Atharva-Kanherkar** [comment]
@palisadoes All the tests pass right now. But the codecov report is still not generated

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
