### PR TITLE
Backend support api ready along with AWS S3 connection.

### PR DESCRIPTION
**Pull request by nishnatadebnath**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
@nishnatadebnath Please resolve the conflicts so we can merge

**Comment by palisadoes** [comment]
@nishnatadebnath Please fix the conflicting files. @DeltaHarbinger, @TheHazeEffect  Please review.

**Comment by SiddheshKukade** [comment]
@DeltaHarbinger please review

**Comment by palisadoes** [comment]
Closing due to lack of activity

**Pull request closed without merging**
