### PR TITLE
Resolves #210 Image upload mutations

### LINKED ISSUE #210: Resolver: Code Coverage for uploadImage.js
**Describe the solution you'd like**
Implement tests for all mutations that include image uploading

### PR DESCRIPTION
**Pull request by XshubhamX**
I have created Image upload test for signup mutation by sending request in multipart form data. @Sagar2366  Sir.

### CODE REVIEW

**Comment by heyjordn** [comment]
@XshubhamX Thanks for this PR but why does it have so many commits from @palisadoes, could you try rebasing please?

**Comment by XshubhamX** [comment]
Sir when i chenged upstream branch from master to develop all these commit came ,I dont know the reason Sir @heyjordn

**Comment by XshubhamX** [comment]
Sir i just rebased and again this is hapenning @heyjordn

**Comment by xsh2047** [comment]
Your constants.js is pointing to a local instance, please resolve

**Review by XshubhamX — COMMENTED** [review]
Completed @xsh2047 Sir

**Pull request closed without merging**
