### PR TITLE
Upgrade nanoid to 3.1.31

### LINKED ISSUE #477: Exposure of Sensitive Information to an Unauthorized Actor in nanoid package
**Describe the bug**

The package `nanoid` before 3.1.31 are vulnerable to Information Exposure via the valueOf() function which allows to reproduce the last id generated.

The earliest fixed version is `3.1.31`

Upgrade `nanoid` to `3.1.31`

### PR DESCRIPTION
**Pull request by DivyanshuParwal**
**What kind of change does this PR introduce?**

Fixes a bug by upgrading `nanoid` to `3.1.31`. Updates `lib/helper_lib/request-tracing/index.js` file to use the upgraded version of  `nanoid`.

**Issue Number:**

Fixes #477 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Not required

**If relevant, did you update the documentation?**

Not required

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Your tests are failing please fix.

- [Details](https://github.com/PalisadoesFoundation/talawa-api/runs/5513090930?check_suite_focus=true)

**Comment by DivyanshuParwal** [comment]
@palisadoes I have looked at the above details but I'm not able to figure out what should be corrected as the server is running without any error in my local environment.

**Comment by palisadoes** [comment]
The error is in the language resolver test. Have you merged your code with the latest updates from `upstream/develop` ?

- [Details](https://github.com/PalisadoesFoundation/talawa-api/runs/5513090930?check_suite_focus=true) 

image

**Comment by DivyanshuParwal** [comment]
Yes, the latest updates are already merged in.
Mozilla Firefox 12-03-2022 22_40_51

**Comment by palisadoes** [comment]
Some work on correcting this is being done with https://github.com/PalisadoesFoundation/talawa-api/pull/611. We need to make sure we are not working in parallel.

**Comment by sumitra19jha** [comment]
@DivyanshuParwal The reason for your error is the random selection of language translation. In your workflow, unfortunately, the test case whose work was to add a new language translation packet picked the one that was already added in the previous test case. Thus throwing error.

What I mean is initially the code added the translation of hello world English to Chinese. In the next test case, it was not supposed to pick Chinese again but any language packet other than that, but random function on the array picked that one.

**Comment by palisadoes** [comment]
@DivyanshuParwal Please merge your code with the latest `upstream/develop` branch and update your PR.

**Comment by palisadoes** [comment]
Please merge your code with the latest updates and all the tests will pass.

**Pull request merged**
