### PR TITLE
feat: Updated the LAST_RESORT_SUPERADMIN_EMAIL logic during setup

### LINKED ISSUE #1550: Update the LAST_RESORT_SUPERADMIN_EMAIL logic during setup
**Is your feature request related to a problem? Please describe.**

When running the setup command `npm run setup`:

1. If no `LAST_RESORT_SUPERADMIN_EMAIL` value has been configured then:
2. The `LAST_RESORT_SUPERADMIN_EMAIL` value should default to the `MAIL_USERNAME` value

This will make the installation smoother and allow easier registration.

**Describe the solution you'd like**
- See above

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Doraemon012**
**What kind of change does this PR introduce?**

- This is PR is a **feature** as requested in #1550 

**Issue Number:**

- Fixes #1550

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

- When `LAST_RESORT_SUPERADMIN_EMAIL` is not configured:

[not_configured.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/fb48063e-3479-4610-8af9-dc2fadadbaa6)

- When `LAST_RESORT_SUPERADMIN_EMAIL` is configured:

[configured.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/7085df2e-207d-4ec2-845f-5b6c8d2b8156)

**If relevant, did you update the documentation?**
There's no need to change the documentation.

**Summary**

- **Motivation** : When running the `npm run setup` command, if the `LAST_RESORT_SUPERADMIN_EMAIL` value has not been configured, it would be beneficial for it to default to the value of `MAIL_USERNAME`. 
- **Solution** : Modified the setup process to automatically set the `LAST_RESORT_SUPERADMIN_EMAIL` to the value of `MAIL_USERNAME` if it is not explicitly configured during the setup.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
It doesn't work if you have:
```
MAIL_USERNAME=me@gmail.com
LAST_RESORT_SUPERADMIN_EMAIL=
```

**Comment by Doraemon012** [comment]
@palisadoes I've updated the logic. Please check it.
Now all the test cases are being passed.
These are some of them :

[user_already_added_16:37.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/1cf190b5-bac2-47be-8b41-78f1d87a4668)

[user_already_added_and_changed_16:38.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/6b9b8f2d-bafb-4af4-8e79-d88ea562e865)

[usr_already_Set_super_congig_16:39.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/6169e1e9-5909-41f3-a7f6-011017bbbb7a)

**Comment by palisadoes** [comment]
1. I also noticed that if you comment out the parameter with a `#` in the `.env`file that the script fails with an incorrect message
1. Please check what happens if the parameter is completely removed from the configuration. It should be added without error. This should be the case with any parameter.
1. Check whether general comments are removed from the `.env` file too. This is not desirable for the devops user.

**Comment by palisadoes** [comment]
1. If you have no `.env` file the script doesn't super admin default to the mail address
2. If you enter a RECAPTCHA_SECRET_KEY value, then the RECAPTCHA_SITE_KEY should be mandatory
3. The `Congratulations` message is sometimes duplicated

**Comment by Doraemon012** [comment]
@palisadoes 
Here, the third point means that comments should be allowed in the `.env` file. Am I right ?
> 1. I also noticed that if you comment out the parameter with a `#` in the `.env` file that the script fails with an incorrect message
> 
> 2. Please check what happens if the parameter is completely removed from the configuration. It should be added without error. This should be the case with any parameter.
> 
> 3. Check whether general comments are removed from the `.env` file too. This is not desirable for the devops user.

Also, for the first and second points, I've made some changes in the code.
1. If a parameter in the `.env` file is missing or commented out with a `#`, the missing parameter is copied from the `.env.sample` file and appended to the `.env` file.
2. If the `.env` file is not present or is deleted, the script automatically copies all the contents (with comments) from the `.env.sample` file.

**Comment by palisadoes** [comment]
> @palisadoes Here, the third point means that comments should be allowed in the `.env` file. Am I right ?
> 
> > 1. I also noticed that if you comment out the parameter with a `#` in the `.env` file that the script fails with an incorrect message
> > 2. Please check what happens if the parameter is completely removed from the configuration. It should be added without error. This should be the case with any parameter.
> > 3. Check whether general comments are removed from the `.env` file too. This is not desirable for the devops user.
> 
> Also, for the first and second points, I've made some changes in the code.
> 
>     1. If a parameter in the `.env` file is missing or commented out with a `#`, the missing parameter is copied from the `.env.sample` file and appended to the `.env` file.
> 
>     2. If the `.env` file is not present or is deleted, the script automatically copies all the contents (with comments) from the `.env.sample` file.

Are the comments preserved when the `.env` file is updated multiple times?

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@xoldyckk PTAL

**Comment by palisadoes** [comment]
This looks good. I'll merge it

**Comment by Doraemon012** [comment]
> 1. I also noticed that if you comment out the parameter with a `#` in the `.env`file that the script fails with an incorrect message
> 
>     2. Please check what happens if the parameter is completely removed from the configuration. It should be added without error. This should be the case with any parameter.
> 
>     3. Check whether general comments are removed from the `.env` file too. This is not desirable for the devops user.

@palisadoes I haven't committed for this yet. 
The video posted by me was just to know your views on my approach.
Should I open a new issue and open a PR for the same ?

**Comment by Doraemon012** [comment]
> If you enter a RECAPTCHA_SECRET_KEY value, then the RECAPTCHA_SITE_KEY should be mandatory

@palisadoes Should I add this to the above or should I open an issue and a PR for this ?

**Pull request merged**
