### PR TITLE
Updated the Sample Data With More Meaningful Entries (#1546)

### LINKED ISSUE #1546: Update the Sample Data With More Meaningful Entries
We need to have more realistic data in the Talawa-API sample data importation process. The data also needs to be more secular so that the application will more likely appeal to a wider range of Admins testing Talawa for their communities.

The organization names also need to reflect the most common use case of related organizations being managed by Talawa. They also need to be more global to have broader appeal

Therefore the following changes are needed.

## Possible Approach

You will need to investigate whether this approach is viable and suggest modifications where applicable.

1. Load the current sample data into Talawa Admin
2. Use Talawa Admin to make the modifications below
3. Save the resulting database as the new sample data that `setup.ts` uses

## New Organization Names

Rename the organizations in the sample data to the following, with updated geographic location data. These cities are well known and geographically close together. This would be a typical scenario for a community based organization

1. Unity Foundation – Bronx
1. Unity Foundation – Queens
1. Unity Foundation – Staten Island
1. Unity Foundation – Brooklyn

## Users

We will need more users who can be used in later tasks

1. Add 8 new users
1. They must be registered members for all 4 organizations

## Events

We need recurring events created so that the calendar is populated no matter when the data is loaded.

### Weekly Recurring Events – Non Registration

Add the following public events to each organization. Registration is not required:

1. Monday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Yoga Class for Seniors": 10:00am – 11:00am, Location: Studio B
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
    1. "Book of the Week Club": 2:00pm – 3:00pm, Location: Atlantic Conference Room
1. Tuesday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Wednesday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Art Class - Advanced": 10:00am – 11:00am, Location:
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Thursday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Kids Karate": 6:00pm – 7:00pm, Location: Studio B
    1. "Art Class - Beginners": 3:00pm – 4:00pm, Location: Studio A
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Friday:
    1. "Aerobics for Everyone": 6:00am – 7:00am, Location: Studio A
    1. "Early Morning Pilates": 6:00am – 7:00am, Location: Studio B
    1. "Neighborhood Watch Meeting": 6:00pm – 7:00pm, Location: Atlantic Conference Room
    1. "Lap Swimming": 6:00am – 3:00pm, Location: Pool
1. Saturday:
    1. "So Bad They’re Good Movie Night": 7:00pm – 9:00pm, Location: Main Theatre
1. Sunday:
    1. "Travel Club": 6:00pm – 7:00pm, Location: Atlantic Conference Room

### Weekly Recurring Events – With Registration

Add the following public events to each organization. Registration is required. Make at least 4 of the newly added users be pre-registered in each of the events with no timing conflicts.

1. Monday:
    1. "Youth Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Finance Committee Meeting": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Risk Committee Meeting": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Tuesday:
    1. "Adult Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Conference Planning Committee": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Organization Strategy Workshop": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Wednesday:
    1. "Youth Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Families With Addiction": 5:00pm – 6:30pm, Location: Pacific Conference Room
    1. "Investment Strategy Committee": 6:00pm – 7:30pm, Location: Arctic Conference Room
1. Thursday:
    1. "Adult Swimming Lessons": 3:00pm – 5:00pm, Location: Pool
    1. "Programming for Everyone": 3:00pm – 5:00pm, Location: Computer Lab
    1. "University Preparation Tips": 5:00pm – 8:00pm, Location: Arctic Conference Room
1. Friday:
    1. "Career Counseling": 3:00pm – 5:00pm, Location: Pacific Conference Room
1. Saturday:
    1. "Saturday Serenade Concert": 5:00pm – 7:00pm, Location: Garden Patio
    1. "Youth Soccer Lessons": 9:00am – 10:00am, Location: Sports Field
1. Sunday:
    1. "Travel Club": 6:00pm – 7:00pm, Location:

## Posts

Make all 8 new users have posts created at the time of data import for these organizations. The posts must have meaningful titles and text that matches the title (at least 20 words). Half the posts must have images, the rest must be text only. The images must be single color royalty-free and a part of the repo in an area dedicated for the sample data importation.

1. Unity Foundation – Bronx
1. Unity Foundation – Queens

## Other
1. All tests must pass
1. No functionality of the app must be affected
1. The suggested entries above may have errors. Wherever possible there must not be scheduling conflicts for:
    1. Locations
    1. Users 
 1. The sample data must be importable by the setup script without error and fully functional no matter how many times the setup script is run.

### PR DESCRIPTION
**Pull request by DecodeAndCode**
**What kind of change does this PR introduce?**
Feature

**Issue Number: 1546**

Fixes #1546 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
This will not be possible until the recurring events feature is added. You'll have to wait until such time.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1583#issuecomment-1872517639

Closing

**Comment by DecodeAndCode** [comment]
Can I raise the PR after this issue is resolved.

**Comment by palisadoes** [comment]
Yes

**Comment by DecodeAndCode** [comment]
Ok

**Comment by DecodeAndCode** [comment]
@palisadoes As the #1658 is now merged can you reopen the PR #1622.

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by DecodeAndCode** [comment]
@palisadoes please check once now

**Comment by palisadoes** [comment]
1. Please fix the failing test. 
2. `package-lock.json` is out of sync

**Comment by palisadoes** [comment]
1. Please fix the failing tests
2. `run npm install` then commit

**Pull request closed without merging**
