### PR TITLE
Potential Privilege Escalation BugFix

### PR DESCRIPTION
**Pull request by krishna619**
What kind of change does this PR introduce?

BugFix

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1792

Did you add tests for your changes?

Yes.

Summary

This vulnerability could allow attackers to gain unauthorized access to user accounts, potentially leading to privilege escalation and compromise of sensitive data.
So, the token should be verified based on the original email address associated with the request.

Does this PR introduce a breaking change?
No

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by krishna619** [comment]
@Cioppolo14 @SiddheshKukade please review.

**Comment by Cioppolo14** [comment]
@krishna619 Please fix the failing tests.

**Comment by krishna619** [comment]
@Cioppolo14 I don't know why this updatePost.spec.ts is failing, I have not worked upon this file, I just took the latest develop pull. Please tell me what to do in this case.
@palisadoes

**Comment by Cioppolo14** [comment]
@krishna619 Please check in the talawa-api slack channel.

**Review by SiddheshKukade — APPROVED** [review]
LGTM.

**Comment by palisadoes** [comment]
@SiddheshKukade The tests are not passing.

**Comment by krishna619** [comment]
> @krishna619 Please check in the talawa-api slack channel.

I did not find any related thing to this

**Comment by krishna619** [comment]
@SiddheshKukade what to do?

**Comment by krishna619** [comment]
> @SiddheshKukade what to do?

++ @palisadoes

**Comment by krishna619** [comment]
image

in my local machine, this specific test is getting passed

**Comment by Cioppolo14** [comment]
@krishna619 Ask the slack channel for advice, see what their feedback is.

**Comment by krishna619** [comment]
> @krishna619 Ask the slack channel for advice, see what their feedback is.
okay 👍
will do

**Comment by palisadoes** [comment]
Please watch this video for insights
- https://www.youtube.com/watch?v=dQuEKpsy1vM

**Comment by krishna619** [comment]
@Cioppolo14 @SiddheshKukade Please do review.

**Comment by palisadoes** [comment]
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

**Review by SiddheshKukade — APPROVED** [review]
Looks good to me. Please take a pull so that we can merge this.

**Comment by SiddheshKukade** [comment]
Please take a pull from origin @krishna619 
and @aashimawadhwa please review

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
This needs to be reverted. It's causing linting errors in other PRs

**Pull request merged**
