### PR TITLE
Fixed typescript enums and restructured the project.

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

Feature, refactoring

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot_20230119_023251

**If relevant, did you update the documentation?**

-

**Summary**

I've changed the graphql code generator config to generate graphql enums as typescript union types instead of object types. This makes it easier to work with enums within typescript code. I've refactored all the places where the old enum approach was being used with the new approach. I've also made several changes to the project structure to make it look cleaner and easier to navigate. The config changes needed for project restructure are also dealt with.

**Does this PR introduce a breaking change?**

It doesn't introduce a breaking change

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@xoldyckk We should get some others to look at this. The level of refactoring is significant.

**Comment by palisadoes** [comment]
@xoldyckk Why did you edit files in the `.github` directory?

**Comment by palisadoes** [comment]
@xoldyckk Please describe the refactoring methodology. 
- For example: what is the new folder structure and why did you change it?

**Comment by xoldyckk** [comment]
@palisadoes

I updated `check-jsdocs-comment.py` file in `.github` folder because it was using names of old directories which have been changed.

New folder structure is to move similar files together. `src` directory will only contain typescript files, `tests` directory will only contain test files, `locales` directory contains only `.json` files so it was put in a separate directory so as to not be mixed with typescript files.

GraphQL code generator config file was changed from `codegen.yml` from `codegen.ts` to make it easier to work with because now we'll get benefits of typescript.

GraphQL code generator was configured to generate typescript unions for corresponding graphql enums, so that makes them easier to work with and provides better type annotations.

Most of the refactoring consists of updating the places where old typescript enums were used with the new typescript unions and also renaming the relative imports because of directory changes.

**Comment by xoldyckk** [comment]
Inclusion of `types` directory was causing the min test coverage to drop down to 68%. The directory is only for typescript types and doesn't need to be included in coverage.

**Comment by SiddheshKukade** [comment]
`Types` and `TypeDefs` are in a separate folder. I'd suggest adding `TypeDefs` into the `types` folder which will be less repetitive. What are your thoughts @xoldyckk 
image

**Comment by xoldyckk** [comment]
> `Types` and `TypeDefs` are in a separate folder. I'd suggest adding `TypeDefs` into the `types` folder which will be less repetitive. What are your thoughts @xoldyckk ? image

`types` and `typeDefs` are different things. `typeDefs` contains graphql schema definition which is used at runtime. `types` will only contain typescript types which will be stripped out after compilation to javascript. `types` folder should not contain anything which is used at runtime. That's one of the reason I replaced typescript object with typescript union for corresponding graphql enum.

**Review by SiddheshKukade — APPROVED** [review]
LGTM !

**Comment by palisadoes** [comment]
@xoldyckk Please fix the conflicting files

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
