### PR TITLE
Refactor: tests/resolvers/Query

### PR DESCRIPTION
**Pull request by KrutikaBhatt**
**What kind of change does this PR introduce?**

 Refactoring the code files from the directory - tests/resolvers/Query

**Issue Number:** #972

**Summary**
Functions were created in `tests/helpers/` for Creating test events, tasks, etc. These functions were used at places for creating test objects to refactor the code files and avoid reputation of codes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@KrutikaBhatt Please attach a screenshot of code coverage as the codecov is not being generated.

**Comment by KrutikaBhatt** [comment]
@noman2002, there are some files whose code coverage isn't completely 100% due to conditional check for PRODUCTION for `requestContext.translate()`. Should I make those changes accordingly?

Here is the screenshot of the Code coverage obtained after refactoring.
code1
image
image

**Comment by palisadoes** [comment]
Yes

**Comment by KrutikaBhatt** [comment]
@noman2002, there is also a small doubt regarding the tests written for file - [postsByOrganizationConnection.spec.ts](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/tests/resolvers/Query/postsByOrganizationConnection.spec.ts). The tests are commented and thus code coverage obtained is very less up to 25%. Can you please guide me on this? Are the tests already covered or new test cases should be added? Thanks

**Comment by KrutikaBhatt** [comment]
> Yes. Will this affect this PR which is doing something similar? #1045

No sir, its actually similar issue but this PR focuses on solving the "conditional check for PRODUCTION" for the code files from directory `tests/resolvers/Mutation`. I will make some similar changes in `/Query` directory

**Comment by anshgoyalevil** [comment]
> @noman2002, there are some files whose code coverage isn't completely 100% due to conditional check for PRODUCTION for `requestContext.translate()`. Should I make those changes accordingly?
> 
> Here is the screenshot of the Code coverage obtained after refactoring. code1 image image

The 

> Yes. Will this affect this PR which is doing something similar? #1045

Actually, this issue was assigned to @EshaanAgg , as far as I know, in the issue https://github.com/PalisadoesFoundation/talawa-api/issues/1005

**Comment by KrutikaBhatt** [comment]
> Actually, this issue was assigned to @EshaanAgg , as far as I know, in the issue #1005
> 
> I guess, that issue was closed before all the files were covered by him, and hence, the issue #1005 need to be reopened.

Ok, actually I started working on it already. Will it be fine to continue on this?

**Comment by anshgoyalevil** [comment]
> > Actually, this issue was assigned to @EshaanAgg , as far as I know, in the issue #1005
> > I guess, that issue was closed before all the files were covered by him, and hence, the issue #1005 need to be reopened.
> 
> Ok, actually I started working on it already. Will it be fine to continue on this?

Yes totally fine. I mentioned to make the things more sorted, by reopening that issue. What's do you suggest Sir @palisadoes ?

**Comment by KrutikaBhatt** [comment]
> @noman2002, there is also a small doubt regarding the tests written for file - [postsByOrganizationConnection.spec.ts](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/tests/resolvers/Query/postsByOrganizationConnection.spec.ts). The tests are commented and thus code coverage obtained is very less up to 25%. Can you please guide me on this? Are the tests already covered or new test cases should be added? Thanks

Hey @anshgoyalevil, can you please check for this also? I would be very much be interested to check on this if its not covered by someone else

**Comment by anshgoyalevil** [comment]
> > @noman2002, there is also a small doubt regarding the tests written for file - [postsByOrganizationConnection.spec.ts](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/tests/resolvers/Query/postsByOrganizationConnection.spec.ts). The tests are commented and thus code coverage obtained is very less up to 25%. Can you please guide me on this? Are the tests already covered or new test cases should be added? Thanks
> 
> Hey @anshgoyalevil, can you please check for this also? I would be very much be interested to check on this if its not covered by someone else

Yes, you may try un-commenting the code, and running the tests again, if that covers the code, then it would be more than good.

**Review by noman2002 — CHANGES_REQUESTED** [review]
@KrutikaBhatt Please resolve the conflicting files

**Comment by KrutikaBhatt** [comment]
@noman2002 @palisadoes,

Here are some changes I have made:
1. Written tests for `postsByOrganizationConnection.ts` and the code coverage obtained is 100%. There were some commented codes before but they were irrelevant, so new tests were added.
2. Refactored the files in `tests/resolvers/Query` to remove the conditional check process.env !== "PRODUCTION" for requestContext.translate(). I have made modifications accordingly and tested them.

This is the code coverage snapshots after completion.
new2
new3
new4

**Comment by palisadoes** [comment]
@Tajcore @noman2002 please review

**Comment by KrutikaBhatt** [comment]
Hey @noman2002 and @palisadoes, can you please review the pull request.

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Review by Tajcore — APPROVED** [review]
LGTM

**Pull request merged**
