### PR TITLE
Bug during file upload resolved.

### LINKED ISSUE #219: Maximum call stack size exceeded when Image is being uploaded.
**Describe the bug**
when a user wants to upload an image api is giving an error from uploadImage.js file .

Screenshot 2021-04-06 131743

Screenshot 2021-04-06 123800
Screenshot 2021-04-06 123739

this can be solved using fs-capacitor package.

Please have a look at it and ping me if I can work on this issue

### PR DESCRIPTION
**Pull request by XshubhamX**
**What kind of change does this PR introduce?**

Fixes #219 

I explained the whole bug in issue #219 and i have resolved it using graphql-upload package @Sagar2366 sir.

Basically the current apollo version which is being used in the project does not support image upload .So we have got two choices either to downgrade node js to version 12 or use graphql-upload. So according to me it would be difficult for everyone to downgrade node js , that's why use of graphql-upload is the best choice.

### CODE REVIEW

**Comment by iamsaumya** [comment]
Hey @XshubhamX, 

Thanks for fixing the bug!

> What kind of change does this PR introduce?

Generally intends to outline the changes you have done in PR. For example, Added a new package `graphql-upload` etc

Could you please update it to something meaningful?

**Comment by XshubhamX** [comment]
> Hey @XshubhamX,
> 
> Thanks for fixing the bug!
> 
> > What kind of change does this PR introduce?
> 
> Generally intends to outline the changes you have done in PR. For example, Added a new package `graphql-upload` etc
> 
> Could you please update it to something meaningful?

ok sir i will give some meaning full description to it Thanks sir.

**Comment by iamsaumya** [comment]
Tip: If you write "Fixes #issueId" in the description, Github will automatically link this PR as a prospect that will fix the issue.

**Comment by XshubhamX** [comment]
> Tip: If you write "Closes #issueId" in the description, Github will automatically link this PR as a prospect that will fix the issue.

Ok sir will keep it in mind.

**Comment by iamsaumya** [comment]
Buddy, I am just like you. Don't call me Sir 😅

**Comment by XshubhamX** [comment]
> Buddy, I am just like you. Don't call me Sir 😅

So from now it will be bro chat 😂

**Comment by Sagar2366** [comment]
> > Buddy, I am just like you. Don't call me Sir 😅
> 
> So from now it will be bro chat 😂

Don't mind if we ask you to do bro chat in slack channel. Please do not spam on GitHub with unnecessary comments.

**Review by XshubhamX — COMMENTED** [review]
Until the PR merges , fellas you can make these changes to your local repo to keep the development process running.

**Pull request merged**
