### PR TITLE
CustomFields and CustomData

### LINKED ISSUE #1431: Custom Fields and Custom Data For Talawa Admin
**Is your feature request related to a problem? Please describe.**
When a member signs up on the mobile app, the information they initially provide creates their profile. Howwever, this data might not cover all the necessary details required by the organization. This feature enables the organization to define additional fields to gather specific data beyond what members initially provide

**Describe the solution you'd like**
The "CustomFields" attribute expands an organization by specifying a list of desired fields, allowing members to register additional data in JSON format. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
  1. Create mutations to add a user's custom data, and an organization's custom field as well as remove a member's custom data and member custom fields
  2. Create a query to view customFieldsByOrganization and customDataByOrganization

**Additional context**

### PR DESCRIPTION
**Pull request by JamarTG**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1431

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
N/A

**Summary**

**Does this PR introduce a breaking change?**

When a member signs up on the mobile app, the information they initially provide creates their profile. However, this data might not cover all the necessary details required by the organization. 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@JamarTG This PR will significantly reduce our code coverage. Many of the updated files have under 100% coverage. Please update the tests accordingly. We cannot afford to return to poor test coverage, it was a very unpleasant user experience in the past when we let it slip.

Please work with @noman2002 on any questions related to this PR or the related issue.

**Comment by JamarTG** [comment]
> @JamarTG This PR will significantly reduce our code coverage. Many of the updated files have under 100% coverage. Please update the tests accordingly. We cannot afford to return to poor test coverage, it was a very unpleasant user experience in the past when we let it slip.
> 
> Please work with @noman2002 on any questions related to this PR or the related issue.

I'm working on increasing it. Only the first 3 are my files

**Comment by JamarTG** [comment]
image

These lines of code are the only ones marked as uncovered for removeUserCustomData, addOrganizationCustomField, and removeOrganizationCustomField. And I did write passing tests for them

image

**Comment by JamarTG** [comment]
> @JamarTG This PR will significantly reduce our code coverage. Many of the updated files have under 100% coverage. Please update the tests accordingly. We cannot afford to return to poor test coverage, it was a very unpleasant user experience in the past when we let it slip.
> 
> Please work with @noman2002 on any questions related to this PR or the related issue.

image

Only these 3 are my changes . And even for these, the lines marked as uncovered were actually covered

**Review by jordan-barrett-jm — APPROVED** [review]
Approving. The remaining files in the code coverage report were not part of this set of changes.

**Comment by JamarTG** [comment]
**Proof of 100% coverage for my files**

image
image
image

**Comment by palisadoes** [comment]
Can this be merged before this PR and is it advisable?
- https://github.com/PalisadoesFoundation/talawa-api/pull/1432

**Comment by palisadoes** [comment]
> @palisadoes I think you meant to link to this talawa-admin PR? --> [PalisadoesFoundation/talawa-admin#1096](https://github.com/PalisadoesFoundation/talawa-admin/pull/1096)
> 
> If so, yes, the API change is best merged before the admin change

Yes, that's right. Let me know when both are ready to be merged so that we can do it simultaneously.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
