### PR TITLE
Fixes Pull Request workflow

### LINKED ISSUE #393: first-interaction action check fails due to deprecated workflow event
**Describe the bug**
The first time interaction GitHub action doesn't work.
When a user submits a PR for the first time in talawa, the first interaction action fails.

**Expected behavior**
The GitHub action checks must pass on pull request from a new contributor

**Actual behavior**
The GitHub action checks fail due to lack of required permissions.

**Screenshots**
Screenshot 2021-12-09 at 11 42 17 PM

**Proposed Solution**
GitHub has solved this issue. Reference : https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

In the workflows, one simply needs to change the the event from pull_request to pull_request_target.

### PR DESCRIPTION
**Pull request by AvneetSingh2001**
**What kind of change does this PR introduce?**
Fixes the pull request workflow so that GitHub secrets can now be accessed by first-interaction action.

**Issue Number:**

Fixes #393 

**Did you add tests for your changes?**
N.A.

**Snapshots/Videos:**
N.A.

**If relevant, did you update the documentation?**
N.A.

**Summary**
Whenever a first-time contributor sends a pull request, first-interaction actions run and add a greeting message to the PR. But this action fails now as it can't access the GitHub token from GitHub secrets due to a deprecated event. This PR updates the event to the latest one so that the issue gets resolved.

**Does this PR introduce a breaking change?**
No

**Other information**
N.A.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@AvneetSingh2001 Will all the actions occur for both first time and experienced PR requesters?

**Comment by AvneetSingh2001** [comment]
yes @palisadoes, it would work for both first time and experienced PR requesters.

**Review by palisadoes — APPROVED** [review]

**Comment by sumitra19jha** [comment]
@palisadoes I think the workflow is now working fine. Check #397, message is added there properly

**Comment by sumitra19jha** [comment]
Should we close this issue?

**Comment by palisadoes** [comment]
Yes. This should be closed. The issue appears to have been fixed.

**Pull request closed without merging**
