### PR TITLE
Reducing multiple error imports by converting them to error objects in `constants.ts`

### LINKED ISSUE #1038: Export multiple arguments of an error as an object to reduce import statements.
**Is your feature request related to a problem? Please describe.**
This issue is related to the refactoring of code, where the multiple arguments of an error are being exported as separate constants. For example:

```
export const COMMENT_NOT_FOUND = "Comment not found";
export const COMMENT_NOT_FOUND_CODE = "comment.notFound";
export const COMMENT_NOT_FOUND_MESSAGE = "comment.notFound";
export const COMMENT_NOT_FOUND_PARAM = "comment";
```
this can be converted to an object like
```
export const COMMENT_NOT_FOUND_ERROR = {
  DESC: "Comment not found",
  CODE: "comment.notFound",
  MESSAGE: "comment.notFound",
  PARAM: "comment",
};
```
which can further be imported in the codebase as an object, and can replace the error constants such as
```
if (!comment) {
    throw new errors.NotFoundError(
      IN_PRODUCTION !== true
        ? COMMENT_NOT_FOUND
        : requestContext.translate(COMMENT_NOT_FOUND_MESSAGE),
      COMMENT_NOT_FOUND_CODE,
      COMMENT_NOT_FOUND_PARAM
    );
  }
```
with 
```
if (!comment) {
    throw new errors.NotFoundError(
      IN_PRODUCTION !== true
        ? COMMENT_NOT_FOUND
        : requestContext.translate(COMMENT_NOT_FOUND_ERROR.MESSAGE),
      COMMENT_NOT_FOUND_ERROR.CODE,
      COMMENT_NOT_FOUND_ERROR.PARAM
    );
  }
```

**Approach to be followed (optional)**
The following approach can be followed:
- Create the error objects.
- Search the codebase for the usage of those constants, and replace them with those objects.

**Additional context**
This will reduce the complexity of codebase import statements, since there are a lot of import statements inside a code file, for the constant, which can be grouped together.

### PR DESCRIPTION
**Pull request by KrutikaBhatt**
**What kind of change does this PR introduce?**

**Issue Number: #1038**

This Pull Request Fixes #1038

**Did you add tests for your changes? No**
But the existing tests were tested for the import changes that were made and they got successfully executed to give 100% code coverage.

**Summary**
The pull request contains the following changes:
1. Converted multiple error export statements to single error objects and replaced them wherever necessary.
2. There were already some error objects created with lowercase key pairs. They were converted to uppercase and their usage was rectified to maintain a proper streamlined format of codes.
3. Some test cases used mocking of the `constants.ts file` to change and test the export objects. Changes were made so that they would run as properly as before avoiding any breaking of code

**Does this PR introduce a breaking change? No**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)? Yes**

### CODE REVIEW

**Comment by KrutikaBhatt** [comment]
@noman2002, I have tried to increase the code coverage for the application. There was a `checkCreator.ts` file that was included first but it has been deleted now referring to the current develop branch. There was a bug in `directMessageChat.spec.ts` but its been fixed and the code coverage of that file is 100% covering all branches. Please review the PR and let me know

**Comment by xoldyckk** [comment]
> @noman2002, I have tried to increase the code coverage for the application but the codecov report shows a drop which I am not able to understand. There was a `checkCreator.ts` file that was included first but it has been deleted now referring to the current develop branch. There was a bug in `directMessageChat.spec.ts` but it's been fixed and the code coverage of that file is 100% covering all branches. Please do review the PR and let me know

Minor code coverage changes are to be expected. Because modifying/deleting lines of code affects the overall code coverage percentage.

**Comment by palisadoes** [comment]
@xoldyckk @noman2002 please review

**Comment by KrutikaBhatt** [comment]
> > @noman2002, I have tried to increase the code coverage for the application but the codecov report shows a drop which I am not able to understand. There was a `checkCreator.ts` file that was included first but it has been deleted now referring to the current develop branch. There was a bug in `directMessageChat.spec.ts` but it's been fixed and the code coverage of that file is 100% covering all branches. Please do review the PR and let me know
> 
> Minor code coverage changes are to be expected. Because modifying/deleting lines of code affects the overall code coverage percentage.

Thank your for letting me know

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
