### PR TITLE
updated:graphql-codegen/typescript-resolvers from 2.7.13 to 4.0.1

### LINKED ISSUE #1511: Upgrade package `graphql-codegen/typescript-resolvers` from 2.7.13 to 4.0.1
For security purposes, we need to bump package [@graphql-codegen/typescript-resolvers](https://github.com/dotansimha/graphql-code-generator/tree/HEAD/packages/plugins/typescript/resolvers) from 2.7.13 to 4.0.1.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1507

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7245533524/job/19735734837?pr=1507

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue
- You PR should have no warning messages
- If this package is no longer used, then references to it must be removed from the code base

### Please ask to be assigned by the contributors mentioned in slack. They will also answer all questions. I no longer assign issues due to the workload with no exceptions.

### PR DESCRIPTION
**Pull request by RAGHAV-N5**
**What kind of change does this PR introduce?**
Updating package
**Issue Number:**

Fixes #1511 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
Screenshot 2023-12-25 174407

**If relevant, did you update the documentation?**

No

**Summary**

I updated the version of graphql-codegen/typescript-resolvers from 2.7.13 to 4.0.1.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by RAGHAV-N5** [comment]
Sure, I will fix the failing tests as soon as possible.

**Comment by RAGHAV-N5** [comment]
@palisadoes 
I am stuck at this point. Please help me how to proceed further with this failed test.

**Comment by palisadoes** [comment]
1. You haven't shown the error message.
1. Most likely the method of function pointed to by the caret doesn't exist anymore or has updated parameters

**Comment by RAGHAV-N5** [comment]
@palisadoes 
1.This is the error message
Screenshot 2023-12-27 182543
2.'Most likely the method of function pointed to by the caret doesn't exist anymore or has updated parameters':
    If this is true please guide me to proceed further.

**Comment by palisadoes** [comment]
Research what the function or method did in the previous version and see what the release notes documentation for subsequent versions recommends for remediation steps

**Comment by RAGHAV-N5** [comment]
Thanks, will work on it.

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by RAGHAV-N5** [comment]
@palisadoes 
Since this PR was raised when I was using node version 21.4.0 and tests are failing, can I close this PR and come up with a new one using node version 20.10.0 which fixes the failing tests?

**Comment by palisadoes** [comment]
OK

**Comment by palisadoes** [comment]
Ask sumitra to review the new PR when ready. I will not review it

**Comment by RAGHAV-N5** [comment]
> Ask sumitra to review the new PR when ready. I will not review it

Okay.

**Pull request closed without merging**
