### PR TITLE
Feat: Added Codecov Github Action

### LINKED ISSUE #386: CodeCov Github Action
**Is your feature request related to a problem? Please describe.**
Workflow related to code coverage needs to be added

**Describe the solution you'd like**
Please refer to the documentation [here](https://github.com/marketplace/actions/codecov) which gives step by step procedure for adding the coverage

**Additional context**
Don't create a separate workflow, write the code in the existing workflow itself

### PR DESCRIPTION
**Pull request by veerreshr**
Signed-off-by: Veeresh <veerreshr@gmail.com>

**What kind of change does this PR introduce?**

1. Aded a codecov github action
2. Added coverage folder to git ignore as it is no longer needed
3. Removed coverage/lcov.info file as it is no longer needed and it will be ignored from now on 

**Issue Number:**

Fixes #386 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

**Summary**

Added codecov github action to existing workflows related to pull requests and set min_coverage value to 60

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
@veerreshr I think there is more to this than what you have. Please work with @sumitra19jha on this. 

- I think the existing coverage system may need to be replaced. 
- We also need to know what the current coverage rate is and set the value in the action to that value, and possibly higher in future iterations.

**Comment by veerreshr** [comment]
Okay sure will work on this. Trying to connect with sumitra on slack

**Comment by sumitra19jha** [comment]
Can you please explain what is lcov.info changes in file is intended for?

**Comment by veerreshr** [comment]
> Can you please explain what is lcov.info changes in file is intended for?

It is being used by `VeryGoodOpenSource/very_good_coverage@v1.1.1` action for setting threshold for code coverage. It is auto generated when you run your tests for code coverage.

**Comment by sumitra19jha** [comment]
I check out this repo, honestly speaking I don't have much confidence in it.
We should stick to using Codecov for reports and Badges in repo

**Comment by palisadoes** [comment]
@veerreshr Please use Codecov as defined in the original issue.

**Comment by veerreshr** [comment]
> @veerreshr Please use Codecov as defined in the original issue. We need a widely used solution that will have ongoing support.

sure give me 15min, I have a doubt, should I keep a fixed value for target coverage rate or should that be based on previous commit ( so that each PR must increase coverage )

**Comment by veerreshr** [comment]
@palisadoes @sumitra19jha I hope I have made requested changes, could you please review again?

**Comment by veerreshr** [comment]
@palisadoes Am I doing it right?

**Comment by palisadoes** [comment]
@veerreshr Please take a look at our [GitHub Actions Guidelines](https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github/workflows). We need your `codecov.yml` file to be added to one of the existing `yaml` files.

**Comment by veerreshr** [comment]
@palisadoes I did not find a way to add configuration file into actions workflow file. Here codecov.yml acts as a configuration file not as workflow, I referred few sources and found out it is only stored inside first level of .github folder. If I can do anything better could you please tell?

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@sumitra19jha Please take a look and review.

**Comment by palisadoes** [comment]
@sumitra19jha Please take a look.

**Comment by sumitra19jha** [comment]
@veerreshr Please go through the doc [here](https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/). This is my expectation from the PR for test files and coverage reports. This PR doesn't reflect this

**Pull request closed without merging**
