### PR TITLE
added tests for src/lib/resolvers/Mutation/removeEventProject.ts

### PR DESCRIPTION
**Pull request by rv602**
### What kind of change does this PR introduce?
Tests for ```src/lib/resolvers/Mutation/removeEventProject.ts``` have been added in ```__tests__/resolvers/Mutation/removeEventProject.spec.ts```

### Video of test coverage : -

https://user-images.githubusercontent.com/92572013/214325286-4ff757b3-87b7-46df-865e-f0d890ca0816.mp4

### Did you update the documentation?
No

### Summary : -
This PR introduces tests for the file - ```src/lib/resolvers/Mutation/removeEventProject.ts```

### Does this PR introduce a breaking change?
No

### Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Couldn't see the coverage comment here! Please wait for review until this issue is fixed.

**Comment by rv602** [comment]
okay 👍

**Comment by palisadoes** [comment]
The code coverage is calculated. @SiddheshKukade @JamaicanFriedChicken Please review

**Review by JamaicanFriedChicken — APPROVED** [review]

**Review by JamaicanFriedChicken — CHANGES_REQUESTED** [review]
Try getting the test coverage to 100%

**Comment by rv602** [comment]
okay

**Review by noman2002 — CHANGES_REQUESTED** [review]
Currently the coverage is at 92% , please try to get it up to 100%

**Comment by rv602** [comment]
okay i'll try increasing it

**Comment by noman2002** [comment]
@rv602 Any progress on this one ?

**Comment by rv602** [comment]
@noman2002, I was working on another PR so didn’t look back on this. I will resume it soon. Sorry for the delay

**Comment by noman2002** [comment]
@rv602 Any update on this?

**Comment by rv602** [comment]
@noman2002 I am working on this.
Actually I have my University end-semester exams in the upcoming days, due to which there may be a slight delay from me in my work for a few days. Kindly excuse me for the same.
Thank you.

**Comment by noman2002** [comment]
This PR is open since 3 weeks. I'm closing this for now. If you get it done, please submit a new PR.

**Pull request closed without merging**
