### PR TITLE
feat: functionality to view unread messages in chat

### LINKED ISSUE #2610: Add feature to view unread messages and mark messages as read in chat (GSoC)
**Is your feature request related to a problem? Please describe.**
Add feature to view unread messages and mark messages as read in chat

**Describe the solution you'd like**
View unread messages

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2610 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Release Notes

- **New Features**
	- Introduced a new field to track unseen messages for users in chats.
	- Added a mutation to allow users to mark chat messages as read, enhancing user interaction.

- **Bug Fixes**
	- Improved error handling for non-existent chats and users in message-related operations.

- **Tests**
	- Enhanced test coverage for the new unseen messages functionality and the marking of messages as read.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting files and make code rabbit approve your changes

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by palisadoes** [comment]
@disha1202 Are you still working on this?

**Comment by Cioppolo14** [comment]
Closing due to inactivity.

**Comment by palisadoes** [comment]
Reopening. GSoC

**Comment by palisadoes** [comment]
@disha1202 Please make the required changes. We'd like to get this feature added.

**Comment by palisadoes** [comment]
1. Please fix the failing tests. Click on the `Details` links for more information.
1. Please make sure that CodeRabbit.ai approves your changes

**Comment by disha1202** [comment]
Hi @palisadoes 
The typecheck test is failing which is not related to the changes in this PR and is fixed in 
https://github.com/PalisadoesFoundation/talawa-api/pull/2770

**Comment by palisadoes** [comment]
@disha1202 The PR was merged and the failed tests persist

**Comment by palisadoes** [comment]
@disha1202 Can we merge this now? Can you make changes so that coderabbit.ai approves?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
