### PR TITLE
Bugfix Incorrect Organization Membership CheckIn

### LINKED ISSUE #1992: [Bug]: Incorrect Organization Membership Check in addEventAttendee Mutation
**Describe the bug**
In the `addEventAttendee` mutation, the function incorrectly checks for organization membership by comparing the `joinedOrganizations` arrays of the `currentUser` and `requestUser`. This approach is not accurate as it does not consider the organization associated with the event.

**Proposed Solution:**
Instead of comparing the `joinedOrganizations` arrays, the function should retrieve the organization associated with the event using its ID (`eventId`). Then, it should check if both the `currentUser` and `requestUser` are members of that organization.

**To Reproduce**

1) Call the `addEventAttendee` mutation with `currentUser` and `requestUser` who are members of different organizations but are attending an event associated with one of the organizations.
2) Observe that the mutation incorrectly permits attendance due to the flawed organization membership check.

_Easy Explanation:_
- Suppose `currentUser` (Admin of Event) and `requestUser` both are part of `Org X`.
- Event happens in `Org Y`
- Current code checks if they have common Org ✅ - YES
- Adds the user to event

**But the requestUser was not even in Org Y**
_(Do not confuse this with AppUser and Non-AppUser)_

**Expected behavior**
The `addEventAttendee` mutation should only allow attendance if both the `currentUser` and `requestUser` are members of the organization associated with the event.

**Screenshots**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**
BugFix 

The `addEventAttendee` mutation should only allow attendance if both the `currentUser` and `requestUser` are members of the organization associated with the event.

**Issue Number:**

Fixes #1992 

**Did you add tests for your changes?**
Yes (were added before)

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by krishna619** [comment]
@palisadoes please review it.

**Comment by palisadoes** [comment]
There is no test for the change

**Comment by krishna619** [comment]
> There is no test for the change

I had written tests for it in this PR https://github.com/PalisadoesFoundation/talawa-api/pull/1909

**Comment by Cioppolo14** [comment]
@DMills27 @EshaanAgg Can you review this PR?

**Comment by palisadoes** [comment]
> > There is no test for the change
> 
> I had written tests for it in this PR #1909

Then why isn't the test failing in this case? It's not written correctly.

**Comment by krishna619** [comment]
> Better stated, why isn't it failing for the other submitted PRs where the bug still exists? The test doesn't seem to be written correctly.

I wanted to clarify that the tests in the previous PR also covered this scenario. The test ensured that the requestUser `organizationID` should not be the same as event's `organizationID` they intend to attend. So, even though the mutation was fine-tuned, the test coverage remained intact. I just narrowed down the mutation `addEventAttendee`

**Comment by krishna619** [comment]
Hey
@DMills27 @EshaanAgg 
Please review this code.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
