### PR TITLE
fixed docker-compose.dev.yaml & separated docker-compose.cloud.yaml

### LINKED ISSUE #2598: setup of talawa-api in local machine  using docker is giving error regarding "PWD" variable not set correctly
**Describe the bug**

This bug is regarding docker-compose.dev.yaml file because of which we are not able to set-up talawa-api in our system.

**Expected behavior**
It should setup the talawa-api by successfully creating 3 docker containers
1. mongodb
2.redis-stack-server
3.minio
upon which the "talawa-api-dev" services depends

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
Error indicate that mongodb is not able to established connection with other containers 

I have attached the screenshot for more detail

**Screenshots**
Screenshot (141)

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by abhayymishraa**
**What kind of change does this PR introduce?**

  bugfix & refactoring
  fixed bug of docker-compose.dev.yaml and introduced docker-compose.cloud.yaml for cloud proxies

**Issue Number:**

Fixes #2598 

**Did you add tests for your changes?**

 No. its already written maybe

**Snapshots/Videos:**
[Screencast from 10-11-24 01:55:37 AM IST.webm](https://github.com/user-attachments/assets/0f137670-5d06-451f-b93e-a0a9972fd3c5)

  

if relevant, did you update the documentation?  no not right now but i will

**Summary**

 So the total summay is majorly in the dev mode of dockercompose we didn't need the caddy service it for cloud for that purpose i made a separate file for it and removed it from dev and also added port mapping to the api server container also added network and there is a bug tooo in the env var that compose-dev of api has it give mongo db url "/" end point suppose if user run the script to addsampledata to database so the api container will look for the / and the script we are running to add sample data have mongodb://mongodb:27017/talawa-api  this talawa-api so i fixed it... also i can update document in next pr if this is ok 

**Does this PR introduce a breaking change?**

yes it will introduce a new file

**Other information**

thats it i didnt tested prod cause its out of context for this issue maybe the same bug in prod too

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** 

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Docker Compose configuration for a multi-service application, including services for MongoDB, Redis, MinIO, Talawa API, and Caddy.
	- Added a dedicated development service for Talawa API with updated configurations.

- **Bug Fixes**
	- Updated the MongoDB connection URL in the development configuration to specify the database name.

- **Chores**
	- Removed the Caddy service from the development configuration and associated volumes.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please make sure that code rabbit approves this PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
You need to update the INSTALLATION.md file to explain how to use the cloud `.yaml` file

**Comment by varshith257** [comment]
@abhayymishraa Inactive?

**Comment by abhayymishraa** [comment]
nope

**Pull request closed without merging**
