### PR TITLE
Improved prompts in setup for loading data.

### LINKED ISSUE #2258: Improve Setup: Better prompts for loading data
**Is your feature request related to a problem? Please describe.**

The current setup process could be confusing for new users.

**Describe the solution you'd like**

1. When data is detected in the database it prompts to overwrite it. This is OK, however the next prompt should be:
    1. `Are you installing this software make open source contributions to the Talawa community ?` or something that more clearly signals the intention.
        1. If `No`, it should prompt to import starting `data for production purposes`, instead of `default data`, which could be confusing, or something that more clearly signals the intention.
        2. If `Yes` it should prompt to import the sample data as before

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above

**Additional context**

image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anubhav-2003**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2258 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Improves the prompts related to importing data in the setup.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, Here is the updated workflow for importing data in the setup. 
Screenshot from 2024-04-29 10-52-39

**Comment by palisadoes** [comment]
1. Thanks, but this is too complicated. 
2. The issue was really simple, mostly just changing the text of the prompts.
3. The section in red can be completely removed. You have two "No" options

image

**Comment by palisadoes** [comment]
Let me think about this some more. The issue isn't that clear.

**Comment by Anubhav-2003** [comment]
> 1. Thanks, but this is too complicated.
> 
>     2. The issue was really simple, mostly just changing the text of the prompts.
> 
>     3. The section in red can be completely removed. You have two "No" options for the open source question. The open source question should default to "No" as most people installing the software will eventually be end users.
> 
> 
> image

Respected sir, it is actually looking complicated here because the entire underlying logic tree is shown, but to the end user for whom only the prompts would be visible, this would remove all ambiguity. 

The section in the red actually addresses the edge cases, that how would an end-user re-import production data if there is already some data in the DB.  The present logic tree actually misses a few edge cases.

If you still feel I should remove those branches, then I would, but then the above edge case won't be addressed.

Thank You.

**Comment by palisadoes** [comment]
PTAL. You have 2 "No" answers coming from the "For Open Source" box. That doesn't make sense. It could be a misprint that doesn't reflect the logic

**Comment by Anubhav-2003** [comment]
> PTAL. You have 2 "No" answers coming from the "For Open Source" box. That doesn't make sense. It could be a misprint that doesn't reflect the logic

Respected sir, one of the "No" options is actually coming from the isDbEmpty box to opensource. And the other is after the opensource prompt. The logic flow starts from the isDbEmpty box according to our setup script.

The flow is like this:
1.Check if DB is empty.
Yes. Then the left blue box prompts.
If No, then the "for opensource" prompts and the entire pink boxes.

**Comment by palisadoes** [comment]
OK, the top of the chart is `isDbEmpty`, I thought it was the open source question.

**Comment by Anubhav-2003** [comment]
> In that case, this section isn't necessary
> 
> image

Ok sir, let me make the changes and I will update you. Thank You.

**Comment by palisadoes** [comment]
Let me get back to you. This is still too complicated. The original issue just asked to change the text of prompts with a minor flow change. 

These PR changes are mostly unnecessary.

**Comment by Anubhav-2003** [comment]
> Let me get back to you. This is still too complicated. The original issue just asked to change the text of prompts with a minor flow change.
> 
> These PR changes are mostly unnecessary.
Ok sir no problem.

**Comment by palisadoes** [comment]
I think we can just change the prompt of the existing setup from

```
Do you want to import default data?
```
to :

```
Do you want to import the initial production data for a new setup?
```

All references to `default data` in prompts and messaging should be `initial production data for a new setup`

That clarifies the purpose of default data file in the `sample_data` directory. The term default was too vague, which was the reason for the issue being created.

No additional prompts are necessary.

I'm sorry about not being clearer.

**Comment by palisadoes** [comment]
Please make those much simpler updates

**Comment by Anubhav-2003** [comment]
> Please make those much simpler updates

Ok sir, let me undo and update the changes as per your instructions. I will update you as soon as they are done. Thank You.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I have undone all the changes as per your advice, and made only minor changes to the prompts of the default data, and the function name and comments associated with it. Thank you.

**Comment by palisadoes** [comment]
Please fix the conflicting file and I'll review once more.

**Comment by palisadoes** [comment]
Closing as abandoned

**Pull request closed without merging**
