### PR TITLE
Add tests for middleware/isAuth.ts

### LINKED ISSUE #801: Resolvers: Tests for is-auth.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/helper_functions/is-auth.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/helper_functions/is-auth.sepc.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/organization_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by beingnoble03**
**What kind of change does this PR introduce?**
Adds tests for `middleware/isAuth.ts`

**Issue Number:**

Fixes #801 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by beingnoble03** [comment]
@palisadoes ptal. Thanks!

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by beingnoble03** [comment]
Sure @palisadoes, I'm having a look.

**Comment by beingnoble03** [comment]
@palisadoes I had to mock Request so I had to use hard-coded value for `headers.authorization`. Is there any alternative to this approach? Or Should we ignore the CodeQL results as hard-coded value is used here only for tests.

**Comment by palisadoes** [comment]
Can you autogenerate a token value instead and test accordingly?

**Comment by beingnoble03** [comment]
@palisadoes done.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
