### PR TITLE
Mutations: Refactored file 61 to 70, removing conditional check for PRODUCTION

### LINKED ISSUE #1003: Refactor: tests/resolvers/Mutation [File 61 to File 70] [Remove the conditional check process.env !== "PRODUCTION" for requestContext.translate()]
This is a child issue to the issue listed here: #993
- Code need to be refactored for folder ```tests/resolvers/Mutation```
- There are certain test files in this folder, which do not cover 100% of their respective code. You may ignore them, for this issue.
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issues on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/993)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by prathamesh-mutkure**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:** 

Fixes #1003 

**Did you add tests for your changes?**

Not Applicable 

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

Not Relevant 

**Summary**

- This PR refactors file 61 to 70
- Removing the conditional check `process.env !== "PRODUCTION"` for `requestContext.translate()`
- Also added new constants where needed

**Does this PR introduce a breaking change?**

No

**Other information**

All tests cases are passing as shown below -

Screenshot 2023-02-10 at 7 55 56 PM

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by prathamesh-mutkure** [comment]
I guess `.gitignore` is a protected file that is causing the pipeline to fail, should I revert that changes?

**Review by xoldyckk — CHANGES_REQUESTED** [review]
@prathamesh-mutkure remove all instances of `IN_PRODUCTION` from test files whether it is in the test message or while importing/mocking constants. Btw you don't even need to mock constants now because `IN_PRODUCTION` variable no longer needs to be mocked.

**Comment by prathamesh-mutkure** [comment]
@xoldyckk I've removes the references to `IN_PRODUCTION`

@palisadoes, I had added `.DS_STORE` to `.gitignore` which seems to be an protected file, should I revert the `.gitignore` file?

**Review by xoldyckk — DISMISSED** [review]

**Comment by prathamesh-mutkure** [comment]
Hey @xoldyckk, can you please review this PR?

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Review by xoldyckk — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
