### PR TITLE
Test code for updateProfileMutation

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Bugfix for issue #170 

**Did you add tests for your changes?**
Yes this is the test code for PR #176 

**If relevant, did you update the documentation?**
No documentation update needed.

**Summary**
Test code will make sure that future changes are not destroying the past developments. 

**Does this PR introduce a breaking change?**
No

**Other information**
Test code will work only after PR #176 will be live in the link

### CODE REVIEW

**Comment by sumitra19jha** [comment]
@Laurell876 Can you please merge the current changes of develop branch(PR #176) to master for making it live on the link. This will help me to fix issue [174](https://github.com/PalisadoesFoundation/talawa/issues/174) of frontend. And also the CLI check of this PR will pass after that merge. As you can see in the image, the status code 400 error is occurring due to the fact that the updateProfileMutation is not live.
Screenshot 2021-03-27 at 11 16 20 AM

**Review by Sagar2366 — APPROVED** [review]

**Comment by Sagar2366** [comment]
@sumitra19jha travis CI is failing on your PR, fix it.

**Comment by palisadoes** [comment]
Please fix the Travis pull request errors

**Comment by palisadoes** [comment]
@DMills27 @Laurell876 please review

**Comment by palisadoes** [comment]
@sumitra19jha  please resolve the PR build fail issue

**Comment by sumitra19jha** [comment]
Yeah sure.
Sorry for the delay

**Pull request merged**
