### PR TITLE
SSL + Encryption helpers

### LINKED ISSUE #1406: HTTPS SSL config + PII encryption
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
1. The current production server lacks SSL and HTTPS config
2. The PII for User is not encrypted 
**Describe the solution you'd like**
1. The current production server should configure HTTPS, a private key, and a certificate.
2. The PII for User should be encrypted using AES algorithm and decrypted only when the user is authorised. 
**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

feature
1. Configures SSL and HTTPS in production
2. Wrote helper text encryption functions
**Issue Number:**

Fixes #1406 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please ask your mentor to review

**Comment by kb-0311** [comment]
@kevoiat @rumone pls do review when you are free. Thanks

**Review by Rumone — APPROVED** [review]

**Review by Kevoniat — APPROVED** [review]

**Comment by kb-0311** [comment]
@palisadoes I think the broken codecov is related to the PR that was merged without having complete tests. The codecov is comparing PRs to 20 commits beind current HEAD at develop branch. 

This PR is safe and can be merged.

**Comment by palisadoes** [comment]
@kb-0311 How can we correct the codecov discrepancy? This has happened before and I don't remember how it was resolved.

**Pull request merged**
