### PR TITLE
Refactor tests/resolvers/DirectChatMessage and tests/resolvers/GroupChat

### LINKED ISSUE #967: Refactor: tests/resolvers/DirectChatMessage
This is a child issue to the issue listed here: #965 

- Code need to be refactored for folder ```tests/resolvers/DirectChatMessage```
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issue on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### LINKED ISSUE #968: Refactor: tests/resolvers/GroupChat
This is a child issue to the issue listed here: #965 

- Code need to be refactored for folder ```tests/resolvers/GroupChat```
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issue on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visiting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This refactors the test code for ```tests/resolvers/DirectChatMessage and tests/resolvers/GroupChat```

**Issue Number:**
Closes #967 
Closes #968 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image
image

**If relevant, did you update the documentation?**

**Summary**
This refactors the test code for ```tests/resolvers/DirectChatMessage and tests/resolvers/GroupChat```

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
> # [Codecov](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/976?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> > Merging [#976](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/976?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([214f58a](https://github.com/PalisadoesFoundation/talawa-api/commit/214f58a25678bcf7511cb7d1cdaf5277b0f7e8f7)) into [develop](https://codecov.io/gh/PalisadoesFoundation/talawa-api/commit/d34f7feb8d70fb1eb569ebff00774f9d12c03427?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([d34f7fe](https://github.com/PalisadoesFoundation/talawa-api/commit/d34f7feb8d70fb1eb569ebff00774f9d12c03427)) will **decrease** coverage by `0.07%`.
> > The diff coverage is `n/a`.
> 
> 📣 This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop     #976      +/-   ##
> ===========================================
> - Coverage    93.23%   93.16%   -0.07%     
> ===========================================
>   Files          168      168              
>   Lines        10101    10100       -1     
>   Branches       998      997       -1     
> ===========================================
> - Hits          9418     9410       -8     
> - Misses         683      690       +7     
> ```
> 
> [Impacted Files](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/976?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)	Coverage Δ	
> [src/resolvers/Mutation/otp.ts](https://codecov.io/gh/PalisadoesFoundation/talawa-api/pull/976?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3Jlc29sdmVycy9NdXRhdGlvbi9vdHAudHM=)	`22.22% <ø> (-16.91%)`	⬇️
> 📣 We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)

Accidently deleted the otp.ts file. Re commiting

**Comment by noman2002** [comment]
@anshgoyalevil Why the coverage of otp.ts has dropped ?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil Why the coverage of otp.ts has dropped ?

I mistakenly deleted the otp.spec.ts file, as i was working on it. I added it again, and the coverage will be back to normal in the updated CodeCov comment

**Comment by anshgoyalevil** [comment]
> Have you pulled the recent code in this PR?

Yes, my local repo and remote repo are all synced.

**Comment by noman2002** [comment]
> > Have you pulled the recent code in this PR?
> 
> Yes, my local repo and remote repo are all synced, and I have added the otp.spec.ts file again.

Okay great, lets wait for the codecov.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@noman2002 Review and merge if OK

**Comment by anshgoyalevil** [comment]
Please have a look at this PR.

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
