### PR TITLE
Fix eslint to check for improper import statements [Fixes #1083]

### LINKED ISSUE #1083: Check for Improper Import Statements [ESLINT]
**Describe the bug**
Currently, we can use the import statements like
```
import { INVALID_FILE_TYPE } from "../../src/constants";
```
But, we shouldn't be able to use the import statements which refer to the ```src``` folder directly. It can be replaced with 
```
import { INVALID_FILE_TYPE } from "../constants";
```
These both statements are same. The problem with the above statement is that, when we produce a build deployment for the project using the ```npm run build``` command, the code searches for ```src``` folder, which is not present over there, since it is in production environment.

**To Reproduce**

1. Run ```npm run build```
2. Delete the ```src``` folder temporarily, to duplicate the production environment locally.
3. Try running the server.js inside the build folder using ```node build/server.js```
4. It will throw an error since there is no src folder.

**Expected behavior**
It must not throw this error since the build folder must not reference the src folder.

**Actual behavior**
It is throwing ```MODULE NOT FOUND``` error.

**Screenshots**
image

**Additional details**
Due to this issue, the current deployment for Talawa-API over Azure is not working. Similarly, the production builds for this project will not work if this issue persists.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This adds the necessary checks to the .eslintrc.json file to check if any code file is using the src import from their parent folder.

**Issue Number:**

Fixes #1083 

**Did you add tests for your changes?**
Not Required

**Snapshots/Videos:**
Not Relevant

**If relevant, did you update the documentation?**
Not Required.

**Summary**
This PR adds the necessary changes to the eslint configuration file which will help in detecting the improper import statements inside the code files. 2 such files are fixed in this PR.

**Does this PR introduce a breaking change?**
No.

**Other information**
No.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
@xoldyckk Please check

**Comment by xoldyckk** [comment]
@anshgoyalevil looks good. Fix the formatting.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by anshgoyalevil** [comment]
@xoldyckk @noman2002 Fixed the failing tests.

**Review by xoldyckk — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Pull request merged**
