### PR TITLE
Added the stripe.js payment gateway for the backend

### LINKED ISSUE #211: Add a payment gateway integration
**Describe the solution you'd like**
Implement a payment gateway system that will allow the organization to receive donations from users of the app

### PR DESCRIPTION
**Pull request by yasharth291**
**What kind of change does this PR introduce?**
It is an Enhancement

**Summary**

Adding payment gateway to take the donation from the user motivated me to raise this PR.

**Other information**
Fixes #211  

Use this link to get to know about the stripe.js https://stripe.com/docs/js/

### CODE REVIEW

**Comment by yasharth291** [comment]
@Laurell876  @palisadoes  Can you review and tell me if there is some change needed

**Comment by yasharth291** [comment]
Changes I have done 
1. Added the Stripe.js Payment gateway.
2. Inserted the Webhook for the notification and checking the endpoint

**Comment by Laurell876** [comment]
This PR needs to be rebased. Also the code seems to be unformatted

**Comment by yasharth291** [comment]
ok sir doing both things rebasing  as  well as the formatting @Laurell876

**Comment by yasharth291** [comment]
sir i think i have rebased the master branch with develop branch @Laurell876

**Pull request closed without merging**
