### PR TITLE
Simulated Testing Database For Talawa Admin

### PR DESCRIPTION
**Pull request by JamarTG**
What kind of change does this PR introduce?

1. Generates a single fake organization with a set number of posts, events, and organizations using _@fakerjs/faker_. This includes the generation of realistic names, email addresses, company names, locations, etc.
2. Gives you the ability to load and unload the data

Note. The related frontend changes provides an interface for the functionalities implemented here

**Issue Number:**
https://github.com/PalisadoesFoundation/talawa-api/issues/1368

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
The video below shows the effect on the frontend 

https://github.com/PalisadoesFoundation/talawa-api/assets/71823011/8ce7261d-c1ec-4e4f-9715-6f9977c73f9f

**Summary**
Acts as a mock database used for demonstrating the application's features and for efficient testing of the software.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by JamarTG** [comment]
> Please fix the failing test

it's fixed now

**Comment by palisadoes** [comment]
Please fix the failing tests. The code test coverage is too low

**Comment by JamarTG** [comment]
> Please fix the failing tests. The code test coverage is too low

I increased the test coverage

**Comment by palisadoes** [comment]
@JamaicanFriedChicken @jordan-barrett-jm Pleases review

**Comment by palisadoes** [comment]
Please fix the conflicting files. We need to get this merged shortly.

**Comment by JamarTG** [comment]
> I've fixed the conflicts

**Comment by palisadoes** [comment]
@JamaicanFriedChicken @jordan-barrett-jm Pleases review
@JamarTG The tests are failing for some reason. Please check.

**Comment by palisadoes** [comment]
@jordan-barrett-jm @JamaicanFriedChicken Please review. I'd like to get this merged into the code base soon

**Comment by rishav-jha-mech** [comment]
@JamarTG 
1. Remove the border above the Create Organization Button
2. Remove the cancel button
3. Remove `backdrop="static"` from Create Organization Modal
4. Make sure the layout looks like the image I provided, `Create Organization button` with full length then `Create Sample Organization`

image

**Comment by JamarTG** [comment]
> @JamarTG
> 
> 1. Remove the border above the Create Organization Button
> 2. Remove the cancel button
> 3. Remove `backdrop="static"` from Create Organization Modal
> 4. Make sure the layout looks like the image I provided, `Create Organization button` with full width then `Create Sample Organization` Button with full width.
> 
> image

Sure. Man you're so talented

**Comment by palisadoes** [comment]
@JamarTG Is this ready for review?

**Pull request merged**
