### PR TITLE
Revised PR: Restrict user data access in User query (replaces #2623)

### LINKED ISSUE #2214: Unrestricted Exposure of User Data Through the User Query
**Describe the bug**
The affected query is `User($id: ID!)`  which fetches detailed information about a user based on the user ID provided. The current implementation **does not restrict users** from querying information about others, which violates common privacy principles and data access controls.

```
query User($id: ID!) {
    user(id: $id) {
        user {
            _id
            joinedOrganizations {
                _id
            }
            phone {
                mobile
            }
            address {
                line1
                countryCode
                city
                state
            }
        }
        appUserProfile {
            _id
            adminFor {
                _id
            }
        }
    }
}
```

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by nitintwt**
**What kind of change does this PR introduce?**

Implement user access control for querying user data.

**Issue Number:**

Fixes #2214

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Summary**

This PR addresses a branch conflict encountered in PR #2623, which failed due to the requirement that source and target branches must be different. This new PR was created from a separate branch off develop to complete the necessary checks.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced user data access control with stricter checks for authorization based on user roles and organization membership.
	- Improved error handling for unauthorized access and non-existent user queries.

- **Tests**
	- Introduced a comprehensive suite of unit tests for the user query resolver, covering various access scenarios and ensuring proper error handling and data retrieval.

### CODE REVIEW

**Comment by pranshugupta54** [comment]
Please fix failing tests and CodeRabbit comments

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by duplixx** [comment]
@nitintwt please fix the failing tests

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Cioppolo14** [comment]
@nitintwt Please fix the failed tests.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Closing. Abandoned

**Pull request closed without merging**
