### PR TITLE
feat: Add Filter and Sort for Action Items

### LINKED ISSUE #1854: Add Filter and Sort for Action Items
**What is this feature request about?**
It's about adding the functionality to filter the action items (i.e. action items belonging to a particular action item category, that are active or completed). And also, the functionality to sort the action items (latest or earliest).

**Additional context**
This is a companion issue for PalisadoesFoundation/talawa-admin#1462

**Demo**
It would look something like this:

https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/3fa86b1d-6d05-4da8-8845-c88f1e0c4e5d

### PR DESCRIPTION
**Pull request by meetulr**
**What kind of change does this PR introduce?**

It adds functionality to filter and sort action items.

**Issue Number:**

Fixes #1854 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Demo**

https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/fbed08d3-f36b-4883-ab3a-0c349af5cedb

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@rishav-jha-mech @aashimawadhwa Can you review this PR?

**Comment by palisadoes** [comment]
Please fix the formatting issues. They were probably listed as you edited them to fix merge conflicts. We won't know for sure whether the tests for this PR pass otherwise.

**Comment by meetulr** [comment]
@palisadoes they were most likely introduced with this PR: #1852 earlier today, since it was merged with failing linting test, and it modified exactly the files that are having the formatting issues here.
These two files are the reason this test is failing in my other PR too #1853.

**Comment by palisadoes** [comment]
1. Thanks I'll revert the other one. 
2. I didn't realize the tests were failing.

**Comment by palisadoes** [comment]
It's reverted. Please do a minor commit

**Comment by meetulr** [comment]
The tests are passing. This is ready for review.

Please add the label.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
