### PR TITLE
@typescript-eslint/eslint-plugin to 8.0.1

### PR DESCRIPTION
**Pull request by prayanshchh**
**What kind of change does this PR introduce?**

<dependency change typescript-eslint/eslint-plugin to 8.0.1->

**Issue Number:**

Fixes #<2462>

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Added a "Videos" section to the "Contributing" guide, enhancing navigational ease for contributors.
	- Introduced a new optional field `X` for handling social media URLs, allowing for more flexible data representation.
  
- **Bug Fixes**
	- Minor formatting adjustments for improved readability in the "README.md" file.

- **Chores**
	- Updated dependencies for TypeScript ESLint tools to the latest versions for improved linting capabilities.

### CODE REVIEW

**Comment by varshith257** [comment]
@prayanshchh Fix lint and fmt errors caught by ci.

**Comment by prayanshchh** [comment]
on it

**Comment by prayanshchh** [comment]
Run echo "Source Branch develop"
Source Branch develop
Target Branch develop
Error: Source and Target Branches are the same. Please ensure they are different.
Error: Process completed with exit code 1.

This is the lint error
previously i was seeing a different error, somehow now i only see this, i pushed in develop branch as per doc, shall i create my own branch and do it?

**Comment by varshith257** [comment]
@prayanshchh  Can you do this with new PR?

**Comment by prayanshchh** [comment]
alright i will create a new PR then.
thank you!

**Pull request closed without merging**
