### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by impiyush83**
**What kind of change does this PR introduce?**
1. Request tracing 
2. Logging with log levels

**Did you add tests for your changes?**
Not required as does not affect business logic

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by palisadoes** [comment]
@sumitra19jha You may want to take a look at this one too.

**Comment by sumitra19jha** [comment]
@impiyush83 
```
TypeError: logger.info is not a function
    at Server.<anonymous> (/Users/sumitra/GSOC/talawa-api-1/index.js:118:14)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at Server.<anonymous> (/Users/sumitra/GSOC/talawa-api-1/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
    at emitListeningNT (net.js:1347:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by impiyush83** [comment]
@sumitra19jha  can you try now. I have fixed the issue.

**Review by Laurell876 — APPROVED** [review]

**Comment by palisadoes** [comment]
@sumitra19jha Does this work for you now?

**Comment by sumitra19jha** [comment]
@impiyush83 Are these logs necessary for every query that is being executed?
Screenshot 2021-05-30 at 5 08 15 PM

**Comment by impiyush83** [comment]
@sumitra19jha  Replaced uuidv4 with request tracing.  

Example:

logger.info('Hello1')
logger.info('Hello2')
Same unique key for both logs, hence request tracing achieved.


Screenshot 2021-05-30 at 5 38 46 PM

**Review by palisadoes — CHANGES_REQUESTED** [review]
@impiyush83 @sumitra19jha 

1. How do we know where in the code the log message is coming from? For example, if there is a "user not found" message how would we be able to see in the logs as to whether it came from the login screen, or chat screen, or search results etc.? 
2. How would we know which line of code generated the log? Doing a recursive search for "user not found" would reveal multiple instances making it hard for troubleshooting.

**Comment by sumitra19jha** [comment]
@palisadoes Actually the executed API shows that information `extensions --> exception --> stacktrace`

Screenshot 2021-05-30 at 11 05 35 PM



@impiyush83 The `errors` do not contain extensions to show file location and code line which was the case previously. Please fix this.

Screenshot 2021-05-30 at 11 08 37 PM

**Comment by impiyush83** [comment]
@sumitra19jha  Ideally stack trace must not be a part of the response in production. 
https://www.apollographql.com/docs/apollo-server/data/errors/#omitting-or-including-stacktrace

@palisadoes  @sumitra19jha  

Logging error something like this would resolve both of your questions @palisadoes.
We can log the error response that @sumitra19jha  pointed out in the first image and send out the response which is shown in the second image.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@Laurell876. @DMills27 @xsh2047  Please review. We now need two reviewers before merging can occur.

**Review by ranilwallace — APPROVED** [review]
LGTM 👍

**Pull request merged**
