### PR TITLE
Apollo v4 

### LINKED ISSUE #1350: Upgrade Apollo Server to v4 .
**Describe the bug**

The current version of Apollo v2 has been deprecated with these features having reached their end-of-life cycle.

1. File Uploads
2. Subscriptions

To make sure the API is well maintained it is essential to keep the packages up to date. 

SOlution migrate the package to apollo v4.

**To Reproduce**

1. Try to utilize `graphq-upload` package
4.  Will throw errors

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**
This PR upgrades the current version of Apollo Server to v4(latest) from v2. 

**Issue Number:**

Fixes #1350 

**Did you add tests for your changes?**
Yes.

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by kb-0311** [comment]
@kevoniat @palisadoes Pls review , The unauthorised change check fail are due to updation of packages.

The codecov results also seem to be  rather buggy since the changes in the tests files weren't made.

**Review by xoldyckk — COMMENTED** [review]
@kb-0311 

Graphql-subscriptions package is outdated and not maintained. Apollo server 4 docs don't make use of it, why have you done so?

Graphql-upload is not officially maintained by apollo, it is a third party package and isn't recommended by apollo. This is one of the reasons I talked about graphql-yoga cuz apollo is too fragmented and makes major changes and deprecations too frequently. Btw here's apollo's recommendations for file uploads:- https://www.apollographql.com/blog/backend/file-uploads/file-upload-best-practices/

If you're upgrading everything I'd suggest to leave behind the legacy bloat and bad practices instead of carrying them over. One example is `i18n` package, other is the error handling. Maybe you meant to do it in a way to get it under working conditions with minimal disruption to existing things, but I'd say take a look at it and try getting rid of such stuff.

**Comment by kb-0311** [comment]
@xoldyckk 

Yes you are right the goal of this PR was to upgrade the server without major breaking changes.

Good Question.I have only used the[ `PubSub` class](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#the-pubsub-class) from `graphql-subscription` which is in the docs although not recommended in production, I don't think I read about it ever being deprecated. In production, we will use [something like this](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#production-pubsub-libraries). The issue was the all the chat and subscription resolvers make use of this PubSub class. Removing it was leading to the breakage of all these resolvers. Ravi Dev Pandey had told me that the current logic of chats is also broken so he will need to refactor the entire chat system. So was planning to let him choose what exactly the best approach would be to eliminate the legacy PubSub class as he is someone who is going to be working on the chats and stuff.

For the Web socket server I have used `graphql-ws` library which the latest apollo v4 docs do make a use of.

>Graphql-upload is not officially maintained by apollo, it is a third party package and isn't recommended by apollo. This is one of the reasons I talked about graphql-yoga cuz apollo is too fragmented and makes major changes and deprecations too frequently. Btw here's apollo's recommendations for file uploads:-

I have read that blog before. From what I understand the other two approaches make use of a 
1) Cloud service signed URLs 
2) A dedicated Image upload service with its own SDKs.

The obvious problem here is the cost. Hence it was decided in the file-uploads slack channel that we will not be using any cloud service from the get go instead files will be stored in the API server. 

Regarding graphql-upload , it is not recommended because like you said, not maintained by apollo and because it is vulnerable to CSRF attacks. There are ways to prevent it though as [specified in the docs.](https://www.apollographql.com/docs/apollo-server/security/cors/#graphql-upload)


>One example is i18n package, other is the error handling

Yes absolutely I was just the other day talking with @EshaanAgg about removing the `requestContext`, `i18n` etc packages but since the `requestContext.translate` is used in almost all resolvers it is best to make changes to the resolvers, their tests and add the Errors in Schema Approach gradually part by part.

For the record, @EshaanAgg and I had tried to migrate directly to GraphQL-yoga but there were a lot of problems with the complexity of the current Apollov2 package and so our main priority in limited constraint in this PR was to at least get the API to a state which will remain stable next year. The yoga migration can be done anytime but most likely will be done by me after GSoC.

**Review by Rumone — APPROVED** [review]

**Review by xoldyckk — DISMISSED** [review]

**Comment by kb-0311** [comment]
@xoldyckk @Rumone Fixed the git conflicts.

@palisadoes I think this PR is done.

**Comment by palisadoes** [comment]
Please fix the merge conflicts.

**Comment by kb-0311** [comment]
@palisadoes done. Pls merge

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
