### PR TITLE
Test for `src/resolvers/Mutations/createEvent.ts`

### LINKED ISSUE #908: Test: src/lib/resolvers/Mutation/createEvent.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Mutation/createEvent.ts 
`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Mutation/createEvent.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #908 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
@palisadoes progress is ongoing for this PR so coverage is not 100% locally yet, however I do wonder why hasn't codecov report shown up on github yet ?

**Comment by palisadoes** [comment]
Unfortunately, code coverage report generation isn't reliable. It's always best to attach your local report

**Comment by kb-0311** [comment]
@palisadoes the test is failing now because codecov failed to properly upload.

Oh sorry my mistake , now this file is already at 100% locally now, which is kinda weird since I swear it was around 94 last time I ran test on this branch...
Screenshot from 2023-02-07 22-41-50

**Comment by palisadoes** [comment]
@SiddheshKukade @xoldyckk please review

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
