### PR TITLE
override semver (to 7.5.4) in package.json

### LINKED ISSUE #1360: semver vulnerable to Regular Expression Denial of Service
- You will need to upgrade to v7.5.2

image

- The upgrade will affect some other dependencies. Here is a list of the ones that you will also need to update.

image

### PR DESCRIPTION
**Pull request by ishtails**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**
fixes #1360

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Overrided semver in package.json to latest 7.5.4 version to fix semver vulnerable to Regular Expression Denial of Service as stated in #1360

**Does this PR introduce a breaking change?**
Not sure

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please refer to the CONTRIBUTING.md file on how to auto-close issues when the PR is merged. This is important.

**Comment by ishtails** [comment]
I have edited my message to include " fixes #1360 " & also fixed the workflow error

**Comment by palisadoes** [comment]
1. Are you sure you rebuilt the packages after doing this upgrade?
2. Dependabot says there are package dependencies that need to be upgraded too. Please review.
3. We would have done the upgrade automatically if we could. This is why we created the manual issue.

image

**Comment by ishtails** [comment]
I am a little unsure if manually updating the version of semver in all the dependent packages is how it should be done... let me know if there is a more standard way of doing this.

**Comment by palisadoes** [comment]
This is not correct. Please upgrade the dependencies rather than manually editing the dependency's dependencies. If there is no solution using this method, then let us know.

**Comment by palisadoes** [comment]
This is not correct. Please upgrade the dependencies rather than manually editing the dependency's dependencies. If there is no solution using this method, then let us know.

**Comment by ishtails** [comment]
I'm not sure how else to go about it...

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
