### PR TITLE
Added node_modules caching for CI workflows.

### LINKED ISSUE #1471: Feature Request: Cache npm dependencies in workflows
**Is your feature request related to a problem? Please describe.**
We can cache the `node_modules` folder in workflows with artifacts to ensure faster workflow runs. 

**Describe the solution you'd like**
[Refer to this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Veer0x1**
**What kind of change does this PR introduce?**
Added caching of node_modules for GitHub workflows. Caching was only needed in these 2 files coz other workflows are using `actions/setup-node@v3` action, which comes with caching.

**Issue Number:**

Fixes #1471

**Did you add tests for your changes?**
This changes doesn't require tests.

**Does this PR introduce a breaking change?**
NO

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
YES

### CODE REVIEW

**Review by EshaanAgg — APPROVED** [review]
LGTM. Thanks

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Merge with the latest upstream. The workflow tests are failing

**Comment by Veer0x1** [comment]
merged with latest upstream!!

**Comment by palisadoes** [comment]
@Cioppolo14 

I think the code coverage test is failing because no typescript files were edited. The reports in the link are blank.

**Comment by Veer0x1** [comment]
@palisadoes is there anything to change in this PR?? Whats stoping it from merging?

**Comment by palisadoes** [comment]
@xoldyckk Please review.

**Comment by xoldyckk** [comment]
@palisadoes i don't know much about github actions, since eshaan proposed the PR and he has approved it, it can be merged i guess

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
