### PR TITLE
Non deterministic test failure

### LINKED ISSUE #1010: Fix tests for `isAuth.spec.ts` and ` src/server.ts`
**Describe the bug**
We have been getting periodic errors where our GitHub action testing fails. Re-running the tests often causes the error to go away.

1. [This is an example of one such failed test run.](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4097595336/jobs/7066087060)
2. Click through and you will see the screen shot below.

_Other_
1. This has been fixed with https://github.com/PalisadoesFoundation/talawa-api/pull/1007 however we need to ensure that this test correctly verifies the existence of the required resources to reduce any future failure scenarios.
1. That PR made modifications to [src/server.ts](https://github.com/PalisadoesFoundation/talawa-api/pull/1007/files#diff-8a8ae07582c9d433ec8c2e5c4310ff8901e604f4965c5b90a49117ad46c47595) This may mean that the tests for that file need to be fixed too.

**To Reproduce**
1. Submit a PR
1. `tests/middleware/isAuth.spec.ts` will occasionally fail.

**Expected behavior**
Tests pass reliably and consitently

**Actual behavior**
See above

**Screenshots**
image

**Additional details**
N/A

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

bugFix
**Issue Number:**

Fixes #1010 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
Probably not

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
This PR does require some extra review and second opinion on this approach, 

Credits for this solution -> https://github.com/vitest-dev/vitest/issues/1692#issuecomment-1366855827

**Review by palisadoes — CHANGES_REQUESTED** [review]
@kb-0311 Please also fix the test that failed to cause this GitHub Action failure.

**Comment by kb-0311** [comment]
@palisadoes there is not a specific test that fails to throw this unhandled error. If any one test is failed then the `uploadImage.ts`  file gets untracked and throws that error. i ha ve mentioned other details here.

https://github.com/PalisadoesFoundation/talawa-api/issues/1010#issuecomment-1424756306

**Comment by palisadoes** [comment]
Please explain some more.

The same suite of tests always pass in the pull request workflow and then intermittently fails when it is rerun in the push to the repo after the merge. 

Why?

This seems to be proving that there is a test that occasionally fails and your test is highlighting the flaw.

Which other test should we be targeting?

Please take a look at all the failed push actions to see whether you can find a culprit.

If you have good reason to think this analysis is incorrect, please state it. This is not an area of strength for me.

**Comment by kb-0311** [comment]
@palisadoes yeah I got what you were saying now, Thankfully @xoldyckk cleared it up.

Fixed that test suite.

**Review by xoldyckk — COMMENTED** [review]
@kb-0311 did you try the changes on your local system? Like intentionally erroring out one of the other tests to see if [this](https://github.com/PalisadoesFoundation/talawa-api/pull/1042#issuecomment-1425186300) issue still persists?

**Comment by kb-0311** [comment]
> @kb-0311 did you try the changes on your local system? Like intentionally erroring out one of the other tests to see if [this](https://github.com/PalisadoesFoundation/talawa-api/pull/1042#issuecomment-1425186300) issue still persists?

Yes , I did , forgot to attach the screenshots - > 
Here I failed one of the tests purposely but did not get an unhandled exception ->
Screenshot from 2023-02-10 17-55-21


At least these changes do work on my local machine, hopefully it works on github CI/CD as well.

**Review by xoldyckk — APPROVED** [review]

**Comment by xoldyckk** [comment]
@kb-0311 Do you think the order matters here? Does this occur if uploadImage test runs before other tests and then one of the tests fails or vice versa?

Idk if vitest runs tests one by one by going through directories and files sequentially or just one at a time randomly from anywhere. If it's random then it'd be better to check if the error persists for the following cases:-

```
random failing test -> uploadImage test runs
uploadImage test runs-> random failing test
```

**Comment by kb-0311** [comment]
@xoldyckk 

1. Running ->
````
npx vitest ./tests/utilities/uploadImage.spec.ts ./tests/resolvers/intentionallyFailedTest.spec.ts
````

Screenshot from 2023-02-10 20-12-42
No unhandled error thrown, looks good.
2. Running ->
````
npx vitest ./tests/resolvers/intentionallyFailedTest.spec.ts ./tests/utilities/uploadImage.spec.ts 
````
Screenshot from 2023-02-10 20-14-47
Same thing, no unhandled exception thrown, looks good.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
