### PR TITLE
Configurable Session Timeout for Community

### LINKED ISSUE #2432: Enhancements For Session Management in Both User And Admin Portal
**Is your feature request related to a problem? Please describe.**
The lack of admin-configurable session timeouts, absence of pre-timeout 
warnings, and inadequate logout messaging disrupt user experience and can lead to frustration 
among users. 

**Describe the solution you'd like**
Solution focuses on overcoming these challenges by introducing configurable 
session timeouts, warning notifications before session expiry, and seamless redirection to the 
login screen upon logout

**Describe alternatives you've considered**
n/a

**Approach to be followed (optional)**
The project involves researching session management solutions and planning the implementation strategy, followed by creating detailed design documents and UI mockups, and reviewing these with stakeholders. Configuration settings will be developed in the Talawa-Admin Portal and backend logic will be implemented in Talawa-API. Pre-timeout notifications will be developed in Talawa Admin, and logout messaging will be enhanced. Testing will include writing and executing test cases, conducting peer reviews, and integrating feedback. Documentation will be updated and new guides will be written and approved. User feedback will be gathered, bugs identified, and necessary improvements made to finalize features. Finally, features will be deployed to production, followed by final testing to ensure smooth operation.

### PR DESCRIPTION
**Pull request by JordanCampbell1**
**What kind of change does this PR introduce?**
Feature: Session Timeout

**Issue Number:**

Fixes #2432

**Did you add tests for your changes?**

Yes 

**Summary**

Making the change to include a session timeout, hence creating sessions for the application, ensures that there is a layer of security when users use the application. These changes to the API allow sessions to be managed in Talawa Admin.

https://github.com/PalisadoesFoundation/talawa-api/issues/2432

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
  - Added a new section for "Videos" in the contributing guidelines for easier navigation.
  - Introduced a new mutation to update session timeout settings for superadmin users.
  - Enhanced localization support with new error messages for timeout validation in multiple languages.
  - Added a timeout field to the Community type, allowing for more granular control over timeout settings.

- **Bug Fixes**
  - Improved error handling for user profile retrieval during login.

- **Documentation**
  - Updated formatting for core features in the README for better readability.
  - Clarified the login function documentation to specify SuperAdmin credential requirements.

- **Tests**
  - Added a new test suite for the `updateSessionTimeout` mutation resolver.
  - Enhanced test coverage for login functionality and superadmin email validation.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@JordanCampbell1 Can you fix the code coverage issue?

**Comment by JordanCampbell1** [comment]
> @JordanCampbell1 Can you fix the code coverage issue?

sure, getting on that right now

**Comment by JordanCampbell1** [comment]
@DMills27 @aashimawadhwa just finished up on the fixes, could you review please

**Comment by JordanCampbell1** [comment]
finished up here as well @DMills27 @aashimawadhwa

**Comment by palisadoes** [comment]
Please fix the failing tests and conflicting files.

**Comment by JordanCampbell1** [comment]
> Please fix the failing tests and conflicting files.

working on it

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review, updated the code

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 fixed the latest issue

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review please

**Comment by DMills27** [comment]
The bulk of what you've submitted is fine. I just have a few nitpicks: 

- **Error Handling Redundancy**: While each test case uses a try-catch block to check for errors, there’s some repetition in verifying the translated error message. You could refactor the tests by extracting common error-handling logic into a helper function, reducing repetition.

- **Async Code Simplification**: In some parts, like updating the `appUserProfile` to non-superAdmin, you’re using `findByIdAndUpdate()` without awaiting it. Since the operation is async, you need to ensure the code properly waits for the operation to complete before proceeding with the test, or race conditions could lead to flaky tests.

- **Inconsistent Mocking and Resetting**: The reset of mocks with `vi.restoreAllMocks()` and `vi.resetModules()` happens after every test, which is good. However, in some cases, you mock `requestContext.translate()` in individual test cases. It may be better to move this to a setup phase (like `beforeEach`) to ensure consistent mocking across all tests unless a specific mock is needed for a particular case.

- **Test Case Clarifications**: The current test names, while functional, could be more descriptive for future developers. For example:
`it("throws NotFoundError if community does not exist")` could be renamed to `it("returns error when attempting to update timeout for non-existent community")`. This gives a better description of the context of the test.

- **Performance Concerns**: The `bcrypt.hash()` function is used to hash the password, which is good for security. However, hashing passwords in tests can slow down the test suite. You may want to mock `bcrypt.hash()` in unit tests where security isn’t the focus, to reduce overhead.

**Comment by JordanCampbell1** [comment]
@DMills27 just made the adjustments you suggested, could you review
@aashimawadhwa could your review as well

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review?

**Comment by aashimawadhwa** [comment]
@JordanCampbell1 can you fix these linting errors?

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review?

**Comment by aashimawadhwa** [comment]
@JordanCampbell1 please fix this
Screenshot 2024-09-22 at 10 07 01 PM

**Comment by JordanCampbell1** [comment]
> @JordanCampbell1 please fix this Screenshot 2024-09-22 at 10 07 01 PM

I took out the eslint disable statement and instead put a ignore statement but it still gives that lint error

**Comment by aashimawadhwa** [comment]
> > @JordanCampbell1 please fix this Screenshot 2024-09-22 at 10 07 01 PM
> 
> I took out the eslint disable statement and instead put a ignore statement but it still gives that lint error

@DMills27

**Comment by JordanCampbell1** [comment]
in addition, it looks like i have to do a lot more changes if i dont use the ignore statement since almost every import that the person used is giving linting errors

**Comment by JordanCampbell1** [comment]
image
I would get these errors if i remove the eslint statement that ignores said errors

**Comment by JordanCampbell1** [comment]
and they are needed for the file so I am not sure what to do

**Comment by JordanCampbell1** [comment]
@DMills27 @aashimawadhwa

**Comment by JordanCampbell1** [comment]
image
image
both of these ignore statements are needed to get no errors for the file

**Comment by JordanCampbell1** [comment]
just moved the setup file in the config folder that has a similar file with eslint disable, so things should be fine now @aashimawadhwa @DMills27

**Comment by JordanCampbell1** [comment]
could this be checked?

**Comment by JordanCampbell1** [comment]
alright so someone updated the code along with the setup file, so i moved the setup file back to its original position as well.

But if it still has linting issues then I will put the setup file back into the config folder for the PR to pass linting

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27

**Comment by palisadoes** [comment]
@JordanCampbell1 

1. We have a check to make sure that persons who have never made a PR before require us to approve the running of tests.
2. There have been 27 commits so far which I've had to approve.
3. Please create another PR against the original issue with a minor update such as an edit to the README.md file. I can merge this then all subsequent commits with this PR will run automatically.
4. Please do the same for the Admin repo

**Comment by JordanCampbell1** [comment]
> @JordanCampbell1
> 
> 1. We have a check to make sure that persons who have never made a PR before require us to approve the running of tests.
> 2. There have been 27 commits so far which I've had to approve.
> 3. Please create another PR against the original issue with a minor update such as an edit to the README.md file. I can merge this then all subsequent commits with this PR will run automatically.
> 4. Please do the same for the Admin repo

alright will do so

**Comment by JordanCampbell1** [comment]
@palisadoes do I use a different branch for the new pull requests?

**Comment by palisadoes** [comment]
Merge to `develop`

**Comment by JordanCampbell1** [comment]
oh alright

**Comment by JordanCampbell1** [comment]
@palisadoes just made the PR that is from my develop branch

**Comment by JordanCampbell1** [comment]
fixed all issues, also updated the schema so the parameter is_active now there, this means that the admin will still show the error until this is merged

@palisadoes @DMills27 @aashimawadhwa

**Review by DMills27 — APPROVED** [review]

**Comment by DMills27** [comment]
Looks good. But come up with more descriptive commit messages in the future.

**Comment by JordanCampbell1** [comment]
> Looks good. But come up with more descriptive commit messages in the future.

Nice, will definitely do so in the future

**Pull request merged**
