### PR TITLE
Fixed Docker auto-reloading

### LINKED ISSUE #1728: Docker not auto-reloading on code changes
#### Is your feature request related to a problem? Please describe.
I am encountering an issue with the automatic reloading of my Node.js application when changes are made to the code within the Docker container. Currently, I have to manually restart the server every time I make modifications to my code.

#### Describe the solution you'd like
I would like the Docker container to automatically reload my Node.js application whenever changes are made to the source code. This would significantly improve the development workflow by eliminating the need for manual server restarts.

#### Approach to be followed
I've ensured proper setup of the project using Docker, and adjusted volumes in the Docker Compose file for seamless automatic code reloading.

### PR DESCRIPTION
**Pull request by harmanbatheja15**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1728 

**Summary**

I am encountering an issue with the automatic reloading of my Node.js application when changes are made to the code within the Docker container. Currently, I have to manually restart the server every time I make modifications to my code.

I would like the Docker container to automatically reload my Node.js application whenever changes are made to the source code. This would significantly improve the development workflow by eliminating the need for manual server restarts.
#1728

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
1. @vasujain275 
1. @kb-0311

Please take a look

**Comment by kb-0311** [comment]
@palisadoes 

I think @vasujain275 perfectly summarised what I wanted to say and I completely agree with him here.

I don't think hot reload should be a thing for docker containers.

**Comment by palisadoes** [comment]
Thanks. Closing

**Comment by EshaanAgg** [comment]
What if we add this as documentation as an alternative? I think so it would be beneficial to users who don't want to setup Redis, all the environment variables and rest of config just for the sake of trying it out, especially for Windows users. 

We can create a 'DEV_DOCKERFILE' and add the same in documentation under the category you can, but you probably shouldn't in the long run.

**Pull request closed without merging**
