### PR TITLE
Implemented Reply functionality for DirectChat and GroupChat

### LINKED ISSUE #2416: Add support to reply to messages in direct chat and group chat
**Is your feature request related to a problem? Please describe.**
Add support to reply to messages in direct chat and group chat

**Describe the solution you'd like**
Users should be able to reply to messages in direct chat and group chat.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Related to https://github.com/PalisadoesFoundation/talawa-admin/issues/2103

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2416 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Introduced the ability to reply to messages in both direct and group chats, enhancing threaded conversation capabilities.
	- Added contextually relevant message retrieval based on replies, improving user interaction.

- **Bug Fixes**
	- Enhanced error handling for cases where messages are not found, providing clearer user feedback.

- **Chores**
	- Removed the `removeGroupChat` mutation, indicating a potential change in group chat management processes.

### CODE REVIEW

**Comment by palisadoes** [comment]
@DMills27 @Kevoniat PTAL

**Review by DMills27 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@disha1202 Please fix the failing tests

**Comment by palisadoes** [comment]
@disha1202 Please get the code coverage for the patch higher

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Cioppolo14** [comment]
@disha1202  Are you working on this?

**Comment by disha1202** [comment]
Hi @DMills27 
Can you please review this PR.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@disha1202 I'm merging this on good faith as I know it's delaying other GSoC work.

**Comment by palisadoes** [comment]
I had to revert as it was affecting your other PR with numerous merge conflicts. Please resubmit.

**Review by DMills27 — COMMENTED** [review]
Looks good to me

**Pull request merged**
