### PR TITLE
migration to fastify and graphql-yoga

### LINKED ISSUE #2283: Migration to fastify and graphql-yoga
**Is your feature request related to a problem? Please describe.**
Talawa-api is making use of many legacy packages that are either not maintained anymore or do not have the best modern features for providing best developer experience.

**Describe the solution you'd like**
The primary server for talawa-api is to be migrated to fastify and the graphql apollo server is to be migrated to graphql-yoga. Fastify is a well maintained and trusted node.js framework with a big community. It's core maintainer Matteo Collina is one of the core contributers to node.js itself. Graphql-yoga is a modern spec-compliant graphql server that works on almost all javascript server runtimes.

**Describe alternatives you've considered**
- 

**Approach to be followed (optional)**
It will be done in parts in a non breaking way so that it is easier to review the changes and also can be incrementally migrated instead of a sudden disruption.

**Additional context**
This is a pre-requisite to a lot of work that is to be done during GSOC 2024. 

**Potential internship candidates**
-

### PR DESCRIPTION
**Pull request by xoldd**
**What kind of change does this PR introduce?**

feature, refactoring

**Issue Number:**

Fixes #2283

**Did you add tests for your changes?**

No, not needed

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

Not yet, will be done after this PR is merged.

**Summary**

The primary web server will be migrated to fastify from express. The graphql server will be migrated to graphql-yoga from apollo-server.

The graphql server will be decoupled from the fastify server to have seperation of concerns make it easier to swap out either the HTTP server(fastify) or the graphql server(graphql-yoga). All the dependencies required by the graphql resolvers at runtime will be provided to them using the graphql context and direct imports inside the resolver functions will be kept to a minimum. 

It is of utmost importance that the HTTP layer does not bleed into the graphql layer to prevent tight coupling.

**Does this PR introduce a breaking change?**

Yes, this PR would introduce a breaking change.

**Other information**

The PR is incomplete, more commits will be made later on to accommodate all the required changes.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by ttaylor92** [comment]
These checks would need to be met before i can approve.

**Comment by palisadoes** [comment]
Please fix the conflicting files so we can merge

**Comment by xoldd** [comment]
@palisadoes actually this PR is incomplete, upon introspection I've found that the current code organization is really messy in the codebase, so I'm still trying to fix that. If it's a problem you can close this PR, I'll open a new one later on.

**Comment by palisadoes** [comment]
Thanks. Closing

**Pull request closed without merging**
