### PR TITLE
standarized file uploads

### PR DESCRIPTION
**Pull request by manishjha-04**
### Description

This pull request addresses the issue < #1715 >, which involves 
1. Limiting the image size and resizing to a configured maximum in the .env file 
2. Updating the setup.ts script to manage this new parameter and
3. Limiting the image types that can be uploaded to the most popular predefined types

### Changes Made

1. Added new environment variables for image validation in `.env.sample`.
2. Created the imageValidation function in `setup.ts` to prompt the user for image upload settings and update the `.env` file accordingly.
3. Integrated image check whereever the upload was needed basically it looks for file type and image size and also resizes the image to the given size in .env file

### Video

Below is changes made in setup.ts file as asked for in the previous PR

https://github.com/PalisadoesFoundation/talawa-api/assets/128405481/5ad9d275-59bb-4b4c-910b-ca2f8acca0d2

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@manishjha-04 Please set the image size in MB and update the installation.md file for the new parameters.

**Comment by manishjha-04** [comment]
@Cioppolo14  done!..please review!

**Comment by manishjha-04** [comment]
hey @Cioppolo14 fixed the linting issue

**Comment by palisadoes** [comment]
Closing due to inactivity

**Comment by manishjha-04** [comment]
Hi @palisadoes sir,

I hope you're doing well. The PR was closed without review. Could you kindly share why it was closed prematurely? I'm eager to learn and improve.

**Comment by palisadoes** [comment]
My mistake. I was using my phone and was looking at the wrong screen in making the decision.

Reopening

**Comment by palisadoes** [comment]
Due to work commitments this will probably not be reviewed until the weekend

**Comment by manishjha-04** [comment]
Okay Sir , no issues! 😃

**Comment by palisadoes** [comment]
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

**Comment by Cioppolo14** [comment]
@manishjha-04 Can you resolve the conflicting files?

**Comment by manishjha-04** [comment]
Sure would be resolving it soon!

**Pull request closed without merging**
