### PR TITLE
Installer

### PR DESCRIPTION
**Pull request by sumitra19jha**
I don't have access to Kailash360:installer-241. So I am creating this new PR.

*Please Note*
This is the extension of Kailash's work on the automated installation. I have just fixed the linting problem in this PR.

### CODE REVIEW

**Comment by palisadoes** [comment]
- Please comment on https://github.com/PalisadoesFoundation/talawa-api/issues/241 so that I can assign it to you.
- Code formatting is failing

**Comment by sumitra19jha** [comment]
@palisadoes This is because when we run a workflow on a pull_request event, the actions/checkout step will check out our repository in detached HEAD mode, on a merge reference created by GitHub. You can see it in the logs. To fix that this solution will [help](https://stackoverflow.com/questions/63594658/git-refs-merge-vs-head-in-pull-request). I am looking into this

**Comment by sumitra19jha** [comment]
Is the test server down?
Connection is failing

**Comment by palisadoes** [comment]
I think it's failing due to your changes in the `pull-request.yml` file. The other PR has passed without any issues.

**Comment by palisadoes** [comment]
@sumitra19jha This is due to your code. The other pull request passed without issue. Please review.

**Pull request closed without merging**
