### PR TITLE
 Added support to change pre-login imagery

### LINKED ISSUE #1611: Add support to change pre-login imagery
**Is your feature request related to a problem? Please describe.**
1. Communities need the ability to change the social media icons and logo images upon login.
1. We don't want users thinking that they are always logging into Palisadoes

**Describe the solution you'd like**
1. `Talawa-API`
    1. You will need to create a new collection specifically meant to store the customizations listed below
    1. You will need to write valid tests for your code
    1. No other functionality must be affected
1. `Talawa-Admin`
    1. Our login screen is not specific to organizations, so we'll need to make this change at the Community level.
    1. This will require the creation of a Community Profile button at the Super Admin level which would lead to a Community Profile edit screen
    1. This screen must be designed in keeping with our Talawa Admin Figma design found here
        1. https://docs.talawa.io/docs/design/ux/ux-design-system
    1. The logo and social media icons to be edited are visible in the attached screen shots
    1. By default, when the Palisadoes Logo is changed, the Palisadoes specific social icons should disappear so that the Community can add theirs. If the Logo is left blank, then the Palisadoes imagery should return, but the database parameters must remain so that the Admin doesn't have to re-enter the information.
    1. This will require the creation of a new collection in the API
    1. Please work with @aashimawadhwa and @rishav-jha-mech on the design approval before submitting a PR

**Related Issues**
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Images that should be editable: 
    image
1. Location of the Community Profile
    image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1611 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Working:

https://github.com/PalisadoesFoundation/talawa-api/assets/97614113/7837685b-fcf9-416f-8939-57f5a2ab4e24

Tests:

image

**Summary**

This PR adds support for changing pre-login imagery and links to various social media for a community by creating an API for updating these details.

**Other information**

Related issue in Talawa-Admin [#1334](https://github.com/PalisadoesFoundation/talawa-admin/issues/1334)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by xoldyckk** [comment]
this seems useless, why not just allow this in talawa-admin?

**Comment by palisadoes** [comment]
Because:

1. Admin can point to any compatible API instance
2. There will be multiple Admin clients

**Comment by xoldyckk** [comment]
there's no concept of `Community` in the database, it has to be created for it to be updated

**Comment by palisadoes** [comment]
`Community` has been added to the schema in the PR

**Comment by chandel-aman** [comment]
@DMills27 @sumitra19jha @xoldyckk @JamaicanFriedChicken 
Could one of you please review and provide feedback on this PR?

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
The code should be acceptable for merging afterwards. This feature is really needed.

**Comment by chandel-aman** [comment]
@palisadoes

I understand that reviewers are busy, and there are many PRs to review. However, could you please provide some feedback and review this PR? I have another issue dependent on this one.

**Comment by JamaicanFriedChicken** [comment]
@chandel-aman, please fix the conflicting files

**Comment by chandel-aman** [comment]
@JamaicanFriedChicken

Certainly! However, could you also provide your review of this PR? Changes may keep conflicting with other modifications.

**Comment by xoldyckk** [comment]
There is no community with `id == args.id`. The community isn't created for it to be updated.

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by chandel-aman** [comment]
@palisadoes does the scope of this issue involve creating mutations for creating a community as well?

**Comment by chandel-aman** [comment]
@palisadoes, I pulled the latest changes from upstream, and now I'm unable to commit the incoming changes as I'm getting ESLint errors. However, these errors are present in incoming files, not in the modified files. Could you guide me on how to proceed? Thank you!

**Comment by palisadoes** [comment]
1. Was this fixed? 
1. Have you merged with the latest upstream? 
1. Linting only on commits has been implemented for some time now

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by chandel-aman** [comment]
Because of changes made in eslint rules I'm unable to commit the changes even though I've resolved the conflicts.

image

Can I make a fresh PR for this?

**Comment by chandel-aman** [comment]
> 1. Was this fixed?
> 
>     2. Have you merged with the latest upstream?
> 
>     3. Linting only on commits has been implemented for some time now

No, I'm unable to commit the changes made after resolving the conflicts as the changes are seen as my changes even though I've just resolved the conflicts.

**Comment by chandel-aman** [comment]
> Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:
> 
>     1. The overall code coverage drops below the target threshold of the repository
> 
>     2. Any file in the pull request has code coverage levels below the repository threshold
> 
> 
> We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

The code coverage is not dropping due to the changes made in this PR. I think once I've pulled the latest changes it will get covered.

**Comment by palisadoes** [comment]
Yes, make a fresh PR

**Comment by chandel-aman** [comment]
> Yes, make a fresh PR

Okay, sir. Thank you! I'll be raising the PR shortly.

**Comment by palisadoes** [comment]
Closing

**Pull request closed without merging**
