### PR TITLE
Added Support for Production Environment

### LINKED ISSUE #1916: Add Support for Production Build of Talawa Api
**Describe the bug**
In the repo `src/server.js` is a stale file and in package.json we are still using the server.js to run the production build files 

```
    "start": "cross-env pm2-runtime start ./build/server.js --watch",
    "prod": "cross-env NODE_ENV=production pm2-runtime start ./build/server.js",
```

We have an old  ts-config-build.json and most of the packages only support the ES modules compatible but our ts-config.build .json emits commonjs and it doesn't support them, leading to new errors for the build environment.

**To Reproduce**

1. npm run build
2. npm run start

**Expected behavior**

1. It has to be pointed to `index.js` instead server.js which is a commented file.
2. The npm run build command should be emitted without any errors. 
3. The server should be accessed at localhost:4000 in a production environment.

**Screenshots**

```
C:\Users\91970\Desktop\talawa\talawa-api>npm run start

> talawa-api@1.0.0 start
> cross-env pm2-runtime start ./build/index.js --watch

2024-02-28T00:17:02: PM2 log: Launching in no daemon mode
2024-02-28T00:17:02: PM2 log: [Watch] Start watching index
2024-02-28T00:17:02: PM2 log: App [index:0] starting in -fork mode-
2024-02-28T00:17:02: PM2 log: App [index:0] online
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\91970\Desktop\talawa\talawa-api\node_modules\nanoid\index.js from C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js not supported.
Instead change the require of index.js in C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js to a dynamic import() which is available in all CommonJS modules.
    at Hook._require.Module.require (C:\Users\91970\Desktop\talawa\talawa-api\node_modules\require-in-the-middle\index.js:101:39)
    at Object.<anonymous> (C:\Users\91970\Desktop\talawa\talawa-api\build\libraries\requestTracing.js:18:18)
    at Hook._require.Module.require 
```

**Additional details**
This has to be addressed in order to support the production setup of talawa-api and started working on it as discussed in #1885 .
This issue require multiple PRs to support Production environment build

### PR DESCRIPTION
**Pull request by varshith257**
**What kind of change does this PR introduce?**

- Changed module to nodenext instead commonjs to support all the packages of ES modules.

**Issue Number:**

Fixes #1916 

**Did you add tests for your changes?**

To be tested after making successful changes suggested by reviewers

**Does this PR introduce a breaking change?**

**Other information**

Need to be solve the recursive errors raised by updating module to nodenext instead commonjs.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by varshith257** [comment]
@xoldyckk  I have changed the module to nodenext instead the commonjs as we discussed in the https://github.com/PalisadoesFoundation/talawa-api/pull/1885#issuecomment-1969476028

The goal is to support the new upgradation of packages that supporting only ESmodules to emmit them as modules I have added `type:module` in the package.json

The below is the same as stated in tsconfig.json documentation.

> [!NOTE]
The detected module format of input .ts/.tsx/.mts/.cts files determines the module format of the emitted JavaScript files. So, for example, a project consisting entirely of .ts files will emit all CommonJS modules by default under --module nodenext, and can be made to emit all ES modules by adding "type": "module" to the project package.json.


@kb-0311

**Comment by varshith257** [comment]
But the issue here is recursive errors after updating to`module: node16 `and `target : es2022`  and run `npm run build`  :

```
src/resolvers/Mutation/createUserTag.ts:11:8 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../../constants.js'?

11 } from "../../constants";
          ~~~~~~~~~~~~~~~~~

src/resolvers/Mutation/createUserTag.ts:14:3 - error TS7006: Parameter '_parent' implicitly has an 'any' type.

14   _parent,
     ~~~~~~~

src/resolvers/Mutation/createUserTag.ts:15:3 - error TS7006: Parameter 'args' implicitly has an 'any' type.

15   args,
     ~~~~

src/resolvers/Mutation/createUserTag.ts:16:3 - error TS7006: Parameter 'context' implicitly has an 'any' type.

16   context,
     ~~~~~~~

src/resolvers/Mutation/createUserTag.ts:47:6 - error TS7006: Parameter 'organizationId' implicitly has an 'any' type.

47     (organizationId) => organizationId.equals(args.input.organizationId),
        ~~~~~~~~~~~~~~

src/resolvers/Mutation/createVenue.ts:1:36 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 import { Organization, User } from "../../models";
                                     ~~~~~~~~~~~~~~

src/resolvers/Mutation/createVenue.ts:2:40 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../../types/generatedGraphQLTypes.js'?

2 import type { MutationResolvers } from "../../types/generatedGraphQLTypes";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/resolvers/Mutation/createVenue.ts:9:8 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../../constants.js'?

9 } from "../../constants";
```

Almost 500+ errors. Is there any alternate way or let solve these errors

**Comment by xoldyckk** [comment]
@varshith257 there is no alternate way I think, since the code is written in typescript most of these errors would only be about including `.js` at the end of imports, start with fixing that, you just have to add `.js` to all imports that import a typescript file

after that we'll see if there are package incompatibility errors, node ecosystem and esm compatibility is a mess apparently so we'll see what has to be done

**Comment by varshith257** [comment]
I have counted them 3200 errors 🥲. And can you provide guidance about type checking any error.

**Comment by xoldyckk** [comment]
@varshith257 yeah that's a mongoose issue, maybe updating it would make it infer correct types, it has an open issue #1695, though I doubt it'll fix it

@palisadoes either the `no-implicit-any` eslint rule has to turned off or mongoose and all packages that are creating type errors have to fixed

**Comment by varshith257** [comment]
I think that  type any error have to be fixed because the errors also emitting when building the files for prod environment. If eslint-any is turned off or warned, it will solve issue of dev environment eslint checking but  same issue can cause for production environment build files

**Comment by xoldyckk** [comment]
@varshith257 it would compile because typescript allows the usage of `any` keyword unless explicitly prohibited using eslint or tsconfig

@palisadoes this PR would result in a minor change in almost all files in the codebase, since the eslint rule is applied on the files modified within a PR, this PR would require the contributer to fix the `no-explicit-any` issue for all files in the codebase

**Comment by xoldyckk** [comment]
sure

**Comment by varshith257** [comment]
> sure, though I doubt it can be solved without fixing the dependencies causing it like mongoose

Can I solve them in this issue itself or new small PRs could be raised for it by opening a issue for type any error. I think the mangoose issue have to completed to start with this work of fixing any type error

**Comment by xoldyckk** [comment]
@varshith257 seperate issue(s)

**Comment by varshith257** [comment]
@xoldyckk This is the modified file of the `src/utilities/userFamilyAdminCheck.ts` file according to the  new tsconfig.build.json:

```
import { Types } from "mongoose";
import { UnauthorizedError } from "../libraries/errors/unauthorizedError.js";
import {translate} from "../libraries/requestContext.js"
import { USER_NOT_AUTHORIZED_ADMIN } from "../constants.js";
import type { InterfaceUserFamily } from "../models/userFamily.js";
import { User } from "../models/User.js";
/**
 * If the current user is an admin of the organization, this function returns `true` otherwise it returns `false`.
 * @remarks
 * This is a utility method.
 * @param userId - Current user id.
 * @param userFamily - userFamily data of `InterfaceuserFamily` type.
 * @returns `True` or `False`.
 */
export const adminCheck = async (
  userId: string | Types.ObjectId,
  userFamily: InterfaceUserFamily,
): Promise<void> => {
  const userIsUserFamilyAdmin = userFamily.admins.some(
    (admin) => admin === userId || Types.ObjectId(admin).equals(userId),
  );

  const user = await User.findOne({
    _id: userId,
  });
  const isUserSuperAdmin: boolean = user
    ? user.userType === "SUPERADMIN"
    : false;

  if (!userIsUserFamilyAdmin && !isUserSuperAdmin) {
    throw new UnauthorizedError(
      translate(`${USER_NOT_AUTHORIZED_ADMIN.MESSAGE}`),
      USER_NOT_AUTHORIZED_ADMIN.CODE,
      USER_NOT_AUTHORIZED_ADMIN.PARAM,
    );
  }
};
```

**ERRORS:**

```
src/utilities/userFamilyAdminCheck.ts:2:40 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

2 import { errors, requestContext } from "../libraries";
                                         ~~~~~~~~~~~~~~

src/utilities/userFamilyAdminCheck.ts:3:43 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../constants.js'?

3 import { USER_NOT_AUTHORIZED_ADMIN } from "../constants";
                                            ~~~~~~~~~~~~~~

src/utilities/userFamilyAdminCheck.ts:4:42 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../models/userFamily.js'?

4 import type { InterfaceUserFamily } from "../models/userFamily";
                                           ~~~~~~~~~~~~~~~~~~~~~~

src/utilities/userFamilyAdminCheck.ts:5:22 - error TS2834: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

5 import { User } from "../models";
                       ~~~~~~~~~~~

src/utilities/userFamilyAdminCheck.ts:19:6 - error TS7006: Parameter 'admin' implicitly has an 'any' type.

19     (admin) => admin === userId || Types.ObjectId(admin).equals(userId),
        ~~~~~


Found 2302 errors in 391 files.
```


For above errors, I have modified it. Am I on the right track @xoldyckk. Should I go for the next files as same  as above?

**Comment by Olatade** [comment]
@varshith257 please update your branch with the lastest changes.

**Comment by varshith257** [comment]
@xoldyckk Any suggestions here?

**Comment by xoldyckk** [comment]
@varshith257 you have to fix the error I guess? https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8226378501/job/22492766668?pr=1938#step:14:31

**Comment by xoldyckk** [comment]
@varshith257 i mean yeah adding those `.js` extensions is a part of it, why don't you take a read about esmodules? besides most of the code is in typescript so it's already using import/export syntax which esmodules is mostly about.

**Comment by xoldyckk** [comment]
@varshith257 when you're shifting to esmodules you don't emit commonjs code unless you're a library author, because library authors need to maintain compatibility with other js packages which are still using commonjs

talawa api is meant to be consumed directly and run as a server, so there's no point of emitting commonjs files in production build

**Comment by varshith257** [comment]
> @varshith257 when you're shifting to esmodules you don't emit commonjs code unless you're a library author, because library authors need to maintain compatibility with other js packages which are still using commonjs
> 
> talawa api is meant to be consumed directly and run as a server, so there's no point of emitting commonjs files in production build

Got it ! We had a small misunderstand. The approach now we have taking is to emit `esmodules` instead commonjs  and same have been added to package.json. Will make changes as adding .js and update you.

**Comment by varshith257** [comment]
Waiting to merge the mongoose PR into develop

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@varshith257 Please fix the conflicting files and failed tests.

**Comment by varshith257** [comment]
Working on it

**Comment by varshith257** [comment]
WIP

**Comment by varshith257** [comment]
@xoldd Closing this PR as It getting efforts more than we thought. Getting every compatibility issue as new code added into codebase. I think we can add production supportonce the codebase got stabilized

**Pull request closed without merging**
