### PR TITLE
solved event creation problem

### LINKED ISSUE #2029: User is unable to create an event and getting an error.
**Describe the bug**
User is unable to create an event and getting an error.

**To Reproduce**

1. Login as user
2. Try to create an event in some organization an error will occur saying: 
`Cast to ObjectId failed for value "id=6537904485008f171cf29924" (type string) at path "_id" for model "Organization"`

**Expected behavior**
User should be able to create an Event.

**Screenshots**
PaliIssue1

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
solved event creation problem

**Issue Number:**

Fixes #2029 

**Did you add tests for your changes?**
Not required

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 Please fix the failing tests.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 Please fix the failed tests.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by AdityaRaimec22** [comment]
@palisadoes So, sorry for the delay but I am a bit busy in writing my GSoC proposal.

**Comment by palisadoes** [comment]
Please remember this. It is blocking the completion of this issue:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1606#issuecomment-2016817505

**Comment by AdityaRaimec22** [comment]
@palisadoes so, sorry for the delay. You can merge the PR now. It is up for merging.

**Comment by palisadoes** [comment]
Please improve the code coverage of the patch it's only 50%

image

**Comment by AdityaRaimec22** [comment]
@palisadoes I think everything fine now.

**Comment by palisadoes** [comment]
The coverage is only 66% now

image

**Comment by AdityaRaimec22** [comment]
@palisadoes All checks are passed now.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
