### PR TITLE
Fixes #255, #284, #285, #286, #289

### LINKED ISSUE #255: Standardize GitHub Actions  File Layout
**Is your feature request related to a problem? Please describe.**

We need to have a standardized way of adding GitHub actions to the repository. [The preferred methodology is that done with the Talawa repo.](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows)

**Describe the solution you'd like**
1. Place all actions related to issues in the issues.yml file.
1. Place all actions related to pull requests in the pull-requests.yml file.
1. Have a greeting for first issue created
1. Have a greeting for first PR created
1. Force the manual running of GitHub actions by the PR approvers if it is the submitters first pull request. This is already done with Talawa.
1. [Add a README.md file that states these requirements](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/README.md) Use this as a guide.

**Describe alternatives you've considered**

1. When the actions are in a single file GitHub gives status messages for each section. This makes it easier for both the PR approver and submitter to troubleshoot the source of the error.
1. The current method gives only a single status. You have to click through to see the results.

**Approach to be followed (optional)**

See guidelines above

**Additional context**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

If we have a standardized approach, both troubleshooting and the addition of new actions will be easier

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

### LINKED ISSUE #284: Add and test GitHub action to lint all PRs before submission
We need to lint all code as part of the pull request process. 

1. The commands for the actions file can be found at the beginning of the documentation of this [outdated GitHub action](https://github.com/marketplace/actions/run-eslint)
1. We will need the action to be activated only on a pull request. [We have an example of how to do that in the Talawa repo](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/.github/workflows/linter.yml)
1. Make the action be defined in a file named `pull-requests.yml`

Test and make sure it doesn't break the code. Try running the linter on the code base as proof.

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

### LINKED ISSUE #285: GitHub Action To Limit Code File Sizes
**Describe the bug**

1. In order to improve the readability of the code we need to enforce a file size limit on code submitted to pull requests. This has been done effectively with Talawa using the [countline.py script](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows)
2. We need a GitHub action specifically for Node.js code that will fail when the code file sizes are too large. 400 lines to start.

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

### LINKED ISSUE #286: GitHub Action: Code Formatter
**Describe the bug**

1. To reduce the risk of conflicting files, we need a standardized way of formatting the Node.js code before a pull request.
2. [There are a number of solutions for this](https://www.google.com/search?q=GitHub+action+formatter+node.js&oq=GitHub+action+formatter+node.js&aqs=chrome..69i57j69i64.9200j1j7&client=ubuntu&sourceid=chrome&ie=UTF-8)

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

Parent Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/287

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

### LINKED ISSUE #289: Run Automated Tests with Each Pull Request
**Is your feature request related to a problem? Please describe.**
To ensure that tests are run before code is merged we need a tool to automatically run the tests to improve the reliability of Talawa-Admin as all feature/pull requests need to be adequately tested before they are merged.

**Describe the solution you'd like**
The tool must be :
    - Free for non-profit organizations (ideally)
    - Automated against the master and develop branches

**Describe alternatives you've considered**

1. [Talawa-Admin currently uses CodeQL](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/.github/workflows/codeql-analysis.yml) 
2. A similar methodology must be used

Parent Issue: Various GitHub Actions Issues #287

### PR DESCRIPTION
**Pull request by muskan399**
**What kind of change does this PR introduce?**

**Issue Number:**
Fixes #255, Fixes #284, Fixes #285, Fixes #286, Fixes #289

**Did you add tests for your changes?**
Some changes have been tested locally.

**Other information**
I'm a GitHub Extern candidate(28-04_Mus695_tfa_262)

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
We'll need the codeql YAML file included in the PR YAML file. Is that possible? We'll also need the codeql run against all branches

**Comment by muskan399** [comment]
@palisadoes , we can include the codeql yml file in pull-request.yml, but the codeql yml runs job on both push and pull request, so we can 
* Either remove the push, from code ql yaml file and then include it in pull-request.yml 
* or we can create a separate file for push also and then keep the same code of codeql analysis in both files(pull.yml and pull-request.yml).
I will change the yml file for running codeql against all files.

**Comment by palisadoes** [comment]
> @palisadoes , we can include the codeql yml file in pull-request.yml, but the codeql yml runs job on both push and pull request, so we can
> 
> * Either remove the push, from code ql yaml file and then include it in pull-request.yml
> * or we can create a separate file for push also and then keep the same code of codeql analysis in both files(pull.yml and pull-request.yml).
>   I will change the yml file for running codeql against all files.

@muskan399

In that case:

1. Rename the codeql YAML   `compulsory.yml`
1. Create a README.md [like this one](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows) and update it with information about `compulsory.yml`

**Comment by muskan399** [comment]
Okay, will do it.

**Comment by palisadoes** [comment]
@muskan399 Why does the codeql action need to be run with every new issue? Shouldn't it only be needed when new code is about to be merged into the branches? Running it when the issue is created seems unnecessary.

**Comment by muskan399** [comment]
For that, I think we should remove push event from that workflow, and only keep the pull_request event in codeql analysis file.

**Comment by palisadoes** [comment]
@muskan399  OK. Please add it to the PR YAML file. Still include the README.md file

**Comment by muskan399** [comment]
Okay, will do it.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@muskan399 the Greeting is failing

**Comment by palisadoes** [comment]
@muskan399 The tests are still failing. Please review.

**Comment by muskan399** [comment]
@palisadoes Styling is failing because it is trying to style the code but talawa-admin doesn't provide access to the repository.
I tested it in my local branches and it was working fine.
I will look for another GitHub action for doing this.
Till that I am thinking of removing the Styler from the pull-request.yml.

**Comment by palisadoes** [comment]
@muskan399 Here is the error on the Styles the code check:

image
image
image
image

**Comment by muskan399** [comment]
In Talawa-mobile we were checking whether the code is formatted or not. But here it is making changes in the code if it is not formatted and talawa-admin don't provide access to it.
I think because of this error is coming.

**Comment by palisadoes** [comment]
> @palisadoes In Talawa-mobile we were checking whether the code is formatted or not. But here it is making changes in the code if it is not formatted and talawa-admin don't provide access to it.
> I think because of this error is coming.

Yes, it should fail with a message stating where the error is without trying to modify the code. That should be up to the developer who authored the pull request.

**Comment by muskan399** [comment]
@palisadoes Okay, got the point, will rectify it soon.

**Comment by palisadoes** [comment]
@muskan399  Please resubmit against the develop branch. All features are now only being added there.

**Comment by Sagar2366** [comment]
@muskan399 is this same as PR https://github.com/PalisadoesFoundation/talawa-api/pull/305 ?
If yes, please close one of PR which is not needed.

**Pull request closed without merging**
