### PR TITLE
Change the data type of storage of attributes of Event Model [Fixes part of #1101]

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes part of #1101 
Must be merged with [this PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/523) to restore the functionality

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Updated the `endDate`, `startDate`, `endTime` and `startTime` variables to be stored as Date type in the database (and not String) so that they can be serialized correctly by `GraphQL-Scalars`
This code has been tested with talawa-mobile's create event functionality too. 

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Review by xoldyckk — APPROVED** [review]

**Comment by xoldyckk** [comment]
@palisadoes @EshaanAgg Dependence on `allDay` boolean is weird if you ask me. Also, the api and database don't handle the edge cases well. Edge cases here bascially are all the combinations of fields like startTime, endTime, startDate, endDate, recurrance and what their contextual meaning is.

**Comment by xoldyckk** [comment]
There could be some inconsistencies with accepting `Date` and `Time` seperately as without the complete `DateTime` the date conversion will be incorrect. At least that's what I think, I don't know much about all the intricacies with date times as it's a broad field.

**Comment by EshaanAgg** [comment]
@xoldyckk I feel that too. Instead of managing these four fields separately, we should rather be using just two variables `start` and `end`, each of `DateTime` type. Though implementing the same would be a breaking change, and would require more review before proceeding with the same.

**Comment by xoldyckk** [comment]
> @xoldyckk I feel that too. Instead of managing these four fields separately, we should rather be using just two variables `start` and `end`, each of `DateTime` type. Though implementing the same would be a breaking change, and would require more review before proceeding with the same.

Also, you've annotated mongodb field as Date, but what you're giving it is just a `Date` and `Time`. Does it automatically convert it to its UTC equivalent?

**Comment by xoldyckk** [comment]
> MongoDB has no support for Date and Time types separately, but rather only for storing DateTime under the type name `Date`. It the the `GraphQL-Scalars` package that does this conversion (and reverts the same upon fetching) to the `UTC` equivalent before storage in the database,

Have you tested this manually? Whether the input fields like `startDate`, `startTime` are converted to their UTC equivalent then given to resolvers as input?

**Comment by palisadoes** [comment]
"All Day" is just a UX convenience. Storing the event timing data as a start/stop only should be OK. We can just let the other repos know that the "All Day" feature is going to have to be refactored in their code.

How do you propose to handle "recurring" events as there is going to be a lot of meta data? (Google calendar has lots of recurring event options both custom and standard"

**Comment by palisadoes** [comment]
Fixing event timing should be handled as a separate issue, and we should merge this PR. I don't want to get into another discussion over architecture and delay the necessary fix this PR will provide.

@xoldyckk can you create the fix events issue so that this can be merged?

**Comment by xoldyckk** [comment]
> Fixing event timing should be handled as a separate issue, and we should merge this PR. I don't want to get into another discussion over architecture and delay the necessary fix this PR will provide.
> 
> @xoldyckk can you create the fix events issue so that this can be merged?

Yes, this can be merged. Because the logic of storing it as DateTime in mongodb is correct I guess.

**Comment by EshaanAgg** [comment]
> > MongoDB has no support for Date and Time types separately, but rather only for storing DateTime under the type name `Date`. It the the `GraphQL-Scalars` package that does this conversion (and reverts the same upon fetching) to the `UTC` equivalent before storage in the database,
> 
> Have you tested this manually? Whether the input fields like `startDate`, `startTime` are converted to their UTC equivalent then given to resolvers as input?
> 
> If you haven't you can console log it inside the resolver while creating the event and see.

Yes I have tested the same. Rather than testing in the backend, I have tested the same of the frontend by logging the same.
Date Type Scalar returns the date in the form of `YYYY-MM-DD` while Time Type Scalar returns the same in the form of `HH:MM:SS.000Z`, and thus the UI has been changed to handle it.

**Pull request merged**
