### PR TITLE
[feature request] : Python script to automate installation process

### PR DESCRIPTION
**Pull request by rv602**
### What kind of change does this PR introduce?

This PR is a feature addition. I have added a python script in the root directory of the project which will help in a much quicker and efficient way of setting up talawa-api for developers.

### Videos : -

1. If no `.env` file exists in the root directory : -

https://user-images.githubusercontent.com/92572013/224138342-87e404d4-5f35-428b-92e2-eaaa9d643cae.mp4

<br>

2. If `.env` file exists with some values already assigned : -

https://user-images.githubusercontent.com/92572013/224139507-9c9d4825-49ec-4f18-b78a-5b890d25d468.mp4

<br>

### Summary : -

The motivation to raise this feature request and work on it was convenience and saving time of developers who wish to contribute to talawa. Many people make minor errors in a hassle to setup a project and that leads them to unnecessary errors and eventually loosing motivation to debug the errors further.
This script aims to eliminate the possibility of almost any minor errors possible from the developer's side.

### Does this PR introduce a breaking change?
No

### Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Review by noman2002 — APPROVED** [review]
Good Work. We can improve it further but its good for now,

**Comment by rv602** [comment]
@xoldyckk could you please review this PR? Thank you.

**Comment by DMills27** [comment]
This works fine as-is but in the future I'd prefer something that can generate all those hard-coded values you have in the .env.template file. But, as I said before we are in dire need of this for simplifying the ease of set up right now.

**Review by DMills27 — APPROVED** [review]

**Comment by rv602** [comment]
@palisadoes since 2 people have approved these changes, can this PR be merged? Thank you.

**Pull request merged**
