### PR TITLE
[Fixes] Error: While logged-in into talawa-admin

### LINKED ISSUE #628: Error: While logged-in into talawa-admin
**Describe the bug**
While logged-in into talawa-admin, the error  `"message": "Cannot return null for non-nullable field Organization.name."` is generated.

**To Reproduce**

1. Login into talawa-admin
2. Open the console
3. You will see the error into the same (you must have created at least one organization)
4. Error is: `TypeError: can't access property "user", data_2 is undefined`

**Expected behavior**

The component should be rendered properly with organization lists and with logged-in user details.

**Screenshots**

* Console error: 
   image

* Graphql Playground: 
   image

**Additional details**

I want to work on this, please assign it to me.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #628 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

* Query
   image

* Response
   image

**If relevant, did you update the documentation?**

No

**Summary**

While logged-in to talawa-admin, the error `"message": "Cannot return null for non-nullable field Organization.name."`  is generated. But in normal circumstances, The component should be rendered properly with organization lists and with logged-in user details.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please lint the code properly

**Comment by palisadoes** [comment]
Please merge with the latest code and resubmit. The code coverage failure should resolve itself.

**Review by JamaicanFriedChicken — APPROVED** [review]
It looks good to me! As @palisadoes has mentioned, merge with the latest code and resubmit.

**Comment by asmitsirohi** [comment]
@palisadoes, I have fixed all the issues.

**Review by JamaicanFriedChicken — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
