### PR TITLE
Add new tests in requestContext.spec.ts

### LINKED ISSUE #1912: Enhance Test Coverage for requestContext Middleware (TEST)
**Description**
The current test suite for the requestContext middleware lacks coverage for certain edge scenarios. This issue proposes the addition of test cases to address the following scenarios:

1) Testing with Missing Locale:
when the locale is intentionally missing during initialization.

2) Testing with Incorrect Locale:
when an incorrect locale is intentionally provided during initialization.

3) Testing with Missing Request Handler:
Ensure that the middleware handles scenarios where no request handler is provided during init.

4) Testing with Empty Options for init:
Validate that the middleware gracefully handles cases where no options are provided to the init function.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by mohamed-adel-alsayed**
**What kind of change does this PR introduce?**

This PR adds more tests for src/libraries/requestContext.ts.

**Issue Number:**

Fixes #1912 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

This PR increases test coverage by implementing more unit tests for src/libraries/requestContext.ts.

**Does this PR introduce a breaking change?**

No.

Following the implementation of new test scenarios, certain adjustments to the src/libraries/requestContext.ts are necessary to maintain complete test coverage.

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Comment by mohamed-adel-alsayed** [comment]
@palisadoes Closed previous PR due to issues. Opened this new one for a cleaner submission.

**Comment by mohamed-adel-alsayed** [comment]
@Cioppolo14 Check it now.

**Comment by palisadoes** [comment]
1. There are too many automated suggestions to improve your code. Please address them.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1961/files
1. When this is done, notify this thread and we'll re-assign reviewers

**Comment by mohamed-adel-alsayed** [comment]
@palisadoes Done.

**Comment by Cioppolo14** [comment]
@mohamed-adel-alsayed Please fix the failed linting check.

**Comment by Cioppolo14** [comment]
@mohamed-adel-alsayed Please fix the failing lint check.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@mohamed-adel-alsayed Please fix the failed tests and conflicting files.

**Comment by palisadoes** [comment]
Closing as abandoned

**Pull request closed without merging**
