### PR TITLE
Fixed case sensitivity security glitch in Emails. 

### LINKED ISSUE #2118: Email Address Case Sensitivity Leads to Potential Privilege Escalation
**Describe the bug**
The case sensitivity of email addresses is not properly handled. This issue allows a user with an email address (e.g., `abc@example.com`) to update their profile email to another user's email using a different case (e.g., `TESTSUPERADMIN@example.com`). Consequently, the system treats these email addresses as distinct, potentially allowing unauthorized access or notifications to be sent to the impersonated user.

It creates two different users with email `TESTSUPERADMIN@example.com` and `testsuperadmin@example.com`, so if someone sends a password reset request to TESTADMIN (Upper Case), the system would sent it to lower case one.

**To Reproduce**

1. Update the second user's email address to TESTSUPERADMIN@example.com through the profile update feature.
2. Observe that the system accepts the update leading to potential security issues such as unauthorized access to notifications or account takeovers.

**Expected behavior**
The application should normalize email addresses to a standard case (e.g., lowercase) before processing them. This normalization should occur at all points where email addresses are entered or processed, including account creation, login, and profile updates. The system should recognize abc@example.com and ABC@example.com as the same email address, preventing case-based impersonation or duplication.

**Screenshots**
image
image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anubhav-2003**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #2118 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
No

**Summary**
Fixes the bug that allowed users to change email to other existing emails with a different casing.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Anubhav-2003** [comment]
@palisadoes Respected Sir, I have fixed the bug related to the case sensitivity of the emails. It was a minor issue. Please review. Thank you.

**Comment by pranshugupta54** [comment]
How about using lowercase:true in User schema instead?
> https://mongoosejs.com/docs/schematypes.html

**Comment by varshith257** [comment]
@Anubhav-2003 I would also suggest enforce email using `lowercase:true` in email field of userSchema instead enforcing in mutations

**Comment by Anubhav-2003** [comment]
> How about using lowercase:true in User schema instead?
> 
> > https://mongoosejs.com/docs/schematypes.html

Ok let me add that as an extra layer as well. Thank you

**Comment by Anubhav-2003** [comment]
> @Anubhav-2003 I would also suggest enforce email using `lowercase:true` in email field of userSchema instead enforcing in mutations

Well, I’m not enforcing in the mutations, but rather in the resolvers associated with it. But let me at that add the extra flag check in the UserSchema as well. Thanks for your suggestion.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, Please review.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
