### PR TITLE
feat: added tests for createPlugin mutation (#1601)

### LINKED ISSUE #1601: Add tests for `createPlugin` mutation
**Is your feature request related to a problem? Please describe.**
Missing tests for the mutation defined in  `src/resolvers/Mutation/createPlugin.ts`

**Describe the solution you'd like**
Write tests for the given mutation in a separate file `tests/resolvers/Mutation/createPlugin.spec.ts` 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by rishabhbizzle**
**What kind of change does this PR introduce?**

- This PR addresses and adds the missing tests for ```createPlugin``` mutation.

**Issue Number:**

Fixes #1601 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
image

**Summary**

This PR adds missing tests of mutation defined in ```src/resolvers/Mutation/createPlugin.ts``` in a separate file ```tests/resolvers/Mutation/createPlugin.spec.ts```

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by noman2002** [comment]
@rishabhbizzle Merge the latest code into this.

**Comment by rishabhbizzle** [comment]
> @rishabhbizzle Merge the latest code into this.

Done ✅

**Comment by noman2002** [comment]
@rishabhbizzle Why the coverage is dropping?

**Review by sumitra19jha — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. @rishabhbizzle Something is wrong
2. The generated code coverage report doesn't include this file
    1. https://app.codecov.io/gh/PalisadoesFoundation/talawa-api/pull/1610?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation
4. The code coverage for the repo is falling with this PR
5. Please fix

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
