### PR TITLE
SMTP Transporter Configuration for Mailer [Fixes #457 in Talawa Admin]  

### LINKED ISSUE #457: Fix Test `tests/user_organization.spec.js`
Our integrated test suites need to function correctly. This test file when run is failing and needs to be fixed.

- `tests/user_organization.spec.js`

Parent issue:
- https://github.com/PalisadoesFoundation/talawa-api/issues/449

### How to run the tests

To test you will need to start the test server, run the test, then stop the test server.

```
npm run start-test-server-in-action
npm run test
npm run stop-test-server-in-action
```

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
It adds the custom smtp server mailer support to talawa applications suite.

**Issue Number:**

Fixes PalisadoesFoundation/talawa-admin#457

**Did you add tests for your changes?**
Not Required

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Yes

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please review.

**Comment by DMills27** [comment]
Can you provide a use case for this? I think it will be needed for the app at some point but it's too barebones right now to be utilised effectively in its current form.

**Comment by anshgoyalevil** [comment]
> Can you provide a use case for this? I think it will be needed for the app at some point but it's too barebones right now to be utilised effectively in its current form.

Yes, I agree with you.

This is for those who don't want to configure Gmail transporter.

Those developers can use ```SendGrid```'s free SMTP server to test the mailer configuration.

Also, in Production Environments, we - cannot rely on Gmail Transporter, because of several reasons like invalid ```DKIM``` or ```SPF``` configuration.

@palisadoes What are your thoughts on this?

**Comment by palisadoes** [comment]
@anshgoyalevil  @DMills27 

1. This PR needs to be integrated.
1. What tests can you add to make sure it works? This is an important feature an it afford to be added to the code base broken.

**Comment by anshgoyalevil** [comment]
@palisadoes 

I just checked the transporter with other services like SendInBlue and SendGrid. It is working like a charm.

ss

We can merge this PR.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
