### PR TITLE
[fix] : organisation icon rendering fixed in backend

### PR DESCRIPTION
**Pull request by rv602**
### What kind of change does this PR introduce?
In the admin homepage, the icon of an organisation isn’t rendered properly. I had raised this issue in the talawa-admin repository. It seems there were some errors to be solved from the backend as well. This PR contains all the necessary changes for the icon to be rendered properly/

### Did you add tests for your changes?
No.
There were just few modifications and minor errors to be rectified. I haven’t written any tests. Although all the tests are running successfully and the application produces the necessary result.

### Snapshots/Videos : -

Admin page before : -

image

Admin page now : -

image

Test coverage after PR : -

https://user-images.githubusercontent.com/92572013/213864603-fcac948b-de3f-46c5-8f5d-39d52f1862c5.mp4

### Did you update the documentation?
No

### Summary : -

The motivation for solving this challenge was the user experience, as the site looks very unprofessional and broken when organisation's icons aren’t being rendered and a placeholder image is shown instead.

I have made a PR regarding this same problem in talawa-admin repo, link below : -
https://github.com/PalisadoesFoundation/talawa-admin/pull/381

### Does this PR introduce a breaking change?
No

### Other information

For this functionality to work as desired, this PR as well as the one I made in talawa-admin, both must be merged.
Talawa admin PR - https://github.com/PalisadoesFoundation/talawa-admin/pull/381

### Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the code linting issue

**Comment by palisadoes** [comment]
@SiddheshKukade @DMills27 Please reviewl

**Comment by JamaicanFriedChicken** [comment]
@rv602, try getting the test coverage to 100% for the two files `src/lib/utilities/reuploadDuplicateCheck.ts` and `createOrganization`. It's looking good so far!

**Comment by rv602** [comment]
okay i'll look into it 👍. Thank you.

**Comment by palisadoes** [comment]
Please also fix the conflicting files

**Comment by rv602** [comment]
@palisadoes @JamaicanFriedChicken I have made the changes and resolved the conflicts.

Although I did not work on increasing test coverage of ```src/lib/utilities/reuploadDuplicateCheck.ts``` and ```createOrganization``` as issues for them have been raised separately.

If needed I will try to get them to 100% and make the PR in their corresponding issues.

**Comment by palisadoes** [comment]
> @palisadoes @JamaicanFriedChicken I have made the changes and resolved the conflicts.
> 
> Although I did not work on increasing test coverage of `src/lib/utilities/reuploadDuplicateCheck.ts` and `createOrganization` as issues for them have been raised separately.
> 
> If needed I will try to get them to 100% and make the PR in their corresponding issues.

- OK. We have issues opened for those tests.
- Please fix the conflicting files to facilitate the approval and merging

**Comment by rv602** [comment]
@palisadoes I fixed the conflict. I think it should work now.

**Comment by rv602** [comment]
@palisadoes is this a codecov error?

image

I found the same issue in codecov repository as well, link attached below : -
https://github.com/codecov/codecov-action/issues/598

**Comment by rv602** [comment]
@palisadoes yes I did comment out some part.
The commented part is basically handling the image file uploading part but it wasn’t working as desired.
Hence I moved with a different method i.e using the FileReader API in frontend and getting the image in the form of the string.
I commented it out instead of removing it entirely just incase some developer would like to reference it.

**Comment by rv602** [comment]
I have made a PR regarding the same in frontend i.e talawa-admin as well making the necessary changes.
This PR can be merged as of now, and I will resolve errors and submit my talawa-admin PR shortly.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
