### PR TITLE
feat :Creating support for event agendas

### LINKED ISSUE #1588: Create Support for Event Agendas
**Is your feature request related to a problem? Please describe.**
Community based organizations will often need to have agendas for their events. Reasons for this requirement would include:

1. The order of ceremony for a wedding
2. The order of ceremony for a concert
3. Agendas for committee meetings

**Describe the solution you'd like**
We need the ability to make events have agendas. The agenda would have sequence of agenda items with the following characteristics:

1. Title
1. Description
1. Agenda item type (See "Note" type below)
1. Agenda item type information (For example if an organization creates a type called "Song, they may want to make this track the key of the music)
1. Duration of the agenda item
1. Multiple Attachments stored on the system
1. Multiple URL links
1. Agenda item "User" to indicate a speaker, performer or similar party
1. Agenda item category which would come from a Agenda category list that is universal to the organization.
1. Agenda section which would allow agenda items to be grouped together. The section will require:
    1. A description
    1. An ordered sequence of sections so that they can follow one another
    1. An ordered sequence of agenda items belonging to a section
1. updatedBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. updatedAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdBy - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542
1. createdAt - See https://github.com/PalisadoesFoundation/talawa-api/pull/1542

We will need schema, mutations and queries created for:

1. Agenda sections and their sequencing within an event
1. Agenda items and their sequencing with a section
1. Agenda item URLs
1. Agenda item attachments
1. Agenda categories within an organization

Other schema, mutation, query requirements:
1. Mutations would include typical CRUD actions. 
1. Document the schema, mutations and query requirements well so that it exports with meaningful information to our automatically generated schema, mutations, and queries documentation page used by our developers.
    1. https://docs.talawa.io/docs/schema

There will also be a need for a special type of agenda item:

1. Called a "Note"
1. Contains a description
1. No duration, no title, attachments, URLs, user 
1. Has all the other characteristics of an Agenda item in terms of sequencing
1. Could be identified by a `Note` flag field in the Agenda schema

Therefore the schema will need an enum for the agenda item type  which would cover regular vs note type items, with a consideration for future support of other item types

There are some additional requirements:

1. When the first section is created, all existing agenda items must be tied to it while maintaining the agenda item order.
1. Changing the sequencing of an agenda section must not alter the sequencing of the agenda items within each section.
1. Changing the sequencing of agenda items must not alter:
    1. The sequencing of sections
    1. The sequencing of any other sections should other sections exist
1. You will need to write valid tests for this work
1. No other functionality must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1.  This is a prerequisite for our menu of GSoC 2024 project ideas
1. This issue would be best handled by someone who already has experience with updating our schema, mutations etc or can prove it in other scenarios. 
1. Please work with @xoldyckk on the details of this issue and the subsequent PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Atharva-Kanherkar**
**What kind of change does this PR introduce?**

 Feature

**Issue Number:**

Fixes #1588

**Did you add tests for your changes?**

 Not yet, but will commit them in a day or two.
 
**Summary**

 This pull request introduces the addition of agendas for an event, the schemas and the resolvers for CRUD operations.

**Does this PR introduce a breaking change?**  No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

 Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please fix the failing tests
2. The code testing coverage has fallen dramatically (-8.85%). You will need to add more testing to pass the minimum level.

image

**Comment by Atharva-Kanherkar** [comment]
> 1. Please fix the failing tests
> 2. The code testing coverage has fallen dramatically (-8.85%). You will need to add more testing to pass the minimum level.
> 
> image

1. Yes, as soon as possible.
2. Does that mean i have to add test files for my created files, each and every? Or i have to improve my code so that it passes the checks?

**Comment by palisadoes** [comment]
Please watch this video
- https://youtu.be/dQuEKpsy1vM?si=NcZzDhLSGj7IR09J

**Comment by Atharva-Kanherkar** [comment]
@palisadoes 

Hello sir, when creating tests for almost every case that there can be, i am still getting 65-70% test coverage in some files. It's telling me some of the lines are not covered. Where can i get some help on this, as i have covered every case i could think of, and the lines its mentioning, has been already covered?

For reference, i have already covered the functions in the lines but its still giving those lines as uncovered.)
image

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

1. If you click on this link it will show you the lines that are not covered. 
image
1. Ask the author of this PR. They have managed to cover testing for a similar type of feature
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1648
1. Ask the `#talawa-api` slack channel for guidance.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Sorry for being a little late for adding the tests. As you can see, there are still some percentage of tests needed, I will finish them soon. But i had some important questions to ask, 1. That the documentation I have added, is in the form of comments and markdown languages, do we need to update this in the docs.talawa website? 2. Secondly, you said that this will also require an admin screen to do CRUD operations and the agenda sections should also be displayed on the front-end in the sequenced manner. I have several ideas also how we can implement this on the frontend, if required. I still have two issue assigned to me, as there can be only 2 issues assigned, after completing one of them, can I make a issue on the talawa-admin portal? Thank-you!

**Comment by palisadoes** [comment]
1. Yes to both questions.
2. The Admin design must comply with the guidelines below. We will need to add your design to our official figma document
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
@Atharva-Kanherkar 

This PR needs to be closed:

1. This PR is too big. 
    1. There are hundreds of lines of code and over 50 files to review.  I'd suggest 3 separate PRs
        1. Category CRUD
        3. Section CRUD
        4. Agenda Item CRUD
    1. Please close this PR and use this approach each with it's own branch based on . The likelihood of getting your code reviewed faster will be much better.
1. It's submitted against the main branch, not develop

Create a separate branch per PR. It will be easier in the long run.

**Pull request closed without merging**
