### PR TITLE
updated:node 20 LTS

### LINKED ISSUE #1555: Upgrade to Node 20 (LTS)
**Is your feature request related to a problem? Please describe.**

1. We need to ensure that the app runs on an LTS version of Node.js
    1. https://nodejs.org/en/about/previous-releases
1. The installation guide doesn't specify the required LTS version of Node.js to be used
1. The application needs to be tested to make sure that it works with an LTS version of Node.js
1. Our GitHub Actions need to be updated to specify the LTS version of Node.js to be used

**Describe the solution you'd like**
1. Upgrade to Node 20 LTS
1. Update the installation guide to specify this LTS version of Node.js to be used
1. Update the installation or automated setup process to fail if the minimum LTS version isn't being used
1. Test the application to make sure that it works with this LTS version
1. Our GitHub Actions need to be updated to specify this LTS version of Node.js to be used
1. Address all warnings and errors (especially those related to deprecation) to the best of your ability according to industry best practice
1. All existing tests must pass

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**

Updated the installation guide to specify this LTS version of Node.js to be used
Update the installation or automated setup process to fail if the minimum LTS version isn't being used
GitHub are updated to specify this LTS version of Node.js to be used

Fixes #1555 

**Did you add tests for your changes?**

NO

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by AVtheking** [comment]
resolved the conflicts

**Comment by palisadoes** [comment]
Why was the video file added? Please remove it

**Comment by AVtheking** [comment]
I have removed video file ,sorry It was added by mistake

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by AVtheking** [comment]
fixed formatting issue

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
