### PR TITLE
create a default organization on running setup

### LINKED ISSUE #2109: Make setup create a default organization
**Is your feature request related to a problem? Please describe.**

1. With a brand new installation of the API we don't create an organization.
2. It would be best to create one so that the user isn't faced with a blank screen on login
3. We also want users to select an organization upon registration. This will be impossible without at least one organization being pre-populated.

**Describe the solution you'd like**

1. Update the setup script to import a default organization with default values for fields if test data isn't imported.
    1. When in doubt about values, use the word `Default`
3. Use the flow chart below for guidance. There is one modification:
    1. If a person wants to import data, they must be given the option of:
        1. Importing sample data. This would remove all prior data from the database beforehand.
        2. Importing the default organization data. This would remove all prior data from the database beforehand.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See flow chart

**Additional context**
1. Use this PR for reference:
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1770
1. Use this issue for reference:
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1703
1. You'll need to write tests for this. All tests must pass and be valid. No other functionality must be affected.
1. Flow chart

    image

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**
It creates a default organization if the database is empty.

**Issue Number:**

Fixes #2109 

**Did you add tests for your changes?**
Yes

**Video**
1. **When there is data in the database** 

 i. User selects to import default data:

https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/bae3a7f4-8086-473b-965e-3ab06f7ee4e6

 ii. User selects to import sample data:

https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/ba64f601-86df-456c-ab2b-cf3422f06cc5
 
 iii. User neither selects default data nor sample data and user does not select to overwrite data:

https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/90402f8e-7061-45ae-a9a0-274831dfdb5a

2. **When there is no data in the database**

 i. User selects to import sample data:

https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/62b05784-de2e-4662-af5a-88ffcd839bcf

 ii. If user does not selects to import sample data then default data would be imported by default:

https://github.com/PalisadoesFoundation/talawa-api/assets/132201033/48d3e19a-21b8-463a-ad7f-6fe265b600f9

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks

1. Don't use dropdowns, make each question require a Yes or No answer. This will reduce the risk of error.
1. This is the logic we are going to need as it is more intuitive

image

**Comment by Cioppolo14** [comment]
@AVtheking Please fix the failing tests.

**Comment by palisadoes** [comment]
1. Is the follow chart in this PR being followed now?
1. If so, please add a video showing all the options in the chart

**Comment by AVtheking** [comment]
ok sir .

**Comment by AVtheking** [comment]
I have already added video in the PR description.

**Comment by palisadoes** [comment]
This is good to see.

Did you fix this?

- https://github.com/PalisadoesFoundation/talawa-api/issues/2109#issuecomment-2028470806

**Comment by AVtheking** [comment]
@palisadoes but the sample data is populating the communtiy data

**Comment by AVtheking** [comment]
image

**Comment by palisadoes** [comment]
Please check whether you can see the Palisadoes Logo on the home screen of the web app after:

1. Loading the sample data
2. Loading the default data

That code was there already and it wasn't working correctly.

**Comment by palisadoes** [comment]
1. I think the best way to handle the logo and urls is to open an issue in Talawa-Admin
2. Please revert any pPalisadoes related URLs and image references you may have added in this PR
3. Otherwise, it's looking good to merge

**Comment by AVtheking** [comment]
I haven't added any url in this.

Will open issue in admin.

**Comment by palisadoes** [comment]
The issue is created already

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
