### PR TITLE
Updated dotenv from version 8.6.0 to 16.3.1

### LINKED ISSUE #1488: Upgrade package `dotenv` from 8.6.0 to 16.3.1
This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1484

However, though the checks passed, this is a major release update and we want to make sure that not just the `pull-request` GitHub actions pass, but also the `push` actions pass too:

Goals:
1. You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
2. Functionality must remain unchanged as a result of completing this issue
3.  The commands in these GitHub action files must pass:
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml
    2. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml 

## Other
- **NOTE:** I’ve stopped assigning people to issues due to the workload, no exceptions. Please watch this video on how to proceed.

[Click me to start video](https://www.youtube.com/watch?v=GlqUm1UO-xM)

### PR DESCRIPTION
**Pull request by RAGHAV-N5**
**What kind of change does this PR introduce?**
Updating version of dotenv from 8.6.0 to 16.3.1

**Issue Number:**

Fixes #1488 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

Screenshot 2023-12-13 173753

**If relevant, did you update the documentation?**

No

**Summary**

Updated the dotenv version from from 8.6.0 to 16.3.1. Since this issue was my first to solve, I had some merge conflicts which I sorted it out and made this new PR . Planning to contribute more to this Repository.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please merge your code with the latest upstream and update this PR with it. We had to revert a previously merged PR

**Comment by RAGHAV-N5** [comment]
Screenshot 2023-12-14 072328

It shows that everything is up-to-date. Please guide me through this if I have done any mistakes and suggest any further steps I have to follow.

**Comment by palisadoes** [comment]
Click on the `details` link and read the error messages carefully. The answer should be there.

**Comment by EshaanAgg** [comment]
Please fix the conflicts.

**Pull request closed without merging**
