### PR TITLE
Tested the push workflow and made the md files mpx compatible

### LINKED ISSUE #1559: Fix Documention Workflow - Talawa-API
## Bug Description
Our automated documentation GitHub action PUSH workflow is failing. 

Under normal operation it:

1. Uses the `typedoc` package to generate documentation
1. Commits any newly changed documentation files to a dedicated documentation directory
1. Copies these files to the Talawa-Docs repository

This process has recently started to fail for both Talawa-API and Talawa Admin. 

1. We are not sure why and it needs to fixed.
1. The workflows help our developers understand the codebase through easily indexed HTML on the docs.talawa.io site

The push workflow files in question are:

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml
- https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/push.yml

Part of the troubleshooting difficulty is that:

1. The two workflows use different package managers (NPX vs Yarn)
1. One workflow uses package caching, while the other doesn’t
1. We are uncertain whether there is an underlying GitHub secret misconfiguration, possibly an expiry.
1. The files produced by the API workflow are compatible, but the Admin files are not. We don't know why. It could be because the API workflow broke before that of Admin, or vice versa.

To complicate matters, we also recently upgraded Talawa-Docs to Docusaurus v3 as the previous version has been deprecated. 

1. Version 3 uses the new MPX standard for markdown files where all `<`, `>`, `{` and `}` characters need to be escaped with a `\` character.
1. More details can be found here https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3

We need the markdown files generated by `typedoc` to be MPX compatible.

## Related difficulties

The non MPX compatible files are causing our Talawa-Docs PRs and pushes to fail. This means that it is difficult for us to update our GSoC ideas page. We have to manually do search and replacement of the incompatible characters.

## Requirements

These are the requirements to fix this issue

1. Get one workflow working
1. Get the other workflow working using the package manager of the first workflow
1. Standardize on a caching mechanism, or none
1. Ideally, use identical standardized workflows with environment variables to differentiate between the repos where necessary
1. The markdown files generated must be MPX compatible using the `npx docusaurus-mdx-checker` command. This may mean finding a typedoc parameter to make the output markdown files MPX compatible or writing a script to do a search and replace operation in the API and Admin documentation directory tree to fix the issue.
1. Create a markdown document describing how the fixed workflow works, including any GitHub configuration parameters, so that our team can use it as a reference. This should be added to Talawa Docs. Please coordinate this activity with the members below.

## Issue assignment
1. We greatly prefer a single person working on the equivalent issue in both repositories. Who ever gets assigned this issue must ask to be assigned to the issue below in the other repository.
    - https://github.com/PalisadoesFoundation/talawa-admin/issues/1279
2. This means we will need to assign the issue to someone who currently has **no assigned issues**

## Additional details
Please work with these contributors who have been focused on this issue for some time

1. @anwersayeed 
2. @tasneemkoushar 

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by adi790uu**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1559 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot 2024-01-31 at 11 06 23 PM

Screenshot 2024-01-31 at 11 07 20 PM

**If relevant, did you update the documentation?**

No

**Summary**

Tested the working of push workflow and integrated a script which make .md files mpx compatible.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by adi790uu** [comment]
The workflow failing is most probably due to expired secrets, they need to be updated.

**Comment by Cioppolo14** [comment]
@adi790uu Please exclude the schema.graphql file.

**Comment by adi790uu** [comment]
@Cioppolo14 when I am commiting the code it is automatically picking up these unneccesary changes.

**Comment by Cioppolo14** [comment]
@adi790uu Ok, I am investigating and I will follow up.

**Comment by adi790uu** [comment]
Hey @Cioppolo14 have you checked on this issue?

**Comment by Cioppolo14** [comment]
@adi790uu Can you use the latest merge and try again?

**Comment by adi790uu** [comment]
Okay @Cioppolo14

**Comment by adi790uu** [comment]
@Cioppolo14 I think its fine now.

**Comment by Cioppolo14** [comment]
@EshaanAgg @xoldyckk Can you review this PR?

**Review by EshaanAgg — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
