### PR TITLE
Removed package easygraphql-tester

### LINKED ISSUE #707: Upgrade Lodash to version 4.17.21
Our current version of the `easygraphql-tester` package is at v5.1.6. It requires a vulnerable version of lodash.

We need to fix this vulnerability so that both packages are upgraded appropriately.

image

### PR DESCRIPTION
**Pull request by xoldyckk**
Removed the package named easygraphql-tester

**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #707

**Did you add tests for your changes?**

-

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

-

**Summary**

Removed the package named easygraphql-tester because it was not being used anywhere in the app and had a security vulnerability.

**Does this PR introduce a breaking change?**

No

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests.

**Comment by xoldyckk** [comment]
The mongodb test database seems to be not working.

**Comment by xoldyckk** [comment]
Maybe re-run the tests

**Comment by xoldyckk** [comment]
@palisadoes please take a look at the error. It's caused on your part. It's not being caused because of the pull request.

**Comment by palisadoes** [comment]
I added detailed debugging and got this output.

The GitHub action is waiting 32s for Mongo to start before failing. I think the [parameters need to expanded](https://stackoverflow.com/questions/66317184/github-actions-cannot-connect-to-mongodb-service). The example we have is taken from StackOverflow, but doesn't seem to be sufficient now.

I'll increase the retries parameter and see whether that helps.

```
1m 15s
##[debug]Evaluating condition for step: 'Initialize containers'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Initialize containers
##[debug]Register post job cleanup for stopping/deleting containers.
Checking docker version
Clean up resources from previous jobs
Create local container network
Starting mongo service container
Waiting for all services to be ready
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  starting
  mongo service is starting, waiting 2 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  starting
  mongo service is starting, waiting 4 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  starting
  mongo service is starting, waiting 7 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  starting
  mongo service is starting, waiting 13 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  starting
  mongo service is starting, waiting 32 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 3cb65093d805f49eb3f7336c98f5cbc3a49b5131fcd946110019853a45b72fc4
  unhealthy
  Error: Failed to initialize, mongo service is unhealthy.
  ##[debug]System.InvalidOperationException: Failed to initialize, mongo service is unhealthy.
  ##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.ContainerHealthcheck(IExecutionContext executionContext, ContainerInfo container)
  ##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
  ##[debug]   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
  ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
  ##[debug]Finishing: Initialize containers
```

**Comment by palisadoes** [comment]
@xoldyckk Increasing the timers worked.

The low level of code coverage is causing the failures now. [Please review and fix](https://github.com/PalisadoesFoundation/talawa-api/runs/8171960367?check_suite_focus=true).

**Comment by xoldyckk** [comment]
@palisadoes still not fixed

**Comment by palisadoes** [comment]
@JamaicanFriedChicken is looking into it

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
