### PR TITLE
getSort() helper funtion

### LINKED ISSUE #994: Feature Request: Using helper functions for queries
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
The `getSort()` function is poorly reused where each file uses the same implementation of the function but it has been compy pasted multiple times. 

Every other query has its own getSort() function with an almost identical  implemntation.
**Describe the solution you'd like**
I proposed the use of helper_function directory so that the function will have its own file and will be reused by everywhere it is defined.
**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.
create `src/reolvers/Query/helper_functions` which will contain a `getSort.ts` file whichi will export the sorting implementation used by all the queries.The files with queries which are using this getSort function will then import this helper function and then appy when it is needed. 
**Additional context**

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #994 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
The error is due the uploadImage.spec.ts file , a file which I had written . It is failing because the directory structure for the testing application in the github CI-CD was changed.

**Comment by xoldyckk** [comment]
@kb-0311 in uploadImage.ts change
    ```
    path.join(__dirname, "../images", `/${id}-${filename}`)
    ```
to
    ```
    path.join(__dirname, "../../images", `/${id}-${filename}`)
    ```

Similarly update uploadImage.spec.ts as well.

**Comment by kb-0311** [comment]
@xoldyckk why the parsing error?

**Comment by palisadoes** [comment]
@kb-0311 Please fix the failing test: https://github.com/PalisadoesFoundation/talawa-api/actions/runs/4092296399/jobs/7057141172#step:7:277

This may be due to a past PR. I've noticed it happening occasionally. We now have an example of it happening and rather than re-running the GitHub action, we need to fix it.

**Comment by kb-0311** [comment]
@palisadoes Hmm , Sorry but CI-CD is not something I am familiar with as of now, I rectified the testing unhandled errors and got the tests to run however there is some 'parsing error' that I do not seem to understand. Maybe someone who is more experienced with CI-CD can help us out here?

**Comment by kb-0311** [comment]
it seems #997 us failing for the same reason too

**Comment by kb-0311** [comment]
https://github.com/VeryGoodOpenSource/very_good_coverage/issues/77

Maybe this is helpful ?

**Comment by EshaanAgg** [comment]
@kb-0311 A minor suggestion, you can consider rewriting all the branches in `getSort.ts` using `switch` statements rather than multiple if-else. They make for a better reading and debugging experience.
Another approach might be to split the `orderBy` variable on `_` and then use the first part as the property name, and the second to determine the value of 1/-1. That would make for the most concise code.

**Comment by noman2002** [comment]
> it seems #997 is failing for the same reason too

it is not failing now. There is some other issue in this PR. please have look.

**Comment by EshaanAgg** [comment]
> This may be due to a past PR. I've noticed it happening occasionally. We now have an example of it happening and rather than re-running the GitHub action, we need to fix it.

I can think of two ways of doing so.
1. We can change our provider for this GitHub action as we are having troubles with it. [I had previously used [this](https://github.com/barecheck/code-coverage-action) action for a project. The downside to this is obviously that these actions are way less active that our current provider.

2. In light of this [comment](https://github.com/VeryGoodOpenSource/very_good_coverage/issues/77#issuecomment-1196028216), we can add a command `[ -f ./coverage/lcov.info ] && echo "Coverage file exists" || echo "Coverage does not exist"  ` before the `VeryGoodOpenSource/very_good_coverage@v2` action to ensure that our coverage file is indeed existing before this step. If not, we can then be certain that the error is in one of the earlier testing steps, as they aren't generating the coverage file as they should.

**Comment by kb-0311** [comment]
@palisadoes @noman2002 Tests are passed now, it was because the lcov file was not being properly generated earlier due to a mistake from my part how ever it is good now.

@EshaanAgg The tests are passed now , it was because of faulty vite.config change on my part. Yeah I was going to go for switch-case approach yesterday itself before my priority was to make the tests pass. I will be making the change now.

Sorry about that .

**Review by xoldyckk — COMMENTED** [review]
You should never use `any` keyword in typescript unless you absolutely have to. Add types to `getSort` helper function parameter `orderBy`. Copy paste this in place of `any`:- 
```
| InputMaybe<
        | EventOrderByInput
        | OrganizationOrderByInput
        | PostOrderByInput
        | TaskOrderByInput
        | UserOrderByInput
      >
    | undefined
```
You also need to test the `getSort` function.

Rename `helper_funtions` folder to `helperFunctions`. Always use camelCase or PascalCase for naming stuff in javsacript/typescript code because it is the industry convention.

**Comment by kb-0311** [comment]
@xoldyckk Yep added the types and naming convention you requested. 

The getSort() helper function already has 100% test coverage because it is tested by all the other queries which uses that helper.

**Review by xoldyckk — APPROVED** [review]
@kb-0311 Looks good.

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
