### PR TITLE
addTest/directChatsByUserID.js/issue#581

### LINKED ISSUE #581: Resolvers: Create tests for directChatsByUserID.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/resolvers/direct_chat_query/directChatsByUserID.js`

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/direct_chat_query/directChatsByUserID.spec.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/direct_chat_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

Adds test file for directChatsByUserID.js file.

**Issue Number:**

Fixes #581

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

Screenshot from 2022-03-24 00-36-29

**If relevant, did you update the documentation?**

No

**Summary**

Added test for directChatsByUserID.js file increasing test code coverage across talawa-api.

**Does this PR introduce a breaking change?**

No

**Other information**

Code coverage is not 100% because the error check in directChatsByUserID.js file never gets triggered. It can't be tested. Resolver's code needs to be refactored to have 100% code coverage.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please try to get the code coverage to 100% for `directChatsByUserID.js`. Almost there.

**Comment by xoldyckk** [comment]
> Please try to get the code coverage to 100% for `directChatsByUserID.js`. Almost there.

The remaining code cannot be tested because it never will never be triggered. The `if` condition inside the resolver always evaluates to false. Even when no directChats are found, value of `directChatsFound` will be an empty array and `if ( ![ ] ) { ...some code here }` will evaluate to false as well. So, the code needs to be refactored for `if` condition to trigger.

**Comment by xoldyckk** [comment]
**Snapshots/Videos:**

Screenshot from 2022-03-25 08-04-12

**Comment by JamaicanFriedChicken** [comment]
@xoldyckk for the code you've refactored, have you tested to see if it'll throw an error if no `directChatsFound` was found and if it was found? Mind sharing a screenshot/video of that?

**Comment by xoldyckk** [comment]
> @xoldyckk for the code you've refactored, did you run the app to see if it'll throw an error if no `directChatsFound` was found and if it was found? Mind sharing a screenshot/video of that?

**Response for a random mongodb objectId:**

Screenshot from 2022-03-25 08-48-18

**Review by JamaicanFriedChicken — APPROVED** [review]
Looks good

**Comment by palisadoes** [comment]
Please fix the failing tests: https://github.com/PalisadoesFoundation/talawa-api/runs/5687442582?check_suite_focus=true

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing tests: https://github.com/PalisadoesFoundation/talawa-api/runs/5687442582?check_suite_focus=true

**Comment by xoldyckk** [comment]
> Please fix the failing tests: https://github.com/PalisadoesFoundation/talawa-api/runs/5687442582?check_suite_focus=true

Why is this test running on the old directChatsByUserID.spec.js? I updated the test file. Here :- https://github.com/PalisadoesFoundation/talawa-api/pull/632/commits/9e693de823be502a3c24ad3b0338bb950f576057

**Comment by xoldyckk** [comment]
Should I close this pull request and make a new one?

**Comment by palisadoes** [comment]
Yes. That would be best.

**Pull request closed without merging**
