### PR TITLE
Remove unused files and packages leading to deprecated warning

### LINKED ISSUE #1517: Upgrade package `uuid`
**Describe the bug**
When installing the application we get this error on the console

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

The package needs to be upgraded

**To Reproduce**
- Run the `npm install` command

**Expected behavior**
1. The error message goes away after the upgrade. No error message must be suppressed
    1. Other dependencies on this package need to be upgraded as recommended by their package maintainers
    2. Deprecated packages depending on this package will need to be replaced with currently maintained equivalents.
    3. Package updates must only be applied to the `package.json` file
1. You may need to update the code base to reflect the updated and/or replaced packages
1. All PR tests pass
1. No functionality is affected by the change
1. You must verify whether the package is still used at all and if not, remove it from any configuration files

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranshugupta54**
**What kind of change does this PR introduce?**

Removed files related to `image-hash` and `pm2` to fix deprecated `uuid@3.4.0`

**Issue Number:**

Fixes #1517 

**Does this PR introduce a breaking change?**

Should try uploading same image for multiple user accounts for testing it once.
- [x] Already tested though

## Note:
I'm not familiar with Talawa App, please make sure to test changing images for user and organisations once

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. You have removed organization an user image functionality.
2. Have you checked whether these changes will affect the ability of users to change their profile pictures and organizations to change their thumbnail image in the Admin organizations screen?

This PR seems to be negatively affecting the end user experience and will cause the API clients to break

**Comment by pranshugupta54** [comment]
> 1. You have removed organization an user image functionality.
> 2. Have you checked whether these changes will affect the ability of users to change their profile pictures and organizations to change their thumbnail image in the Admin organizations screen?
> 
> This PR seems to be negatively affecting the end user experience and will cause the API clients to break

@palisadoes, these files are not being used.
I've tried changing image for the organisation and also for users
https://www.loom.com/share/bff223e2b50344afbadad024ca2d240a?sid=94774c63-7279-4a73-a317-f9edeee47a0c

**Comment by pranshugupta54** [comment]
Files from `src/utilities/encodedImageStorage` are being used for this.

image

**Comment by palisadoes** [comment]
> Files from `src/utilities/encodedImageStorage` are being used for this.
> image

Thanks

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Cioppolo14** [comment]
@pranshugupta54 It looks like there are still some failing tests.  Let us know when its ready.

**Review by varshith257 — CHANGES_REQUESTED** [review]
@pranshugupta54  Can I know why you removed pm2?

As pm2 is an important process manager for talawa-api production environment which facilitates built in load-balancing,logging, provide 24/7 no downtime for applications and various facilities for prod env setup.

**Comment by pranshugupta54** [comment]
> @pranshugupta54 Can I know why you removed pm2?
> 
> As pm2 is an important process manager for talawa-api production environment which facilitates built in load-balancing,logging, provide 24/7 no downtime for applications and various facilities for prod env setup.

@varshith257, Oh, wasn't sure about production, didn't find it getting imported anywhere.
If we have to use `pm2` for production then we'll get the `uuid` deprecated warning _until pm2 fixes it_

**Comment by pranshugupta54** [comment]
`pm` indirectly depends on `uuid@3.4.0` 
image

**Comment by varshith257** [comment]
> `pm` indirectly depends on `uuid@3.4.0` image

I have found many reporting about this issue in the package repo of pm2 
https://github.com/Unitech/pm2/issues/5733

@xoldyckk Can we use pm2 ignoring the deprecated warning of uuid which hasn't been solved for almost 2+ years of the same issue?
OR
Can we use pm2 alternatives but none of the alternatives provide features of pm2 such as load-balancing , no downtime etc....
https://nodejs.libhunt.com/pm2-alternatives

**Comment by pranshugupta54** [comment]
_Opinion:_ In my view, as I've removed `image-hash` and `pm2` and found that everything operates smoothly, it indicates that we're not directly relying on 'uuid' for any system function. Therefore, we can confidently continue using it despite its deprecation.

**Comment by xoldyckk** [comment]
if talawa-api is to be deployed using docker containers pm2 is useless

**Comment by varshith257** [comment]
@guptapriyanshu7 Keep the package pm2 for as now let us leave the deprecation warnings related to packages of pm2. If it solved in newer version it will be fine or else let investigate to use another in future

**Comment by Olatade** [comment]
@pranshugupta54, please update your branch with the latest changes in the develop branch  and try to fix the failing tests

**Comment by pranshugupta54** [comment]
Hey @Olatade, updated the PR.

The test is failing due to some env issue of the repo. It passes well on my local setup.
Other failed actions -> counting file limit (maybe bcuz this PR has 21 file changes)
-> File change not allowed - not sure which file? maybe a whitespace due to prettier in yml file?
image

**Comment by pranshugupta54** [comment]
> @pranshugupta54 Keep the package pm2 for as now let us leave the deprecation warnings related to packages of pm2. If it solved in newer version it will be fine or else let investigate to use another in future

Hey @varshith257, I've added `pm2` back and only removed `image-hash`

**Comment by pranshugupta54** [comment]
Not sure why it's giving some env issue
image

**Comment by palisadoes** [comment]
Merge your code with the latest upstream. The replica set detection issue should have been resolved

**Comment by pranshugupta54** [comment]
> Merge your code with the latest upstream. The replica set detection issue should have been resolved

@palisadoes, it's already up to date

**Comment by palisadoes** [comment]
This replica set error isn't happening in other PRs

The PR tests against a local instance. Are you testing against a cloud instance on your local system?

**Comment by pranshugupta54** [comment]
> This replica set error isn't happening in other PRs
> 
> The PR tests against a local instance. Are you testing against a cloud instance on your local system?


@palisadoes, other pull requests are encountering the same problem with the replica set error, but their tests are still passing. When you look at the tests for those other pull requests, you'll see that they also show the replica error in the logs, but the tests still pass. I think there might be another issue causing this pull request to fail. I'm trying to figure it out, but everything seems to work fine when I run the tests on my computer, and I'm not using cloud instance.

**Comment by varshith257** [comment]
@pranshugupta54  I think you have connected to local instance of MongoDB using mongo Compass. Switch to replica set using mongo atlas.
If you need step by step guidance you can follow this: 
[https://www.mongodb.com/docs/compass/current/connect/](url)

**Comment by pranshugupta54** [comment]
@varshith257, the failing test shows the env which uses localhost 🤔

**Comment by pranshugupta54** [comment]
Failing test's env:
image

**Comment by pranshugupta54** [comment]
Test passed on another PR with same error - [here](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8198855748/job/22423057194?pr=1956)


image

**Comment by varshith257** [comment]
> @varshith257, the failing test shows the env which uses localhost 🤔

Switch to replica set. It should resolve the above problem. Get ahead to mongo atlas and create a cluster and copy connection string for use of mongo-compass and use that string in mongo atlas to create a new connection in mongoDB comopass and connect it .

**Comment by pranshugupta54** [comment]
> > @varshith257, the failing test shows the env which uses localhost 🤔
> 
> Switch to replica set. It should resolve the above problem. Get ahead to mongo atlas and create a cluster and copy connection string for use of mongo-compass and use that string in mongo atlas to create a new connection in mongoDB comopass and connect it .

Connecting to a mongodb atlast won't do anything as i'll be adding it on my local, so there will be no change on Github Action test

**Comment by pranshugupta54** [comment]
> Test passed on another PR with same error - [here](https://github.com/PalisadoesFoundation/talawa-api/actions/runs/8198855748/job/22423057194?pr=1956)
> 
> image
How is this PR passing with replica set error

**Comment by varshith257** [comment]
@pranshugupta54 Got it. I haver observed the behaviour of it. Let me update you on this

**Comment by varshith257** [comment]
@pranshugupta54 I have seen the related changes you made to remove image-hash instead it using encodedImageStorage.

1. You have made changes related to organization image functionality to use encodedImageStorage but you have also deleted the user image functionality instead of modifications.
2. IMO the image functionality for the user has been dropped. Can you test the image functionality of the user and submit a video as you have done for the org image functionality?

**Comment by pranshugupta54** [comment]
@varshith257, 
User profile: https://www.loom.com/share/9f55534d77f245a58f8273a3a9ecb840?sid=a6b066b6-fbad-4fb7-9076-a7a75971356f
Admin profile: https://www.loom.com/share/e6a9e594780c492dbc795f74f018be5e?sid=8820e57c-c0fb-44d1-b82e-a9e60ca433bf

**Comment by pranshugupta54** [comment]
@varshith257, it fails on 1 test of fundraising, though this PR has no file changes related to it
image

**Comment by pranshugupta54** [comment]
It's so confusing now, when i try to test particular file then it passes all

image
image

**Comment by pranshugupta54** [comment]
Hey @palisadoes / @Cioppolo14 / @xoldyckk , is there anything else needed here?

**Comment by Olatade** [comment]
@pranshugupta54 please can you update your branch, it is currently out of date with the develop branch

**Comment by pranshugupta54** [comment]
Hey @Olatade, updated 👍

**Review by varshith257 — APPROVED** [review]
LGTM

**Review by varshith257 — CHANGES_REQUESTED** [review]
```
> talawa-api@1.0.0 format:check
> prettier --check "**/*.{ts,tsx,json,scss,css}"

Checking formatting...
[warn] src/utilities/index.ts
[warn] Code style issues found in the above file. Run Prettier to fix.
Error: Process completed with exit code 1.
```

fix this only it is stopper to pass the all tests
Run Prettier to fix this to src/utilities/index.ts

**Comment by pranshugupta54** [comment]
Fixed it. 
(Didn't add an empty line at the end 😃)

**Comment by palisadoes** [comment]
Please ask the `#talawa-api` slack community

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@pranshugupta54 Please fix the conflicting files and failed tests.

**Comment by pranshugupta54** [comment]
Now, the issue requires too many other packages to be removed too for fixing the deprecated packages.

**Pull request closed without merging**
