### PR TITLE
#1415 feature request deleting advertisements

### LINKED ISSUE #1415: Feature Request: Delete ads mutation is talawa API
**Describe the solution you'd like**
I would like the "Delete Advertisement" GraphQL Mutation to be fixed and fully functional. When invoking this mutation, it should successfully remove the specified advertisement data from the database, ensuring that the deletion operation is completed accurately and promptly.

**Describe alternatives you've considered**
One alternative solution could be implementing a different GraphQL mutation endpoint specifically for advertisement deletion. Another approach could involve thoroughly reviewing the existing codebase to identify any potential issues or bugs causing the deletion operation to fail.

**Approach to be followed (optional)**
I recommend conducting a comprehensive code review of the current implementation to identify any logical or syntactical errors. Additionally, testing the mutation with various input scenarios and edge cases can help ensure its robustness. If necessary, consult relevant GraphQL documentation to confirm the correct syntax and usage for the deletion operation.

**Additional context**
Currently, the malfunctioning "Delete Advertisement" GraphQL Mutation impacts the overall functionality of the Talawa API. Fixing this issue is crucial for maintaining the integrity of the platform and providing users with a seamless experience. Any additional information, error messages, or debugging details related to this problem can be provided upon request.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
Deleting advertisement in api

**Issue Number:**

Fixes #1415

**Did you add tests for your changes?**

**Snapshots/Videos:**

 #### Youtube video ⬇️ 

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=Pu01_0fdqfc)
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=Pu01_0fdqfc)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by tasneemkoushar — APPROVED** [review]

**Comment by tasneemkoushar** [comment]
@SiddheshKukade Please resolve the failing test, and all lines of some code files aren't covered in tests.

**Comment by SiddheshKukade** [comment]
@tasneemkoushar yes, now I've added the tests for the files that I've changed in the PR. @palisadoes please merge.

**Comment by palisadoes** [comment]
@SiddheshKukade Tests are failing. Please fix.

**Comment by SiddheshKukade** [comment]
@palisadoes fixed them.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
