### PR TITLE
Added tests for missing lines

### LINKED ISSUE #1420: Some files have lines that are not covered in testing
**Describe the bug**
There are several files with lines that are not covered in testing which is reducing the code coverage and also some indirect changes are causing PR's codecov report to fail.

**Files which I will be covering in this issue**

1. src\resolvers\middleware\currentUserExists.ts
2. src\resolvers\Mutation\createMember.ts
3. src\resolvers\Mutation\createPost.ts
4. src\resolvers\Mutation\updatePost.ts
5. src\resolvers\Query\helperFunctions\getWhere.ts
6. src\utilities\encodedImageStorage\uploadEncodedImage.ts
7. src\utilities\encodedVideoStorage\uploadEncodedVideo.ts

**Expected behavior**
All lines in these files should be covered.

**Actual behavior**
Some lines are not covered in testing

### PR DESCRIPTION
**Pull request by nitishkumar333**
**What kind of change does this PR introduce?**

Fixes #1420 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**
N/A

**Summary**
Added tests to cover the missing lines.

### CODE REVIEW

**Comment by nitishkumar333** [comment]
working to fix the errors

**Comment by nitishkumar333** [comment]
@palisadoes I wrote some tests that should have increased the coverage ( which it does in my local machine when tested using npm run test )

Report is comparing to 34 commits behind head, which I think is the reason for code coverage not increasing.

**Comment by Ayush0Chaudhary** [comment]
@EshaanAgg @aashimawadhwa please review the PR.

**Comment by noman2002** [comment]
@nitishkumar333 Please fix the conflicting files.

**Comment by nitishkumar333** [comment]
@palisadoes @tasneemkoushar  Merging of #1412 has caused this PR to fail with 944 warnings. All upcoming PRs will continue to fail until all 900+ warnings are resolved. So, I think that PR should be reverted.

**Comment by palisadoes** [comment]
Rather than reverting the entire PR (because there was some good looking work done) we could just revert the changes to the eslint file. @tasneemkoushar and I are discussing the next steps

**Comment by tasneemkoushar** [comment]
@nitishkumar333 have made changes to the linting rules. Now it will throw `warn` not the `error`. Make sure to resolve the lint warning related to your code changes.

**Comment by nitishkumar333** [comment]
@tasneemkoushar we will still need to resolve all 900+ warnings so that all upcoming PRs don't fail.

This is because we are using "--max-warnings=0" in npm run lint:check command.

**Comment by tasneemkoushar** [comment]
@nitishkumar333 I have increased that from `max 0 to 1500`, now till the warnings are resolved we can make sure upcoming PRs don't fail for that.

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
