### PR TITLE
Refactor: Advertisement functionality

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
Refactoring

**Issue Number:**

Fixes #1585
This PR fixes the issues identified in https://github.com/PalisadoesFoundation/talawa-api/pull/1585.

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**
This PR address the issues identified in https://github.com/PalisadoesFoundation/talawa-api/pull/1585

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
What's the issue for this, or else we'll need to close it.

**Comment by disha1202** [comment]
> What's the issue for this, or else we'll need to close it.

Hi @palisadoes, This PR is extension of https://github.com/PalisadoesFoundation/talawa-api/pull/1585 which was merged.

Do I need to create an issue for this?

**Comment by palisadoes** [comment]
Please update the first comment's template so there is an easy reference.

**Comment by disha1202** [comment]
Hi @xoldyckk 

I have made the requested changes on https://github.com/PalisadoesFoundation/talawa-api/pull/1585

Please take a look.

**Comment by sumitra19jha** [comment]
Please merge the develop branch changes

**Comment by palisadoes** [comment]
@disha1202 

Is this test for review? There have been frequent recent updates

**Comment by disha1202** [comment]
> @disha1202
> 
> Is this test for review? There have been frequent recent updates

Yes, this PR is ready for review. I have also tested the changes.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
