### PR TITLE
Enhance Token Management: Refresh Token Handling and Database Integration

### LINKED ISSUE #1419: Issue with implementing token refresh functionality
**Describe the bug**
Currently, the talawa-api lacks the functionality to handle token refresh using the provided refreshToken. The missing functionalities include but are not limited to saving the refreshed tokens in the database, revoking tokens after single use, and implementing security measures for secure token exchange.

**To Reproduce**

1. Login a user.
2. Check the database if the refresh token has been stored in user document (it is not getting stored now).
3. Let the user get logged out automatically after the access token has expired.
4. Check if a new refresh and access token is generated and set to the user.

**Expected behavior**
1. Save refreshed tokens in the database.
2. Revoke used tokens after a single exchange.
3. Send the newly generated access token and refresh token to the user.

**Actual behavior**
The talawa-api code currently lacks the aforementioned functionalities for token refresh, leading to an inability to perform the intended token exchange.

**Screenshots**
N/A

**Additional details**
The token refresh functionality in the talawa-api is partially implemented but lacks the final steps for saving tokens in the database, revocation after single use, and implementing essential security measures.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Bug fix

**Issue Number:**

Fixes #1419

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

Yes

**Summary**

Currently, the talawa-api lacks the functionality to handle token refresh using the provided refreshToken. The missing functionalities include but are not limited to saving the refreshed tokens in the database, revoking tokens after single use, and implementing security measures for secure token exchange.

To resolve the above mentioned issues this PR implements:
* saving the refreshed tokens in the database
* revoking the used tokens after a single exchange
* sending the newly generated access token and refresh token to the user

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by chandel-aman** [comment]
@palisadoes @kb-0311 
Can you brief me on why these checks are failing?

**Comment by noman2002** [comment]
@chandel-aman your commit contains linting errors and unauthorised file changes. Thats why its failing.

**Comment by palisadoes** [comment]
1. @chandel-aman We have checks to make sure that certain sensitive files aren't modified unintentionally. `.env.sample` is one of them. It is necessary in this case. Why have you set the default to development? We will soon be making the master branch the default.
2. Please also lint your code.

**Comment by palisadoes** [comment]
1. Update `INSTALLATION.md` with this information too.
2. Make the `env.sample` file default to `production`. We will soon be making the `master` branch the default branch

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Update `INSTALLATION.md` with this information too.
2. Make the `env.sample` file default to `production`. We will soon be making the `master` branch the default branch

**Comment by chandel-aman** [comment]
> 1. Update `INSTALLATION.md` with this information too.
> 
>     2. Make the `env.sample` file default to `production`. We will soon be making the `master` branch the default branch

@palisadoes 
I've updated the `INSTALLATION.md` as well as `env.sample`, where I've changed the `development` to `production` and have documented the same in the `INSTALLATION.md`

**Screenshots**

image
image
image

And regarding the linting errors, I've fixed those occurring in the files which were created or in which the changes were made for this PR.
There are 900+ linting problems which were not caused due to any changes made for this implementation.
So, do I also need to fix them first?
image

**Comment by palisadoes** [comment]
@tasneemkoushar has been working on issues to eliminate those linting errors. She'll have more to say in her review. Eventually we will be failing vs warning on linting.

**Comment by tasneemkoushar** [comment]
@chandel-aman This lint check will fail since the codebase had 886 lint errors. You just make sure all the lint warning related to your issue gets resolved.

**Comment by chandel-aman** [comment]
@tasneemkoushar Thanks for you feedback. I've already fixed and reviewed any linting warnings related to this PR please let me know if there're any other errors or updates that needs to be addressed.

**Review by tasneemkoushar — APPROVED** [review]

**Pull request merged**
