### PR TITLE
tests for tests/utilities/reuploadDuplicateCheck.spec.ts

### LINKED ISSUE #887: Test: src/lib/utilities/reuploadDuplicateCheck.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/utilities/reuploadDuplicateCheck.ts`
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/utilities/reuploadDuplicateCheck.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #887

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

No.
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
Same issue as #795 so after this one is merged pls close that issue also

**Comment by kb-0311** [comment]
I don't understand why the test is failing even though it was passing just a few minutes ago? @palisadoes

**Comment by kb-0311** [comment]
could you rerun the tests?

**Comment by kb-0311** [comment]
````
Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```
Is the error

**Comment by kb-0311** [comment]
For whatever reason codecov is not not loading,
could you pls look into that ?

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@noman2002 Please review and merge if OK

**Review by noman2002 — APPROVED** [review]

**Comment by noman2002** [comment]
> @noman2002 Please review and merge if OK

Don't have access to merge.

**Pull request merged**
