### PR TITLE
Postimage

### LINKED ISSUE #1258: Add image upload in updatePost mutation
**Describe the bug**
Currently, there is no implementation of image upload in the updatePost mutation due to which the images are not getting updated.

Issue - https://github.com/PalisadoesFoundation/talawa-admin/issues/844
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akankshat05**
**What kind of change does this PR introduce?**

Bugfix
**Issue Number:**

Fixes #1258 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
No

**Summary**

**Other information**

Screenshot_2

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by xoldyckk** [comment]
@kb-0311 what do u think? If this keeps up all the implementation on client side for images uploads will be coupled to the hacky approach. 

What if they start implementing the video upload the same way. Should we reject the PRs?

**Comment by kb-0311** [comment]
@xoldyckk @akankshat05 You can refer to this comment in the future for  general Issues regarding file uploads.

Yes, I do think generally at this time interval PRs regarding image/file uploads are generally pointless. unless they are discussing a long-term solution with a good high level approach taking in mind the differing file sizes and formats + multi tenant architecture + compression within the api server filesystem as @palisadoes had said that the files will need to be stored within the api server.

The reason for the hacky solution was an upsurge of client side cnotributors for outreachy suring which peter had asked me to atleast make the image uploads funcitonal by encoding so that the admin portal contributors have something to work with. Now that it is not the case I don't think we should rely on that encoding function anymore instead we should think of a more scalable long-term approach.

Why Encoding files is a bad idea->
https://github.com/PalisadoesFoundation/talawa-api/pull/956#issuecomment-1410244587

A better approach is to make use of `File` scalar in yoga or `Upload` scalar in apollo. Or only sending the metadata in graphql layer and actual content of the file through a separate service other than graphql layer(But I have not thought about this in detail). Why I could not do that at that time ->
https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1434149051


@akankshat05 Also I was thinking about implementing that function in updatePost too when I was implementing the entire encoded image thingy.
 Instagram does not allow any sort of updatetion on the image only caption and tags whereas Facebook does allow it. 
However, this is not the approach most platforms use for "updating" images in posts where uploading a new image directly overrides the previous one. You have to manually remove that picture (think of the small cross button on Slack/Facebook) and add a new one manually (unlike profile pics). And I am not even getting into multiple images yet.
This was my thought process for not implementing for updatePost whereas other mutations have it. It was not an overlooking mistake, it was because of business logic ambiguity.

**Comment by palisadoes** [comment]
I asked about encoding as a hashing method to see how we could deduplicate uploaded files.

The intention wasn't to store the files as encoded data. I decided not to be more thorough in my questioning because I wanted a quick solution, the thread was becoming very long, and there was so much related Talawa activity at the time. We all knew it could have been done better, but expediency had to take priority. I should have emphasized hashing more too.

If there is a better simple intermediate fix, we should consider it. If I remember correctly, the current solution cannot handle video.

**Comment by kb-0311** [comment]
@palisadoes Yeah, true. As I said A better solution for files would be a multipart form format which is the intermediate fix. Then comes the hashing and duplicate uploads checking 

>A better approach is to make use of File scalar in yoga or Upload scalar in apollo. Or only sending the metadata in graphql layer and actual content of the file through a separate service other than graphql layer(But I have not thought about this in detail). Why I could not do that at that time ->
https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1434149051

Ofc that can only be done after yoga migration which I was taking look into Eshaans branch but it will take a lot of consistent time and my end sem exams are starting again and will end on 10th may. So will go into that full throttle.

**Comment by palisadoes** [comment]
Closing this and the issue until we have a permanent image upload solution.

**Pull request closed without merging**
