### PR TITLE
Test for src/lib/resolvers/Mutation/addOrganizationImage.ts

### LINKED ISSUE #910: Test: src/lib/resolvers/Mutation/addOrganizationImage.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

- Tests need to be written for file `src/lib/resolvers/Mutation/addOrganizationImage.ts `
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `__tests__/resolvers/Mutation/addOrganizationImage.spec.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by nishant3721**
**What kind of change does this PR introduce?**

Test

**Issue Number:**

Fixes #910 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

Not relevant

**Does this PR introduce a breaking change?**

No

**Other information**

Not required

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please try to get the code coverage to 100% for addOrganizationImage.ts its currentry at 92%

**Comment by nishant3721** [comment]
@noman2002 code coverage is now 100%

image

**Comment by nishant3721** [comment]
> Please try to get the code coverage to 100% for addOrganizationImage.ts its currentry at 92.85%

code coverage is 100% now

**Review by noman2002 — APPROVED** [review]

**Comment by nishant3721** [comment]
@palisadoes please review it now

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
Please get your branch current in terms of commits. It'll make our PR evaluation work easier.

```
git fetch upstream
git reset upstream/develop --hard 
git push origin develop --force
```

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
