### PR TITLE
Minor bug fixes which include undeclared variables, unused variables and invalid imports etc

### LINKED ISSUE #157: [Bug] Wrong import path name
In `resolvers/template.js` the import path of `authCheck.js` is wrong. I am attaching the screenshot of the same

It should be 
```js
const authCheck = require("./functions/authCheck");
```
instead of 
```js
const authCheck = require("../functions/authCheck");
```
@Sagar2366 Can you assign me this issue?

### PR DESCRIPTION
**Pull request by gauravdas014**
## Fixes #157 
In this PR, I removed the unused variables, defined the undefined variables wherever required, and resolved invalid imports.

### CODE REVIEW

**Comment by Sagar2366** [comment]
All checks are failed. Have you pulled latest master code ?

**Comment by gauravdas014** [comment]
> All checks are failed. Have you pulled the latest master code?

Three tests are failing. I think, some PRs were merged after I pulled the changes. Fixing the error, will push once all the checks pass.

**Comment by gauravdas014** [comment]
@Sagar2366 You can review the pr now.

**Comment by gauravdas014** [comment]
@Sagar2366 There is a depreciation warning for using ` useFindAndModify: true` instead of ` useFindAndModify: false`. I did not include this in the PR as a PR was already given for the same. Apart from this warning, I don't see any other warnings as of now.

**Comment by Laurell876** [comment]
@gauravdas014 change the target branch to develop

**Comment by gauravdas014** [comment]
@Laurell876 I have changed it.

**Pull request merged**
