### PR TITLE
Encode image Solution

### LINKED ISSUE #1111: Completing the Upload Encoded Image Utility
**Describe the bug**
Now that there has been no breaking change for create organization image , this solution can be applied everywhere.
This PR will introduce the following change:
1. Optimise the reupload logic for multiple reuploads , 
2. Delete Image Function
3. Apply upload Image function wherever necessary.
4. Add the tests for 2. and 3.

**To Reproduce**

1. Try to delete an image or upload an image in any other pop up beside create org 
2. The server hangs
3. Because the uploadEncodedImage is not implemented yet.
4.  

**Expected behavior**
There should be a clear logic to delete images in the FS.
There should be the ability to upload images from the talawa-admin portal and mobile app.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
This PR will introduce the following change:

Optimise the reupload logic for multiple reuploads ,
Delete Image Function
Apply upload Image function wherever necessary.
Add the tests for 2. and 3.

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1111

**Did you add tests for your changes?**

Partially.
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by kb-0311** [comment]
The tests for this changes have been implemented , right now only the unit tests are remaining for this PR. It was getting late so gonna do that first thing tomorrow morning along with implementing this change in admin app.

**Comment by Kevoniat** [comment]
@kb-0311  can you bring up the testing coverage, mainly the one that says 18%

**Comment by kb-0311** [comment]
@palisadoes @Kevoniat yep, tests added !

**Comment by palisadoes** [comment]
Is it ready for review now?

**Comment by palisadoes** [comment]
Almost there. Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by kb-0311** [comment]
@palisadoes aah okay got the problem, fixed it. The tests should pass now.

**Comment by palisadoes** [comment]
1. @xoldyckk
1. @JamaicanFriedChicken
1. @Kevoniat
1. @Tajcore
1. @DMills27
1. @noman2002

Please review this PR. It fixes broken image uploading in the API. It is a blocking PR for improvement work in all repositories involving any type of uploading

**Comment by kb-0311** [comment]
@palisadoes Because the file uploading logic was never implemented on the client-side app, this is not a breaking PR. So it does not require its sister PRs in the client apps to be merged, before.

The manual thorough testing would be required when implementing it in the client-side apps but fortunately, I had added this function for creating organization and @rishav-jha-mech had added it on the admin project and it worked well so that process for admin project I have made sure would be easy too.

I will be creating its sister issues and coordinating with other contributors after lunch (just timezones things).

**Comment by palisadoes** [comment]
Thanks. It's broken in the sense that it's preventing the correction of image functionality that should have been there all along.

**Comment by xoldyckk** [comment]
@kb-0311 So, that thing about storing base64 encoded images in database, you're doing it for every resolver that needs image upload functionality?

**Comment by kb-0311** [comment]
@xoldyckk yeah, pretty much , it is just a temporary solution though. 

Here check this out -> https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1441179015

**Comment by xoldyckk** [comment]
> @xoldyckk yeah, pretty much , it is just a temporary solution though.
> 
> Here check this out -> [#952 (comment)](https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1441179015)

I see. Btw what's the talk about deduplication?

**Comment by palisadoes** [comment]
> > @xoldyckk yeah, pretty much , it is just a temporary solution though.
> > Here check this out -> [#952 (comment)](https://github.com/PalisadoesFoundation/talawa-api/issues/952#issuecomment-1441179015)
> 
> I see. Btw what's the talk about deduplication?

We don't need to store duplicate copies of the same object (image, video, attachment, etc). We want to prevent copies in scenarios such as:

1. someone forwarding a post with an image to someone else.
1. someone uploading an image that already exists in the system

I'm sure there are other examples.

**Comment by kb-0311** [comment]
@xoldyckk if there is same binary data being uploaded over and over it will just increase the size of the DB and occupy unnecessary space on disk, so basically if the same binary data is being uploaded again, it will not write the file to disk or store it into the database again , it will return the image path for the already existing binary data to the requesting resolver where it will be stored as `image` field in ost ,user etc. 

In the database we will be keeping track of the number of uses of a particular file for eg a file is being used by 10 different db objects(users, posts ,orgs) then it will only be stored once with `numberOfUses` as 10. This logic is also helpful for deleting images.

**Comment by xoldyckk** [comment]
@palisadoes @kb-0311 IDK about this post sharing thing and why it needs to be like that, couldn't the post link just be shared with people and the post would be embedded in some form on the person's app, or maybe just open a post tab, or maybe just direct them to post page. Well these are just my assumptions idk how these things would work in mobile applications. Also this approach seems to have many flaws but it's a temporary approach so I guess it's ok.

**Comment by palisadoes** [comment]
1. Let's focus on fixing this is in the short term and develop a long term solution for all the edge cases and best practices as part of GSoC.
1. We need this fixed as it is preventing others from creating bug fix code.

**Comment by kb-0311** [comment]
@palisadoes There would be no duplication of data during sharing posts as it will only be a simple query so don;t worry about that part. 

All the other cases are covered.

@xoldyckk 
> But it's a temporary approach so I guess it's ok.

Yes. The idea is to give mobile and admin portal devs something to work with.

**Review by Kevoniat — DISMISSED** [review]

**Review by DMills27 — DISMISSED** [review]
Looks good to me

**Comment by palisadoes** [comment]
@kb-0311 let me know when you get see changes are complete.

**Comment by kb-0311** [comment]
@palisadoes added the changes,

@xoldyckk pls review again.

**Review by xoldyckk — APPROVED** [review]
Since, this is a temporary solution, the check for tests on my part is a bit lax.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
