### PR TITLE
restored countline.py functionality to our github action flow

### LINKED ISSUE #1558: Restore countline.py functionality to our GitHub Action workflow
**Is your feature request related to a problem? Please describe.**

We used to have a GitHub action section in this file that would count the number of lines in the code submitted and fail if they were too many lines in any one file. This greatly helped with our code quality

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Describe the solution you'd like**

1. Go through the history of this file
1. Restore the functionality of countline.py that was **most recently** in effect.
1. Ensure that all the files in the repository are in compliance. If not, refactor the code to make it compliant.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
1. The other repositories have maintained this functionality.
1. You can use their pull request YAML GitHub actions file as a guide
1. You can get help on countline.py by running the script like this:
```
./countline.py --help 
```
**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
This PR restores countline.py functionality to our github action flow

**Issue Number:**

Fixes #1558 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Not required

**If relevant, did you update the documentation?**
Not relevant

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**
None

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
1. This has to be reverted. It's causing issues with our PRs.
2. Please verify this against your own local repository
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7324513262/job/19948161263?pr=1551

**Comment by AdityaRaimec22** [comment]
> 1. This has to be reverted. It's causing issues with our PRs.
> 2. Please verify this against your own local repository
> 
> * https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7324513262/job/19948161263?pr=1551

@palisadoes I don't think the tests are failing because of my pr. My pr ensures count number of line to work properly and other functionalities remain untouched. And that is working without any error.

The error message in the action that you linked suggests that there is a mismatch between the versions of some packages specified in your package-lock.json file and the versions specified in your package.json file. This can happen when the package-lock.json file is not up-to-date with the latest changes in the package.json file.

And my PR has no relation with package.json

**Comment by AdityaRaimec22** [comment]
I tested it against my local repository and all the tests passed

image

image

`Linting`, `formatting` and `type error` checks are passed.

**Comment by palisadoes** [comment]
OK, please resubmit. We'll need to verify with a subsequent PR after yours.

**Pull request merged**
