### PR TITLE
Added the field identifier

### PR DESCRIPTION
**Pull request by ARYANSHAH1567**
What kind of change does this PR introduce?
Feature

Added the identifier field
Issue Number:

#1554
https://github.com/PalisadoesFoundation/talawa-api/issues/1554
Fixes #

Did you add tests for your changes?
Yes

Snapshots/Videos:

If relevant, did you update the documentation?

Summary

The User collection currently has a _id field. This is an internal unique identifier. Unfortunately it is not easily memorable. We need a memorable ID that an Talawa Administrator or User can use to reference themselves or other users.

It's to help provide a means for searching for someone by a member ID that you would find on a membership card

## Summary by CodeRabbit

- **New Features**
	- Added a "Videos" section to the contributing guidelines for easier access to resources.
	- Introduced a unique `identifier` field for users, enhancing user management capabilities and data integrity.

- **Bug Fixes**
	- Updated dependencies to improve functionality and performance of the application.

- **Documentation**
	- Improved formatting in the README for better readability.
	- Enhanced the structure of the `CONTRIBUTING.md` file for better navigation.

- **Tests**
	- New tests added for the `identifier` property in the `User` model, ensuring its functionality and integrity.

### CODE REVIEW

**Comment by ARYANSHAH1567** [comment]
@palisadoes please merge this pr

**Comment by palisadoes** [comment]
@xoldd PTAL. The aim is to have an automatically generated user friendly ID for each new user. For example it would be used for 

1. printing a member number on an ID card.
2. easy user searching by ID number versus an email address

**Comment by ARYANSHAH1567** [comment]
> @xoldd PTAL. The aim is to have an automatically generated user friendly ID for each new user. For example it would be used for
> 
> 1. printing a member number on an ID card.
> 2. easy user searching by ID number versus an email address

I have added that in schema and added the increament feature in mongodb so whenever the user is created its get's an identifier id

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. In the Talawa Admin, when I try to add a new member I get a duplicate entry error related to the identifier.
1. The Talawa Admin needs to reflect your changes too 
image
1. Make sure it works for new and existing users
image

**Comment by ARYANSHAH1567** [comment]
I have fixed the issues now do i have to create a new pull request?
i just had to change the identifer field from the sample_data of user 
and it will work fine

**Comment by palisadoes** [comment]
1. Update this PR if it is for this repo
2. Make sure all the tests pass and that no other functionality is affected

**Comment by ARYANSHAH1567** [comment]
Changed the files

**Comment by palisadoes** [comment]
Please add a test to make sure we don't have this error again

**Comment by ARYANSHAH1567** [comment]
How do i add test like share a screenshot or something? can you guide me

**Comment by palisadoes** [comment]
Please ask the `#talawa-api` slack channel

**Pull request closed without merging**
