### PR TITLE
Added test cases for like and unlike comment 

### PR DESCRIPTION
**Pull request by KunalAnkur**
Issue #179 
**What kind of change does this PR introduce?**
This PR introduces the test cases for like and unlike comment.

**Did you add tests for your changes?**
Yes, I have added the test cases for like and unlike comment in the `newsfeed.spec.js` file.

Screenshot from 2021-03-23 15-08-56

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by KunalAnkur** [comment]
The test case which is failing is in `organization_subqueries.spec.js`. This file is nothing to do with this PR. The test case of `newsfeed.spec.js` is successfully passing.

**Comment by palisadoes** [comment]
Please fix the Travis pull request errors

**Comment by palisadoes** [comment]
@KunalAnkur Please resolve the failed checks

**Comment by KunalAnkur** [comment]
[](http://calico.palisadoes.org/talawa/graphql) This link is not working currently.
If this will work then I can able to check all these failed test cases

**Comment by palisadoes** [comment]
> http://calico.palisadoes.org/talawa/graphql This link is not working currently.
> If this will work then I can able to check all these failed test cases

Use https://talawa-graphql-api.herokuapp.com/graphql which is the current test environment. How can we update the URL in a single location for testing. This will change from time to time.

**Review by Laurell876 — APPROVED** [review]

**Pull request merged**
