### PR TITLE
Updated package-lock.json file from version 2 to 3

### LINKED ISSUE #1335: Bug Report: Update `package-lock.json`
**Describe the bug**
Currently, on running the workflows, we get the following warning while installing dependencies:
image
The lock file must be upgraded from version 1 to version 3.

### PR DESCRIPTION
**Pull request by Anubhav-2003**
**What kind of change does this PR introduce?**

It updates the package-lock.json file to version 3, and also updates certain dependencies accordingly.

**Issue Number:**
Fixes #1335 

**Did you add tests for your changes?**
No.

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
No

**Summary**
The following PR updates the package-lock.json file from version 2 to version 3.  While also 
updating other dependecies to fix various vulnerabilities using either npm audit fix, or manually updating the versions
and running npn install.
It solves 8 out of 12 vulnerabilities through 'npm audit'. 

**Does this PR introduce a breaking change?**
No
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Anubhav-2003** [comment]
@palisadoes KIndly look into my PR and approve/merge it. Thank you.

**Comment by palisadoes** [comment]
@EshaanAgg Please review.
@Anubhav-2003 Please remove the `dump.rdb` file. It should not be required.

**Comment by Anubhav-2003** [comment]
> @EshaanAgg Please review. @Anubhav-2003 Please remove the `dump.rdb` file. It should not be required.

I have removed the 'dump.rdb' file. Thank you for your response.

**Review by EshaanAgg — APPROVED** [review]
Looks good to me. Thanks!

**Comment by Anubhav-2003** [comment]
@palisadoes Please approve my PR. Thank you.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
