### PR TITLE
Bug fixed: Agenda Item & section mutation and Query

### LINKED ISSUE #2320: Bug Report: Agenda Item & Section Mutation and Query not working
**Describe the bug**
solve the bug

**To Reproduce**

**Current behavior**
image

image

Screenshot from 2024-05-22 13-05-07

Screenshot from 2024-05-22 13-07-35

Screenshot from 2024-05-22 13-16-22

**Expected behavior**
Screenshot from 2024-05-22 13-06-37

Screenshot from 2024-05-22 13-07-53

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2320

**Did you add tests for your changes?**

**Snapshots/Videos:**
Screenshot from 2024-05-22 13-16-39

Screenshot from 2024-05-22 13-06-37

Screenshot from 2024-05-22 13-07-53

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
  - Added the ability to retrieve specific agenda sections with the new `getAgendaSection` query.

- **Bug Fixes**
  - Improved permission checks for removing agenda sections, ensuring only the creator can delete them.
  - Enhanced validation for updating agenda sections, verifying the creator or superadmin status before allowing changes.

### CODE REVIEW

**Comment by gautam-divyanshu** [comment]
@palisadoes please review this pr, I can't processed further because I have multiple pr for AgendaCategory issue

**Comment by Cioppolo14** [comment]
@SiddheshKukade @Atharva-Kanherkar @pranshugupta54  Please review this PR.

**Review by pranshugupta54 — APPROVED** [review]

**Review by AVtheking — APPROVED** [review]

**Review by Atharva-Kanherkar — APPROVED** [review]
LGTM!

**Review by Atharva-Kanherkar — COMMENTED** [review]
Weren't they already present here?

**Comment by gautam-divyanshu** [comment]
> Weren't they already present here?

You tell me you implemented it. 😄

**Comment by palisadoes** [comment]
Please fix the conflicting file so that we can merge

**Comment by gautam-divyanshu** [comment]
@palisadoes we can merge now

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
