### PR TITLE
add graphql implementation for advertisements

### PR DESCRIPTION
**Pull request by xoldd**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

This pull request includes graphql implementation for handling read and write operations for talawa organization advertisements and read operations for new relations introduced between entities.

**Does this PR introduce a breaking change?**

**Other information**

# Includes commits from PR #2729 which is yet to be merged.

## EACH INDIVIDUAL COMMIT CONTAINS CHANGES RELATED TO THE COMMIT MESSAGE, COMMITS SHOULD BE VIEWED IN A SERIAL ORDER FOR AN EASIER REVIEW PROCESS

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by xoldd** [comment]
https://github.com/PalisadoesFoundation/talawa-api/commit/d6ed32024d066e28e435bd1068bfb16ead731468

@palisadoes Why is this added? The node version is already being managed using `engines.node` field in the `package.json` file.

**Comment by palisadoes** [comment]
Because our INSTALLATION.md file recommends using it.

**Comment by xoldd** [comment]
> 1. Because our INSTALLATION.md file recommends using for the `develop` branches for Talawa-API and Talawa-Admin.

I will create an installation guide for this branch soon enough. Installation guides from other branches or repos can't be used in this branch.

> 2. I didn't realize that you were using something different. We should be using a consistent methodology across all our talawa* repos

This branch is different as things are done in a better more organized way so please don't make arbitrary changes like that based on assumptions. The consistent methodology only applies to api and admin because both are typescript projects. If it is to be followed, it is better that admin follows the methodology of this branch than the other way.

**Comment by xoldd** [comment]
Can the change be reverted without disrupting the commit history or will I have to rebase all the pull requests?

**Comment by xoldd** [comment]
Closing as the merged PR #2741 includes the changes in this PR.

**Pull request closed without merging**
