### PR TITLE
Updated doc files

### PR DESCRIPTION
**Pull request by XshubhamX**
Changes in doc files for top feature

**What kind of change does this PR introduce?**

docs update

**Did you add tests for your changes?**

not required

### CODE REVIEW

**Comment by palisadoes** [comment]
@XshubhamX please close this PR. 

1. It's in draft
2. There is no stated issue that it is related to

**Comment by XshubhamX** [comment]
@palisadoes sir this documentation needs to be merged after the OTP system is reviewed and merged successfully.

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
@XshubhamX As I haven't heard back from you. I'm going to close PR #248 and #245. We prefer to go with an email service for the reasons stated previously.

**Comment by palisadoes** [comment]
@XshubhamX As I haven't heard back from you. I'm going to close PR #248 and #245. We prefer to go with an email service for the reasons stated previously.

**Pull request closed without merging**
