### PR TITLE
fix: db.js only favours local mongodb instance

### PR DESCRIPTION
**Pull request by iamsaumya**
Fixes: #121

### CODE REVIEW

**Comment by iamsaumya** [comment]
I have updated README.md and contribution.md as well. Please let me know if anything else has to be updated. 

Thanks!

**Review by heyjordn — APPROVED** [review]
Thanks for the docs update!

LGTM 👍🏼

**Comment by iamsaumya** [comment]
Always happy to add value 😊.

**Comment by iamsaumya** [comment]
Btw @heyjordn I need your help on #117 .

**Pull request merged**
