### PR TITLE
fix: Usage of helmet in default configuration blocks graphql playground to open

### PR DESCRIPTION
**Pull request by iamsaumya**
Fixes: #126

### CODE REVIEW

**Comment by yasharth291** [comment]
its problem on your environment because it was running smooth on my as well as @Laurell876  computer so this pull request should be closed.

**Comment by yasharth291** [comment]
now you can close this and fix your system for the same.

**Comment by Swayam221** [comment]
@iamsaumya This might solve PalisadoesFoundation/talawa#208 & PalisadoesFoundation/talawa#204.

**Comment by iamsaumya** [comment]
> @iamsaumya This might solve PalisadoesFoundation/talawa#208 & PalisadoesFoundation/talawa#204.

I'm sorry, What might solve?

**Comment by Swayam221** [comment]
> > @iamsaumya This might solve [PalisadoesFoundation/talawa#208](https://github.com/PalisadoesFoundation/talawa/issues/208) & [PalisadoesFoundation/talawa#204](https://github.com/PalisadoesFoundation/talawa/issues/204).
> 
> I'm sorry, What might solve?

@iamsaumya This PR .  The change this PR produces will most probably solve the problem of profile and organisation pics not able to right?

**Comment by iamsaumya** [comment]
@Sagar2366 Sorry to ping you. This is a P1 bug, could you please merge this PR?

**Comment by iamsaumya** [comment]
@Sagar2366 and @Laurell876 I read in the slack that we should create PR to develop a branch. I have rebased this PR to point to the `develop` branch as this bug still exists there.

Is there any that preventing this PR to get merged? this is a P1 bug without resolving this I don't think anyone can use the playground.

**Comment by yasharth291** [comment]
have you checked the new code? i think someone has changed it.

**Comment by yasharth291** [comment]
yeah i guess your changes has been implemented 
Capture

**Comment by yasharth291** [comment]
@iamsaumya

**Comment by iamsaumya** [comment]
Hey @yasharth291, I think you have misinterpreted. As we are advised in the slack channel to create PR to `develop` branch. I have rebased this to it as I don't see the fix in the `develop` branch. 

https://github.com/PalisadoesFoundation/talawa-api/blob/ab6731f9fbe4598c6b28b1d989a1f3e284a62722/index.js#L95

**Comment by iamsaumya** [comment]
>  i think someone has changed it.

It's you who has changed it. Thanks for your contribution!

**Comment by yasharth291** [comment]
ok yeah it is not solved in the other branch but it is there in main branch

**Comment by yasharth291** [comment]
> > i think someone has changed it.
> 
> It's you who has changed it. Thanks for your contribution!

i?? oh sorry may be i changed it for my laptop and didn't removed it before commiting sorry

**Comment by iamsaumya** [comment]
> i?? oh sorry may be i changed it for my laptop and didn't removed it before commiting sorry

Hey, don't be sorry bro. It's alright. 🍻

**Comment by Sagar2366** [comment]
@iamsaumya please check why checks are failing.

**Comment by nikulbeladiya** [comment]
Hey, @iamsaumya , does your issues fixed ? i also getting same errors in playground while using helmet.

**Comment by iamsaumya** [comment]
@nikulbeladiya this issue is fixed for me. What are the errors you are facing in the playground?

**Pull request merged**
