### PR TITLE
Enforces stricter access control and fixes a lot of related Mutation bugs 

### LINKED ISSUE #1066: Super Admin Access Control Security Bug and API Mutation bugs
**Describe the bug**
Now that I have implemented the `superAdminCheck` function and authorization directive https://github.com/PalisadoesFoundation/talawa-api/pull/1065 . I will be next implementing them in each resolver when necessary.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kb-0311**
**What kind of change does this PR introduce?**

bugfix
**Issue Number:**

Fixes #1066 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
THe PR aims to - 
1. Implement a form of access control for specific mutations based on user role (superadmin , admin etc) with an appropriate error message when needed.
2. Fix the bug in blocking users from a organization where in the admin could block himself. After this PR that will not be possible.
3. Fix the logic for `removeAdmin` , `rejectAdmin` and `acceptAdmin` mutations.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by kb-0311** [comment]
pls do not merge for now , there are some final checks remaining plus I am also going to add documentation detailing the access controlled mutations etc in this PR for swifter development progress for other developers in the future.

**Comment by aviraldevv** [comment]
@kb-0311  Nevermind I can see you have done refactoring of code which were assigned to me. I will submit a PR for same latest by tomorrow. Please wait for me to submit a PR.

**Comment by kb-0311** [comment]
@aviraldevv 
1. I have only done refactoring of code when needed (only for a few mutations related to access control) only for the purpose of standardized testing for the errors thrown in my changes it was not the main point of this PR.
2. Sure we can do that but then I will have to fix the conflicts after your PR merge (which honestly will just increase the work for me in fixing conflicting files. :skull:  ) But I think you have seen my recent messages on slack channel that I am kinda focusing on fixing the API bugs and API design documentation stuff before 22nd Feb when Orgs get announced for GSoC and a whole new flood of contributors come in to contribute before GSoC. 

Will you be open to refactoring the remaining Mutations not covered in this PR or you want to get your PR merged first then I fix the conflicts? because this PR is still not totally complete.

**Review by noman2002 — DISMISSED** [review]
Looks good to me.

**Comment by aviraldevv** [comment]
@kb-0311 you can go ahead with this PR, I acknowledge it would be a very tedious task for you to fix the conflicts.

**Comment by palisadoes** [comment]
@kb-0311 Are you finished with your changes?

**Comment by xoldyckk** [comment]
@kb-0311 Ping me when the final review is needed. Btw try to keep PR changes minimal. If you have many changes make seperate issues for them. It becomes very hard to review an enourmous amount of changes in a single PR.

**Comment by kb-0311** [comment]
@palisadoes This PR is done now.

@xoldyckk Yes I figured but actually while manually testing my superadmin/admin thingy changes with the Client apps, I found that many other mutations are broken. So I fixed smaller ones here itself. The large bugs will get their own dedicated issues.

I had batched my changes commit wise like this - mutations where I had made my change + tests for my changes in its pec file. So maybe it would be easier to review commit wise.

**Comment by kb-0311** [comment]
for some reason the codecov decreased even though all the individual files have increased or no coverage changes.

**Comment by palisadoes** [comment]
@Kevoniat @Tajcore @noman2002 @xoldyckk please review

**Review by Kevoniat — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
