### PR TITLE
Migrating to eslint.config.js

### LINKED ISSUE #2472: Switching from eslintrc.json to eslint.config.json
**Describe the bug**
We need to switch from `eslintrc.json` to `eslint.config.js` as the former is considered deprecated now.

**To Reproduce**

1. Make changes in any file in the code base. 
2. Add all the changes using `git add .` command
3. Try and commit the changes using `git commit -m "<Your commit message>"`
4. Examine the error, The process fails after the initial few tests.

**Expected behavior**
The changes should have been committed without any such error messages.

**Actual behavior**
After the initial few tasks the commit action fails. Since "`.eslintrc.json`" file is no longer supported. And it asks to switch over to `eslint.config.js` file.
More over the property `.eslintignore` is also not supported rather user is supposed to use the "ignores" property in `eslint.config.js`.

**Screenshots**
image

**Additional details**
None.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Suyash878**
**What kind of change does this PR introduce?**
Bug fix

**Issue Number:**
Fixes #2472

**Did you add tests for your changes?**
Not relevant

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Not relevant here.

**Summary**
This PR migrates the deprecated version of `eslintrc.json` to `eslint.config.js`.
Now eslint will correctly fix all the linting issues which was not the case earlier as mentioned in the screenshot of the issue raised. Now this PR is in reference to an earlier PR which was closed due to some dependency issues.

**Does this PR introduce a breaking change?**
Not sure if relevant here.

**Other information**
None

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Added a "Videos" section to the table of contents in the CONTRIBUTING.md file for improved navigation.
	- Introduced a comprehensive ESLint configuration for TypeScript and GraphQL projects to enhance code quality.

- **Bug Fixes**
	- Minor formatting adjustments made in the README.md for better visual alignment of the features list.

- **Chores**
	- Added new development dependencies and updated existing ones to improve linting and code quality tools in the project.

### CODE REVIEW

**Comment by Suyash878** [comment]
The conflicts occur due to some newly added packages which are necessary for the migration to happen, As I even mentioned in my previously closed PR #2483.

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

Unfortunately, if this continues we will have to close the offending PR and unassign you from the issue.

- https://github.com/PalisadoesFoundation/talawa-api/pulls?q=is%3Apr+author%3ASuyash878

image

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
1. Please fix the conflicting files.
2. We have been merging other PRs that would have caused this.
3. The PR looks good, so once you have made the changes we can merge

**Comment by Suyash878** [comment]
Now the only conflict that arises is due to the `globals` package, But since it is a required dependency for this migration to take place I cannot remove it.

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by Suyash878** [comment]
I would like to know how I should continue with this, because resolving the conflicts would require me to remove the `globals` package entirely, but it is a required dependency for the migration. 
Any insights or recommendations are much appreciated.

**Comment by palisadoes** [comment]
Did you get any feedback from the #talawa-api slack channel?

**Comment by Suyash878** [comment]
Okay, I will surely try to seek assistance from there.

**Comment by Suyash878** [comment]
I got a suggestion to add the `globals` dependency package, So should I raise an issue for it? because in that way only the `package.json` file in develop would match the `package.json` in my custom branch leading to the conflicts being resolved.

**Comment by palisadoes** [comment]
Make the changes to this PR. It is in scope of what needs to be done to do the migration.

**Comment by Suyash878** [comment]
I have performed the migration successfully, Kindly review

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
