### PR TITLE
Fix: loadSampleData isn't working

### LINKED ISSUE #2119: loadSampleData isn't working
**Describe the bug**

When we try to import sample data from ` npm run import:sample-data --format` it throwing mongo connection error.

**To Reproduce**

1.  npm run import:sample-data --format

**Expected behavior**

The sample data has to be imported successfully without any errors when formatted.

**Actual behavior**

The code isn't checking for them mongo client connection which maybe an issue with this.

**Screenshots**

image

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by nikhil-pandey-digital**
**What kind of change does this PR introduce?**

fixed the  MongoDB, not connecting error

Fixes #2119

**Did you add tests for your changes?**

N/A

**Snapshots:**

image

**Summary**

fixed  MongoDB not connecting error by making sure that mongoose.connect() should be able to read the mongo uri from .env file.
but this introduces a new error of duplicate ids because of the wrong workflow in the loadSampleData.js, which needs to be resolved  in a separate issue .

**Does this PR introduce a breaking change?**
NO

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by varshith257 — APPROVED** [review]
LGTM

**Comment by meetulr** [comment]
@nikhil-pandey-digital use `npm run import:sample-data -- --format". npm run uses a separator `--` to differentiate between the arguments passed to the npm command itself and the arguments passed to the script.

**Comment by nikhil-pandey-digital** [comment]
@meetulr i ran `npm run import:sample-data -- --format` and now it is successfully adding all the data.
attached screenshot:
image
image

**Comment by palisadoes** [comment]
1. We can't merge this if it introduces a new error with `loadSampleData.js` as you mentioned. 
2. Your error seems to be fixed by updating our documentation.
3. This PR doesn't seem appropriate

**Comment by palisadoes** [comment]
1. Closing. 
2. This is covered in the documentation

image

**Comment by nikhil-pandey-digital** [comment]
@palisadoes this doesn't introduces any new error ,
the error was generated due mis typo of `npm run import:sample-data -- --format` command.

this pr solves the issue of mongoose.connect() error.
BEFORE
image
AFTER
image
image

**Pull request merged**
