### PR TITLE
updated tough-cookie to fix vulnerability

### LINKED ISSUE #1361: tough-cookie Prototype Pollution vulnerability #60
- You will need to update to v4.1.3
image

- You will also need to update some dependencies. Here are some that you'll need to consider:
image

### PR DESCRIPTION
**Pull request by ishtails**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**
fixes #1361 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Overrided tough-cookie in package.json to fix tough-cookie Prototype Pollution vulnerability

**Does this PR introduce a breaking change?**
Not sure

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please refer to the CONTRIBUTING.md file on how to auto-close issues when the PR is merged. This is important.

**Comment by palisadoes** [comment]
According to dependabot, there are other dependencies that you need to address. This is why we created the manual issue. Please review.

image

**Comment by ishtails** [comment]
Sorry, my bad. I thought overriding would automatically take care of that. anyway, I have updated the version in the dependent package, let me know if this is fine?

**Comment by ishtails** [comment]
@palisadoes please review

**Comment by palisadoes** [comment]
This will need to be closed as it appears as if there is no solution without manually updating the dependencies of dependencies.

**Pull request closed without merging**
