### PR TITLE
Post and Organization image deletion fixed

### LINKED ISSUE #1424: Post and Organization deletion not deleting there Image
**Describe the bug**
When we delete a Post or Organization, there image is not deleted, only the data is deleted from there respective collection in database. Image from file system and encodedimages is not deleted. 

**To Reproduce**

1. Create a Post with image/video
2. Delete it
 
(Post is deleted but it's image/video still remains in file system and encodedimages)

Same issue when an Organization is deleted.

**Expected behavior**
After deleting the Post or organization, there's image should also delete from file system and database.

https://github.com/PalisadoesFoundation/talawa-api/assets/123248648/0db086c4-9d56-40f7-af7b-8b4ef0acd8da

### PR DESCRIPTION
**Pull request by nitishkumar333**
**What kind of change does this PR introduce?**
Bugfix

Fixes #1424 

**Did you add tests for your changes?**
Yes

**Summary**
This PR makes sure that when Posts and Organization is deleted, there image is also deleted from file system and encodedImages.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

**After changes**

https://github.com/PalisadoesFoundation/talawa-api/assets/123248648/dd5b6ca7-471e-46e5-8391-83ed80b74f14

### CODE REVIEW

**Comment by nitishkumar333** [comment]
My another PR ( #1421 ) covers the indirect changes of code coverage that are causing in every PR.

**Comment by noman2002** [comment]
@nitishkumar333 Add a video to show if its working or not.

**Comment by nitishkumar333** [comment]
@noman2002 video added

**Comment by nitishkumar333** [comment]
Any feedback on the PR please ?

**Review by xoldyckk — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
