### PR TITLE
update dotenv to version 16.3.1 FIXES #1488

### LINKED ISSUE #1488: Upgrade package `dotenv` from 8.6.0 to 16.3.1
This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa-api/pull/1484

However, though the checks passed, this is a major release update and we want to make sure that not just the `pull-request` GitHub actions pass, but also the `push` actions pass too:

Goals:
1. You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
2. Functionality must remain unchanged as a result of completing this issue
3.  The commands in these GitHub action files must pass:
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml
    2. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml 

## Other
- **NOTE:** I’ve stopped assigning people to issues due to the workload, no exceptions. Please watch this video on how to proceed.

[Click me to start video](https://www.youtube.com/watch?v=GlqUm1UO-xM)

### PR DESCRIPTION
**Pull request by RAGHAV-N5**
**What kind of change does this PR introduce?**

Updating the version of dotenv from version 8.6.0 to 16.3.1

**Issue Number:**

Fixes #1488 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Screenshot 2023-12-13 173753

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

I upgraded the dotenv to version 16.3.1 from 8.6.0, tested it with 100% coverage and passing the threshould.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting files. Merge your code with the latest upstream

**Comment by RAGHAV-N5** [comment]
Can anyone please help me out since this is my first pull request? Is this pull request merged or not?

**Comment by palisadoes** [comment]
- This PR is closed. Merged PRs will have a merged status.
- When you submit a PR it is reviewed by our contributors who may ask for modifications. They will approve it and merge it when they are satisfied.
- First time PR submitters will have our normally automated GitHub actions manually applied as a precaution. Subsequent PRs will have this process automatically applied.

**Comment by RAGHAV-N5** [comment]
Okay, will fix the conflicting files and create a pull request soon.

**Pull request closed without merging**
