### PR TITLE
Refactor & Fixes : Multiple folders and files [Fixes: #1002 & #993]

### LINKED ISSUE #993: Remove the conditional check `process.env !== "PRODUCTION"` for `requestContext.translate()` in code files.
**Is your feature request related to a problem? Please describe.**
The whole idea of checking `process.env !== "PRODUCTION"` in places where `requestContext.translate()` function was being used was to make it not error out when testing the code that utilised that function. This was because `requestContext.translate()` would only properly work under the context of a running api server.

But as the recent test changes have shown, `requestContext.translate()` can be mocked while testing a particular module/file and therefore the check `process.env !== "PRODUCTION"` no longer needs to exist.

**Describe the solution you'd like**
All the places in code where the check  `process.env !== "PRODUCTION"` is made should be removed and `requestContext.translate()` should be mocked when testing the code utilising that function. 

This also means all the test code that doesn't mock `requestContext.translate()` should be removed/replaced with the one that does mock it. Two identical suites of tests running for the same logic should not exist when there's no need.

**Describe alternatives you've considered**

-

**Approach to be followed (optional)**
1. Removed all instances of the check  `process.env !== "PRODUCTION"` and conditional usage of  `requestContext.translate()` function depending on that check from code files.
2. Migrate/refactor tests to test code files using the mocked version of `requestContext.translate()`. All test code depending on the check `process.env !== "PRODUCTION"` should be removed.

**Additional context**
I can't think of any reason for which this would affect talawa-api negatively. Leave your opinions/thoughts on this.

### LINKED ISSUE #1002: Refactor: tests/resolvers/Mutation [File 41 to File 60] [Remove the conditional check process.env !== "PRODUCTION" for requestContext.translate()]
This is a child issue to the issue listed here: #993
- Code need to be refactored for folder ```tests/resolvers/Mutation```
- There are certain test files in this folder, which do not cover 100% of their respective code. You may ignore them, for this issue.
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issues on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/993)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by aviraldevv**
**What kind of change does this PR introduce?**
This PR completely refactores and fixes related issues in Mutation, Organizations, Query and Utilities folder.

**Issue Number:**
Fixes #993 
Fixes #1002 

**Snapshots/Videos:**
Screenshot_322

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aviraldevv** [comment]
Thanks @anshgoyalevil for helping me out with `refreshToken.ts` file.

**Comment by palisadoes** [comment]
Please read the PR_GUIDELINES.md file to see how you can automatically choose an issue when the PR is merged. It helps us greatly with our housekeeping

**Comment by aviraldevv** [comment]
> Please read the PR_GUIDELINES.md file to see how you can automatically choose an issue when the PR is merged. It helps us greatly with our housekeeping

Sure @palisadoes .

**Comment by Kevoniat** [comment]
looks good to me

**Review by Kevoniat — APPROVED** [review]

**Review by xoldyckk — COMMENTED** [review]
@aviraldevv I don't get why we need to mock constants?

**Comment by aviraldevv** [comment]
@xoldyckk I had removed it for some of the tests it worked fine. I added it again to make it consistent with the rest of the test  files.

**Comment by xoldyckk** [comment]
> @xoldyckk I had removed it for some of the tests it worked fine. I added it again to make it consistent with the rest of the test files. I googled about it in some places its mentioned its a good practice. If we remove it test will still run but in some cases it may fail unexpectedly.

Can you give an example where it would fail?

**Comment by aviraldevv** [comment]
> > @xoldyckk I had removed it for some of the tests it worked fine. I added it again to make it consistent with the rest of the test files. I googled about it in some places its mentioned its a good practice. If we remove it test will still run but in some cases it may fail unexpectedly.
> 
> Can you give an example where it would fail?

@xoldyckk That was just an information from google. But I had an interesting observation while trying this out. Commenting out the portion of code mockin constants significantly decreased the test time.
Screenshot_340

Screenshot_340

**Comment by xoldyckk** [comment]
> > > @xoldyckk I had removed it for some of the tests it worked fine. I added it again to make it consistent with the rest of the test files. I googled about it in some places its mentioned its a good practice. If we remove it test will still run but in some cases it may fail unexpectedly.
> > 
> > 
> > Can you give an example where it would fail?
> 
> @xoldyckk That was just an information from google. But I had an interesting observation while trying this out. Commenting out the portion of code mocking constants significantly decreased the test time. What do you think should we remove it ?? Screenshot_340
> 
> Screenshot_342

We don't need to mock constants, it was only done considering that `requestContext` thing. You should get rid of all of them.

**Comment by aviraldevv** [comment]
@xoldyckk  Shall I create a new issue after this one gets merged ??

**Comment by xoldyckk** [comment]
> @xoldyckk Shall I create a new issue after this one gets merged ?? This PR is already very big.

Sure

**Review by xoldyckk — APPROVED** [review]

**Comment by palisadoes** [comment]
@xoldyckk do you approve the current changes for this PR?

**Pull request merged**
