### PR TITLE
Audit trail fields in Schema

### LINKED ISSUE #1474: Feature Request: Implement GraphQL Error Handling: Resolver user
Parent: #1450 
**Is your feature request related to a problem? Please describe.**
Implement Error handling in user resolver as mentioned in #1450.

**Describe the solution you'd like**
We can set the return type of user resolver to ```UserResult``` which will contain the ```data``` and ```errors``` . ```errors``` can be ```UserNotFoundError``` or ```UnauthenticatedError```. The ```UnauthenticatedError``` can come from authdirective. Then we can handle all these errors in the client side.

### LINKED ISSUE #1479: Feature Request: Implement Audit Trail Fields in Schema
**Is your feature request related to a problem? Please describe.**
Currently, the schema doesn't have basic audit trail features

**Describe the solution you'd like**
Adding `createdAt`, `updatedAt`, `createdBy`, and `updatedBy` fields to each collection in the database. The goal is to automatically capture and store information about when and by whom a record was created and last updated.

### PR DESCRIPTION
**Pull request by LakshyaSatpal**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #1479

**Did you add tests for your changes?**
yes

**Summary**
Added `createdBy`, `updatedBy`, `createdAt`, `updatedAt` fields to the following models:
1. Advertisement
2. Comment
3. DirectChat
4. Event
5. EventProject
6. GroupChat
7. Message
8. Organization
8. Post
10. Task

Added just `createdAt`, `updatedAt` timestamp fields to the following models:
1. Checkin
2. DirectChatMessage
3. Donation
4. Feedback
5. File
6. MessageChat

**Does this PR introduce a breaking change?**|
Changed the `creator` field to `createdBy` field at many models. The clients will have to be changed accordingly, if they use `creator` field.

### CODE REVIEW

**Comment by LakshyaSatpal** [comment]
I've added resolvers for the `createdBy` and `updatedBy` fields, for models, which have a mutation defined to update. 
For example, Organization, Post, Task, Event, these models have a corresponding `updateOrganization`, `updatePost`, etc. mutation defined.

**Comment by LakshyaSatpal** [comment]
@palisadoes 
I've added the fields for the models, based on my current understanding. Please feel free to suggest any additions or removals to better align them with our requirements. Thanks.

**Comment by LakshyaSatpal** [comment]
Fixing failing tests

**Comment by Cioppolo14** [comment]
@LakshyaSatpal There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

**Comment by LakshyaSatpal** [comment]
I apologize, there was an error in typing the issue number for the PR. @Cioppolo14 Can we reopen this?

**Comment by palisadoes** [comment]
We need to close this. The changes need to be made against the develop branch

**Comment by LakshyaSatpal** [comment]
Sorry for the bad PR :(
Will create a new one.

**Pull request closed without merging**
