### PR TITLE
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events

### LINKED ISSUE #2624: Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.
**Is your feature request related to a problem? Please describe.**
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.

**Describe the solution you'd like**
Add mutations to mark chat messages as read, update message, update group chat info, add user to group chat, share images in chats, and create dedicated group chats for events.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #2624

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Release Notes

- **New Features**
  - Enhanced chat functionality with new fields for tracking unseen messages and media in chat messages.
  - New mutations for adding users to group chats, marking messages as read, and updating chat/message details.
  - New queries for retrieving group chats and unread chats by user ID.
  - Introduced new input types for better filtering and chat creation options.

- **Bug Fixes**
  - Improved error handling in various mutation resolvers.

- **Documentation**
  - Updated GraphQL schema definitions to reflect new input types and mutations.

- **Tests**
  - Expanded test coverage for chat-related functionalities, including new tests for group chats and unread messages.

### CODE REVIEW

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by palisadoes** [comment]
Please fix the conflicting files and tests

**Comment by palisadoes** [comment]
@disha1202 Are you still working on this?

**Comment by Cioppolo14** [comment]
Closing this as inactive.

**Comment by palisadoes** [comment]
Reopening. GSoC

**Comment by disha1202** [comment]
> 1. Please fix the failing tests. Click on the `Details` links for more information.
> 2. Please make sure that CodeRabbit.ai approves your changes

Hi @palisadoes
The typecheck test is failing which is not related to the changes in this PR and is fixed in
https://github.com/PalisadoesFoundation/talawa-api/pull/2770

**Comment by palisadoes** [comment]
@disha1202 The PR was merged and the failed tests persist

**Comment by palisadoes** [comment]
@disha1202 Can we merge this now? Can you make changes so that coderabbit.ai approves?

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
