### PR TITLE
removeAdvertisement.ts test updated to 100% coverage

### LINKED ISSUE #1825: Test: src/resolvers/Mutation/removeAdvertisement.ts
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file
    1. src/resolvers/Mutation/removeAdvertisement.ts
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by i-m-Paras**
Certainly! Here's a professional description template for your pull request:

What kind of change does this PR introduce?
It addresses the issue #1825 , providing a solution to coverage of test file for removeAdvertisement.ts file by making coverage to 100%.

Issue Number:
Fixes #1825 

Did you add tests for your changes?
Yes

Snapshots/Videos:
Screenshot from 2024-02-11 02-07-20

If relevant, did you update the documentation?
No.

Summary:
This pull request addresses test coverage for removeAdvertisement.ts. The main motivations behind these changes is to increase the test coverage to 100% for removeAdvertisement.ts file.

Does this PR introduce a breaking change?
No.

Other information:

I created ` const myId = args.id ? args.id : ""; ` separately because there was no need of checking this twice both for findOne and deleteOne hence reducing test coverage.

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes.

### CODE REVIEW

**Review by Kevoniat — DISMISSED** [review]

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by i-m-Paras** [comment]
These errors were not the outcome of my code changes, so I was not sure if I am supposed to fix them up in the same PR.
I will fix them soon.

**Comment by i-m-Paras** [comment]
@palisadoes Please let me know if any more changes are required.

**Review by SiddheshKukade — APPROVED** [review]
LGTM

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
