### PR TITLE
Refactor files 61-70 in tests/resolvers/Mutation [Fixes #989]

### LINKED ISSUE #989: Refactor: tests/resolvers/Mutation [File 61 to File 70]
This is a child issue to the issue listed here: #971 and #965

- Code need to be refactored for folder ```tests/resolvers/Mutation```
- There are several files in this folder, so the files from 61 to 70 range [unregisterForEventsByUser.spec.ts to updateUserType.spec.ts]
- There are certain test files in this folder, which do not cover 100% of their respective code. You may ignore them, for this issue.
- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all all methods, classes and/or functions in the refactored file will need to be tested.
- Refer to the parent issue on getting an insight on how this issue need to be resolved.

## IMPORTANT:
Please refer to the parent issues on how to refactor the code correctly.

[Parent Issue](https://github.com/PalisadoesFoundation/talawa-api/issues/965)

## PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own codecov.io to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This PR introduces the refactoring of tests in ```tests/resolvers/Mutation``` from file 61-70

**Issue Number:**

Fixes #989 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
Not Required.

**Summary**
This PR introduces the refactoring of tests in ```tests/resolvers/Mutation``` from file 61-70

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by xoldyckk** [comment]
@anshgoyalevil what's the coverage for authDirective?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil what's the coverage for authDirective?

at 100%

**Comment by anshgoyalevil** [comment]
The workflow failed due to the issue https://github.com/PalisadoesFoundation/talawa-api/issues/1010

Please re-run it.

**Comment by xoldyckk** [comment]
Hmmmmm why does it not show the coverage?

**Comment by anshgoyalevil** [comment]
> Hmmmmm why does it not show the coverage?

Really confused. Seems like it's an issue with the Codecov workflow

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
