### PR TITLE
 feat : GitHub Actions :  Detection of eslint-ignore statements

### LINKED ISSUE #1726: API: GitHub Action Required: Fail on detection of eslint-ignore statements
**Is your feature request related to a problem? Please describe.**

The quality of our code is paramount to us. This includes:

1. Functionality
2. Consistency of coding style for improved readability
3. Following best practice coding standards

To achieve the last 2 points, we have been gradually increasing the linting rules enforced in the repository to maintain a consistency of our code style. We have implemented `githooks` to try to enforce this linting best practice.

Even so, we have seen contributors adding statements to ignore our linting rules.

**Describe the solution you'd like**

1. Remove the linting ignore statements to reveal the original linting errors
1. Fix the causes of the linting errors without affecting functionality
1. Add a test to our pull request GitHub action file to fail if any files submitted in the PR:
    1. under the `src/` and `tests/` directories have ignore statements
    2. the `setup.ts` script in the root directory
1. The GitHub action file is:
    1. https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- Evidence of the use of the ignore statements in the `tests/` directory

image

- Evidence of the use of the ignore statements in the `src/` directory

image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Atharva-Kanherkar**
**What kind of change does this PR introduce?**

 Feature 

**Issue Number:**

Fixes #1726 

**Did you add tests for your changes?**

 Yes

 

**If relevant, did you update the documentation?**

 No

**Summary**
This PR tries to bring out change in the workflow of the talawa-api, where there has been some changes, introduction of a test so that it detects that is there a esLint disable statement, to ensure best code quality.
This PR also has deleted some of the comments that were existing, and without affecting functionality, has tried that no ES lint error occurs. But even, if there is any case that some files need to be excluded, we can exclude them using the python file, currently three current files have been excluded from the checker. 
 

**Does this PR introduce a breaking change?**
 No

 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Atharva-Kanherkar** [comment]
> @Atharva-Kanherkar Please fix the failing tests.

Yes, i am trying to, the errors seem of the code I have not written (the lint errors) and they have a count of 700+, can you please help me with figuring out what might be the reason for this? It would be much helpful.

**Comment by palisadoes** [comment]
Are you bypassing the husky checks?

Are you up to date on the code base? We recently updated the prettier package which reformatted a lot of code. That may be the cause

**Comment by Atharva-Kanherkar** [comment]
> Are you bypassing the husky checks?
> 
> Are you up to date on the code base? We recently updated the prettier package which reformatted a lot of code. That may be the cause

Alright, i will try to debug it myself, once, and will try upgrading other packages too.

**Comment by Atharva-Kanherkar** [comment]
> Are you bypassing the husky checks?
> 
> Are you up to date on the code base? We recently updated the prettier package which reformatted a lot of code. That may be the cause

There is something wrong with my local changes. I will close this PR and make a new one again. Maybe the installation package manager is wrong somewhere, i will try to update it. Sorry, my bad.

**Pull request closed without merging**
