### PR TITLE
Fix: Removed Depricated XSS-CLEAN

### LINKED ISSUE #1518: Upgrade package ` xss-clean`
**Describe the bug**
When installing the application we get this error on the console

```
npm WARN deprecated xss-clean@0.1.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

```

The package needs to be upgraded

**To Reproduce**
- Run the `npm install` command

**Expected behavior**
1. The error message goes away after the upgrade. No error message must be suppressed
1. All PR tests pass
1. No functionality is affected by the change
1. You must verify whether the package is still used at all and if not, remove it from any configuration files

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**

 - This PR addresses the deprecation warning related to the 'xss-clean' package and introduces a suitable replacement. The 'xss-clean' package is deprecated and no longer supported, prompting the need for an alternative solution to ensure ongoing security.
- The 'xss' library has been chosen as a replacement for server-side XSS protection, providing a seamless transition while maintaining the previous functionality. 

**Issue Number:**

Fixes #1518 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**
No

**Summary**
This change of replacing xss-clean with xss package resolves the deprecation issue and ensures the continued security and reliability of our application.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14 since the xss-clean package is deprecated and is no longer supported, I explored alternatives to replace this package. I considered utilizing the sanitize function in the dompurify package as an alternative for XSS protection. However, upon further research, I discovered that it primarily focuses on client-side sanitization.

So, I have opted to use the xss library as a suitable replacement for xss-clean, as it focuses on both server-side and client-side XSS protection.

@EshaanAgg  @xoldyckk  is this package acceptable, or would you like me to make any other changes?  Please check.

**Comment by palisadoes** [comment]
Is the package still being used in the code base? If not, it should be removed from `package.json`.

**Comment by akhilender-bongirwar** [comment]
@palisadoes, the package is being used as a middleware in `app.ts`

**Review by xoldyckk — COMMENTED** [review]
Dunno what's the use of xss package nowadays since frontend frameworks already handle it for us. 

Fine grained input validation should be done in the graphql layer instead of here.

**Review by xoldyckk — DISMISSED** [review]

**Comment by palisadoes** [comment]
@xoldyckk What would your solution be? The fewer dependencies the better.

**Comment by xoldyckk** [comment]
@palisadoes since talawa-api is primarily a graphql server it benefits less from expressjs related packages, apollo server could function without any backend framework since the business logic is encapsulated in the graphql layer, overtime the node.js runtime itself has gotten significant updates that kind of renders the use of frameworks useless

the main use of a backend framework like expressjs is the documentation, tooling, packages and support for it, expressjs lacks in that regard since it has been abandoned and doesn't receive updates anymore, the goto backend nodejs framework right now is fastifyjs which is maintained by active core maintainers of the node.js runtime itself

**Comment by palisadoes** [comment]
> @palisadoes since talawa-api is primarily a graphql server it benefits less from expressjs related packages, apollo server could even function without any backend framework since the business logic is encapsulated in the graphql layer, overtime the node.js runtime itself has gotten significant updates that kind of renders the use of frameworks useless
> 
> the main use of a backend framework like expressjs is the documentation, tooling, packages and support for it, expressjs lacks in that regard since it has been abandoned and doesn't receive updates anymore, the goto backend nodejs framework right now is fastifyjs which is maintained by active core maintainers of the node.js runtime itself

So does this mean that all references to the `xss` package should be removed? It's only in one file at the moment.

**Comment by akhilender-bongirwar** [comment]
> @palisadoes since talawa-api is primarily a graphql server it benefits less from expressjs related packages, apollo server could even function without any backend framework since the business logic is encapsulated in the graphql layer, overtime the node.js runtime itself has gotten significant updates that kind of renders the use of frameworks useless
> 
> the main use of a backend framework like expressjs is the documentation, tooling, packages and support for it, expressjs lacks in that regard since it has been abandoned and doesn't receive updates anymore, the goto backend nodejs framework right now is fastifyjs which is maintained by active core maintainers of the node.js runtime itself

@xoldyckk, do you then want me to proceed with removing the xss package completely?

**Comment by xoldyckk** [comment]
@akhilender-bongirwar yes

**Comment by palisadoes** [comment]
@xoldyckk Please take a look

**Comment by akhilender-bongirwar** [comment]
@xoldyckk, please review

**Comment by akhilender-bongirwar** [comment]
@xoldyckk, please review I have resolved the conflicts

**Comment by akhilender-bongirwar** [comment]
I have resolved the conflicts. Please review.

// @palisadoes @xoldyckk @sumitra19jha

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
