### PR TITLE
feat: Installation.md added with few sample data (without Docker)

### PR DESCRIPTION
**Pull request by bandhan-majumder**
**What kind of change does this PR introduce?**

**Issue Number:** #2666 

**Snapshots/Videos:**
### Migrations are applied:
image

### Sample data loaded, graphql sdl file generated, server starts
image

### Endpoint working 
image

**If relevant, did you update the documentation?**
Added installation process in INSTALLATION.md file.

**Summary**
Local installation steps without docker with sample data loaded and working steps are defined in INSTALLATION.md file.  

**Other information**
As I added some files which are crucial for sample data import, please git clone https://github.com/bandhan-majumder/talawa-api/tree/develop-postgres and the rest of the steps are as it is.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please work with @xoldd here and in the slack `#talawa-api` channel to make sure this is appropriate.
2. We need the sample data to help with testing and to create a demo site so that users can determine whether they want to use the app or not.

**Comment by palisadoes** [comment]
@xoldd 

We will need a way for people to test the application by seeing what it can do. The loading of sample data via the setup script helps a lot. It also helps with the new contributors as they can get a better understanding of the features.

We really need this. How can you facilitate this with the coding you are doing?

**Comment by bandhan-majumder** [comment]
Sure. I would love to apply the suggestions/modifications suggested by @xoldd.

**Comment by palisadoes** [comment]
> Sure. I would love to apply the suggestions/modifications of @xoldd. And @palisadoes, can u please merge his PR #2698. I will be able to test the user authentication functionalities. Thank you :)

It's merged

**Comment by xoldd** [comment]
According to me this way of seeding the database is bad and should not be carried out. Also, there are two types of database seeds, one is for dummy data that is only useful in development, testing environments etc., and one is for data that is common in all environments including the production.

Since there isn't a concept of service layer, for now the graphql resolvers are the single source of truth for most of the business logic. Database seeding will be done by triggering graphql mutation operations. Manually inserting data into the database like this is just gonna lead to duplication of business logic, inconsistency and seed data corruption.

The only exception to this right now is creation of the administrator user associated to the `API_ADMINISTRATOR_USER_EMAIL_ADDRESS` and `API_ADMINISTRATOR_USER_PASSWORD` environment variables which is a seed operation that is common for all environments.

**Comment by bandhan-majumder** [comment]
Thanks @xoldd . I think I should close this PR. The recent merge will change the script a bit (`npm` to `pnpm`). I have already written the script. It's working and the mutations (signUp) are also inserting data into database successfully. I have checked a few queries and mutations. After checking the rest of them (based on the recent merge), I will raise a new PR with installation script and screenshot proof.

**Pull request closed without merging**
