### PR TITLE
Increase Code Coverage for updateUserType.ts [Fixes #1253]

### LINKED ISSUE #1253: Increase Code Coverage for ```updateUserType.ts``` resolver
**Describe the bug**
The Code Coverage of ```updateUserType.ts``` is at 90%.

**To Reproduce**

1. npm run test updateUserType
2. Check code coverage

**Expected behavior**
The coverage must be 100%

**Actual behavior**
Coverage is 90%

**Screenshots**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This PR increases the code coverage for ```updateUserType.ts``` file from 90% to 100%

**Issue Number:**

Fixes #1253 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
NR

**Summary**
This PR increases the code coverage for ```updateUserType.ts``` file from 90% to 100%

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
@xoldyckk 

Previously, the test which checks for the error to be thrown when a superadmin tries to demote itself was not being executed correctly.

The two ids being compared were giving the ```false``` because of their type mismatch. Due to this, the test never moved inside the if statement, and the test passed not because of catch error block, but because of try block.

**Comment by xoldyckk** [comment]
@anshgoyalevil the problem is test itself. It's using just `._id` instead of `._id.toString()` to pass `data.id`.

**Comment by xoldyckk** [comment]
Fix the test then I guess

**Comment by anshgoyalevil** [comment]
@xoldyckk 

So, what do you prefer, changing the test, or changing the code. 

I guess, changing the code would be better since converting ids to string would error free in all cases

**Comment by anshgoyalevil** [comment]
@xoldyckk 

Done!

**Review by xoldyckk — APPROVED** [review]

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
