### PR TITLE
Fix/user type

### LINKED ISSUE #1711: API: Fix the usage of userType
**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.

This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
2. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
3. All other `userType`s would be on a per organization basis

This means that all code logic referencing the `userType` will need to be updated accordingly.

_TALAWA API_

Additional considerations include:

1. New user registrations will need to default to the `userType` `USER` if not done so already
1. The Schema will need to be updated to reflect this requirement
1. Mutations and queries will need to be updated and in some cases new ones added.

_TALAWA ADMIN_

Additional considerations include:

1. The current screen that edits a person's userType will need to be updated. A design is being created for this and will be reflected in the Figma file on our Design Guide page:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA MOBILE_

No expected changes as userType isn't referenced in the code base

**Actual behavior**

- The schema doesn't apply a person's `userType` by organization. 

**Screenshots**

The current schema:

image

**Additional details**

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**

Fix the usage of userType ,created a new appUserProfile model

Fixes #1711 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Why is `isSuperAdmin` not defined in the schema?
2. It's referenced in some `AppUserProfile` related objects, but not in the schema.

**Comment by AVtheking** [comment]
Sorry sir it was defined inside my schema 😅 ,ig it may be removed while removing conficts .I have fixed it

**Comment by palisadoes** [comment]
@AVtheking 

1. How would you propose we integrate this while minimizing the impact on the various client repos?
1. If we merge this into develop, it will be a major disruption.
1. For example, could we merge this into a new branch and have Admin and Mobile have a similar branch to work against?
1. Would we need a team etc?

**Comment by AVtheking** [comment]
Yes @palisadoes sir we should merge this into a new branch and create issues regarding changes in this repo in mobile and admin repo.

Having a team for these changes would be helpful as this will speed up the process and we can merge changes into develop together in all repo

**Comment by AVtheking** [comment]
Creating separate branches in all repos is a good idea as other contributors working on different features would be working  based on old model so we need to constantly update it until it is merged in develop

**Comment by palisadoes** [comment]
Thanks,

1. In that case, I'll close this PR
1. Please reopen this against the new `userTypeFix` branch
1. When this is merged we'll open issues in Admin and Mobile to get the compatibility working

**Pull request closed without merging**
