### PR TITLE
add graphql implementation for handling user authentication and user read/write functionalities

### PR DESCRIPTION
**Pull request by xoldd**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

This pull request contains graphql implementation for handling read and write operations to talawa users. It also includes tests for that graphql implementation which adhere to the black box testing approach where all data manipulation is done using only the graphql interface exposed by talawa api.

**Does this PR introduce a breaking change?**

**Other information**

## EACH INDIVIDUAL COMMIT CONTAINS CHANGES RELATED TO THE COMMIT MESSAGE, COMMITS SHOULD BE VIEWED IN A SERIAL ORDER FOR AN EASIER REVIEW PROCESS

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Is this ready to be merged?

**Comment by xoldd** [comment]
> Is this ready to be merged?

Yes

**Comment by xoldd** [comment]
I was waiting for this PR to get merged but I guess I'll just start making more PRs that are based off of this one.

**Comment by palisadoes** [comment]
@xoldd Merged

**Pull request merged**
