### PR TITLE
Bug Fix - Incorrect validation for organization membership in addEventAttendee resolver

### PR DESCRIPTION
**Pull request by krishna619**
What kind of change does this PR introduce?

BugFix

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1856

Did you add tests for your changes?
No

Snapshots/Videos:

If relevant, did you update the documentation?

Summary

Does this PR introduce a breaking change?

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by krishna619** [comment]
@Cioppolo14 @palisadoes https://github.com/PalisadoesFoundation/talawa-api/pull/1866 this PR is also pending

**Comment by Cioppolo14** [comment]
@krishna619 Please write the tests for this.  Do you have a specific challenge you have a question about?

**Comment by krishna619** [comment]
@Cioppolo14 @palisadoes , I have written the test cases for it.

**Comment by Olatade** [comment]
@krishna619 can you please update your branch with the latest changes?

**Comment by krishna619** [comment]
@Olatade Hi, I have updated my branch with the latest upstream.
Please do review.

**Comment by Olatade** [comment]
@SiddheshKukade @DMills27 please can you review

**Comment by krishna619** [comment]
https://github.com/PalisadoesFoundation/talawa-api/assets/52276473/1b8495c6-a7a7-4777-8010-6bae2a01aef7

@sumitra19jha

**Comment by krishna619** [comment]
Please review.
@palisadoes 
@SiddheshKukade 
@DMills27 
@sumitra19jha

**Review by DMills27 — APPROVED** [review]
LGTM

**Comment by krishna619** [comment]
@palisadoes @DMills27 
Thanks
Also can you also close PR #1866 as merged 
And issue #1792 
Since this very PR has covered that as well

**Pull request merged**
