### PR TITLE
feat: event volunteer group

### LINKED ISSUE #1670: Add Support for Event Volunteers
## Introduction
This issue requires someone with:

1. provable GraphQL coding experience **_OR_**,
2. significant activity in their GitHub profile

It is the first in a series of issues and we want to make sure that it will be completed quickly so that others can use it as a guide

## Problem Description

1. We will need the _**OPTIONAL**_ ability to assign volunteer groups to events. 
2. This will help event organizers have greater success.

## Preferred Solution

1. We will need DB schema updates to facilitate this.
1. Queries and mutations will need to be created to satisfy CRUD operations for volunteers
1. Valid tests must be created for the code added for this issue
1. No other functionality must be affected

### Event Volunteer Groups Collection

At a minimum this will need to record:

1. Event ID
2. Group Name
3. Volunteer Group Leader User ID
4. Number of volunteers required
5. List of Event Volunteer Types
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

### Event Volunteer Collection

At a minimum collection of Event Volunteer Types will need to record:

1. Event ID
2. User ID
3. Response [No, Yes, None]
4. Invited - T/F
5. Assigned - T/F
8. Our standard update and creation fields as outlined in these pull requests
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1603
    2. https://github.com/PalisadoesFoundation/talawa-api/pull/1542

## Other

It is best for our reviewers to verify smaller PRs. Therefore you will need to create one PR per collection created.

1. Event Volunteer Collection CRUD
2. Event Volunteer Groups Collection CRUD

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

1. Multiple PRs
1. See above for details

**Additional context**
1. When recurring meetings are correctly implemented, Admins will want event volunteers to be part of the recurring event up to some end date. Volunteers may also only want to participate in the role every N events. 
    1. Supporting recurring events is beyond the scope of this issue, but your work must not make support for this at a later date be more difficult. See this issue for details.
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1583
    1. Explain how you think this could best be achieved when eventually implemented to show that you have considered your impact on this long term goal.
1. Reminders will eventually need to be sent to volunteers prior to the event. 
    1. This is beyond the scope of this issue, but your work must not make support for this at a later date be more difficult. 
    1. Explain how you think this could best be achieved when eventually implemented to show that you have considered your impact on this long term goal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by lakshz**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1670 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Adds event volunteer group to an event

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@lakshz Please fix the failing tests.

**Comment by lakshz** [comment]
@Cioppolo14 Tests are passing now.

**Comment by Olatade** [comment]
@lakshz please fix the merge conflicts.

**Comment by Cioppolo14** [comment]
@lakshz It looks like there are more conflicts.  Can you check those out?

**Comment by lakshz** [comment]
@EshaanAgg @DMills27 Could you please review this PR?

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by lakshz** [comment]
@palisadoes resolved merge conflicts.

**Comment by palisadoes** [comment]
@EshaanAgg 
@DMills27 

Please review

**Comment by Cioppolo14** [comment]
@lakshz Can you resolve the conflicting file?

**Comment by lakshz** [comment]
@Cioppolo14 @palisadoes The number of lines in types.ts and constants.ts are exceeding 600 after the latest merge on this PR. Till now, we have worked with only a single file for graphql types and constants. Let me work to meaningfully separate them into multiple files.

**Comment by palisadoes** [comment]
Add those files as exceptions to this file for the countline test
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

**Comment by palisadoes** [comment]
You still need to fix the tests

**Comment by lakshz** [comment]
@palisadoes Tests are fixed now. Apologies for the delay, I was travelling yesterday.

**Comment by palisadoes** [comment]
@SiddheshKukade @sumitra19jha Please review

**Comment by SiddheshKukade** [comment]
@lakshz please take a pull and fix conflicts if any so that I can test this. Thanks

**Comment by lakshz** [comment]
Hey @SiddheshKukade, sorry but I couldn't find any merge conflicts on this PR. Could you please check again?

Screenshot 2024-03-16 at 13 50 16

**Comment by SiddheshKukade** [comment]
I've updated your branch.

**Comment by lakshz** [comment]
The workflow checks are passing.

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@lakshz Please fix the conflicting file.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by lakshz** [comment]
@palisadoes Tests are passing

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
