### PR TITLE
Added constants for the error messages src/resolver/Mutation

### LINKED ISSUE #1039: Adding constants for the error messages`src/resolver/mutation`
**Is your feature request related to a problem? Please describe.**

This is a child issue to the issue listed here: #1035 
 - The code needs to be changed in `src/resolver/mutation`.
 - constant are values that are already defined for the different values of error message/code/param that are then further used by importing the src/constants folder.

**Describe the solution you'd like**
- we have to define constants for all the hard-coded message/code/param exist in this file. 
-  Refer to the parent issue on getting an insight on how this issue need to be resolved

**Important**
 - Please refer to the parent issues on how to refactor the code correctly.

### PR DESCRIPTION
**Pull request by Manoramsharma**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:**

Fixes #1039

### CODE REVIEW

**Comment by Manoramsharma** [comment]
Hi @noman2002 can you guide me through the way to resolve this failing test, it says no images folder found but we are using `app.use("/images", express.static(path.join(__dirname, "./../images")));` as a directory name in the code base.

**Comment by Manoramsharma** [comment]
Hi @noman2002 can you guide me through the way to resolve this failing test, it says no images folder found but we are using `app.use("/images", express.static(path.join(__dirname, "./../images")));` as a directory name in the code base.

**Comment by palisadoes** [comment]
1. This looks related to https://github.com/PalisadoesFoundation/talawa-api/issues/1010#issuecomment-1424756306 by @kb-0311
2. @kb-0311 please comment. Your solution may need more work.

**Comment by kb-0311** [comment]
@Manoramsharma @palisadoes It seems whenever this unhandled error is thrown, it is because some other test is failing in the PR itself as was in the case of my other PR you linked. But even then in the PR above I had handled it 

However, the app throwing this unhandled error is a bit of surprise since the entire suite is completely wrapped in try catch blocks.  

It seems to be a problem with how the image upload tests are handled i.e asynchronously -> which in turn is also the problem with how the the uploadimage logic is written i.e with streams. Now that my exams are over I am giving a complete overhaul to how file objects are handled in the API, I will be using `stream/promises` approach towhile giving a overhaul to make sure that this kind of asynchronous error does not happen in the new version of utilities. 

@Manoramsharma could you run the test files for the mutations you refactored individually instead of all together to find which test is failing exactly? Also pls check your slack.

**Comment by kb-0311** [comment]
@palisadoes @Manoramsharma alright I got the source of the problem finally after beating my head over it for some time.

The issue was with the `uploadImage.spec.ts` file itself. The problem was that the `createReadStream` function is async function and it throws error as an event Emitter.
So what I had to do was handle the error event itself for the tests to work.

// This is where vitest was throwing unhandled error. It was because of `createReadStream` function and not `writeFile` which isn what I was previously thinking.
Screenshot from 2023-02-16 11-03-22

// Handled that this way

**Comment by Manoramsharma** [comment]
Hi @noman2002 @palisadoes all the checks have passed and this PR has no inflicting files. Please make sure to have a review and merge the same.

**Comment by kb-0311** [comment]
@palisadoes I implemented the changes of uploadImage.spec file along with @Manoramsharma on a one-on-one call in the morning and now the tests are passed, hopefully the unhandled error does not happen again.

 However, in his system the deleteImage.ts file was throwing an unexpected error during mocking (unrelated to the my previous PR's I have never worked on deleteImage file) Do you want me to look for a fix rn or should I continue to prioritize #952 and look into that after at least the basic of binary object storage is consistently done?

**Comment by Manoramsharma** [comment]
> @palisadoes I implemented the changes of uploadImage.spec file along with @Manoramsharma on a one-on-one call in the morning and now the tests are passed, hopefully the unhandled error does not happen again.
> 
> However, in his system the deleteImage.ts file was throwing an unexpected error during mocking in `removeOrganizationImage.spec.ts` file(unrelated to the my previous PR's I have never worked on deleteImage file) Do you want me to look for a fix rn or should I continue to prioritize #952 and look into that after at least the basic of binary object storage is consistently done?

Yes, in particular we witnessed this error in` removeOrganizationImage.spec.ts` file after mocking this error is generated. I think I can work on this bug fix, just want how can I proceed @palisadoes ?

**Comment by kb-0311** [comment]
@Manoramsharma you can go ahead and fix it. But try to do this in this PR  itself so that all the resolver/Mutations error messages refactor are done.

**Comment by Manoramsharma** [comment]
> @Manoramsharma you can go ahead and fix it. But try to do this in this PR itself so that all the resolver/Mutations error messages refactor are done.

I think I should make the changes for the bug fix in PR for issue #1002 before the error is after the refactoring is implemented.

**Comment by noman2002** [comment]
@Manoramsharma Is there anything left for this PR ?

**Comment by xoldyckk** [comment]
> @Manoramsharma Is there anything left for this PR ?

I requested for a change. @Manoramsharma has not yet made that change.

**Comment by Manoramsharma** [comment]
> > @Manoramsharma Is there anything left for this PR ?
> 
> I requested for a change. @Manoramsharma has not yet made that change.

Exactly which change @xoldyckk , sorry I am able to recall for now?

**Comment by xoldyckk** [comment]
> > > @Manoramsharma Is there anything left for this PR ?
> > 
> > 
> > I requested for a change. @Manoramsharma has not yet made that change.
> 
> Exactly which change @xoldyckk , sorry I am able to recall for now?

Scroll up you'll see.

**Comment by Manoramsharma** [comment]
> > > > @Manoramsharma Is there anything left for this PR ?
> > > 
> > > 
> > > I requested for a change. @Manoramsharma has not yet made that change.
> > 
> > 
> > Exactly which change @xoldyckk , sorry I am able to recall for now?
> 
> Scroll up you'll see.

Hi @xoldyckk I think you asked this "MembershipRequest already exists as MEMBERSHIP_REQUEST_NOT_FOUND? Does it make sense?" That I already changed I renamed the variable as `MEMBERSHIP_REQUEST_ALREADY_EXISTS`

**Comment by xoldyckk** [comment]
> > > > > @Manoramsharma Is there anything left for this PR ?
> > > > 
> > > > 
> > > > I requested for a change. @Manoramsharma has not yet made that change.
> > > 
> > > 
> > > Exactly which change @xoldyckk , sorry I am able to recall for now?
> > 
> > 
> > Scroll up you'll see.
> 
> Hi @xoldyckk I think you asked this "MembershipRequest already exists as MEMBERSHIP_REQUEST_NOT_FOUND? Does it make sense?" That I already changed I renamed the variable as `MEMBERSHIP_REQUEST_ALREADY_EXISTS`

I said use the error message constant in the test instead of asserting against a custom message. If that constant's value is changed your tests will fail because they are asserting against a hardcoded string instead of the constant.

**Comment by Manoramsharma** [comment]
> 

Ok, I got that. I will be making changes to the test files that are asserting against the hardcoded string values rather the corresponding constants.

**Comment by Manoramsharma** [comment]
@xoldyckk done the asked changes for `tests/mutation `folder I find same thing to be done for `tests/Utilities` folder that @aashimawadhwa was working on, done a few in this PR also you can have a look.

**Review by xoldyckk — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
