### PR TITLE
Remove the unnecessay files name to allow users to modify them

### LINKED ISSUE #2772: Authorized checks for  unnecessary Files  which is causing to failing every PR
**Describe the bug**
 There is a restriction for users to not allow them to change specific files like setup.ts. If user made changes to those files it will cause the workflow to fail that's why every PR  is getting failed  
**To Reproduce**
Open a pull request 

1. create a issue
2. link a PR to it
3. github workflow will expose the errors

**Screenshots**
image

**Additional details**

### PR DESCRIPTION
**Pull request by AQIB-NAWAB**
**What kind of change does this PR introduce?**
Bug Fix

**Issue Number:**  #2772

Fixes  #2772

**Did you add tests for your changes?**
No

## Summary by CodeRabbit

- **Chores**
	- Streamlined the GitHub Actions workflow for improved monitoring of sensitive files.
	- Enhanced error handling for file count checks.
	- Improved application testing with health checks for main server and Apollo Server.

### CODE REVIEW

**Comment by AQIB-NAWAB** [comment]
Hy @palisadoes , is it necessary to give different names to source branch and target branch ??
I am getting error due to this 
**it says** 
image

**Comment by AQIB-NAWAB** [comment]
I am adding a new pull request with different branch name

**Comment by Aad1tya27** [comment]
> Hy @palisadoes , is it necessary to give different names to source branch and target branch ?? I am getting error due to this **it says** image

Create a different branch which has a name different from develop(target branch), using github checkout -b <branch-name>
You can then create another pr using that branch.

**Comment by Cioppolo14** [comment]
There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

**Comment by AQIB-NAWAB** [comment]
> There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

Apologies for the oversight, and thank you for the correction. I will ensure to follow the guidelines moving forward.

**Pull request closed without merging**
