### PR TITLE
Events attended support added with fetching recurring event query

### LINKED ISSUE #2550: GSoC'24: EventsAttended api support for improved Attendance system
**Is your feature request related to a problem? Please describe.**
There is lack of events attended support for admins and super admin to track the members attendance in events

**Describe the solution you'd like**
Added Api support with new member `eventsAttended` in user schema, also added query for fetching recurring events 

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**
I have added the support for events attended by the member of the organisation and also made the query to fetch all the recurring events throught its base recurring event id

**Issue Number:** 

Fixes #2550 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
  - Introduced new query methods for retrieving event volunteers and events attended by users.
  - Added a field to the User type to track events attended.

- **Bug Fixes**
  - Enhanced error handling in the `addEventAttendee` mutation to ensure proper user updates and error messages.

- **Tests**
  - Added comprehensive unit tests for the new queries and mutation, ensuring robust coverage and error handling.

- **Documentation**
  - Updated documentation to reflect new fields and query capabilities in the GraphQL schema.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests and ensure that the coderabbit.ai suggestions are applied

**Review by DMills27 — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please make sure your code passes all tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
@duplixx Please increase the patch code coverage

**Comment by palisadoes** [comment]
@duplixx Please remember to get the code coverage tests to pass

**Comment by duplixx** [comment]
@palisadoes yes i am working on it, handling some errors rn

**Comment by duplixx** [comment]
@palisadoes @DMills27 can you review it now😅

**Comment by palisadoes** [comment]
Please make sure that code rabbit approves the PR

**Comment by palisadoes** [comment]
@DMills27 @Kevoniat Please review

**Review by DMills27 — APPROVED** [review]

**Pull request merged**
