### PR TITLE
MongoDB Connection error solved after removing `userTypeFix`

### LINKED ISSUE #2049: [userTypeFix] Improve Tests for MongoDB Connection
**Is your feature request related to a problem? Please describe.**

Current tests of `setup.ts` can't  catch the mongo db basic connection issue

**Describe the solution you'd like**

- The tests have to catch the connection fails of MongoDB 

**Describe alternatives you've considered**

- N/A

 **Approach to be followed (optional)**

Create tests for different scenarios to connect of database to catch the issues of  MongoDB connection

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
The MongoDB connection error was resolved after removing 'userTypeFix' and adding verification for all collections after importing sample data.

**Issue Number:**

Fixes #2049 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
No

**Summary**
Verification is performed by comparing the documents in the json file of sample_data to the documents in the collection in MongoDB after import.

**Does this PR introduce a breaking change?**
No

**Other information**
Similar issue: #2099 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@gautam-divyanshu Please update your PR with the issue number you are fixing.

**Comment by gautam-divyanshu** [comment]
[Screencast from 2024-03-26 17-14-21.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/137816099/1eafe893-c3ff-4b9d-8b8c-cf36f22a81c9)

**Comment by gautam-divyanshu** [comment]
@palisadoes  @Cioppolo14  Please review this PR.

**Comment by Cioppolo14** [comment]
@SiddheshKukade @EshaanAgg Can you review this PR?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
