### PR TITLE
Add the test case for ImageSizeLimitExceed

### LINKED ISSUE #1819: Test: src/libraries/errors/ImageSizeLimitExceeded.ts`
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

1. Tests need to be written for file `src/libraries/errors/ImageSizeLimitExceeded.ts`
1. We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
1. When complete, all all methods, classes and/or functions in the refactored file will need to be tested. 
1. These tests must be placed in a single file with the same path as the tested file, but under the `tests/` with a `.spec.ts` suffix.
1. You may need to create the appropriate directory structure to do this.

### IMPORTANT:

Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found by visting this page](https://app.codecov.io/gh/PalisadoesFoundation/talawa-api?displayType=list). Login using your GitHub credentials.
- Create your own `codecov.io` to help with testing.
- The PR you create will show a report for the code coverage for the file you have added. You can also use that as a guide.

### Other

Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by samiali12**
**What kind of change does this PR introduce?**

This PR introduces a fix for issue https://github.com/PalisadoesFoundation/talawa-api/issues/1819 It includes test case and bug fixes in the  ImageSizeLimitExceed.spec.ts file.

**Issue Number:**

Fixes #1819 

**Did you add tests for your changes?**

Yes, I've added unit tests to cover all functions and classes in ImageSizeLimitExceed.spec.ts

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

No documentation updates are required for this test case.

**Summary:**

This pull request introduces tests for the `src/libraries/errors/ImageSizeLimitExceeded.ts` file to achieve 100% code coverage. The code has been refactored for testability, and comprehensive tests have been added to cover all methods and scenarios.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Other information:**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@DMills27 @SiddheshKukade Can you review this PR?

**Comment by Olatade** [comment]
@samiali12 please update your branch with the latest changes

**Review by SiddheshKukade — APPROVED** [review]
looks fine.

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Pull request merged**
