### PR TITLE
Increases code coverage for resolvers/Organization

### LINKED ISSUE #808: Resolvers: Create Test for resolvers/Organization.js
The Talawa-API code base needs to be 100% reliable. This means we need to have 100% test code coverage.

 
Tests need to be written for file 

_src/lib/resolvers/Organization/index.ts_

- We will need the API to be refactored for all methods, classes and/or functions found in this file for testing to be correctly executed.
- When complete, all methods, classes and/or functions in the refactored file will need to be tested. These tests must be placed in a
single file with the name `tests/resolvers/Organization.sepc.js`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa-api/issues/490

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-api/tree/develop/lib/resolvers/organization_query/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.

### PR DESCRIPTION
**Pull request by beingnoble03**
**What kind of change does this PR introduce?**
Increases code coverage to 100% for `creator.ts` and adds unit test for `Organization/index.ts`.

**Issue Number:**

Fixes #808 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by beingnoble03** [comment]
@palisadoes @SiddheshKukade I have created tests for both `creator.ts` and `index.ts`, but I have a doubt here, although I have created test for `index.ts` but c8 will not generate any coverage report for this file because we have excluded every `index.ts` file from `vitest.config.ts`. So, please look into this. Thanks!

Screenshot 2022-12-28 at 4 33 16 PM

**Comment by palisadoes** [comment]
@beingnoble03 We have included the `index.ts` in the code coverage calculations in #825. Please update your branch and continue.

**Comment by beingnoble03** [comment]
@palisadoes done. @SiddheshKukade ptal. Thanks!

**Review by SiddheshKukade — APPROVED** [review]
Changes are looking fine to be merged. 👍🏻

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
