### PR TITLE
fixed package installation script in INSTALLATION.md

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

Docs fix

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

-

**Summary**

Changed installation script for packages from `npm run install` to `npm install` in INSTALLATION.md.

**Does this PR introduce a breaking change?**

-

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@xoldyckk I made significant changes to INSTALLATION.md earlier today. Please sync your repo.

**Comment by xoldyckk** [comment]
> 

yea wait

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@xoldyckk Can you also add some context on how to setup nvm and fnm?

For example (You may need to do some editing here):

### FNM Setup

1. Follow the installation procedure on the link
1. Follow the steps in the `Shell Setup` section to get your environment properly configured
1. Install node using this command

         fnm install

1. Use the configured version of node

        fnm use

**Comment by xoldyckk** [comment]
We don't need to do this when there's comprehensive official docs for those tools. We just need to direct people to them.

**Comment by xoldyckk** [comment]
> @xoldyckk Can you also add some context on how to setup nvm and fnm?
> 
> For example (You may need to do some editing here):
> ### FNM Setup
> 
>     1. Follow the installation procedure on the link
> 
>     2. Follow the steps in the `Shell Setup` section to get your environment properly configured
> 
>     3. Install node using this command
>        ```
>          fnm install
>        ```
> 
>     4. Use the configured version of node
>        ```
>         fnm use
>        ```

We don't need to do this when there's comprehensive official docs for those tools. We just need to direct people to them. There's already shell specific instructions on their docs.

**Pull request merged**
