### PR TITLE
Updated setup.ts to support docker compose v2 and pass npm run typecheck

### LINKED ISSUE #2767: Bug Report: npm run setup command encountering an issue when starting Docker Containers on Linux
**Describe the bug**
When running npm run setup, and choosing to start the docker containers, we encounter an error because of the outdated version of docker compose being used in setup.ts . 

**To Reproduce**

1. Run npm run setup in the root folder of the talawa-api.
2. Select all default options, and answer "Are you setting up this project using Docker?" with Y.
3. Answer "Do you want to start the Docker containers now?" with Y

**Expected behavior**
Docker containers should have started and docker build file should have run in detached mode.

**Actual behavior**
Error: spawn docker-compose ENOENT
Error running docker-compose: Error: spawn docker-compose ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn docker-compose',
  path: 'docker-compose',
  spawnargs: [ '-f', 'docker-compose.dev.yaml', 'up', '--build', '-d' ]
}
Some error occurred: Error: spawn docker-compose ENOENT

**Screenshots**
image

**Additional details**
In the setup.ts file, the spawn function takes "docker-compose" as the command for Linux Users. Now this function is deprecated and by default on Docker Desktop or Compose installation, Docker Compose V2 is installed. 
image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Aad1tya27**
**What kind of change does this PR introduce?**

Changes in setup.ts, src/typedefs/unions.ts
Now the setup.ts is compatible with both docker compose v1 and v2, and the error handling of the 
The empty gql which was creating EOF error during npm run typecheck has been removed. Moreover, the module unions.ts exported wasn't being used anywhere in the codebase.
This PR also fixes a unit test which expected wrong volunteered hours(details in the comment below).

**Issue Number:**

Fixes #2767, #2769  

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
image
image
image

**If relevant, did you update the documentation?**
Updation in the documentation is not required.

**Summary**
Now the docker containers start without facing any error related to outdated Docker Compose version. Also the error faced in the test ```npm run typecheck``` is now fixed by removing the empty gql block.

**Does this PR introduce a breaking change?**
No, the bug only effected ```npm run setup``` and ```npm run typecheck``` commands.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a command retrieval function for enhanced Docker Compose management.

- **Bug Fixes**
	- Improved error handling for Docker daemon checks, providing clearer user feedback.
	- Enhanced timeout management for Docker Compose operations.
	- Updated test cases for volunteer ranks to reflect accurate expected values.

- **Chores**
	- Commented out unused code related to GraphQL imports and exports.

### CODE REVIEW

**Comment by Aad1tya27** [comment]
@palisadoes 
image
I am getting this error in the ```npm run test``` job. I think this is a common error which everyone is facing.

Also, the main change which I have done is in setup.ts file to fix the bug. And as it is a sensitive file I have failed another test. How do I proceed further?

**Comment by Aad1tya27** [comment]
@palisadoes  I got why ```npm run test``` was getting the above error.
image
Here the expected volunteer hours are wrong. They should be equal to 6.

image
In the testVolunteer1 (using testUser1 id), the total hours upto a month ago are clearly 2(yesterday) + 4(two weeks ago) = 6

The other 3 unit tests under "resolvers -> Query -> getVolunteerRanks" are correct, only this one had wrong hours written.

I'm changing the getVolunteerRanks.spec.ts file in order to change the hours to 6 and for my PR to pass the TESTING APPLICATION(22.x) job.

**Comment by palisadoes** [comment]
@coderabbitai

**Comment by palisadoes** [comment]
@coderabbitai full review

**Comment by palisadoes** [comment]
Please fix:

1. Any failing tests
1. Any conflicting files

Make sure CodeRabbit.ai approves your changes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
